### ISSUE TITLE
cannot uninstall package under emacs23

### ISSUE THREAD

**Issue by redguardtoo** [purcell/emacs.d#20]
search `(delete-directory dir t t)` in package.el.

only emacs24's `delete-directory` has third argument (which by default is t). see http://www.masteringemacs.org/articles/2011/12/12/what-is-new-in-emacs-24-part-2/

in emacs 23.2, the second optional argument is added which by default is nil.

**Comment by ahjstone** [comment]
I'm encountering the same problem
What is the fix please?
- GNU Emacs 23.4.1 (i486-pc-linux-gnu, GTK+ Version 2.24.10) of 2012-09-09 on murphy, modified by Debian
- Debian GNU/Linux 7.8 (wheezy)

**Comment by purcell** [comment]
@ahjstone The original submitter confirmed this fixed 3 years ago. Please can be more specific about what problem you're seeing?

**Comment by ahjstone** [comment]
package uninstall error: see the screenshot below
![_screen](https://cloud.githubusercontent.com/assets/6587029/8395249/77c00612-1d65-11e5-8f1b-9d359a079a66.png)

**Comment by purcell** [comment]
I don't think that's related to this bug report, because it appears that the function is being called with `nil` instead of a string directory name. How can I reproduce this? Fire up this config with Emacs 23.x and then...? I can't see from the partial backtrace in the screenshot what was being executed at the time.

**Comment by ahjstone** [comment]
Sorry, I now realise I'm in the wrong place: using package.el on emacs23 (http://wikemacs.org/wiki/Package.el) and trying to remove a package, probably the problem is with package.el

**Comment by purcell** [comment]
No problem. To be honest, I can't encourage you strongly enough to move across to Emacs 24: there's no support route for the old `package.el`, and issues can potentially be showstoppers. In contrast, the `package.el` bundled with each Emacs 24 release has been functional, and actively developed during a period in which a large proportion of the Emacs community was already using `package.el`.

**Comment by ahjstone** [comment]
Thanks for your friendly advice... and patience.  :)
