### ISSUE TITLE
How to figure out unrecognizable characters problem?

### ISSUE THREAD

**Issue by realhsu** [purcell/emacs.d#217]
especially utf-8.the codes are the ANSI encoding now.

**Comment by russellfei** [comment]
@realhsu 
Use `revert-buffer-coding-system` ;-) there's someone function you can find at `smex.
revert buffer coding system to your language. Keep in mind, 
this function just change current display, it won't change anything of your file.
@purcell is there any function can save the buffer with changed coding system?

**Comment by purcell** [comment]
`M-x set-buffer-file-coding-system`

**Comment by russellfei** [comment]
@purcell  got it ;-)
