### ISSUE TITLE
dear sir,I get a problem about lisp when use your .emacs.d

### ISSUE THREAD

**Issue by zqy767** [purcell/emacs.d#237]
when I use M-x slime , it tells me that Can't locate module: SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG.Why?

**Comment by chenjinqian** [comment]
I find the same issue, I have solved it. The reason is that I installed slime with "sudo apt-get install slime" before, I guess this package will mess up with the one in ~/.emacs.d/elpha/slime-2*. After remove it with "sudo apt-get remove slime", everything goes right.
