### ISSUE TITLE
erb-html mode and flycheck

### ISSUE THREAD

**Issue by zherk** [purcell/emacs.d#243]
The erb-html mode is handled by mmm, and when a ruby code part is highlighted (inside <% %>) the ruby major mode is also enabled. Because of this, flycheck enables the ruby syntax checker and, obviously, it doesn't helps too much to detect syntax errors of the erb file. Everything gets highlighted as an error.

So, what I did on https://github.com/zherk/emacs.d/commit/4ebabc6f2920a7c3b0d0c0a9d89ac34621a93af6 was a new syntax checker that keeps the eruby-erubis mode when ruby major mode is on but the the mmm minor mode is also activated (mmm mode is not used in plain ruby, so the normal syntax checker for ruby still works).

How do you feel about integrating something like that in your repo? I'm very junior on Lisp, and I don't trust this thing that I wrote, that's why I didn't asked for a pull.

**Comment by dcorking** [comment]
I don't think erubis claims support for Ruby > 1.9.x . Let's think about using `erb -x` here, or possibly kicking this idea upstream to `flycheck`](https://github.com/flycheck/flycheck)
