### ISSUE TITLE
about C-x C-r ido-find-file-read-only

### ISSUE THREAD

**Issue by beixingqiao** [purcell/emacs.d#246]
Hi steve,
It's quite strange that when I open `*.el` ,`*.lisp` files, then press `C-x C-r`, emacs can't invoke ido-find-file-read-only, but I open any other type files (eg. `*.php`), then press `C-x C-r`, emacs can.I don't know whether I do this correctly and how I can invoke `ido-find-file-read-only` with `C-x C-r` keymap when I open `*.el`.Thanks!

**Comment by purcell** [comment]
This appears to be due to `redshank-mode`, which uses `C-x C-r` as its prefix binding. I enable `redshank-mode` in all lisps. It looks like you could try customizing the variable `redshank-prefix-key`.

**Comment by beixingqiao** [comment]
It works!Thank you for your help!

**Comment by purcell** [comment]
Great!
