### ISSUE TITLE
Cancel Key binding missing

### ISSUE THREAD

**Issue by russellfei** [purcell/emacs.d#248]
@purcell  Quite strange that `C-g` did nothing
By default, `C-g` is used as cancel function, but this doesn't work now.
Do you use `evil-escape` or something alternative?
What will you do if some operations need to be canceled?
thx~

**Comment by russellfei** [comment]
`C-]` works.
What I guess is there might be some conflicts for global `C-g` for canceling,
or you just try to balance the strike between two hands?

**Comment by purcell** [comment]
I don't use `evil`. `C-g` always works for me, so I don't really understand what this issue is about. :-)

**Comment by jguenther** [comment]
`C-g` works fine for me as a cancel command. I don't use `evil-mode` but I switched to it just now, and `C-g` doesn't appear in the `C-h b` bindings list anywhere.

Check that list of bindings and see if `C-g` is being rebound by some other mode that you're using, perhaps?

Another thing you could try is checking out a clean copy of this repo and using `emacs -Q --load=/path/to/fresh/repo/init.el` to see if the issue goes away.

**Comment by russellfei** [comment]
Well, I got an unexpected key bind bug.
Details:
1. installed `evil-mode` and related `eval-leader`
2. often switch between emacs-mode and evil-mode

Error: `C-g` doesn't work ( I thought this repo's update just changed this bind o_o )

Thanks @jguenther and @purcell  I'll perform more tests on this issue

PS: If you guys don't use `evil-mode`, how do you fold your code blocks?
I've been trying to make a compromise between `evil` and `emacs`.( struggling but still prefer `emacs` )
I've  find the key bind through related function, that's such a complex multi-key combination

**Comment by russellfei** [comment]
0_ob
I've got the bug......

It's readcube, a scientific paper reader software, that directly set `^G` as the hotkey for smartcite (not so smart =_=b! )

Just strange about key logs on my on-screen keyboard that `Ctrl-g` cannot be pressed at same time.

Well. checked materials about `C-g` and `C-]`.

Happy again, yeah ;-)

**Comment by russellfei** [comment]
Plus: `evil-mode` has nothing to do with this.
