### ISSUE TITLE
Need help for using Emacs Tags in lua files

### ISSUE THREAD

**Issue by russellfei** [purcell/emacs.d#249]
Hi,

I'm currently using `etags` to browse source code, however, the `TAGS` file cannot be found in `ido`.

![screenshots](https://cloud.githubusercontent.com/assets/3415940/6092258/c527d73a-af11-11e4-8ae5-e5afc82aea56.png)

What's wrong with that `TAGS` file? Or `etags` has limits on not pure `lua` files?
(PS: I've tried `c` source files, it works fine.)

**Comment by purcell** [comment]
Not sure, sorry. I don't really use TAGS support, and I haven't worked with Lua. This would probably be better asked over on the [Emacs stackexchange](https://emacs.stackexchange.com/).

**Comment by russellfei** [comment]
Thx~

**Comment by russellfei** [comment]
@purcell Google told me tags for lua program is a bug for `ctags` T_T
Thankfully, the lua code is quite simple than c/c++
