### ISSUE TITLE
init.el is giving me an error

### ISSUE THREAD

**Issue by tiagonbotelho** [purcell/emacs.d#250]
Im running emacs GUI on a Windows 7 machine and is giving me an error that is breaking emacs(it wont let me press any keys not C nor M) the error is as follows:

Error in post-command-hook (global-magit-wip-save-mode-check-buffers): (file-error "Searching for program" "no such file or directory" "git")

I've experimented on my mac emacs with your setup and it works btw :)
thank you for your time!

**Comment by purcell** [comment]
Hmm. I've probably worked around this with 024f651. `magit-wip-save-mode` really shouldn't fail hard like that, so this may be an upstream issue. (I've generally assumed that any machine with this `emacs.d` config on it will have `git` on it too, since that's the standard installation method.)

**Comment by tiagonbotelho** [comment]
now its giving me the error Cannot save customizations; init file was not fully loaded.

**Comment by tiagonbotelho** [comment]
(file-error "http://melpa.org/packages/cider-20150201.1117.tar" "Not found")
  signal(file-error ("http://melpa.org/packages/cider-20150201.1117.tar" "Not found"))
  url-insert-file-contents("http://melpa.org/packages/cider-20150201.1117.tar")
  package-install-from-archive([cl-struct-package-desc cider (20150201 1117) "Clojure Integrated Development Environment and REPL" ((clojure-mode (4 0 0)) (cl-lib (0 5)) (dash (2 4 1)) (pkg-info (0 4)) (emacs (24)) (queue (0 1 1))) tar "melpa" nil ((:url . "http://www.github.com/clojure-emacs/cider") (:keywords "languages" "clojure" "cider")) nil])
  mapc(package-install-from-archive ([cl-struct-package-desc cider (20150201 1117) "Clojure Integrated Development Environment and REPL" ((clojure-mode (4 0 0)) (cl-lib (0 5)) (dash (2 4 1)) (pkg-info (0 4)) (emacs (24)) (queue (0 1 1))) tar "melpa" nil ((:url . "http://www.github.com/clojure-emacs/cider") (:keywords "languages" "clojure" "cider")) nil]))
  package-download-transaction(([cl-struct-package-desc cider (20150201 1117) "Clojure Integrated Development Environment and REPL" ((clojure-mode (4 0 0)) (cl-lib (0 5)) (dash (2 4 1)) (pkg-info (0 4)) (emacs (24)) (queue (0 1 1))) tar "melpa" nil ((:url . "http://www.github.com/clojure-emacs/cider") (:keywords "languages" "clojure" "cider")) nil]))
  package-install(cider)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(cider)
  eval-buffer(#<buffer  *load*-612684> nil "c:/home/.emacs.d/lisp/init-clojure-cider.el" nil t)  ; Reading at buffer position 81
  load-with-code-conversion("c:/home/.emacs.d/lisp/init-clojure-cider.el" "c:/home/.emacs.d/lisp/init-clojure-cider.el" nil t)
  #<subr require>(init-clojure-cider nil nil)
  ad-Advice-require(#<subr require> init-clojure-cider)
  apply(ad-Advice-require #<subr require> init-clojure-cider)
  require(init-clojure-cider)
  (progn (require (quote init-clojure-cider)))
  (if (>= emacs-major-version 24) (progn (require (quote init-clojure-cider))))
  eval-buffer(#<buffer  *load*> nil "c:/home/.emacs.d/init.el" nil t)  ; Reading at buffer position 2866
  load-with-code-conversion("c:/home/.emacs.d/init.el" "c:/home/.emacs.d/init.el" t t)
  load("c:/home/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by purcell** [comment]
The package list is out of date. You need to run `M-x package-refresh-contents`, then restart Emacs.

**Comment by tiagonbotelho** [comment]
It Worked!! Thanks alot!

**Comment by purcell** [comment]
Great! :-)
