### ISSUE TITLE
A bug in  EVIL mode

### ISSUE THREAD

**Issue by andyque** [purcell/emacs.d#251]
Hi purcell,
When I use "/"(which is bind to (evil-search-forward))  in EVIL normal mode, I can't use "c-r" to call (evil-paste-from-register REGISTER) to paste some content from registers.

The "c-r" is bind to (isearch-repeat-backward). Is this a bug of EVIL? Because in Vim I can do this properly. But in EVIL, it fails.  Or do I miss something here?

Thanks.

**Comment by purcell** [comment]
Sorry, I don't use `evil`. I'd suggest asking the evil guys about this.

**Comment by russellfei** [comment]
@andyque 

Maybe I can offer you some information.

I'm currently use `evil` on this config.

If you want to use `/` for `forward search`, say, you want to search 'hello'

then you type `/hello` then hit `enter` then the all related results will be highlighted

forward search using `n` and using 'S-n' or 'N' to jump back to previous results.

PS: here I prefer the emacs way of using `C-s` and `C-r` to do corresponding search,

and you just type and type again to junp between results. ;-)

Also you want to use REGISTER, maybe you need more detailed settings on your own.

**Comment by purcell** [comment]
Thanks Russell!

**Comment by russellfei** [comment]
@andyque 
I use `apropos` command suggested from *scha chua* to find `evil-paste-from-register`,
and `apropos` shows that this command is not binded to any key, maybe you can  use `evil-leader`
to customize its shortcut.
I'm just new to `evil-xxx` series and happy to learn them together.

@purcell I'm currently learning how to plug in and play with `evil-xxx`, 
just try to select packages relevant to myself, happy hacking ;-)
BTW: do you use pure emacs shortcuts, `viper-mode` or a highly customized key set?
I didn't find something about this when digging the youtube with my ladder

**Comment by purcell** [comment]
@russellfei I just use the Emacs keybindings these days. I switched over from `viper` a few years ago, after at least 10 years using `viper`. I still frequently use `vi` for casual editing in terminals. :-)

I've tried `evil`, but I'm not really interested in using it these days.
