### ISSUE TITLE
Helm 

### ISSUE THREAD

**Issue by tiagonbotelho** [purcell/emacs.d#252]
Good evening, 

To install helm do i need to just package-install or do i need to set it up on some other init-locale file?

I know this is not really an issue related topic but helm was really usefull when i used it, and i was just wondering :)
Thank you!

**Comment by purcell** [comment]
Hi Tiago, yes, you can just install the package and then use `M-x customize` to enable `helm-mode` permanently if you like.

Alternatively, you can put something like this in your `init-local.el`:

```el
(require-package 'helm)
(helm-mode 1)

;; and further config if you like:
(helm-adaptative-mode 1)
(global-set-key [remap execute-extended-command] 'helm-M-x)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
```
