### ISSUE TITLE
html-mode: annoying  auto jump when typing '<'

### ISSUE THREAD

**Issue by liyichao** [purcell/emacs.d#254]
When editing a '.html' file, typing '<', it auto completes '>', so there are '<>' on screen, but the cursor then jumps to behind '>', so I have to move cursor before to insert text in between '<' and '>'.

I use latest '.emacs.d'. The mode is `HTML MMM FlyC:0/2 Rbow Tagedit WSC AC`, and I also use `evil-mode` if it is related.

I can provide any additional information which is necessary.

**Comment by purcell** [comment]
I'm guessing this is due to `evil-mode`, because I can't reproduce this with my default configuration. It's `electric-pair-mode` which inserts the matching `>`, but on my system it leaves the cursor *before* the `>`. Please try it without `evil-mode`. If the problem still happens, let me know which Emacs version you have.

**Comment by liyichao** [comment]
Then it's odd, because when I comment out `evil-mode` related config, the problem remains there.

My Emacs version is `GNU Emacs 24.4.50.1`.

**Comment by purcell** [comment]
> Then it's odd, because when I comment out evil-mode related config, the problem remains there.

Are you still sure that `evil-mode` is actually disabled in that buffer after restarting Emacs? If you're allowing `desktop` to remember open buffers between Emacs sessions, then it might be restoring `evil-mode` after restarting.

If `evil-mode` is definitely disabled, then perhaps pasting the exact steps to reproduce this would be helpful. I simply created a fresh `foo.html` with the template inserted by `auto-insert-mode`, and tried adding a `<` in the middle.

**Comment by liyichao** [comment]
Sorry, I have not remove `.emacs.desktop`. It is the problem of `evil-mode`. Thanks.

**Comment by purcell** [comment]
Yay, great!
