### ISSUE TITLE
Question about undo-tree mode

### ISSUE THREAD

**Issue by liuxianming** [purcell/emacs.d#256]
Hi,

Thanks for the classic emacs configurations. I used your emacs.d, and everything works well, except the undo-tree. I'm not sure if is my problem, but when I use undo-tree-mode, it looks like:
![screen shot 2015-03-11 at 11 42 14 am](https://cloud.githubusercontent.com/assets/1305722/6601550/4ba9a802-c7e4-11e4-903b-53177bdeeee7.png)

not the style of:
;;                                o  (initial buffer state)
;;                                |
;;                                |
;;                                o  (first edit)
;;                                |
;;                                |
;;                                o  (second edit)
;;                                |
;;                                |
;;                                x  (current buffer state)

Thanks

**Comment by purcell** [comment]
It looks like you have a different theme from any of the ones I use -- I'm guessing the problem is with the theme.

**Comment by liuxianming** [comment]
Thanks for the instant reply. I didn't change theme. However, I can try to see if it happens. Thanks very much.

**Comment by liuxianming** [comment]
@purcell Yes sir, it is because of the terminal I used. I use zsh on mac. If I change back to bash, everything works.

**Comment by purcell** [comment]
That's interesting -- I use `zsh` on OS X too. If you use a Terminal or iTerm theme, sometimes it can clash with the Emacs theme: that might be what is happening here.

**Comment by liuxianming** [comment]
@purcell Yes, that's just what I want to say. The terminal theme (actually, I set up oh-my-zsh theme in iTerm) overwrite emacs' theme setting. 

Thanks for the reply.

**Comment by purcell** [comment]
Glad you figured it out. :-)
