### ISSUE TITLE
Something about erlang syntax flycheck.

### ISSUE THREAD

**Issue by daizhongyi** [purcell/emacs.d#258]
First of all, thank you for your configuration. I am a novice. I use Erlang programming, but flycheck is not normal. How to configure it supports Erlang syntax testing?

**Comment by purcell** [comment]
`flycheck` works with Erlang files automatically for me without any configuration: you just need to make sure the `erlc` command is on your path. You can test whether Emacs can find that command using `M-: (executable-find "erlc")` -- it should return a string rather than `nil`.
