### ISSUE TITLE
term mode cannot input ctrl-r

### ISSUE THREAD

**Issue by zhengjiezxxy** [purcell/emacs.d#260]
when input ctrl-r, it became quotation mark, when the bare emacs don't have this problem.

**Comment by purcell** [comment]
Hmm, it works for me in Emacs HEAD with zsh on OS X. Which Emacs version do you have, with which shell, and on what platform?

**Comment by zhengjiezxxy** [comment]
I use emacs24 and bash under ubuntu 14.04 32bit. And it sometimes didn't work under ubuntu 14.04  64bit. I will try emacs HEAD anyway.

**Comment by zhengjiezxxy** [comment]
I found that when I remove evil from my init list, it works right. Thanks.

**Comment by purcell** [comment]
Aha, great! Glad you figured it out. I used `viper` for over 10 years to make my Emacs work like `vim`, but eventually just switched to using the Emacs bindings a few years ago. I still use `vim` in terminals though. :-)
