### ISSUE TITLE
Indentation in JS files does not align with existing row indent.

### ISSUE THREAD

**Issue by bgvianyc** [purcell/emacs.d#261]
Installed the latest emacs.d today with M-x version of: 

GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian.

When opening JS files. The automatic indentation is a few spaces behind the indent of the row. If you need more information, let me know.

**Comment by purcell** [comment]
I'm guessing that you might be opening files which contain tabs: the config assumes that tabs are equivalent to 8 spaces by default, while the increment for each level in indentation is 2 spaces. The solution will be different depending on whether this guess is correct, and what result you want.

You may have to customise `preferred-javascript-indent-level`, `js2-basic-offset` or `tab-width`, or set one or both of the latter in a `.dir-locals.el` file for the javascript files' directory.

**Comment by purcell** [comment]
P.S. Since coding conventions vary from project to project, having a `.dir-locals.el` for each project can be a helpful practice.

**Comment by stevejordan** [comment]
Another more generic option would be to use [editorconfig](https://github.com/editorconfig/editorconfig-emacs) along with a suitable `.editorconfig` file and have emacs apply this setting and any others you might want per project.

**Comment by bgvianyc** [comment]
Just to give you an example of the actual ident to confirm the solution is as described above, (THIS IS A TEST COMMENT) starts after hitting RET at the end of line above:

                    date: $("#txn_date").val(),
                  (THIS IS A TEST COMMENT)
                    explanation: $("#txn_expl").val(),
                    description: $("#txn_desc").val()
                };
                var new_txn = clicked_row.data();
                /*                                                                                                                                                                                                                                                              
                    txn.id, 0                                                                                                                                                                                                                                                   
                    txn.nw, 1                                                                                                                                                                                                                                                   
                    "", 2                                                                                                                                                                                                                                                       
                    fileName, 3                                                                                                                                                                                                                                                 
                    txn.date, 4                                                                                                                                                                                                                                                 
                    txn.desc, 5                                                                                                                                                                                                                                                 
                    Debit, 6                                                                                                                                                                                                                                                    
                 (THIS IS A TEST COMMENT)                                                                                                                                                                                                                                       
                    Credit, 7                                                                                                                                                                                                                                                   
                    txn.grade, 8                                                                                                                                                                                                                                                
                    txn.expl, 9                                                                                                                                                                                                                                                 
                */
                var txn_data = global_txns[new_txn[0]];
              (THIS IS A TEST COMMENT)

**Comment by purcell** [comment]
Thanks, but it's going to be hard to test or reproduce this based on a fragment like that. Are you able to post the original file somewhere (even by email to me: steve, sanityinc dotcom)?

**Comment by bgvianyc** [comment]
Check out this file pastebin, using the same insertion method as described above.

http://pastebin.com/JDnV2aQG

**Comment by purcell** [comment]
Thanks - that was really helpful. Here's what's going on:

When figuring out the indentation for a given line, `js2-mode` doesn't use only the previous line: it understands the block context of the line, and since `js2-basic-offset` is 2, it decides the correct indent is 2 spaces deeper than the line which starts the containing block -- e.g. the `THREE.AudioObject =` line in the pastebin example. (If you select the whole file with `C-x h` and then hit `TAB`, Emacs will reindent everything so you can see what it thinks the code should look like!)

Given this behaviour, there's no default Emacs setup which will correctly indent all the code you come across. You should therefore plan to customize `js2-basic-offset` to your preferred default value, and/or override it on a project-by-project basis. To do the latter, create a `.dir-locals.el` file in the project root directory, with the following contents:

```el
((js2-mode . ((js2-basic-offset 8))))
```

**Comment by bgvianyc** [comment]
The strange thing is that I use js2 mode in emacs on another machine without having this problem. I'm wondering if some other module interferes?

Changing the js2-basic-offset does change the indent problem. So I'm wondering if something else is interfering?

**Comment by purcell** [comment]
Do you use this same config on that other machine?

**Comment by bgvianyc** [comment]
No, I put the configuration together myself on the other machine 
including installing js2-mode. However there are other packages running 
on purcell/emacs.d that are not running on the other machine. That is 
why I suspect this maybe another package interferring

**Comment by purcell** [comment]
In addition to having further packages installed in this config, I'm also configuring `js2-mode` to a limited extent, including setting `js2-basic-offset`: see `~/.emacs.d/lisp/init-javascript.el`. Without setting `js2-basic-offset`, it apparently defaults to `c-basic-offset`, which may well be 8 for you. I might revert that part of my config...

**Comment by bgvianyc** [comment]
I fixed this issue by commenting out in init-javascript.el:

line 40: js2-basic-offset preferred-javascript-indent-level

line 47: (setq-default js-indent-level preferred-javascript-indent-level)
