### ISSUE TITLE
Emacs Shell cannot detect current path

### ISSUE THREAD

**Issue by jiangshanyu** [purcell/emacs.d#263]
Hi Purcell,

Thanks for your work.

I found that when I run m-x shell in Emacs on terminal (Yosemite), if I cannot click tab to find/complete the name of files in the current directory, as the shell only shows the files in my home directory. I don't have this problem in my linux pc.

(btw, I found it is very slow to start my emacs, what will be you recommendation to speed it up? I use emacs mainly for latex, org-mode, and python.)

**Comment by purcell** [comment]
> I found that when I run m-x shell in Emacs on terminal (Yosemite), if I cannot click tab to find/complete the name of files in the current directory, as the shell only shows the files in my home directory. I don't have this problem in my linux pc.

I'm also on Yosemite. TAB completion works for me inside `M-x shell`, I think. Can you give me specific steps to reproduce the problem you're seeing?

> (btw, I found it is very slow to start my emacs, what will be you recommendation to speed it up? I use emacs mainly for latex, org-mode, and python.)

It will always be slow the first time you start it up, because it has to install packages. After that it should be fast: most code is loaded only when needed. You could try commenting out some of the language-specific `require` lines in `~/.emacs.d/init.el` to see if that helps. Immediately after start-up, you can look at the `*Messages*` buffer to see which `.el` files took a long time to load. Feel free to paste that list here.

**Comment by jiangshanyu** [comment]
For the TAB completion, all I did is: run emacs on terminal, then M-x shell without having any extra steps....

For the start time, I pasted two *messages*, the first one on mu macbook and the second one on my Linux PC.
********Mac**********
("/Applications/Emacs.app/Contents/MacOS/Emacs-10.7")
Loading /Users/username/.recentf...done
Cleaning up the recentf list...done (0 removed)
Checking whether Dash is installed
Loading /Users/username/.emacs.d/custom.el (source)...done
init completed in 5264.70ms
Loading /Users/username/.emacs.d/.session...done
Loading vc-git...done
Desktop: 2656.77ms to restore ~/.emacs.d/init.el
OVERVIEW
Loading vc-svn...done
Desktop: 3477.59ms to restore ~/UN/SVN/Storage/todo.org
Could not find config file "~/.tidyrc".  Winging it. [2 times]
Loading mmm-sample...done
Desktop: 1952.28ms to restore ~/UN/web/xxxxxx.github.io/index.html
Wrote /Users/UN/.emacs.d/.emacs.desktop.lock
Desktop: 3 buffers restored.
Desktop restored in 8114.46ms
For information about GNU Emacs and the GNU system, type C-h C-a.

********Linux**********
Removing local package.el from load-path to avoid shadowing bundled version
Loading /directoryname/.recentf...done
Cleaning up the recentf list...done (0 removed)
Loading /directoryname/.emacs.d/custom.el (source)...done
init completed in 27725.81ms
Loading /directoryname/.emacs.d/.session...done
Wrote /directoryname/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 0 buffers restored.
Desktop restored in 197.90ms
For information about GNU Emacs and the GNU system, type C-h C-a.

**Comment by purcell** [comment]
> For the TAB completion, all I did is: run emacs on terminal, then M-x shell without having any extra steps....

I tried that too, and TAB completion works fine for me in all directories on OS X.

Not sure what to suggest.

> For the start time, I pasted two messages, the first one on mu macbook and the second one on my Linux PC.

Wow, the startup time difference is really surprising: 5 times slower on Linux. Now, it's *possible* that there's a lot of elisp in the Linux machine's system-wide `site-lisp` directory, which might adversely affect the startup time.

But beyond that, it's not obvious to me why there would be a problem there.

The OS X startup time is pretty much as I would expect.

**Comment by jiangshanyu** [comment]
Thanks! I will try to figure our what are the problems for the TAB one, and possibly live with the slow start up in Linux (it is at most once a day anyway).

**Comment by jiangshanyu** [comment]
Hi, here are something that might cause the TAB problem.
1. I have (setq shell-command-switch "-ic") in my init-local.el to set shell commend to be interactive. 
2.  To enable M-! to load .bash_profile, I have "if [ -f ~/.bashrc]; then source ~/.bashrc fi" in my  .bash_profile

But I cannot see why it would cause the TAB problem ...

**Comment by purcell** [comment]
Yep, not really sure either, sorry. Without a way to reproduce this issue locally, I can't offer any suggestions.

**Comment by jiangshanyu** [comment]
Finally..... The problem is, if you use alias for a path (e.g. alias A = 'cd ~/abc/def/g/'), then the shell in emacs won't detect the current path after running A.

**Comment by purcell** [comment]
Also odd, but doesn't sound specific to this config. You might try commenting out parts of the config to see if the problem is really related to it. Start with `init-exec-path.el` and `init-xterm.el`.

**Comment by jiangshanyu** [comment]
> Also odd, but doesn't sound specific to this config.
> 
I tested by renaming the whole .emacs.d, and the problem remains. So, it does not specific to your emacs config. It seems to be a general problem.

I just found the same question posted here:
http://emacswiki.org/emacs/ShellMode <http://emacswiki.org/emacs/ShellMode>

with the title 'Tracking the current working directory of the shell’.

It has not been solved yet.

**Comment by jiangshanyu** [comment]
I found some related text: 
    "Emacs has no way of knowing when the shell actually changes its
     directory. This is an intrinsic limitation of Unix. So, it tries
     to guess by recognizing cd commands. If you enter cd followed by
     a directory name with a variable reference (e.g., cd $HOME/bin)
     or with a shell metacharacter (e.g., cd ../lib*), Emacs will fail
     to correctly guess the shell's new current directory."

To solve it, we might manually tell the shell the current directory by M-x dirs; or use Dirtrack mode.

**Comment by azzamsa** [comment]
@purcell Hi Mr. Purcell.

Most of the time. `cd <dir name>` doesn't work for me. Until I run `M-x dirs` manually. As sugessted https://www.gnu.org/software/emacs/manual/html_node/efaq/Shell-mode-loses-the-current-directory.html

How do you handle that ?. Do you have to run `M-x dirs` manually ?

Especially when we extensively use `autojump` in emacs shell. It will lost current dir. And have to do `M-x dirs` manually. How do you jump to certain dir in emacs shell ? helm-find-files not fast as autojump.

Thank you in advance.

**Comment by azzamsa** [comment]
> Finally..... The problem is, if you use alias for a path (e.g. alias A = 'cd ~/abc/def/g/'), then the shell in emacs won't detect the current path after running A.

As @jiangshanyu mentioned. I spotted the problem. It comes from autojump. when I jump with `j` (autojump). emacs lost the current buffer and I need to run `m-x dirs`
