### ISSUE TITLE
annoying backup files

### ISSUE THREAD

**Issue by liyichao** [purcell/emacs.d#264]
I have set these in my init-local.el

```
(setq backup-directory-alist
      `(("." . ,(expand-file-name
                 (concat user-emacs-directory "backups")))))
(setq auto-save-file-name-transforms
      `((".*" ,(expand-file-name
                (concat user-emacs-directory "backups")) t)))
```

but when I edit files, backup file stays in current directory, for example when I edit `test.less`, there will be a file named `.#test.less` which is linked to `username@host.emacs_pid`, how to set it produced in `~/.emacs.d/backups` ?

**Comment by purcell** [comment]
I think "." should be ".*" there.
