### ISSUE TITLE
Bootstrap from behind proxy

### ISSUE THREAD

**Issue by mfehlhaber** [purcell/emacs.d#270]
Had to set proxy before the _Bootstrap_ section in order to use your config from behind a corporate firewall. init-preload-local.el was too late.

**Comment by purcell** [comment]
How were you setting the proxies? Or are you on a mac, and relying on `init-proxies.el`?

**Comment by mfehlhaber** [comment]
I am on Windows there...

```lisp
(setenv "http_proxy" "http://proxy:8080")
(setenv "https_proxy" "https://proxy:8080")

(setq url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10.*\\)")
     ("http" . "proxy:8080")
     ("https" . "proxy:8080")))
```

**Comment by sjy** [comment]
I met up with same issue,  is it better to really preload the  'init-preload-local.el' ? Besides, may be init-peoxy.el is a plus? Since proxy settings differs and what if our configure script auto detect OS type and apply IE proxy by default ?

**Comment by kecode** [comment]
![image](https://user-images.githubusercontent.com/23140388/84880334-f772eb80-b0be-11ea-9789-b744742d2791.png)
me too.

**Comment by kecode** [comment]
> Had to set proxy before the _Bootstrap_ section in order to use your config from behind a corporate firewall. init-preload-local.el was too late.



> Had to set proxy before the _Bootstrap_ section in order to use your config from behind a corporate firewall. init-preload-local.el was too late.

Did you solve it later?

**Comment by Eason0210** [comment]
I recommand use your local Melpa mirrors instead of proxy.  For example the bellow mirror can be use for Chinese user, the speed is fast.

```
(add-to-list 'package-archives '( "melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/") t)
```
