### ISSUE TITLE
Can't get syntax highlighting for nim files to work.

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#271]
First of all thanks to you and all others for you labour of love. I'm having a challenge getting emacs to provide syntax highlight for .nim file. Here is what I've done so far. In the lisp folder under .emacs.d, I've created an init-nim-mode.el which contains the following code:
```
;;; Basic nim setup

(require-package 'nim-mode)
(require-package 'ac-nim')


;; Use nim-mode for .nim file extention
(add-auto-mode 'nim-mode "\\.nim\\'")


(provide 'init-nim-mode)
```
I have also downloaded and installed the nim compiler with ```brew install nim```. I am able to compile scripts on the command line. 

My understanding is that once I create the appropriate ```init-``` with the correct require-package command, emacs will automatically download and install the mode if its not present. The strange thing is that, that did not happen after several restarts of emacs. I therefore install both ```nim-mode``` and ```ac-nim``` manually. Yet I still cannot get basic syntax highlighting to work.

I even removed the elpa folder and restarted emacs. I downloaded and installed everything except ```nim-mode``` and ```ac-nim```.

**Comment by purcell** [comment]
This:
```
(require-package 'ac-nim')
```
should be
```
(require-package 'ac-nim)
```

Is that perhaps the problem?

**Comment by purcell** [comment]
Oh, and you should also add `(require 'init-nim)` to `init.el`.

**Comment by thepreacher** [comment]
Thanks for your help. I did as you ask only that I put the ```(require 'init-nim-mode)``` to ```init-local.el``` according to your read me. I figured if I added it to ```init.el``` and did a ```git pull``` it'll get overwritten. Strange thing though and I guess it's because I'm an emacs noob but I had to comment out the line ```(add-auto-mode 'nim-mode "\\.nim\\'")
```
in init-nim-mode.el for syntax highlighting to work. Anyway it's working now.

**Comment by purcell** [comment]
> I did as you ask only that I put the (require 'init-nim-mode) to init-local.el according to your read me. I figured if I added it to init.el and did a git pull it'll get overwritten. 

yep, that's fine.

> Strange thing though and I guess it's because I'm an emacs noob but I had to comment out the line (add-auto-mode 'nim-mode "\\.nim\\'")
> in init-nim-mode.el for syntax highlighting to work. Anyway it's working now.
