### ISSUE TITLE
Getting the below error while trying to open python code.

### ISSUE THREAD

**Issue by omps** [purcell/emacs.d#272]
Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output:Checker definition probably flawed.

**Comment by omps** [comment]
Soory this is fixed in the flycheck update. Closing now.

**Comment by omps** [comment]
flycheck/flycheck#635

**Comment by omps** [comment]
Looks like the above issue didn't fix the bug, and same error as reported earlier is still persistent. :)

**Comment by purcell** [comment]
You probably have an incompatible flake8 version. This doesn't seem like something specific to my `.emacs.d` config.

**Comment by purcell** [comment]
Specifically, I don't have any related configuration for `flycheck`, or `flake8`, so I'll close this issue, but please feel free to continue to discuss it here because I'm happy to help if I can.

**Comment by omps** [comment]
Thanks, yes I modified your emacs a little, but then I cloned your emacs.d from scratch and tried to run again, somehow I am getting the same error, trying to figure out what could be wrong here. Do you think there could be issue with flake8?

**Comment by purcell** [comment]
> Do you think there could be issue with flake8?

Yes, that would be my guess. Hey @lunaryorn, is there a way to make `flycheck` show the raw command output to aid in debugging this sort of issue?

**Comment by lunaryorn** [comment]
@purcell `C-c ! C-c python-flake8` will run flake8 and shows its output in a separate buffer.  `C-c ! v` will also be of interest, as it shows the state of syntax checkers.

I wonder why `flake8` fails.  Last time I look, its tests passed fine.  I rather think that there's an issue with the OP's system.

**Comment by omps** [comment]
@lunaryon Actually, I first thought it could be issue with the system, but
after trying on to other systems the problem remains. I in fact tried
building spurcell Emacs from scratch too. But I would check the commands
and report the output in the evening.

**Comment by omps** [comment]
Well I think i found the error, i hope this should be correct, actually my bad i overlooked the code, and thought its bug with flychek. :) thanks for helping. Both the commands you suggested above does work.

**Comment by purcell** [comment]
Great, glad you figured it out.
