### ISSUE TITLE
M-x usage

### ISSUE THREAD

**Issue by lybeen** [purcell/emacs.d#276]
Why not can I use M-x in my terminal??
I use emacs -nw to open emcas in my iTerm2

**Comment by purcell** [comment]
In iterm with the standard settings, I use Alt/Option as the Meta key. Depending on your iTerm2 settings, that may or may not work for you.

**Comment by lybeen** [comment]
thank u purcell

**Comment by freegnu** [comment]
I was doing just that and then I realized that a full emacs session
launched from the app it even better. Especially when you combine it with
emacs 24.1 transparency or toggle-frame-fullscreen without a menu or
toolbar. C-u M-x shell on remote directories opened like C-x C-f
/ssh:user1@host1|sudo:user2@host1: for most remote terminal work and M-x
term to reconnect to remote screen sessions. It makes it easy to C-x C-f or
C-x C-r in a shell and open a file or directory and v(iew) and o(pen) files
or v(iew) and then e(dit) files if I need to with remote directory
tracking. The true icing on the cake is when you remote debug a python file
using M-x pdb and change the command to python -m pdb file.py and it all
runs remotely.

I'm not saying that you can't do the same things in a terminal. I just
don't know why I did it and put up with C-arrow and M-arrow errors and
basic mouse inconsistences. It doesn't take much time browsing in M-x
customize-group emacs and it children and C-x C-s to set and store those
changes to get history and completetion and ido working everywhere. My
favorite is adding the melpa package archive to the packages customization
group and getting ido-vertical installed with a M-x list-packages.

**Comment by purcell** [comment]
@freegnu Agreed! :-)
