### ISSUE TITLE
emacs orgmode org-clock bugs

### ISSUE THREAD

**Issue by fengruifei** [purcell/emacs.d#277]
(setq org-time-clocksum-format
       '(:hours "%d" :require-hours t :minutes ":%02d" :require-minutes t))

this variable is not a string, cause emacs report error when using org clock.
like this.
org-clock-get-clock-string: Wrong type argument: stringp, (:hours "%d" :require-hours t :minutes ":%02d" :require-minutes t

**Comment by purcell** [comment]
Thanks. How can I reproduce this? I'm using org clock with this configuration, and I haven't seen this problem.

**Comment by fengruifei** [comment]
I have no ideal.
I will check this tommow.
May becouse the version of orgmode I used.

Steve Purcell <notifications@github.com>于2015年7月1日周三 下午1:44写道：

**Comment by purcell** [comment]
Yes, it could be. I'm using the org-mode included in recent Emacs versions.

**Comment by fengruifei** [comment]
i upgrade my orgmode from 7.9 to 8.2
it seems everything works fine.
thanks for help☺

Steve Purcell <notifications@github.com>于2015年7月2日周四 上午4:36写道：

**Comment by purcell** [comment]
Great!
