### ISSUE TITLE
how to disable paredit-everywhere

### ISSUE THREAD

**Issue by fanbingxin** [purcell/emacs.d#278]
It seems that paredit-everywhere is enabled in every major mode by default.  How to disable it? 
Thanks.

**Comment by purcell** [comment]
You can just edit `~/.emacs.d/lisp/init-paredit.el` and remove the section relating to `paredit-everywhere`. Hope that helps!

**Comment by fanbingxin** [comment]
Thanks for  your help!
What I mean is how can I enabled it manually like this `(add-hook 'css-mode-hook 'paredit-everywhere-mode)`, rather than enabled by default.
Forgive my poor english. Thanks!

**Comment by purcell** [comment]
Ah, okay. The reason you're seeing it in many major modes is because of the line which adds it to `prog-mode-hook`. Just remove that line, and then add specific hooks as needed, like in your example. :-)

**Comment by fanbingxin** [comment]
It works! Thank you very much!

**Comment by purcell** [comment]
Were there particular modes in which it didn't work well for you? I can perhaps turn it off in those modes for everyone...

**Comment by fanbingxin** [comment]
I mostly use `go-mode`. I have been using your emacs config for a long time. About a month ago, after `git pull`, I found `([{"` become auto closed like in `paredit-mode`, then I found `Par-` at status line.  I thought it was `paredit-everywhere-mode` that caused this behavior. With your help,  I disabled the  `paredit-everywhere-mode`. However, the autoclosed still exists.

**Comment by purcell** [comment]
It's probably due to `electric-pair-mode`, which was added to Emacs in recent releases, so try disabling that in `go-mode`.
