### ISSUE TITLE
Comments are coming in centre.

### ISSUE THREAD

**Issue by omps** [purcell/emacs.d#279]
I am using your .emacs.d but had my customisation placed in init-local file, i am trying to put a comment but the emacs is automatically putting it into the centre, also while copy some code from browser to emacs, emacs takes lot of time while pasting it into the buffer, could you please help suggest which modules might be initiating this behaviour.

I am attaching the screenshot here.
![screenshot 2015-07-05 05 30 58](https://cloud.githubusercontent.com/assets/985481/8509787/000f7c1a-22d8-11e5-817b-ae2a161574d9.png)

**Comment by purcell** [comment]
Use `;;` for comments on their own line. `;` comments are for adding comments after the code on a single line. Please refer to the [Emacs Lisp Reference](https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html). Hope that helps!

**Comment by omps** [comment]
thanks a lot sir.
