### ISSUE TITLE
Conflicts since Magit updated to v 2

### ISSUE THREAD

**Issue by bgvianyc** [purcell/emacs.d#280]
I noticed there are several conflicts since magit was auto updated to the latest version. Ie: git-commit-mode.

**Comment by purcell** [comment]
The config has been updated to work with the latest `magit`, so please first make sure you have the latest version of this config installed. Re. the conflicts, you should get a startup message which tells you to remove the obsolete `git-commit-mode` and `git-rebase-mode` packages. Once you've done that, and restarted Emacs, please let me know whether you still experience any problems.

**Comment by bgvianyc** [comment]
Magit seems to work fine now, there are some other issues after the upgrade, like mousescroll no longer works the same way. I noticed the build is not currently passing, should I just wait until it passes and then pull again?

**Comment by purcell** [comment]
Don't necessarily trust the build -- that's mainly a smoke test to make sure the config starts up cleanly on all the supported Emacs versions.

What's changed with the mouse scrolling?

**Comment by bgvianyc** [comment]
Before the mouse scroll was a smooth scroll now its scrolls down a screen and half, There also seems to be an issue with flycheck now and when opening a new file it does not bring the buffer to the foreground. Here is what shows up in messages on startup:

byte-code: Symbol's function definition is void: flycheck-checker-option-vars
Could not find config file "~/.tidyrc".  Winging it. [2 times]

**Comment by purcell** [comment]
It's probably aborting start-up before it reaches the part of the config which deals with scrolling. The "Symbol's function definition is void" message looks like the problem. Are you getting that even after removing and reinstalling the `flycheck-ledger` package? You shouldn't be. If in doubt, delete `~/.emacs.d/elpa/flycheck-*` and restart Emacs.

**Comment by bgvianyc** [comment]
That seems to have fixed it. Thanks

**Comment by purcell** [comment]
Great!
