### ISSUE TITLE
Error running timer `highlight-symbol-temp-highlight': (void-variable multiple-cursors-mode)

### ISSUE THREAD

**Issue by Enzo-Liu** [purcell/emacs.d#281]
After the latest commit@7099bbd041c1dbb6c6d315643797998be183c77a[Don't highlight symbols while multiple-cursors is active]. 
When I start emacs (init), this error msg occurs in the \*Messages\* buffer. 
```
Error running timer `highlight-symbol-temp-highlight': (void-variable multiple-cursors-mode) [2 times]
nil
Error running timer `highlight-symbol-temp-highlight': (void-variable multiple-cursors-mode)
nil [2 times]
```

I think the problem is that variable `multiple-cursors-mode` was not properly initialized.

Putting  
``` emacs-lisp
(multiple-cursors-mode) 
```
or
``` emacs-lisp
(require 'multiple-cursors-core)
```
in the init file can fix the problem.

But I don't know weather it's the good way to do so.
Consider to fix this?

**Comment by purcell** [comment]
Sorry about that -- fixed now.
