### ISSUE TITLE
is there any emacs configuration for golang

### ISSUE THREAD

**Issue by YuleiXiao** [purcell/emacs.d#282]
I use golang for some time, but I still do not get a comfortable edit for it. Is there any good plugins for golang?

**Comment by purcell** [comment]
Hmm, not really sure, because I don't use Go. There's a bunch of relevant stuff MELPA which you might like to try out, though: http://melpa.org/#/?q=go-

**Comment by YuleiXiao** [comment]
thanks a lot. @purcell
