### ISSUE TITLE
Flycheck message be covered by occurrence message

### ISSUE THREAD

**Issue by kongfy** [purcell/emacs.d#283]
When I want to read the flycheck warning or error messages, It just give me a few seconds, and then soon be replaced by a message like "2 occurrences in buffer".

Do I miss something?

**Comment by purcell** [comment]
I've noticed that too. I'll see if I can fix it. :-)

**Comment by purcell** [comment]
Hmm. I can't currently reproduce this. Have you changed `highlight-symbol-print-occurrence-count` from its default? By default, this message isn't displayed.

**Comment by kongfy** [comment]
Where are those code ? I don't remember I changed something like this.

**Comment by purcell** [comment]
Please can you try `M-:`, then enter `highlight-symbol-print-occurrence-count` and tell me what you see?

**Comment by kongfy** [comment]
Bottom buffer shows:
Symbol's value as variable is void: highlight-symbol-print-occurrence-count

**Comment by kongfy** [comment]
I'm really sorry...
I should have updated all the packages before openning this issue.
That solves the problem.

Thank you for your time!

**Comment by purcell** [comment]
Ah, great! I must have been remembering the problem from a while ago. :-) Glad it's working for you now.
