### ISSUE TITLE
package management

### ISSUE THREAD

**Issue by magichowl** [purcell/emacs.d#286]
Apart from package.el, I use el-get to manage packages as there are some packages only in github or those forked at my page,
so I can add those by 
```
(setq el-get-sources
  '( (:name blahblah :type github :pkgname "magichowl/blahblah")
)
```
As to the advantage of package.el, I can use function

 package-install-file 

without el-get some large packages, and I can install the stable version of some package. 

Do you have any different point?  Can one (package.el, el-get) replace the other?

 Recently, I found another management package called "quelpa" 

https://github.com/quelpa/quelpa

It combines some features of el-get and package.el. Seems interesting, but I'm careful to try it as it require reconfigure a lot in emacs. 

Any suggestions? Thanks in advance. :smile:

**Comment by purcell** [comment]
If there are officially-maintained packages in github which you think should be installable with `package.el`, please submit recipes to MELPA (http://melpa.org/)

For personal forks, by all means use quelpa. It is based on the code we use for MELPA, which I help to maintain. I've never used it myself, so I can't really provide any advice in that area, sorry.

Hope that helps!
