### ISSUE TITLE
error: Package `emacs-24.4' is unavailable again

### ISSUE THREAD

**Issue by lyqscmy** [purcell/emacs.d#287]
I have seen #194. It should be resolved.But I get this error when I start emacs.My emacs version is 24.3.1

**Comment by purcell** [comment]
Please start emacs with `--debug-on-init` and paste the corresponding stacktrace here so we can see which package is causing this problem. Thanks!

**Comment by purcell** [comment]
(If you're on a Mac, you can start Emacs like this from Terminal with a command like `/Applications/Emacs.app/Contents/MacOS/Emacs --debug-init`.)

**Comment by lyqscmy** [comment]
I use linuxmint17.2. I have installed emacs24.5 on my machine.It works well.sorry , I didn't record the debug information.

**Comment by purcell** [comment]
Addressed via #288 and related changes.
