### ISSUE TITLE
Enable smoke tests on Emacs 24.1 / 24.3

### ISSUE THREAD

**Issue by purcell** [purcell/emacs.d#288]
See #287.

Solution is probably to switch Travis build to [EVM](https://github.com/rejeep/evm).

**Comment by alanyu1** [comment]
I also meet such problem. my emacs version 24.3. here is my message 
Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Error while loading 50dictionaries-common: Symbol's value as variable is void: debian-aspell-only-dictionary-alist
Loading /home/mindray/.recentf...done
Cleaning up the recentf list...done (0 removed)
Couldn't install package `magit': (error "Package `emacs-24.4' is unavailable")
Couldn't install package `git-commit': (error "Package `emacs-24.4' is unavailable")
Couldn't install package `github-clone': (error "Package `emacs-24.4' is unavailable")
Couldn't install package `magit-gh-pulls': (error "Package `emacs-24.4' is unavailable")
Couldn't install package `flycheck-elm': (error "Package `emacs-24.4' is unavailable")
Loading /home/mindray/.emacs.d/custom.el (source)...done
init completed in 3260.15ms
Loading /home/mindray/.emacs.d/.session...done
Wrote /home/mindray/.emacs.d/.emacs.desktop.lock
Desktop: 0 buffers restored.
Desktop restored in 5.53ms
For information about GNU Emacs and the GNU system, type C-h C-a.
command-line-1: Unknown option `--debug-on-init'

**Comment by purcell** [comment]
`--debug-on-init` should be `--debug-init`. Where did that come from?

**Comment by purcell** [comment]
Ah, I see that it was in my comment on #287. Please try that out and comment on that issue with the specific problem you're seeing.

**Comment by alanyu1** [comment]
Thanks ,I saw the key to solve this problem is the version of emacs. So I updated it to 24.5 and it works.

**Comment by purcell** [comment]
Done.
