### ISSUE TITLE
M+{ will insert a pair brace , can't move by code block

### ISSUE THREAD

**Issue by zhuoyikang** [purcell/emacs.d#290]
how to change this ?
pleaese help

you can test by open any ruby or python file.

**Comment by emuio** [comment]
add this
(add-hook 'python-mode-hook 'turn-off-paredit-everywhere-mode)
(add-hook 'ruby-mode-hook 'turn-off-paredit-everywhere-mode)
in your init-local.el file.
Reopen the emacs app and the python file.

**Comment by zhuoyikang** [comment]
@emuio thanks.

**Comment by purcell** [comment]
Fixed more directly in paredit-everywhere now. Thanks.
