### ISSUE TITLE
editing xml in emacs can be very slow

### ISSUE THREAD

**Issue by banyudu** [purcell/emacs.d#293]
Platform: Windows 7 & 10, 64bit

If the xml file has a big region of comment, such as

    

emacs can be very very slow when editing the comment region.

But a one-line comment such as `<!-- hello emacs -->` doesn't make emacs slow.

**Comment by redguardtoo** [comment]
usually it's flyspell-mode.

**Comment by banyudu** [comment]
So what's the solution? Just turn off flyspell-mode?

**Comment by redguardtoo** [comment]
you could turn off flyspell-mode on certain projects, and use flyspell-buffer instead.

**Comment by purcell** [comment]
> you could turn off flyspell-mode on certain projects, and use flyspell-buffer instead.

You can also disable flyspell in `nxml-mode`. Take a look at `lisp/init-flyspell.el`. This is a bit of a pathological case, so I don't think there's anything which needs changing in this config.
