### ISSUE TITLE
custom.el always missing

### ISSUE THREAD

**Issue by emuio** [purcell/emacs.d#297]
My custom.el file is always replaced in default one.
I just update the 'Org-mode', which version is 8.3.1 20150831.And restart the Emacs,I got this message:

    Invalid function: org-babel-header-args-safe-fn

So I byte compiled ob-R.el 
This moment the custom.el is replaced the default one.
I don't know which steps do this. And how can I prevent this next time?

**Comment by purcell** [comment]
If startup fails because a package is broken, then the custom file doesn't get set up, and it might get overwritten. So the main problem here, I think, is that the org package is broken. I just use the `org` built into recent Emacs versions, and I don't have this problem.

**Comment by emuio** [comment]
what's your org-mode version?
So I need to backup the custom.el file every time when I update the elpa packages.

**Comment by emuio** [comment]
If I need create another custom config file for my personal cfg(e.g. my-custom.el).

**Comment by purcell** [comment]
No, my point is that the `custom.el` scheme works just fine, but if you have a broken package at start-up time, the customisation system doesn't get properly initialised, and so you get this problem. The solution is to fix the broken package, which appears to be `org` in this case. I don't have an `org` package installed: I'm just using the `org` bundled into my recent Emacs version.

**Comment by purcell** [comment]
P.S. I saw the same behaviour myself when I installed the upstream `org` package, so I uninstalled it.

**Comment by emuio** [comment]
OK, thank you for explain it.
