### ISSUE TITLE
open ".jsp" file, html-mode doesn't work

### ISSUE THREAD

**Issue by liuchunhua** [purcell/emacs.d#298]
init-html.el:
(add-auto-mode 'html-mode "\\.(jsp|tmpl)\\'")
==> "\\.\\(jsp\\|tmpl\\)\\'"

**Comment by purcell** [comment]
Hi! Thanks, but "doesn't work" isn't a bug report. Please can you be more specific? And is there a different mode which would be preferable?

**Comment by purcell** [comment]
Okay, I found what you meant.
