### ISSUE TITLE
org-mode doesn't show any global TODOs after fetch upstream

### ISSUE THREAD

**Issue by alant** [purcell/emacs.d#300]
Hi Steve,

I really like your emacs setting. I just add the line numbers via "(global-linum-mode t)" in init-local.el and use everything else you've configured. Thank you. 

After syncing my fork, however, my org-mode no longer shows any TODOs after C-c a t. I use emacs in OSX Yosemite.  I installed it via homebrew. Here is the version:

$ emacs --version
GNU Emacs 24.5.1

I was able to see a list of un-done TODOs with a previous cloned version of yours. Since I switched to fork and added line numbers I started having this issue.

Do you know if this is an issue cause by any changes recently? Thank you very much.

**Comment by purcell** [comment]
Hard to say without knowing how old your previous version was. A few things have [changed in the org config](https://github.com/purcell/emacs.d/commits/master/lisp/init-org.el) this year, but `C-c a t` should still work. First check that your `org-agenda-files` variable is customised correctly: that's what determines where the command looks for `TODO` entries.

**Comment by alant** [comment]
Did a search for org-agenda-files on Google. C-c [ did the trick. This is
totally not intuitive for someone new to org-mode. Thank you. You rock
Steve!

**Comment by purcell** [comment]
Yeah, it's perhaps a bit obscure. It's in the org menu, though. Glad you figured things out!

**Comment by alant** [comment]
I've been agonizing over this one for a few days. Did a bunch of Google
search prior to writing to you. Only after you mentioned org-agenda-files  ,
I was able to get it working. Thank you so much!

**Comment by purcell** [comment]
Happy to help. Enjoy organising your TODOs. :-)
