### ISSUE TITLE
How do I use company for completion instead of auto-complete?

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#302]
Hi Sir, I am using your .emacs.d as a base for my own config. At the moment, I haven't made any changes to your code at source. Every change of my has been made via init-local.el of other custom .el files. I use elpy for python development and I will really like to use company for completion instead of auto-complete which comes with your .emacs.d by default.

What will be the best way to acomplish this, not just for elpy mode but for any mode where I'll like to use company for?

**Comment by purcell** [comment]
You'd currently have to change a ton of stuff, I think. I plan to switch the whole config over to `company`, but I haven't had chance to work on that yet.

**Comment by thepreacher** [comment]
Ok. I'll keep an eye out :)
