### ISSUE TITLE
Problems on Windows 8

### ISSUE THREAD

**Issue by bwang7** [purcell/emacs.d#303]
Hi, I am using the Windows 8 system, when I download your emacs configuration files and open emacs  it says 

Warning (initialization): An error occurred while loading `c:/HOME/.emacs.d/init.el':

error: Package `fullframe-' is unavailable

is there something wrong?

Thanks.

**Comment by purcell** [comment]
Which Emacs version?

**Comment by bwang7** [comment]
Emacs 24.5.1 (i686-pc-mingw32)

**Comment by bwang7** [comment]
I saw the debug log, it says 
Opening TLS connection to `melpa.org'...failed
maybe there is something wrong with the network setting?

**Comment by bwang7** [comment]
Hi Steve, I have found where went wrong, it seems like I didn't enable GNUTls on my computer, this is pretty tricky on windows. I enable GNUTls follow this article 
http://xn--9dbdkw.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html

maybe you can tell a anyone who have the same problem about this article, this is really useful.
Thanks, really appreciate your emacs configuration file.

**Comment by purcell** [comment]
Great, glad you figured it out.
