### ISSUE TITLE
A show error in Mac OS X El Capitan

### ISSUE THREAD

**Issue by BiosSun** [purcell/emacs.d#304]
Scroll to the top，show it:

![image](https://cloud.githubusercontent.com/assets/2755933/10473663/754f4424-7260-11e5-83e3-582c39b334c1.png)

emacs version: Emacs For Mac OS X 24.5-1
system version: OS X 10.11

**Comment by Stelgard** [comment]
I've the same problem. However I think it is a package problem...

**Comment by purcell** [comment]
It's an Emacs bug - see http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21662. As a temporary workaround, you might like to customize `visual-bell` to nil.

**Comment by emuio** [comment]
Perhaps the variable is visible-bell

**Comment by purcell** [comment]
oops, right
