### ISSUE TITLE
edit clj file will make cpu full busy

### ISSUE THREAD

**Issue by mut0u** [purcell/emacs.d#305]
I update the emacs.d and I found emacs will make  excessive CPU utilization when I edit the clojure files on Mac OS X El Capitan.

I watch the Activity Monitor and find that emacs make CPU rate almost 100 percent.

**Comment by purcell** [comment]
I can't duplicate this locally on El Capitan with a recent Emacs version by just opening a couple of randomly selected clojure file. Can you give me any more information so that I can investigate?

**Comment by mut0u** [comment]
I am not very clear about all my environment . 

My Emacs is install by Homebrew like

```
   brew install emacs --cocoa
```

My Mac is  OS X 10.11

my lein profiles.clj  like this


```
:plugins [[lein-exec "0.3.3"]
                  [cider/cider-nrepl "0.9.0"]    ;; cider-nrepl 0.10.0 will display triple logs in terminal
                  [refactor-nrepl "1.1.0-SNAPSHOT"]
                  [lein-immutant "1.2.1"]
                  [com.jakemccrary/lein-test-refresh "0.10.0"]
                  [lein-gen "0.2.1"]
                  [lein-drip "0.1.1-SNAPSHOT"]
                  [jonase/eastwood "0.2.1"]
                  [lein-kibit "0.0.8"]
                  [lein-ritz "0.7.0"]
                  [lein-sub "0.3.0"]]

        :dependencies [[org.clojure/tools.nrepl "0.2.7"]
                       [alembic "0.3.2"]
                       ;;[org.clojure/core.typed "0.2.72"]
                       ;;[jonase/eastwood "0.2.1" :exclusions [org.clojure/clojure]]
                       ;;[jonase/kibit "0.0.8"]]
        :repl-options {
                       :timeout 120000
                       :nrepl-middleware
                       [cider.nrepl.middleware.classpath/wrap-classpath
                        cider.nrepl.middleware.complete/wrap-complete
                        cider.nrepl.middleware.info/wrap-info
                        cider.nrepl.middleware.format/wrap-format
                        cider.nrepl.middleware.inspect/wrap-inspect
                        cider.nrepl.middleware.macroexpand/wrap-macroexpand
                        cider.nrepl.middleware.pprint/wrap-pprint
                        cider.nrepl.middleware.resource/wrap-resource
                        cider.nrepl.middleware.stacktrace/wrap-stacktrace
                        cider.nrepl.middleware.test/wrap-test
                        cider.nrepl.middleware.trace/wrap-trace]}}

```


 and my emacs.d config based on commit e20032e5761b44b178b50779273193a377e660ff


I find commit b6e9333f72e50c5c6d8f2efaf9e9ab251be7ff29 maybe solve the problem, but I failed.


I found that when I edit large file with 100+ lines , the emacs will be very slow, when the file lines blow 100 , I can tolerate the speed. 


I change the emacs to emacs-mac 

```
    brew install emacs-osx
```


It seems faster a little , but it useless when editing large files.

**Comment by purcell** [comment]
My guess is that the problem is due to `eastwood`, `kibit` or `typed` -- my config includes the `flycheck-clojure` package, and probably `flycheck` is trying to run these checkers. To confirm this, try modifying [init-clojure-cider.el](https://github.com/purcell/emacs.d/blob/master/lisp/init-clojure-cider.el) to remove any mention of the `flycheck-clojure` package, then restart Emacs. You'll probably find everything works better. If that helps, you should contact the `flycheck-clojure` maintainer for further help. :-)

**Comment by mut0u** [comment]
I think it is caused by `flycheck`. I delete the `flycheck-clojure`  config and run is  both mac and ubuntu. 
The result is that ubuntu is faster than mac, but the ubuntu emacs24.5 which was builded with source code still will deadlock for a little while. 

If I find the reason about it , I will tell you  :-(
