### ISSUE TITLE
Tag and bracket closing with and without electric-pair-mode

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#306]
I don't know emacs-lisp and although I'm able so understand a fair bit of your code most of them are over my head. Therefore I never make any changes to .el files that you provide. All my changes are in init-local.el plus additional .el files that I add.

I use web-mode as the major mode for editing .html files because I get better Django template support than your default config. I also use elpy for Python and Django related code. 

With electric-pair-mode on, I get additional closing tags for django and html in my .html file. Therefore I disable electric-pair-mode using the following code:
```
(defun turn-off-electric-pair-mode ()
  "Disable `electric-pair-mode'."
  (electric-pair-mode -1))
;; Disable electric-pair-mode
(add-hook 'web-mode-hook 'turn-off-electric-pair-mode)
```
However with electric-pair-mode off, I loose bracket completion in my .py files. I know it's not a big deal but it just kind of bothers me from time to time. Is there a way of disabling ```electric-pair-mode``` for only web-mode?

Also, apart from deleting ```(add-hook 'prog-mode-hook 'paredit-everywhere-mode)``` from init-paredit.el, is there any way of disabling ```paredit-everywhere-mode``` for only web-mode?

**Comment by purcell** [comment]
> However with electric-pair-mode off, I loose bracket completion in my .py files. I know it's not a big deal but it just kind of bothers me from time to time. Is there a way of disabling electric-pair-mode for only web-mode?


Sure: `electric-pair-mode` is the global mode, but it just enables `electric-pair-local-mode` in each buffer, so I think you can do this:

```el
(add-hook 'web-mode-hook 'electric-pair-local-mode)
```

> Also, apart from deleting (add-hook 'prog-mode-hook 'paredit-everywhere-mode) from init-paredit.el, is there any way of disabling paredit-everywhere-mode for only web-mode?

Maybe

```el
(add-hook 'web-mode-hook (lambda () (paredit-everywhere-mode -1)))
```

?

**Comment by purcell** [comment]
Closing this issue, but feel free to discuss or ask further questions.
