### ISSUE TITLE
my startup is so slow

### ISSUE THREAD

**Issue by lybeen** [purcell/emacs.d#307]
Hi Purcell
Today My emacs starts so slow
When I start my emacs in terminal(emacs -nw),  emacs showing the message 'cleaning up the recentf list'  so long, and finally show the error 'command-line-1: Unknown option `-''

Why? below is the message

Loading /Users/binlai/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
ad-handle-definition: `find-function-search-for-symbol' got redefined
Checking whether Dash is installed
Loading /Users/binlai/.emacs.d/custom.el (source)...done
init completed in 77951.22ms
Loading /Users/binlai/.emacs.d/.session...done
Desktop: 569.06ms to restore nil
Desktop: 335.26ms to restore ~/.emacs.d/lisp/init-local.el
Wrote /Users/binlai/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 2 buffers restored.
Desktop restored in 912.80ms
For information about GNU Emacs and the GNU system, type C-h C-a.
command-line-1: Unknown option `-'

**Comment by purcell** [comment]
What changed today? Did you change or update code, or your system?

**Comment by lybeen** [comment]
I delete one folder files in Mac Finder which is opened in emacs, and I found emacs crash in terminal
and I restart my emacs , the problem occured 
I delete the file recentf in .emacs.d , it seems ok now
