### ISSUE TITLE
Error from syntax checker emacs-lisp-package: Search failed: "^;+[ 	]+\\(@(#)\\)?[ 	]*\\$?\\(?:Package-\\(?:Requires\\|Version\\)\\)"

### ISSUE THREAD

**Issue by magichowl** [purcell/emacs.d#309]
As the title

for GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6) of 2015-09-18 on lgw01-52, modified by Debian
```
Error from syntax checker emacs-lisp-package: Search failed: "^;+[ 	]+\\(@(#)\\)?[ 	]*\\$?\\(?:Package-\\(?:Requires\\|Version\\)\\)"
```

I tried for emacs 25.0.50.2, error is 
```
Symbol's value as variable is void: seq
```
and backtrace is 
![qq 20151029222035](https://cloud.githubusercontent.com/assets/1439061/10821061/51d097aa-7e8b-11e5-9be9-35b67c0c0afe.png)

**Comment by purcell** [comment]
Yikes, sorry -- that was due to an error I made in `flycheck-package`, and I've just fixed it now. When the new version of that package builds (in the next few hours), just update it and that should fix the problem. Apologies once again.

**Comment by purcell** [comment]
Actually, I think those are 2 separate problems. The second one looks like maybe you installed the packages in a different version of Emacs, and now the bytecode doesn't match: you should delete the contents `~/.emacs.d/elpa/` if you change Emacs version significantly.

**Comment by magichowl** [comment]
thanks, both problems are solved
