### ISSUE TITLE
emacs always disappear(I think crash) in windows

### ISSUE THREAD

**Issue by chechunli** [purcell/emacs.d#310]
Hi purcell,
    Your emacs config is great, I use it from the beginning of this year. But I found my emacs always disappear when I 'm using.
    emacs version is 24.3, it's installed by cygwin, launched by  XWin Server(also installed from cygwin).
When it's disappear, I can't find any sign or clue. 
    Could you get me some suggestion ? 
    e.. by the way, one more question, when emacs boot up, it always  connect melpa.org:443, it will take a long time. Can I disable it ?

**Comment by purcell** [comment]
> Hi purcell,
> Your emacs config is great, I use it from the beginning of this year. But I found my emacs always disappear when I 'm using.
> emacs version is 24.3, it's installed by cygwin, launched by XWin Server(also installed from cygwin).
> When it's disappear, I can't find any sign or clue.
> Could you get me some suggestion ?

It sounds like some kind of platform-specific issue, and I don't have access to a Windows machine to test on. Perhaps try starting Emacs from a terminal window so that you can see if a message is printed when Emacs crashes. Alternatively, see if the XWin Server keeps a log. Or perhaps try a different Emacs version.


> e.. by the way, one more question, when emacs boot up, it always connect melpa.org:443, it will take a long time. Can I disable it ?

This is usually because the config is trying to install required packages. Perhaps try adding `(setq debug-on-quit t)` to the top of `init.el`, then press `C-g` while Emacs is waiting to connect. You should then see a backtrace which will show which part of the config is causing a problem. Paste the backtrace here and I'll take a look. :-)

**Comment by chechunli** [comment]
It sounds like some kind of platform-specific issue, and I don't have access to a Windows machine to test on. Perhaps try starting Emacs from a terminal window so that you can see if a message is printed when Emacs crashes. Alternatively, see if the XWin Server keeps a log. Or perhaps try a different Emacs version.

Thank you for your advice, I will try by using Emacs on terminal.

**Comment by chechunli** [comment]
It sounds like some kind of platform-specific issue, and I don't have access to a Windows machine to test on. Perhaps try starting Emacs from a terminal window so that you can see if a message is printed when Emacs crashes. Alternatively, see if the XWin Server keeps a log. Or perhaps try a different Emacs version.

Thank you for your advice, I will try by using Emacs on terminal.

**Comment by jguenther** [comment]
Any particular reason why you're not using vanilla emacs for w32? I've never had much luck running cygwin-emacs, but the [GNU-provided emacs 24.5 win32 builds](https://ftp.gnu.org/gnu/emacs/windows/) just worked out of the box for me.

**Comment by chechunli** [comment]
I have updated to emacs 24.5, and will report whether hanging.
but I alse need wait long time when I boot up emacs, 
the *Message* column show:
gnutls.el: (err=[-54] Error in the pull function.) boot: (:priority NORMAL :hostname melpa.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/pki/tls/certs/ca-bundle.crt /usr/ssl/certs/ca-bundle.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
Loading /home/Administrator/.emacs.d/.session...done
Wrote /home/Administrator/.emacs.d/.emacs.desktop.lock
Desktop: 2 frames, 0 buffers restored.
Desktop restored in 511.03ms
Loading a theme can run Lisp code.  Really load? (y or n) n [2 times]
For information about GNU Emacs and the GNU system, type C-h C-a.

the *Warnings* show:
Warning (initialization): An error occurred while loading `/home/Administrator/.emacs.d/init.el':

GnuTLS error: melpa.org, -54

**Comment by purcell** [comment]
Yep, not sure about that, sorry. Seems like that's a problem with Emacs on Windows, and I can't really investigate that myself.

**Comment by chechunli** [comment]
It won't hang again after I updated to Emacs 24.5 in windows.
many thanks to your support purcell.

**Comment by purcell** [comment]
Yay, great!
