### ISSUE TITLE
Warning (emacs): You appear to be setting environment variables ("LC_CTYPE" "PATH" "MANPATH") i

### ISSUE THREAD

**Issue by d0f** [purcell/emacs.d#315]
Warning (emacs): You appear to be setting environment variables ("LC_CTYPE" "PATH" "MANPATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .bash_profile or .zshenv.  Refer to your shell’s man page for more info.  In future, exec-path-from-shell will not read variables set in the wrong files

**Comment by dcorking** [comment]
The code that issues this warning is in `exec-path-from-shell-copy-envs`  https://github.com/purcell/exec-path-from-shell/blob/master/exec-path-from-shell.el#L184

If you need the exec-path-from-shell magic to get your compile and similar commands to work correctly (on some GUI desktops such as Mac), follow the advice in the warning.

**Comment by purcell** [comment]
> follow the advice in the warning.

Yes, exactly.
