### ISSUE TITLE
Adding customization isn't work

### ISSUE THREAD

**Issue by chechunli** [purcell/emacs.d#317]
hi purcell, 
      I need to say thank you for your last time help for me to fix emacs client crash issue. I have one more question.
      I add My customization int the file .emcs.d/lisp/init_local.el as you said in README.md, but it didn't work. My config like this:

;;; init-local --- add my customize
;;; Commentary:

;;; Code:
;; show line number
(require 'linum)
(global-linum-mode t)

;; chinese input shortcut
(global-set-key (kbd "C-c \\") 'chinese-py)

;;scroll up/down one line
(defun scroll-down-in-place (n)
  "N: line number."
  (interactive "p")
  (previous-line n)
  (scroll-down n))
(defun scroll-up-in-place (n)
  "N: line number."
  (interactive "p")
  (next-line n)
  (scroll-up n))
(global-set-key (kbd "M-N") 'scroll-down-in-place)
(global-set-key (kbd "M-P") 'scroll-up-in-place)

;; highlight character
(require 'highlight-symbol)
(global-set-key [(meta f3)] 'highlight-symbol-at-point)
(global-set-key [f3] 'highlight-symbol-next)
(global-set-key [(shift f3)] 'highlight-symbol-prev)

;; chinese character
(set-language-environment "Chinese-GB")

;; load-theme
(require 'color-theme-sanityinc-tomorrow)
(color-theme-sanityinc-tomorrow--define-theme eighties)

...
(provide 'init-local)
;;; init-local ends here

     Am I config right ? or How can I get some clue for this issue ?
     
Thank you

**Comment by purcell** [comment]
Did you use the filename `lisp/init_local.el` as you wrote above, or `lisp/init-local.el`? It should be the latter.

**Comment by chechunli** [comment]
I use init-local.el

**Comment by emuio** [comment]
change (global-set-key (kbd "C-c \") 'chinese-py)
to
(global-set-key (kbd "C-c \\") 'chinese-py)

**Comment by chechunli** [comment]
I disable  ;(global-set-key (kbd "C-c ") 'chinese-py)  and I found that:
(require 'linum)
(global-linum-mode t)
;; load-theme
(require 'color-theme-sanityinc-tomorrow)
(color-theme-sanityinc-tomorrow--define-theme eighties)

above is work well, but some of in init-local.el doesn't work. like below:
;;scroll up/down one line
(defun scroll-down-in-place (n)
  "N: line number."
  (interactive "p")
  (previous-line n)
  (scroll-down n))
(defun scroll-up-in-place (n)
  "N: line number."
  (interactive "p")
  (next-line n)
  (scroll-up n))
(global-set-key (kbd "M-N") 'scroll-down-in-place)
(global-set-key (kbd "M-P") 'scroll-up-in-place)

;; highlight character
(require 'highlight-symbol)
(global-set-key [(meta f3)] 'highlight-symbol-at-point)
(global-set-key [f3] 'highlight-symbol-next)
(global-set-key [(shift f3)] 'highlight-symbol-prev)

**Comment by emuio** [comment]
can you run the function with 'M-x scroll-down-in-place'?
and check the key binding with 'C-h k M-N'
the letter N should be capitalized.

**Comment by chechunli** [comment]
can you run the function with 'M-x scroll-down-in-place'?
the scroll-down-in-place is undefined
it show "M-N is undefined" by running C-h k M-N

but the function is work when I use C-x C-e at the end of the function manually .

**Comment by chechunli** [comment]
sorry for my mistake, 
all the config isn't work in init-local.el. I think perhaps there is something wrong with load init-local.el

**Comment by emuio** [comment]
I have no idea.
any other error messages?
maybe the other cfg interrupt load init-local.
you can check the init.el file if it contain (require 'init-local nil t).And did you modify the init.el?

**Comment by chechunli** [comment]
I haven't modify it. 
but it has an error:
Warning (initialization): An error occurred while loading `/home/Administrator/.emacs.d/init.el':
File error: make client process failed, connection timed out, :name, melpa.org, :buffer, #<killed buffer>, :host, melpa.org, :service, 443, :nowait, nil

**Comment by purcell** [comment]
So it looks like your emacs can't make a secure connection to melpa.org... do you need to configure a proxy somehow?

**Comment by chechunli** [comment]
Is this error will block loading init-local.el ?

**Comment by purcell** [comment]
Yes.

**Comment by chechunli** [comment]
e...OK, thanks your help :)
