### ISSUE TITLE
error: Package `fullframe-' is unavailable

### ISSUE THREAD

**Issue by yetone** [purcell/emacs.d#318]
### Note from @purcell

`fullframe` is the first package loaded by this config, so if you see this error, it means Emacs couldn't install packages correctly. Common reasons for this:
- You're not online
- Your emacs has no SSL support, or your system has an old root certificate store such that it refuses to connect to MELPA via HTTPS. There's a workaround in `init-elpa.el` for some Windows configurations, but this may affect builds on other platforms too.
- Your package list is out of date: try `M-x package-refresh-contents`

I'll keep this issue open, even though it's not really a problem with this config specifically.

---
Original issue text was blank.

**Comment by purcell** [comment]
Does this help: https://github.com/purcell/emacs.d/issues/303

**Comment by yetone** [comment]
Thank you for your reply, but I use Mac OSX

**Comment by purcell** [comment]
Try `M-x package-refresh-contents`, then restart Emacs.

If the problem persists, you should provide some information about which Emacs version you're using, and whether you have been using the `.emacs.d` directory with different Emacs versions. It's very hard for me to help without more information.

**Comment by avatar29A** [comment]
When i got this problem, i run test-startup.sh. It's helped me.

**Comment by TianYuwan** [comment]
I also encounter this problem, and my os version is Fedora 23(Workstation Edition), Linux 4.3.3-300.fc23.x86_64, emacs version is GNU Emacs 24.5.1.
Here is what I see using "emacs --debug-init":
Debugger entered--Lisp error: (gnutls-error #<process melpa.org> -110)
  signal(gnutls-error (#<process melpa.org> -110))
  gnutls-negotiate(:process #<process melpa.org> :type gnutls-x509pki :hostname "melpa.org")
  open-gnutls-stream("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443)
  network-stream-open-tls("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443 (:type tls :nowait t))
  open-network-stream("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443 :type tls :nowait t)
  byte-code("\306\211\n\307>\203$

**Comment by purcell** [comment]
These symptoms will indicate different problems for different people: this is the first package which the `emacs.d` config tries to load.  In the case of @TianYuwan, it looks like it's not possible to open an `https` connection to `melpa.org`. Most likely you need a network proxy, or you are behind a restrictive firewall.

**Comment by TianYuwan** [comment]
@purcell I happen to travel to other city today and have tried once again. Luckily my desktop could connect to melpa.org and the issues disappear. But this time it pops up several windows asking for OpenSSH password, I ignore them and the initiation succeed at last.

**Comment by YCchou** [comment]
well,  people live in china will encounter this problem because of GFW

**Comment by purcell** [comment]
Yep, but I'm not sure it would make sense to try to intercept this error and describe possible reasons for it.

**Comment by lijunsong** [comment]
I got this error today after I pulled new changes. But my problem is quite different.

I use Emacs behind a proxy. Normally things work fine if I change melpa url from https to http. Emacs will read $http_proxy anyway.

Now I have to explicitly set 
```
(setq url-proxy-services
      '(("http" . "myproxy.com:80")))
```
before loading everything. It seems emacs won't read environment variable $http_proxy anymore.

And I also made a mistake writing "myproxy.com:80" as "http://myproxy.com:80" during my debugging. The url parser somehow wrongly parsed "http" as a host name.

**Comment by ccruquan** [comment]
"http://elpa.popkit.org/packages/" elpa mirror in china, maybe can help for you.

https://github.com/aborn/popkit-elpa

**Comment by laurentHYZ** [comment]
@ccruquan 
thank you for the suggestion, I am trying it. 2 problems:

-I am unable to access your 用户指南  （http://elpa.popkit.org/#/getting-started). I tried with and without VPN. Because of that all I could try to follow was your github instruction:
(add-to-list 'package-archives
            '("popkit" . "http://elpa.popkit.org/packages/"))

-Unfortunately I am really new to emacs, forgive my naive question but where am I supposed to add the following code?

thank you

**Comment by ccruquan** [comment]
@laurentHYZ 


> I am unable to access your 用户指南 （http://elpa.popkit.org/#/getting-started).

elpa.popkit.org hosting in China.  Maybe you can't access.

> Unfortunately I am really new to emacs, forgive my naive question but where am I supposed to add the following code that I found on your github link?
(add-to-list 'package-archives
'("popkit" . "http://elpa.popkit.org/packages/"))

If you use @purcell 's configuration, you can find the code  in ~/.emacs.d/list/init-elpa.el.
Code :https://github.com/purcell/emacs.d/blob/master/lisp/init-elpa.el#L28.

p.s. I'm not the author of popkit.org :), author is @aborn
p.s. popkit change http to https


sorry for my poor English :)

**Comment by vyorkin** [comment]
I have the same issue, currently in Russia, Moscow. Not sure how to diagnose this, I'm new to emacs

**Comment by vyorkin** [comment]
it works if I use `http` instead of `https` here:
```
;;; Also use Melpa for most packages
(add-to-list 'package-archives `("melpa" . ,(if (< emacs-major-version 24)
                                                "http://melpa.org/packages/"
                                              "http://melpa.org/packages/")))
```

**Comment by runelabs** [comment]
Another variant of this is running Emacs 25.0.50.1 from Alpine Linux 3.4.2  (repo "testing" for `/etc/apk/repositories`) in a Docker container and console-mode, where the package `gnutls-utils` is needed. The same error message displays about "fullframe-" when the binary `gnutls-cli` is not available.

In `test-startup.sh` there could be a 
```sh
[ -z "$(which gnutls-cli)" ] && echo -e "Error: missing binary 'gnutls-cli'.\nTip: have you installed the package for it?\n 'gnutls-bin' (Debian/Ubuntu) -- 'gnutls-utils' (Alpine) -- 'gnutls' (Gentoo)?\n" && exit 1
```

With `apk -v add gnutls-utils` done on Alpine Linux the Melpa packages all download and compiling seems fine, however I get another error after all initial compiling finishes:

`Error while checking syntax automatically: (void-function seq-find)`,

and subsequent starting emacs gives the error:

`Recursive 'require' for feature 'seq'`,

 but it is impossible to quit Emacs and it has to be suspended and killed.

**Comment by runelabs** [comment]
So on Alpine Linux in a Docker terminal running `emacs -nw`, as mention in the spacemacs-thread removing the package `elpa/seq-2.16` and then all compiled `.elc` files as well as commenting the `load-prefer-newer` as mentioned in #340  -- I still get the flycheck error reported for `*scratch*`, but everything else seem to be working fine.

I can quit emacs, restoring session also works fine.
`go-mode.el` seems somewhat buggy still, but otherwise good. 👍

**Comment by purcell** [comment]
@runelabs Hmm. `gnutls-cli` isn't absolutely needed, because `openssl_connect` will be used as a fallback if necessary, so I'd be wary of adding that specific check to `test-startup.sh`, but perhaps a variation of it could be useful.

In general there can be bytecode-related problems when either switching Emacs versions, or when upgrading packages which define macros used elsewhere, e.g. `flycheck` and `seq`: the old macro definitions will have generated code into the `.elc` of the packages which use them, and that generated code can be incompatible with the upgraded `seq` or `flycheck`. There's no automatic fix or verification method here: the safe option is generally to clear out the `~/.emacs.d/elpa` directory and restart Emacs so the packages all get reinstalled.

**Comment by raghuugare** [comment]
I did a fresh clone of the repo & on start-up get the same error 
```
Package `fullframe-' is unavailable
```

On running `./test-startup.sh`, I find the following:

```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Making url-show-status local to  *http melpa.org:443* while let-bound!
Failed to download ‘melpa’ archive.
Debugger entered--Lisp error: (error "Package ‘fullframe-’ is unavailable")
  signal(error ("Package ‘fullframe-’ is unavailable"))
  error("Package `%s-%s' is unavailable" fullframe "")
  package-compute-transaction(nil ((fullframe)))
  package-install(fullframe nil)
  (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package))
  (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(fullframe nil t)
  (progn (package-refresh-contents) (require-package package min-version t))
  (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(fullframe)
  eval-buffer(#<buffer  *load*-51365> nil "/Users/rags/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 2994
  load-with-code-conversion("/Users/rags/.emacs.d/lisp/init-elpa.el" "/Users/rags/.emacs.d/lisp/init-elpa.el" nil t)
  #<subr require>(init-elpa nil nil)
  funcall(#<subr require> init-elpa nil nil)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t)))))
  (let (ad-return-value) (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis ... require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))) ad-return-value)
  ad-Advice-require(#<subr require> init-elpa)
  apply(ad-Advice-require #<subr require> init-elpa)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/Users/rags/.emacs.d/init.el" nil t)  ; Reading at buffer position 1569
  load-with-code-conversion("/Users/rags/.emacs.d/init.el" "/Users/rags/.emacs.d/init.el" nil nil)
  load("/Users/rags/.emacs.d/init.el" nil nil t)
  load-file("/Users/rags/.emacs.d/init.el")
  (let ((debug-on-error t) (url-show-status nil) (user-emacs-directory default-directory) (package-user-dir (expand-file-name (concat "elpa-" emacs-version))) (user-init-file (expand-file-name "init.el")) (load-path (delq default-directory load-path))) (load-file user-init-file) (run-hooks (quote after-init-hook)))
  eval((let ((debug-on-error t) (url-show-status nil) (user-emacs-directory default-directory) (package-user-dir (expand-file-name (concat "elpa-" emacs-version))) (user-init-file (expand-file-name "init.el")) (load-path (delq default-directory load-path))) (load-file user-init-file) (run-hooks (quote after-init-hook))))
  command-line-1(("--eval" "(let ((debug-on-error t)\n                              (url-show-status nil)\n                              (user-emacs-directory default-directory)\n                              (package-user-dir (expand-file-name (concat \"elpa-\" emacs-version)))\n                              (user-init-file (expand-file-name \"init.el\"))\n                              (load-path (delq default-directory load-path)))\n                           (load-file user-init-file)\n                           (run-hooks (quote after-init-hook)))"))
  command-line()
  normal-top-level()
```

**Note:** If it is of any help, my emacs version is `25.1.50.1`

Is it possibly due to not being able to access MELPA over https?

**Comment by limTeTE** [comment]
@purcell Hi Steve. I met the same problem of GnuTLS in windows10(x64) using Emacs 25.1.1 (x86_64-w64-mingw32) as here. And i found the original url you gave in the README.md about GnuTLS in windows works well in Emacs24, not in Emacs25. The problem i met is that, following the exact same order from [http://xn--9dbdkw.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html](url) and when i enter [M-: (gnutls-available-p) RET], i got a 'nil' back. Here is the solution that gets me out [http://emacs.stackexchange.com/questions/27202/how-do-i-install-gnutls-for-emacs-25-1-on-windows](url). May it help with others who meet the same problem.

**Comment by Steven-AA** [comment]
I met the same problem, and this works. 
> it works if I use http instead of https here:
>
>```
>;;; Also use Melpa for most packages
>(add-to-list 'package-archives `("melpa" . ,(if (< emacs-major-version 24)
>                                                "http://melpa.org/packages/"
>                                              "http://melpa.org/packages/")))
>                                                ; ^
>```

**Comment by purcell** [comment]
@Steven-AA @limTeTE I've made the config use HTTP by default now on Windows, if `gnutls-available-p` reports nil. This should help the default config to work automatically in  more situations. Thanks.

**Comment by jw-miaem** [comment]
@purcell I'm having same issue on mac all of a sudden
