### ISSUE TITLE
can't push commits to github under Windows

### ISSUE THREAD

**Issue by magichowl** [purcell/emacs.d#319]
I've forked a emacs.d from you, but I failed to push commits under Windows 

```
﻿128 C:\Users\pan\AppData\Local\Programs\Git\mingw64\libexec\git-core\git … push -v origin master:refs/heads/master
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
Pushing to https://github.com/magichowl/emacs.d.git
```

My Emacs version is GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-11-10
and I 've added "C:\msys64\usr\bin\tty.exe" to environment variable "PATH".

**Comment by quant67** [comment]
Try GitHub desktop https://desktop.github.com/ .

**Comment by purcell** [comment]
Yep, this isn't really something I can help with, sorry: I don't use Windows, and I don't think this is related to any of the config in this repo.
