### ISSUE TITLE
default-input-method is overridden

### ISSUE THREAD

**Issue by Tyrn** [purcell/emacs.d#320]
I've created init-local.el file, as per instructions; it contains my AUCTeX settings. It clearly works, with the exception of one line: toggle-input-method doesn't deliver as expected.

My init-local.el contains this:

(setq default-input-method "russian-computer")

but the statement gets ignored/overridden. The only seemingly relevant line in your code is in init-osx-keys.el; I tried to comment it out, but nothing changed. Where am I to look? I'm sorry, it is not really your problem, but I'm stuck with this otherwise excellent solution.

**Comment by purcell** [comment]
Hmm, if your `init-local.el` is getting loaded, then the setting should override the settings in `init-osx-keys.el`. Have you maybe also customized that variable to a different value with `M-x customize`?

**Comment by Tyrn** [comment]
I did not customize anything in your code. This wrinkle is not a showstopper, as it turned out:

M-x set-input-method RET russian-computer

works as expected. Curiously, the setting appears to be effective on a per buffer basis, so it is not very useful being put into init-local.el. BTW, russian-computer shows in the mode line as RU; your own layout alternative shows as m. What is it?

**Comment by purcell** [comment]
Aha -- then try `setq-default` instead of `setq`:

```
(setq-default default-input-method "russian-computer")
```

My own default on OS X is "m" => "Mac".

**Comment by Tyrn** [comment]
setq-default has no effect, just as setq, unfortunately.

**Comment by re-mx** [comment]
Emacs will automatically set `default-input-method` to` rfc1345` if locale is UTF-8.

In Mr. Purcell's configuration, the locale setting is placed at the end of [init.el](https://github.com/purcell/emacs.d/blob/0c7d2cb3ddd336e02a17b28f6ac6afd44beaa0e6/init.el#L164), which is later than init-local.el.

At this point, Emacs will overwrite your settings.

When I comment out `(require 'init-locales)`, the value of `default-input-method` becomes` nil`,
And if I set this variable in init-local.el, it will also take effect after commenting out `(require 'init-locales)`.

Some workaronds：
1. `(add-hook 'after-init-hook (lambda () (setq default-input-method "russian-computer")))`
2. `M-x customize-variable RET default-input-method`.
     Then change the value to `russian-computer`.


Sorry for my poor English.

**Comment by purcell** [comment]
Ah, right. I just pushed 29d5f3c to help with this.
