### ISSUE TITLE
exec-path-from-shell problem ...

### ISSUE THREAD

**Issue by curbina** [purcell/emacs.d#321]
Hello Steve,

I keep getting the following message during emacs startup.

You appear to be setting environment variables ("PATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell's man page for more info.  Customize `exec-path-from-shell-arguments' to remove "-i" when done, or disable `exec-path-from-shell-check-startup-files' to disable this message.
Loading /Users/mlb/.emacs.d/recentf...done

My shell is zsh and have tried placing the following in both zshenv and zprofile.

export PATH="/Users/mlb/miniconda/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/mlb/dotfiles/bin"

Best regards,
curbina

**Comment by curbina** [comment]
Hello Steve,

Problem solved. I used zlogin to export environment variables.

Best regards,
curbina

**Comment by purcell** [comment]
Awesome, was just about to reply.

**Comment by curbina** [comment]
Thanks for your message.
