### ISSUE TITLE
Ovveride keymap bindings

### ISSUE THREAD

**Issue by avatar29A** [purcell/emacs.d#322]
Hi, i trying use your config, and i faced with the problem. I want rebind some standard keymap bindings, for example:

C-k (http://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html), C-i, C-j, C-l.

And in my init-local.el  I added next lines:

(global-set-key (kbd "C-i") 'windmove-up)
(global-set-key (kbd "C-k") 'windmove-down)
(global-set-key (kbd "C-j") 'windmove-left)
(global-set-key (kbd "C-l") 'windmove-right)

C-k, C-j don't work. When i pressed them, I got default behavior. 

Does can you help me? Thank's.

P.S: If i use only my config (https://github.com/avatar29A/emacs-config/blob/master/.emacs) it's work.
P.S.S: My init-local.el https://github.com/avatar29A/emacs-config/blob/master/init-local.el

**Comment by purcell** [comment]
Hi! Firstly, those are such common Emacs keybindings that I *really* wouldn't recommend trying to override them. Additionally, many major modes bind those keys to their own versions of the standard meanings of those keys, e.g. `newline-and-indent` for `C-j`, so you'll always be battling against the major modes to grab control of those keys. You *may* be able to work around that by creating your own global minor mode, but I'd strongly suggest choosing something like `C-S-i`, `C-S-k` instead.

**Comment by arijoon** [comment]
I suggest using C-c C-k, C-c c-k ... instead. Or use default C-x o to switch windows

**Comment by avatar29A** [comment]
Thanks for answer. Just i have habit switch between windows by C-j, C-k, C-l, C-i. It's very convenient for me.
