### ISSUE TITLE
(Just FYI) Package fullframe bug

### ISSUE THREAD

**Issue by arthurl** [purcell/emacs.d#325]
Error at initialisation:
```
Warning (initialization): An error occurred while loading `/Users/arthur/.emacs.d/init.el':

Wrong number of arguments: (2 . 2), 1
```
Bug is fixed (here: https://github.com/tomterl/fullframe/commit/e61a66a129082bba2b6ae7c84ca3250edd33f27d), but isn't yet updated on the repo so Emacs will not start as of right now.

Just in case someone is wondering.

**Comment by olivertaylor** [comment]
I was wondering! Thanks for the info.

**Comment by boboyada** [comment]
HI,you should download fullframe-20140619.305.zip,and extract to  ~/.emacs.d,and delete fullframe-20160118...dir.
rerun    emacs.exe
ok

**Comment by purcell** [comment]
Thanks. Latest version is on MELPA now, so if anyone else comes across this, just delete `~/.emacs.d/elpa/fullframe-*` and restart Emacs.
