### ISSUE TITLE
update error 

### ISSUE THREAD

**Issue by causlayer** [purcell/emacs.d#326]
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 1)
  version<("24.4")
  (if (version< "24.4") (progn (progn (ad-add-advice (quote list-packages) (quote (fullframe nil t (advice lambda nil (let ... ad-do-it ...)))) (quote around) (quote nil)) (ad-activate (quote list-packages) nil) (quote list-packages)) (progn (ad-add-advice (quote quit-window) (quote (fullframe nil t (advice lambda nil (let ... ...)))) (quote around) (quote nil)) (ad-activate (quote quit-window) nil) (quote quit-window))) (progn (advice-add (function list-packages) :around (function (lambda (orig-fun &rest args) (let ((fullframe/--window-config28900 ...)) (if (commandp orig-fun t) (call-interactively orig-fun) (apply orig-fun args)) (let (...) (delete-other-windows) (if ... nil ...)))))) (advice-add (function quit-window) :around (function (lambda (orig-fun &rest args) (let ((fullframe/--window-config28900 fullframe/previous-window-configuration) (fullframe/--buf28902 ...)) (prog1 (if ... ... ...) (fullframe/maybe-restore-configuration fullframe/--window-config28900) nil)))))))
  eval-buffer(#<buffer  *load*-241261> nil "/Users/apple/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 3032
  load-with-code-conversion("/Users/apple/.emacs.d/lisp/init-elpa.el" "/Users/apple/.emacs.d/lisp/init-elpa.el" nil t)
  #<subr require>(init-elpa nil nil)
  funcall(#<subr require> init-elpa nil nil)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t)))))
  (let (ad-return-value) (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis ... require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))) ad-return-value)
  ad-Advice-require(#<subr require> init-elpa)
  apply(ad-Advice-require #<subr require> init-elpa)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/Users/apple/.emacs.d/init.el" nil t)  ; Reading at buffer position 1569
  load-with-code-conversion("/Users/apple/.emacs.d/init.el" "/Users/apple/.emacs.d/init.el" t t)
  load("/Users/apple/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by inflation** [comment]
It's the same problem with #325

**Comment by purcell** [comment]
Closing as duplcate of #325. `M-x list-packages`, hit `U`, `x`, wait while packages upgrade, then restart Emacs.
