### ISSUE TITLE
How do I swap double quote character with single quote?

### ISSUE THREAD

**Issue by bigos** [purcell/emacs.d#328]
Let's say I edit ruby file with following line:
  require "yaml"
and I want to replace " with '.

I press M-% to swap characters
then press "
and it gets a companion.
I want to replace " NOT ""
at the moment I have to press C-d to be able to do it, which is very annoying.

I guess init-paredit.el is to blame.

**Comment by purcell** [comment]
No, that'd be `electric-pair-mode`. `C-q "` would be the way to avoid any special interpretation of `"`. I'm not sure I'll keep `electric-pair-mode`, since I don't know that it's helpful more than 50% of the time, but the `C-q` ("quote") trick is at least the standard workaround.

**Comment by bigos** [comment]
I've switched it off in minibuffer by adding following line to init-local.el
(add-hook 'minibuffer-setup-hook (lambda () (electric-pair-mode 0)))

**Comment by purcell** [comment]
Yeah, might do something similar myself at some point. I'm not even sure if I like `electric-pair-mode` in regular buffers really.
