### ISSUE TITLE
Symbol's function definition is void: tramp-tramp-file-p 

### ISSUE THREAD

**Issue by junwei-wang** [purcell/emacs.d#329]
I am newer to emacs. My emacs was installed throw Homebrew with version 24.5.1 

When I learn you repo, specifically, `./lisp/init-utils.el` file. I type `M-x browse-current-file`.
Something unexpected happened.

Please have a look and help me figure it out.
Thank you in advance.

**Comment by purcell** [comment]
Thanks, that's fixed in d4d51d3.

**Comment by junwei-wang** [comment]
@purcell Thank you very much for your help.

**Comment by purcell** [comment]
Thanks for filing the issue, and for trying out my emacs config.
