### ISSUE TITLE
Can't locate module: SWANK-IO-PACKAGE::SWANK-MACROSTEP

### ISSUE THREAD

**Issue by Gupern** [purcell/emacs.d#332]
when i use `M-x` `slime`, it comes 

> Can't locate module:  SWANK-IO-PACKAGE::SWANK-MACROS

how could i fix it?

what's more, how can I change the themes? (I have try to build a file named init-local.el as the README.md said.)

**Comment by purcell** [comment]
> when i use M-x slime, it comes
> 
>     Can't locate module: SWANK-IO-PACKAGE::SWANK-MACROS

Not completely sure about that, sorry, but it's almost certainly a problem with `slime`, and not with this config. Someone has reported a similar issue previously (in #237) but didn't provide any details: at that time, a new `contrib` module had been added to Slime, and `macrostep` also seems to be new.

My suggestion would be to delete `~/.emacs.d/elpa/slime-2*`, then restart Emacs, and ensure that any Common Lisp process you're connected to is also restarted.

> what's more, how can I change the themes? (I have try to build a file named init-local.el as the README.md said.)

First install the extra themes, either via `M-x list-packages` or by adding a `(require-package 'some-new-theme)` in your `init-local.el`. Then select and save a new preferred theme using `M-x customize-themes`.

Hope that helps!

**Comment by earl-ducaine** [comment]
I know this is old, but adding to what Purcell said: swank/slime in quicklisp don't coexist well with swank/slime in elpa.  If your going to use quicklisp and slime use the quicklisp version and make sure to remove all slime and swank related packages you've downloaded via elpa.
