### ISSUE TITLE
How to customize emacs.d?

### ISSUE THREAD

**Issue by hemichael** [purcell/emacs.d#333]
Sometimes I'd like to turn off `paredit-mode` when emacs starts, though I know I can manually disable it by `M-x disable-paredit-mode` command. I tried every possible place `(init.el, init-preload-local.el, init-local.el, init-paredit.el, etc.)` to opt out it from pre-loaded packages but it never works. I even tried to uninstall it in `melpa`, but when I restart emacs, `paredit` still stays as before.  

Through these attempts I got an impression that your emacs.d is hard to customize (that is, hard to opt in and opt out emacs modes). Do you have any suggestions?

**Comment by purcell** [comment]
There's a reference to `enable-paredit-mode` in `init-lisp.el` too, which you probably missed: that's where the mode is triggered. And if you're allowing the config to save your buffers when you restart Emacs, the old modes will be restored after you restart.

**Comment by futurist** [comment]
If want to replace `paredit` with `smartparens`, how to do that in `init-local.el` file? 

How to prevent load `paredit` totally, that way can do customize in local.

**Comment by purcell** [comment]
You would need to fork the config to do that.
