### ISSUE TITLE
way to restore 'kill-sentence?

### ISSUE THREAD

**Issue by futurist** [purcell/emacs.d#335]
The file `init-paredit.el` has a line:

````lisp
(define-key paredit-everywhere-mode-map [remap kill-sentence] 'paredit-kill))
````

that remap the emacs default `kill-sentence`, but I need it to bind some key, how to restore that in my key binding? below not work:

````lisp
(global-set-key (kbd "C-S-k") 'kill-sentence)
````

it continue invoke `paredit` version. but if I `M-x kill-sentence`, it's worked.

**Comment by purcell** [comment]
The `paredit-everywhere` keymap is overriding the global keymap in your case. Try `(define-key paredit-everywhere-mode-map (kbd "C-S-k") nil)`.

**Comment by futurist** [comment]
After tried, it's not work.

````lisp
(after-load 'paredit-everywhere
  (global-unset-key (kbd "C-S-k"))
  (define-key paredit-everywhere-mode-map (kbd "C-S-k") nil)
  (define-key paredit-mode-map (kbd "C-S-k") nil)
  (global-set-key (kbd "C-S-k") 'kill-sentence)
  )

````

**Comment by purcell** [comment]
Ah yes, sorry, there are two maps to modify. So I'd expect just this to work, assuming you put it in `init-local.el`:

```el
(after-load 'paredit
  (define-key paredit-mode-map [remap kill-sentence] nil))
(after-load 'paredit-everywhere
  (define-key paredit-everywhere-mode-map [remap kill-sentence] nil))
```

> Maybe it's easier to bind paredit-kill to single key, but not to remap it?
> Please re-think this. Thanks

I'm not sure that's better, and I wouldn't really want to change this: I created the config for myself, after all. It's expected (and recommended) that users who want to customise the configuration should simply fork it and edit it as desired.

**Comment by futurist** [comment]
See your stars, it's largely used in emacs users, and IMO it's the best of the others. But using `sentence` key binding is importance in the project, think below:
````javascript
var fs = require('fs')
var http = require('http')

//read config
var CONFIG_FILE = 'config.json'
var CONFIG = {}
fs.read(CONFIG_FILE, function(err, data){
    if(err) return
    CONFIG = JSON.parse(data)
})

// http server
var HttpServer = http.createServer(function(req,res){
    .... ....
})


````

If want to swap the `read config` and `http server` part, just `kill-sentence`, then yank. The code managing way also applied to the whole team.
But now the `M-k` not work, try bind to another key, still failed.

Just want to keep track your updates, and suggest rethink the usage.

**Comment by purcell** [comment]
Fair enough -- done in c87e6c8, thanks!
