### ISSUE TITLE
how to change the default background and foreground color

### ISSUE THREAD

**Issue by dreamfly281** [purcell/emacs.d#336]
Thanks for sharing the configuration, everything look fine except how to change the default background&foreground color, the currently default are yellow&white, I have been try add below lines at init.el. but looks be overwrite
;; set back ground, foreground and cursor color
(set-background-color"gray20")
(set-foreground-color"white")
(set-cursor-color"gold2")

**Comment by purcell** [comment]
Have you tried `M-x customize-themes`? :-)

**Comment by dreamfly281** [comment]
Thanks, it works, I use the M-x customize-face which should be similar as you showed and will write some configuration to the custom.el

**Comment by purcell** [comment]
Great!
