### ISSUE TITLE
pbcopy is not work properly.

### ISSUE THREAD

**Issue by easeflyer** [purcell/emacs.d#337]
I am in eshell, and executive command:
~$ ls | pbcopy
but the clipboard  did not get any content, echo 3333 | pbcopy  command is ok.

M-x shell also the same.

Consult, thank you.

**Comment by purcell** [comment]
How are you testing that? If I run `M-x shell` and then `ls|pbcopy`, I can then switch to TextEdit and choose Paste, and the clipboard content is there. Are you trying the same thing?

**Comment by easeflyer** [comment]
think you. I use the same steps, but there is no content posted from the clipboard

**Comment by easeflyer** [comment]
I installed Emacs by homebrew  in os x .
and download your .emacs.d/  by git

**Comment by easeflyer** [comment]
The problem is solved!!
If I use /usr/local/Cellar/emacs/24.5/emacs.app
Will appear this problem.
If I use /usr/local/Cellar/emacs/24.5/bin/emacs
Then everything is normal.
Only the specific reason that has not been found.
