### ISSUE TITLE
Package listing improvements

### ISSUE THREAD

**Issue by Silex** [purcell/emacs.d#339]
Hello,

I thought you might be interested by https://github.com/Silex/tabulated-list-extensions#interactive, namely the `tle-resize-column` function.

It's a ripof from https://github.com/purcell/emacs.d/blob/master/lisp/init-elpa.el#L92-103 but it's not "destructive" as the one you have in there, because in this code the `(setf (elt column 1) width))` *permanently* changes the listing while mine is temporary and can be added as a tabulated-list-hook (especially `tle-auto-resize-all-columns`)

Feel free to close/ignore this ;)

**Comment by purcell** [comment]
Thanks for the heads-up. I might tidy that up sometime. :-)
