### ISSUE TITLE
compatible with ubuntu 16.04

### ISSUE THREAD

**Issue by xishi00** [purcell/emacs.d#340]
I tried this configuration on the new released ubuntu 16.04 x64,desktop, with emacs 25.1.50.2. After initialization for the configuration,  emacs just gives some warnings. And when I restart my emacs, it stop with following errors:
`Loading /home/xishi/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
ad-handle-definition: ‘ido-completing-read’ got redefined
Recompiling /usr/share/emacs/25.1.50/lisp/server.el.gz...failed
insert-file-contents: Recursive load: "/usr/share/emacs/25.1.50/lisp/jka-compr.el.gz", "/usr/share/emacs/25.1.50/lisp/jka-compr.el.gz", "/usr/share/emacs/25.1.50/lisp/jka-compr.el.gz", "/usr/share/emacs/25.1.50/lisp/jka-compr.el.gz", "/usr/share/emacs/25.1.50/lisp/jka-compr.el.gz", "/usr/share/emacs/25.1.50/lisp/emacs-lisp/warnings.el.gz"`

At the same time, emacs can not be shut down normally, only by killing the process.

I debugged the init.el file and find that it is the line (require 'init-lisp) that gets emacs down. when I delete this line, emacs works well again. 

How to fix this problem without killing init-lisp?

**Comment by purcell** [comment]
Not sure, but that's a recent snapshot version of Emacs, so it's not really supported. I'm using a similar snapshot (as of today) on OS X, though, and I don't see the same problem. I don't have an easy way to reproduce this, but if you can track down the problem I'll be happy to follow up.

**Comment by xishi00** [comment]
The probable reason may be the automatic byte compilation in init-lisp.el. when i comment this group code,  especially line 100:
`(setq load-prefer-newer t)`,
 everything has been ok.   I don't know whether this line is necessary or not.

**Comment by purcell** [comment]
Hmmm. I wonder if - on your system - the file `/usr/share/emacs/25.1.50/lisp/server.el.gz` is newer than `/usr/share/emacs/25.1.50/lisp/server.elc`?

**Comment by xishi00** [comment]
This bug has disappeared in the new versions and updates. So I decide close this issure.

**Comment by qsimpleq** [comment]
I'm using ~ubuntu-elisp ppa. Problem still exists in .debs. Fix Recursive load: *.el.gz
`(setq load-file-rep-suffixes '(""))`

**Comment by purcell** [comment]
Good to know -- thanks for noting it here for users to find. (I don't really want to patch this in the config directly.)

**Comment by boern** [comment]
or try "touch /usr/share/emacs/25.1.50/lisp/*.elc"
