### ISSUE TITLE
multi-byte language problem with keybinding in init-editing-utils.el

### ISSUE THREAD

**Issue by futurist** [purcell/emacs.d#341]
When using multi-byte language(Japanese, Chinese), there's an important key <kbd>C-x C-m</kbd> to change encoding of buffer, e.g. <kbd>r</kbd> to revert buffer with some other encoding.

But found it's bound to below:

```lisp
;; To be able to M-x without meta
(global-set-key (kbd "C-x C-m") 'execute-extended-command)
```

Every time I have to comment this line to work with multi-byte env.

Is that an issue with this?

**Comment by purcell** [comment]
Nope, I don't really need that, so I've removed that line. Thanks!
