### ISSUE TITLE
question about robe-doc

### ISSUE THREAD

**Issue by melotusme** [purcell/emacs.d#343]
I'm try reading the source code of `rails` in emacs, but when I key in chinese character in the source code, it can't show correctly in `robe-doc`.For example, I write `中文` in source code, and it turns to be
![image](https://cloud.githubusercontent.com/assets/10104231/14808984/763090be-0bbc-11e6-8288-f2d675619b06.png)
in robe-doc.

**Comment by purcell** [comment]
Sounds like an issue for Robe, I expect: https://github.com/dgutov/robe/blob/master/robe.el

/cc @dgutov

**Comment by melotusme** [comment]
I also found that it didn't indent correctly in `erb` files.

**Comment by purcell** [comment]
Which type of erb files? `.html.erb`?

**Comment by melotusme** [comment]
This code was excerpted from a `_form.html.erb`file.
```erb
<%= form_for @leave, html: {class: "form-horizontal"} do |f| %>
  <% attribute_tag(@leave, :attachment_ids) do %>
  <div class="form-group hide" id="attachments-group">
    <%= f.label :attachment , "附件信息:", class: 'col-sm-4 control-label' %>
    <div class="col-xs-4">
      <%= render 'attachments/attachment_fields', f: f %>
    </div>
    <div class="col-xs-4">
      <%= @leave.errors.messages[:attachments].try(:join, ",") %>
    </div>
  </div>
  <% end %>
<% end %>
```
But after I press `C-x h tab`, it turned to be 
```erb
<%= form_for @leave, html: {class: "form-horizontal"} do |f| %>
<% attribute_tag(@leave, :attachment_ids) do %>
<div class="form-group hide" id="attachments-group">
  <%= f.label :attachment , "附件信息:", class: 'col-sm-4 control-label' %>
  <div class="col-xs-4">
    <%= render 'attachments/attachment_fields', f: f %>
  </div>
  <div class="col-xs-4">
    <%= @leave.errors.messages[:attachments].try(:join, ",") %>
  </div>
</div>
<% end %>
<% end %>
```
And I think this  may  not  be suitable for read.

**Comment by dgutov** [comment]
> when I key in chinese character in the source code, it can't show correctly in robe-doc

Thanks, should be fixed now.

Regarding the ERB example, though, it indents fine here, in Emacs 25 snapshot, using `mmm-mode` (`html-erb-mode`, to be exact).

**Comment by melotusme** [comment]
@dgutov thank you, now I can read the comments in chinese, I should raise the question earlier. Thank you.
