### ISSUE TITLE
It seems that ac-slime is not installed automatically

### ISSUE THREAD

**Issue by hjolin** [purcell/emacs.d#344]
@purcell 
hi purcell, I've been using this configuration for a while and thank you very much for this.
when I run "M-x slime" there is a error that says "set-up-slime-ac function is void", I googled this function and find it in "ac-slime" package written by you, but I can't find somthing like "require-package 'ac-slime" in init-slime.el, then I installed it myself and no error occurs, it works well now, did you forget to put it in or it is included in another place?

**Comment by purcell** [comment]
Thanks for the heads-up! Yep, I recently switched the config from `auto-complete` to `company`, and this was something I missed - I'm not actively working with Common Lisp these days, so I didn't notice.

The commit 992eebe should fix it, but I'm not convinced that the replacement I've added there - `slime-company` - is working well. Perhaps you could give it a try?

**Comment by purcell** [comment]
Actually, it does seem to be working. :-)

**Comment by purcell** [comment]
Actually, it does seem to be working. :-)
