### ISSUE TITLE
weird auto upcase character

### ISSUE THREAD

**Issue by defclass** [purcell/emacs.d#345]
Hi Steve,
I encountered a strange problem that I use mouse select some text , one of which  will auto uppercase when I edit clojure files.
eg:  
```
{:after after
 :before before}
```
after several cursor select by mouse the text will turn into 

```
{:After afteR
 :Before befOre}
```
environment:
OS X 10.11.3
emacs 24.5.1
in cider mode

**Comment by purcell** [comment]
Hmm, sorry, I'm not able to reproduce this.

**Comment by defclass** [comment]
not every select trigger the problem, it just happens frequently.

**Comment by defclass** [comment]
It seems to related to `(setq mac-command-modifier 'meta)` , it will happens after I hit `Ctrl+Command+z`.Almost every time cursor select use mouse will cause the problem. Maybe it's a emacs's bug.

**Comment by purcell** [comment]
When I do the same thing (in a recent Emacs snapshot), I get the message `C-M-z is undefined`. And if `Ctrl-Option-z` reports as `C-M-z` for you, then it sounds like the `mac-command-modifier` option is either not getting applied, or isn't working. Not sure there's anything more I can add to the investigation, sorry.

**Comment by defclass** [comment]
It maybe be a bug on emacs 24.5.1, as I can reproduce the problem when I put just only one line `(setq mac-command-modifier 'meta)` in `.emacs`. I think this issue could be closed for now.Thanks for your work again.

**Comment by purcell** [comment]
Cool, thanks for digging into that.
