### ISSUE TITLE
Cannot set default font size

### ISSUE THREAD

**Issue by jamieabc** [purcell/emacs.d#347]
Hi,

I try to edit ~/.emacs.d/lisp/init-local.el with following code

`
(set-default-font "Source Code Pro-14")
(provide 'init-local)
`
But it seems not woking, font is always melo and size 12 whenever emacs is started, it there any problem with my settings?

**Comment by trezona-lecomte** [comment]
Hey @jamieabc,

The way I set my font is:
`(add-to-list 'default-frame-alist
             '(font . "Source Code Pro-14"))
`
In my `init-local.el'. Try this and see if it works for you.

**Comment by jamieabc** [comment]
thanks, I will try it.

**Comment by purcell** [comment]
I use `M-x customize-face` => `default`, then I change the font, and leave other properties unchecked. Finally I save the settings. This way, the settings are stored in `custom.el`, and restored on startup.

PS. Check out the "Input Mono" font, particularly the "condensed" variants. I find it wonderful for code.

**Comment by jamieabc** [comment]
Thanks a lot, when I try `M-x customize-face` and set font, don't know why but it seems not working at all, so at last I use `(add-to-list 'default-frame-alist '(font . "Source Code Pro-14"))` to set font
