### ISSUE TITLE
Settings ibuffer name column width.

### ISSUE THREAD

**Issue by zw963** [purcell/emacs.d#350]
Hi, following code work well for me. though, it change my ibuffer name (the first column)
to very narrow, make me could not read full name directly. 

```
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (bunffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))
```

I have another code to make my name column more widthly.
But those two snippets conflict each other.

``` cl
(setq ibuffer-formats '((mark modified read-only " "
                              (name 35 35 :left :nil)
                              " "
                              (size 9 -1 :right)
                              " "
                              (mode 16 16 :left :elide)
                              " " filename-and-process)
                        (mark " "
                              (name 16 -1)
                              " " filename)))
```

I have no idea how to make those two code work together?

**Comment by magicdirac** [comment]
you need change the size to size-h
```
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (bunffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))

  (setq ibuffer-formats
        '((mark modified read-only " "
                (name 35 35 :left :nil)
                " "
                (size-h 9 -1 :right)
                " "
                (mode 16 16 :left :elide)
                " " filename-and-process)
          (mark " "
                (name 16 -1)
                " " filename)))
```

**Comment by zw963** [comment]
Not worked. 

```cl
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (bunffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))
```

will result in:

```cl
((mark modified read-only " " (name 35 35 :left :nil) " " (size-h 9 -1 :right) " " (mode 16 16 :left :elide) " " filename-and-process) (mark " " (name 16 -1) " " filename))
Updating buffer list...
Formats have changed, recompiling...
ibuffer-expand-format-entry: Unknown column (size-h 9 -1 :right) in ibuffer-formats
```

**Comment by zw963** [comment]
Sorry,  code error, I update previous reply.

**Comment by magicdirac** [comment]
could you use `emacs -Q` and try the code below, it works for me.
```
(require 'ibuffer)
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (bunffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))

  (setq ibuffer-formats
        '((mark modified read-only " "
                (name 35 35 :left :nil) " "
                (size-h 9 -1 :right) " "
                (mode 16 16 :left :elide) " " 
                filename-and-process)))
```

**Comment by magicdirac** [comment]
Found there was a typo in my previous post and just got corrected.
you can try with `emacs -Q` and the following code should work for you. 

```
(require 'ibuffer)
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (buffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))

  (setq ibuffer-formats
        '((mark modified read-only " "
                (name 35 35 :left :nil) " "
                (size-h 9 -1 :right) " "
                (mode 16 16 :left :elide) " " 
                filename-and-process)))
```

**Comment by zw963** [comment]
Oh, I found the problem is caused by `ibuffer-vc` is required. 
After load this package, name-width settings is overrided.

@purcell , could you please fix this?

**Comment by purcell** [comment]
@zw963 I don't quite see what you mean here, sorry. Please provide:
1. Steps to reproduce
2. Expected result

**Comment by zw963** [comment]
@purcell.

### Purpose, 
I want to change ibuffer name width and use human readable capability column

### I set following code from @magicdirac , It worked!
```cl
(require 'ibuffer)
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (buffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))

  (setq ibuffer-formats
        '((mark modified read-only " "
                (name 35 35 :left :nil) " "
                (size-h 9 -1 :right) " "
                (mode 16 16 :left :elide) " " 
                filename-and-process)))
```

### And then  (require 'ibuffer-vc)
human readable capability column still worked.
But  ibuffer name width restore to default value.


So, I think ibuffer-vc maybe change somethings to make previous code invalid.
Could you please fix this?
Thanks

**Comment by purcell** [comment]
No, I can't duplicate this with a fresh Emacs (started with -Q), so I don't believe there's an issue with `ibuffer-vc`. However, `init-ibuffer.el` *does* change `ibuffer-formats`, so you should either edit that file in your fork, or modify it later in your `init-local.el` file, as per the README.

**Comment by magicdirac** [comment]
The file [init-ibuffer.el](https://github.com/purcell/emacs.d/blob/master/lisp/init-ibuffer.el) reset `ibuffer-formats` setting.
So the easiest way to fix is change this file directly, and delete `init-ibuffer.elc` and compile it.

**Comment by purcell** [comment]
Yep, that file shouldn't get byte-compiled anyway, thanks to the .dir-locals.el file in the lisp directory. And in any case, load-prefer-newer is set to t, which should ensure that stale bytecode never gets loaded.

**Comment by zw963** [comment]
> However, init-ibuffer.el does change ibuffer-formats

I not run this file. I test with emacs -Q.

Following is step to step:

### emacs -Q

### Run following code in *scratch* buffer
```cl

(add-to-list 'load-path "...")

(require 'ibuffer)
(define-ibuffer-column size-h
  (:name "Size" :inline t)
  (cond
   ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
   ((> (buffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
   (t (format "%8d" (buffer-size)))))

(setq ibuffer-formats
      '((mark modified read-only " "
              (name 35 35 :left :nil) " "
              (size-h 9 -1 :right) " "
              (mode 16 16 :left :elide) " "
              filename-and-process)))

(require 'ibuffer-vc)
```

###  M-x 'ibuffer', the first column (buffer name column) is not setting correct.

**Comment by zw963** [comment]
if not load ibuffer-vc, buffer name column (MR Name column) is more widely, make me easy to see longer buffer name.

**Comment by purcell** [comment]
Which Emacs version do you have? That works fine for me, at least in a recent Emacs snapshot, and in the last stable release (24.5).

**Comment by zw963** [comment]
24.5.1
2016年6月19日 下午3:51，Steve Purcell <notifications@github.com>写道：Which Emacs version do you have? That works fine for me, at least in a recent Emacs snapshot, and in the last stable release (24.5).

**Comment by purcell** [comment]
Weird. I get *exactly* the same results with or without `ibuffer-vc` loaded.

**Comment by zw963** [comment]
Hi, I update a gif for this. please review.

![recorded151716173.gif](http://zw963.github.io/recorded151716173.gif)

**Comment by purcell** [comment]
Thanks. I see what you mean from the gif, but I really can't reproduce that behaviour even if I follow *exactly* the same steps with Emacs 24.5. :-/

**Comment by zw963** [comment]
I compile with following config:

```sh
./configure \
    --with-x \
    --with-x-toolkit=lucid
```

though, I don't think this relative to current issue.

Thanks for help.
