### ISSUE TITLE
Small advices

### ISSUE THREAD

**Issue by shwsun** [purcell/emacs.d#351]
Hello purcell!

I have been using Emacs for quite a long time and later I found out that your repo might just be the one I want. I modify few things like adopting anaconda-mode to write Python and else.

Just two piece of advice:

In ``.travis.yml`` , looks like the allow_failures works like bellow:

```env:
  - EVM_EMACS=emacs-23.4-travis
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-23.4-travis
    - env: EVM_EMACS=emacs-24.1-travis
    - env: EVM_EMACS=emacs-24.2-travis
    - env: EVM_EMACS=emacs-24.3-travis
```

Another thing is that I am using Emacs 25 and seems that I have to do a recompile package after the initial process is finished.
```
;;; tmp -- this function resolve the Emacs25 warning.
(defun my-package-recompile()
  "Recompile all packages"
  (interactive)
  (byte-recompile-directory "~/.emacs.d/elpa" 0 t))
```
function is from stackoverflow and I just thought maybe you would be interested to look into these kind of warnings if planning to support Emacs25

Cheers!

**Comment by purcell** [comment]
Awesome, thanks. I've implemented the `.travis.yml` changes and they work nicely. Can you give me more info about the Emacs 25 problem, please? I use a recent HEAD version of Emacs too and have never experienced a problem with files going uncompiled.

**Comment by shwsun** [comment]
Hmm, I wonder whether it is because I am using the emacs25-git pkg from Arch User Repo.

The message buffer wont complain, but compile-log will give me same warnings like #314 . And the recompile function that I googled help me resolve it. My fork or this repo works perfectly for emacs24

**Comment by purcell** [comment]
Are you switching between Emacs versions with the same `.emacs.d`? If so, that can cause problems.

**Comment by shwsun** [comment]
No. I purged my .emacs.d. 

Maybe it is because of the AUR pkg that I am using. I guess you can close it though.

**Comment by purcell** [comment]
Yeah, sounds likely to be a packaging thing. Very odd.
