### ISSUE TITLE
init-sessions.el breaks the awesomewm layout management

### ISSUE THREAD

**Issue by kylidboy** [purcell/emacs.d#352]
awesome is tile windows manager. 
after I comment out the init-session part, every thing works nicely.
but with init-session part effective, the wm layout will be broken & emacs frame will be displayed on every wm tag

**Comment by purcell** [comment]
That will be `desktop-save-mode`. Probably what you should do is add `(setq desktop-restore-frames nil)` before the line in `init-sessions.el` which says `(desktop-save-mode 1)`. Then you still get desktop restoration, but not the frame layout.

(Ideally you'd be able to just customize `desktop-restore-frames`, but in this config the customisations would get loaded too late to affect `init-sessions.el`.)

**Comment by kylidboy** [comment]
SOLVED!!
thank u,
worship!

**Comment by purcell** [comment]
Yay, glad that worked for you. :-)
