### ISSUE TITLE
ad-handle-definition: 'ido-completing-read' got redefined

### ISSUE THREAD

**Issue by gentcys** [purcell/emacs.d#353]
OS: ubuntu 16.04
Emacs: 24.5.1
While start with command `emacs -nw` got an error:
`ad-handle-definition: 'ido-completing-read' got redefined`,
remove .emacs.d directory and reinstall, i got the error again.

**Comment by purcell** [comment]
That's not an error, that's a warning, and you can ignore it. :-)
