### ISSUE TITLE
Got a long time to stop emacs daemon via systemd

### ISSUE THREAD

**Issue by Xiaomu0** [purcell/emacs.d#354]
I created the emacs.service like this (refer to Archlinux Wiki)

> ~/.config/systemd/user/emacs.service
> 
> [Unit]
> Description=Emacs: the extensible, self-documenting text editor
> 
> [Service]
> Type=forking
> ExecStart=/usr/bin/emacs --daemon
> ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
> Restart=always
> 
> [Install]
> WantedBy=default.target
> 

Thus I got a long wait when I shutdown my machine as well as when I use command below
systemctl stop emacs.service
systemctl restart emacs.service

How was it happening?
I guessed it was the warning:"Saving desktop? ( y or n )", but it seems not to be.
I've tried this command: emacsclient --eval "(kill-emacs)". It works well, needing no waiting.

**Comment by purcell** [comment]
Sorry, I don't know how to help with this. Perhaps Emacs was prompting you to save unsaved buffers.
