### ISSUE TITLE
about company-anaconda

### ISSUE THREAD

**Issue by seventhking** [purcell/emacs.d#355]
i installed anaconda-mode and company-anaconda base on your emacs config,i got a problem that when i type dot the select box didn't show automaticly ,i should type the command 'company-anaconda' to deal it.
i'm a beginner
thanks

init-local.el:
(eval-after-load "company"
  '(add-to-list 'company-backends 'company-anaconda))
;;use anaconda-mode
(add-hook 'python-mode-hook 'anaconda-mode)

(require 'company)
(require 'company-lua)
(add-to-list 'company-backends 'company-lua)

(provide 'init-local)

**Comment by huseyinyilmaz** [comment]
@seventhking 
Here is How I did it:
```
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook #'(lambda ()
                               (add-to-list 'company-backends 'company-anaconda)))
```

It seems like I have added company-anaconda to company-backends on python-mode-hook instead of after-load. That might solve your problem.

**Comment by arthurl** [comment]
@seventhking, @huseyinyilmaz: Steve has already written a function `sanityinc/local-push-company-backend` to handle that for you.

Like this:

```lisp
(after-load 'company
  (add-hook 'python-mode-hook
            (lambda () (sanityinc/local-push-company-backend #'company-anaconda)))))
```

**Comment by seventhking** [comment]
@arthurl :it works well under your advice, thank you.
also thanks for @huseyinyilmaz

**Comment by purcell** [comment]
Thanks folks! I might consider adding `anaconda-mode` to the core config, but at least for me the auto-install of the necessary Python libraries on OS X failed, and I'm wary of causing breakage for other users.

**Comment by arthurl** [comment]
@purcell: Just curious, is there a reason for your preference of `anaconda-mode` over `elpy`? (I'm using `emacs-jedi` now, and am looking to switch to either one of them. It's not clear to me how they differ though...)

**Comment by purcell** [comment]
@arthurl I don't have a preference, actually: I don't work much with Python these days. Looks like `elpy` is bigger and tries to do more: it requires `yasnippet`, which I don't love.

**Comment by arthurl** [comment]
@purcell I see! Just FYI, I've just tried `anaconda-mode`, and the auto-install failure that you mentioned still happens as of now. Hence, the very first python file opened will not have `anaconda-mode` enabled. However, it seems that the install was actually successful, and subsequent opening of python files no longer display any errors, and _does_ have `anaconda-mode` enabled. (Note: the `anaconda-mode` github page suggests downgrading jedi, but I _did not_ do that. So this is what a new unwitting user will see.)

In any case, the errors do not affect existing python editing functionality, so enabling anaconda by default might not be so bad. Still, the errors appearing on the first run might make some people uncomfortable.

**Comment by purcell** [comment]
Yeah, still doesn't work for me, so I don't think the install succeeded. I'm not really comfortable risking enabling this by default.
