### ISSUE TITLE
about skeleton

### ISSUE THREAD

**Issue by lokihsx** [purcell/emacs.d#356]
we get more "define-skeleton" on our php-mode files, but how can I use that in my own project? please help

**Comment by purcell** [comment]
Sorry, I don't understand the question. Could you clarify please?

**Comment by lokihsx** [comment]
I'm Sorry, fogive me terrible English, I mean we got more "define-skeleton"
in our php-mode, these look like so useful, But i don't know how use them...

**Comment by purcell** [comment]
I've never used `skeleton` before, but it looks like it works like this: a `define-skeleton` form like
```el
(define-skeleton php-array_change_key_case
  "Insert an array_change_key_case statement. Changes the case of all keys in an array"
  ""
  '(setq array (skeleton-read "array: "))
  '(setq case (skeleton-read "case: "))
  > "array_change_key_case(" array ", " case ");" \n
)
```
defines an interactive command `php-array_change_key_case`. So to use that skeleton, you would just say `M-x php-array_change_key_case`. I guess you could bind that into a keymap if you used it a lot.

Hope that helps!

**Comment by lokihsx** [comment]
it's work! thanks
