### ISSUE TITLE
High CPU usage on OS X 10.11.5

### ISSUE THREAD

**Issue by OscaRoa** [purcell/emacs.d#358]
For some reason with this configuration Emacs uses most of time 99% of CPU, anyone with the same problem?

Thanks.

**Comment by purcell** [comment]
Which Emacs version?

I haven't seen this behaviour on 10.11.5 with either a recent snapshot build of Emacs or a released version, but if you provide more info I'm happy to suggest some things you might try to investigate.

**Comment by OscaRoa** [comment]
Nevermind, I updated the configuration with a git pull and it's fine again, thanks for the answer.

**Comment by wangruifei** [comment]
Hi
  My Mac version is 10.12.3. and Emacs uses most of time 26% of cup. My cup is core i7.
  Is it a problem?
  My emcas version is 25.1.1

**Comment by purcell** [comment]
Hi! I have the same Emacs and OS X versions, and I don’t see the same problems. My Emacs uses perhaps 10% CPU right now, with 94 buffers of various types open. Do you have lots of buffers open? If so, what types of buffer are they?
