### ISSUE TITLE
url-http do not work

### ISSUE THREAD

**Issue by lokihsx** [purcell/emacs.d#359]
My emacs version is 25.0.95, but when i try to link some website with "browse-url-emacs" or try to install package with "package-install", it always give me Wrong type argument: processp, nil
backtrace:
Debugger entered--Lisp error: (wrong-type-argument processp nil)
  set-process-buffer(nil #<buffer  *url-http-temp*>)
  ad-Advice-open-network-stream(#[(name buffer host service &rest parameters) "\306\307!\204\n\310\311!\210\312\313\"\312\314\"	\204F\n\315=\2042\n\316>\203F\312\317\"\2032\312\320\"\204F\307\321\322\f\323
\324)\325\312\325\"&\n\202\272\f\206M\326\327!\n\315=\203^\312\330\"\204^\331\202\200\n\332>\203h\333\202\200\n\334>\203r\335\202\200\n\336=\203|\337\202\200\310\340\n\"\341*+,\342\216+,
)%*)	\203\266*@\343*A@\344\345*8\313\346*8\347\350*8\257	\202\271*@+*\207" [parameters return-list type name buffer host featurep make-network-process error "Emacs was compiled without networking support" plist-get :type :return-list plain (nil network) :success :capability-command :name :buffer :host :service :nowait generate-new-buffer " *stream buffer*" :always-query-capabilities network-stream-open-plain (nil network starttls plain) network-stream-open-starttls (tls ssl) network-stream-open-tls shell network-stream-open-shell "Invalid connection type %s" nil #[nil "?\205\303	@!\203\304	@\305\"\210\306\n!\207" [buffer result work-buffer processp set-process-buffer nil kill-buffer] 3] :greeting :capabilities 2 3 :error 4 service result fun work-buffer] 13 ("/usr/share/emacs/25.0.95/lisp/net/network-stream.elc" . 613)] "www.google.com" #<buffer  *url-http-temp*> "www.google.com" 80 :type plain :nowait t)
  apply(ad-Advice-open-network-stream #[(name buffer host service &rest parameters) "\306\307!\204\n\310\311!\210\312\313\"\312\314\"	\204F\n\315=\2042\n\316>\203F\312\317\"\2032\312\320\"\204F\307\321\322\f\323
\324)\325\312\325\"&\n\202\272\f\206M\326\327!\n\315=\203^\312\330\"\204^\331\202\200\n\332>\203h\333\202\200\n\334>\203r\335\202\200\n\336=\203|\337\202\200\310\340\n\"\341*+,\342\216+,
)%*)	\203\266*@\343*A@\344\345*8\313\346*8\347\350*8\257	\202\271*@+*\207" [parameters return-list type name buffer host featurep make-network-process error "Emacs was compiled without networking support" plist-get :type :return-list plain (nil network) :success :capability-command :name :buffer :host :service :nowait generate-new-buffer " *stream buffer*" :always-query-capabilities network-stream-open-plain (nil network starttls plain) network-stream-open-starttls (tls ssl) network-stream-open-tls shell network-stream-open-shell "Invalid connection type %s" nil #[nil "?\205\303	@!\203\304	@\305\"\210\306\n!\207" [buffer result work-buffer processp set-process-buffer nil kill-buffer] 3] :greeting :capabilities 2 3 :error 4 service result fun work-buffer] 13 ("/usr/share/emacs/25.0.95/lisp/net/network-stream.elc" . 613)] ("www.google.com" #<buffer  *url-http-temp*> "www.google.com" 80 :type plain :nowait t))
  open-network-stream("www.google.com" #<buffer  *url-http-temp*> "www.google.com" 80 :type plain :nowait t)
  url-open-stream("www.google.com" #<buffer  *url-http-temp*> "www.google.com" 80 nil)
  url-http-find-free-connection("www.google.com" 80 nil)
  url-http([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t])
  url-http-options([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t])
  url-dav-supported-p([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t])
  url-http-file-attributes([cl-struct-url "http" nil nil "www.google.com" nil "" nil nil t nil t] nil)
  url-file-attributes("http://www.google.com")
  apply(url-file-attributes "http://www.google.com")
  url-file-handler(file-attributes "http://www.google.com")
  file-attributes("http://www.google.com")
  find-file-noselect("http://www.google.com" nil nil nil)
  find-file-other-window("http://www.google.com")
  browse-url-emacs("http://www.google.com")
  eval((browse-url-emacs "http://www.google.com") nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-last-sexp nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

That i'm sure my network is no problem, because when i started emacs with "-Q" option, Everything will be ok, so I guess maybe something wrong, when initialize our emacs config, but I can't find it. 

Please help thx!

**Comment by lokihsx** [comment]
Okay, it seems be solved, The problem is geben's config, when i load geben package, that configure my Proxy automatically...so I can't use http after.... sorry about my terrible English

**Comment by purcell** [comment]
Hah, no problem - glad you figured it out. :-)
