### ISSUE TITLE
company-clang

### ISSUE THREAD

**Issue by seventhking** [purcell/emacs.d#360]
I do what mentioned in [http://tuhdo.github.io/c-ide.html#orgheadline15](url).However, it didn't work for me.
My init-local.el file looks like below:

;;anaconda-mode
(add-hook 'python-mode-hook 'anaconda-mode)
(after-load 'company
  (add-hook 'python-mode-hook
            (lambda () (sanityinc/local-push-company-backend #'company-anaconda))))

;;company-lua
(after-load 'company
  (add-hook 'lua-mode-hook
            (lambda () (sanityinc/local-push-company-backend #'company-lua))))

;;company-c-headers
(require 'company-c-headers)

(after-load 'company
  (add-hook 'c-mode-common-hook
            (lambda () (sanityinc/local-push-company-backend #'company-c-headers))))

(add-to-list 'company-c-headers-path-system '"/usr/include/c++/4.8.2/")

;;company-clang
(setq company-backends (delete 'company-semantic company-backends))

Maybe, in our config, default backends is not company-semantic?If yes, how to customize it when just in cc-mode to use company-clang?

Thanks.

**Comment by purcell** [comment]
Correct, `company-clang` wouldn't be in the default backends for this config, so I'm guessing you need something like this:

```el
(after-load 'company
  (add-hook 'c-mode-common-hook
    (lambda () (sanityinc/local-push-company-backend #'company-clang))))
```

**Comment by seventhking** [comment]
I just set the file as you said, but it doesn't work. Does any other backends have higher priority than company-clang(just like company-semantic which has higher priority than company-clang)

**Comment by purcell** [comment]
I don't know, sorry, and I don't have time right now to try to reproduce what you are attempting. There are various ways to inspect the variable to see what it actually is in the source code buffer, so why not try one of those? All the information will be accessible to you, so start with using `C-x h v` to examine `company-backends`.
