### ISSUE TITLE
the google-translate.el error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#361]
I want to add google-translate.el in this config from MELPA, some message show that the init config can't work:
>Warning (initialization): An error occurred while loading `/Users/sb/.emacs.d/init.el':
>End of file during parsing: /Users/sb/.emacs.d/lisp/init-google-translate.el  
>To ensure normal operation, you should investigate and remove the  
>cause of the error in your initialization file.  Start Emacs with
>the `--debug-init' option to view a complete error backtrace.

the content of init-google-translate.el is:
```;; google-translate packages```
```(require-package 'google-translate)```
```(require-package 'google-translate-smooth-ui)```
```;; shotcut```
```(global-set-key "\C-ct" 'google-translate-smooth-translate)```
```;; translate en <-> cn```
```(setq google-translate-translation-directions-alist '(("en" . "cn") ("cn" . "en"))```
```(provide 'init-google-translate)```

what happened?

**Comment by purcell** [comment]
You're missing a closing parenthesis at the end of this line:
```el
(setq google-translate-translation-directions-alist '(("en" . "cn") ("cn" . "en"))
```

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
well.....just make a joking

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
what's the difference from require and require-package

**Comment by purcell** [comment]
`require` is an Emacs built-in function which loads a library so that your code can use it.

`require-package` is a function written for my config which ensures the named package is installed. It doesn't load it, though: I rely on `require` or autoloads for that to happen.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
tks for replay
