### ISSUE TITLE
Split Screen

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#362]
try to horizontal split the screen 
one buffer one window
1. using C-x 3 can add many
2. but leaving only one when use C-x C-b
I want to retain the original location

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the screenshot
1.
<img width="1277" alt="2016-08-03 1 30 35" src="https://cloud.githubusercontent.com/assets/16307328/17355705/134aa310-5985-11e6-9ebd-eb92043eb317.png">
2.
<img width="1280" alt="2016-08-03 1 41 56" src="https://cloud.githubusercontent.com/assets/16307328/17355715/1854ca8e-5985-11e6-8e52-36adca682e65.png">

**Comment by purcell** [comment]
Just hit `q` to exit `ibuffer` and your window configuration will be restored. You can also use `winner-undo` (bound to `C-c left`) to step back through previous window configurations.

If you want to remove the full-screen behaviour, then remove the `fullframe` references in the `lisp/init-ibuffer.el` file in your fork.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Expecting to give some propose to modify full-screen function instead of remove all ```init-ibuufer.el```
