### ISSUE TITLE
use C-h can't pop the keys Tips

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#363]
is it a error?

**Comment by purcell** [comment]
I think you mean that there is not the same pop-up as for `C-x` etc. That's non-standard behaviour provided by `guide-key`.

I didn't add that prefix to the `guide-key` list because it provides its own help with `?`, ie. `C-h ?`. However, I've added it now.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
thanks for give a help
