### ISSUE TITLE
defadvice for shell-command-on-region breaks with C-u

### ISSUE THREAD

**Issue by tesujimath** [purcell/emacs.d#367]
I often sort lines of text by selecting a region, and using C-u M-|, for replacing the text in the region with the output of shell-command-on-region.

The defadvice clause for shell-command-on-region in init-compile.el breaks this.  It gives "wrong number of arguments".  I don't know how to fix this without simply deleting the defadvice clause, which makes it work again.

**Comment by purcell** [comment]
Thanks for reporting that — fixed!
