### ISSUE TITLE
the 'unmatched bracket or quote' error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#368]
the init config can't go pass when add org-feed-alist function to init-org.el  
## added function:
```;;; RSS FEED LIST```
```(setq org-feed-alist
      '(("ZhiHu Daily"
         "http://zhihu.com/rss"
         "~/org/feeds.org" "知乎每日精选")```  
## error report:
>Contacting host: elpa.gnu.org:80
Couldn't install package `mac-grab-link': (error "Package `mac-grab-link-' is unavailable")
Loading /Users/sb/.emacs.d/.session...done
Please type y, n, or !: !
Saving file /Users/sb/.emacs.d/custom.el...
Wrote /Users/sb/.emacs.d/custom.el [2 times]
byte-code: Unmatched bracket or quote  

## scanshot:
<img width="758" alt="2016-08-10 11 03 01" src="https://cloud.githubusercontent.com/assets/16307328/17540803/fff3adc2-5eeb-11e6-9980-7db0a922922d.png">

**Comment by twlz0ne** [comment]
Same issue

<pre>
⋊> git pull
⋊> ./test-startup.sh
Attempting startup...
Loading ~/toolkit/emacs.d-purcell/init.el (source)...
Loading ~/toolkit/emacs.d-purcell/recentf...
Cleaning up the recentf list...
Cleaning up the recentf list...done (0 removed)
ad-handle-definition: ‘ido-completing-read’ got redefined
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Opening TLS connection to ‘melpa.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘melpa.org’...done
Making url-show-status local to  *http melpa.org:443* while let-bound!
Package refresh done
<h3>Couldn’t install package ‘mac-grab-link’: (error "Package ‘mac-grab-link-’ is unavailable")</h3>
Loading ~/toolkit/emacs.d-purcell/custom.el (source)...
init completed in 18.60ms
Loading ~/toolkit/emacs.d-purcell/.session...
Desktop restored in 0.00ms
Startup successful
</pre>

**Comment by purcell** [comment]
Thanks, fixed.
