### ISSUE TITLE
GUI cannot activate input method fcitx even if disabled C-SPC

### ISSUE THREAD

**Issue by cmal** [purcell/emacs.d#37]
ubuntu 12.04 LTS amd64
ibus works perfectly in emacs23
but when I uninstall ibus and switch to fcitx, fcitx cannot be activated when using GUI.
fcitx works perfectly in other places.
I have added (global-set-key (kbd "C-SPC") 'nil) in custom.el
when hit C-SPC, minibuffer shows: C-SPC is undefined.
when using "emacs -nw" or "emacs -Q" to start emacs, fcitx works perfectly and does not have any problems.

**Comment by oKarolMoroz** [comment]
To anyone struggling with this issue: you have to set `LC_CTYPE` to something Chinese (`zh_TW.UTF-8` did the trick in my case).
