### ISSUE TITLE
the init-org.el error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#370]
## add funtion to init-org.el:
>;;; Opening pdf at specific page
>(delete '("\\.pdf\\'" . default) org-file-apps)
>(add-to-list 'org-file-apps '("\\.pdf::\\([0-9]+\\)\\'" . "evince \"%s\" -p %1"))

## error report:
>Symbol's value as variable is void: org-file-apps

## message from --debug-init:
it shows 'void-variable org-file-apps'
<img width="925" alt="2016-08-13 5 41 56" src="https://cloud.githubusercontent.com/assets/16307328/17642557/4ab3ca2a-617d-11e6-8a3e-5d1126edeb25.png">

## snapshot:
<img width="1251" alt="2016-08-13 5 22 56" src="https://cloud.githubusercontent.com/assets/16307328/17642455/a6ad9fac-617a-11e6-9d7e-47fd02cac7f0.png">

**Comment by purcell** [comment]
Your question isn't specific to this config, but I will answer it anyway this time.

The error message here explains the problem - you're referring to a variable that has not yet been defined when the code run. Consider wrapping the code in an `(after-load 'org ...)` block.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
my false 
aleady amend the title
very thanks for take care of

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Results after tuning:
<img width="602" alt="2016-08-13 9 14 03" src="https://cloud.githubusercontent.com/assets/16307328/17643371/ec46314e-619a-11e6-84a4-75ee43227901.png">

**Comment by purcell** [comment]
Sorry, that is not something I can help you with. I can only provide support for what is in this configuration, not what users add to it.
