### ISSUE TITLE
Symbol’s value as variable is void: company-quickhelp-mode-map

### ISSUE THREAD

**Issue by getong** [purcell/emacs.d#373]
I clone the repo, and install packages, then it appears this msg, and emacs not works any more.

**Comment by lipanXJ** [comment]
How about trying clone repo again?it maybe because network problem.

**Comment by purcell** [comment]
Yes, restarting should fix this -- your package index is out of date. Otherwise, try `M-x package-refresh-contents` and then restart.

**Comment by getong** [comment]
I don't think this is the network problem. I delete  the .emacs.d and clone this many times, and after I install the packages, this message appear again. I also has a old repo, it works fine, but after I update the packages, the message appears again. I think some package is wrong, but I don't know which.

**Comment by getong** [comment]
Thanks. It works.
