### ISSUE TITLE
Some thing about buffer.

### ISSUE THREAD

**Issue by lipanXJ** [purcell/emacs.d#374]
When i switch buffer(shutcut is C-x b),there also a lot of    ***autoloads.el,here are the examples

` regex-tool-autoloads.el | dsvn-autoloads.el | htmlize-autoloads.el | lua-mode-autoloads.\
el | gnuplot-autoloads.el | flycheck-ledger-autoloads.el | ledger-mode-autoloads.el | flycheck-clojure-autoloads.el | cider-autoloads.el | queue-autoloads.el |`

I think they are not usable,why not consider exclude them?besides,there also many ***autoloads.el in recentf-open-files.I want to konw how to exclude them,could you help me?

**Comment by purcell** [comment]
I think they have resulted from installing a bunch of packages: the package installation process involves generating those files using a temporary buffer, and it looks like they get added to the recent files list. There may be a way to customize `recentf` to prevent that, but I'm not convinced it would be worth the effort.

**Comment by lipanXJ** [comment]
Thanks for you help,i can not agree with you more,it is not  worth doing this.
