### ISSUE TITLE
org can't effect chinese font with **

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#376]
when use * chinese *  
the font is not changed to bold

**Comment by purcell** [comment]
Sorry, this isn't a well-specified bug report, and I can't help fix issues I cannot reproduce.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
ok I will find the solutions
it seems actually exist

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
so difficulty
