### ISSUE TITLE
file naming convention

### ISSUE THREAD

**Issue by svsmailus** [purcell/emacs.d#379]
When I C-x C-f and create a new file test.org. When I save the file C-x C-w it saves as .#test.org

Is this a problem with my installation or part of your emacs.d setup?

**Comment by purcell** [comment]
That's an Emacs backup file, produced automatically to save you from yourself. It's based on the name you chose for the file initially. If you then choose to write the file to a different filename (using C-x C-w), the backup file will remain. So this is standard Emacs behaviour, and not related to this config.
