### ISSUE TITLE
how to completely use this config?

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#380]
There are many programming language in this config , how can I taste the benefits of it in actual programming.
Example: I write ruby , but I can't know how to test and compile it by handy.

**Comment by purcell** [comment]
I should maybe record some screencasts or write some documentation, but I really only maintain this configuration to be useful to me, and while a lot of other people now use it, I'm sorry that I am not very keen to spend time on those tasks. My suggestion would be to look at `init-ruby.el`, and read a little about each of the packages it mentions, e.g. [Robe](https://github.com/dgutov/robe).

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
thanks for opening a way
