### ISSUE TITLE
flycheck checker always complain

### ISSUE THREAD

**Issue by imnisen** [purcell/emacs.d#382]
Hi, when I edit any clojure file with cider repl open, such as test.clj, every time I print a character, flycheck reports a error, such as:

```
error in process filter: Wrong number of arguments: (4 . 4), 0 [2 times]
Error from syntax checker clojure-cider-eastwood: Done with no errors
```

so I try to disable the checker as following in init-local.el(I found need to disable the three checker so it can work):

```
(with-eval-after-load 'flycheck
  (setq-default flycheck-disabled-checkers '()))

(provide 'init-local)

```

it stops reporting checking errors, which makes it finally can type something.
But I wonder if I need to disable the three checkers , why add them in init-clojure-cider.el ?
And if you have this problem, and how you solve it?
Any sugesstions will be appreciated!

**Comment by olessavluk** [comment]
Hi, @imnisen 

I've had the same issue and resolved it by adding `acyclic/squiggly-clojure` to the dependencies as pointed in the readme - https://github.com/clojure-emacs/squiggly-clojure#dependencies-in-clojure

Also keep in mind that you no longer need to add `cider/cider-nrepl` to `:plugins`, see - http://cider.readthedocs.io/en/latest/installation/

**Comment by purcell** [comment]
Thanks @olessavluk.
