### ISSUE TITLE
Emacs fails to start due to failed package signature

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#383]
Hello Steve, I reverted back to your `.emacs.d` after trying spacemacs. I therefore took the opportunity to do a clean setup. I removed all emacs configurations on my system and cloned your `.emacs.d`. 

Upon starting emacs and accepting to load the default theme, the setup stops with the message

    Warning (initialization): An error occured while loading '/Users/user/.emacs.d/init.el':
    Failed to verify signature: nlinum-1.6.el.sig

The setup stops there after several delete and restarts. I'll sure appreciate any help.

**Comment by purcell** [comment]
Hmmm. You have `gpg` installed, and probably don't have the public key for the GNU ELPA repository in your keyring. Try commenting out the section in `lisp/init-elpa.el` which refers to `package-check-signature` and then re-start -- does that help? I might need to adjust the config if so.

**Comment by thepreacher** [comment]
Your solution indeed worked. Thanks.
