### ISSUE TITLE
anaconda-mode is not available

### ISSUE THREAD

**Issue by melotusme** [purcell/emacs.d#385]
![image](https://cloud.githubusercontent.com/assets/10104231/19209901/e49384c4-8d46-11e6-90fe-e678478ce5ab.png)
I use pyenv, and found that anaconda-mode and anaconda-eldoc-mode do not work in emacs.
It show errors `Can't open posix module`
![image](https://cloud.githubusercontent.com/assets/10104231/19209918/28a63b34-8d47-11e6-8cd3-405e2906645c.png)

**Comment by purcell** [comment]
Hmm. That's really an anaconda-mode problem, I think. Would you mind filing an issue upstream instead please?
