### ISSUE TITLE
Invalid options error with Emacs26

### ISSUE THREAD

**Issue by shwsun** [purcell/emacs.d#391]
It is showing a "Invalid options for slot timer in spin" error with today's master branch. And I suspect it affects some behavior of Emacs. Is there anyone experiencing the same thing or having any solutions?

My system:
Arch Linux
Emacs 26

**Comment by purcell** [comment]
I'm guessing the problem here is due to old `.elc` files. Try deleting your `~/.emacs.d/elpa` directory and restarting.
