### ISSUE TITLE
c++-mode can't be typed in via M-x

### ISSUE THREAD

**Issue by lijunsong** [purcell/emacs.d#393]
Synopsis:

User can't type in `c++-mode` in M-x

Reproduce:

To reproduce, open a C file, and then try to switch to `c++-mode`. Notice that if the `c++-mode` is not the first suggestion, the only way you can get `c++-mode` is to up and down arrow keys.

I am using `Emacs 25.1.1`.

**Comment by purcell** [comment]
Yeah, that's not very comfortable, I guess, but it's because the completion works using `ivy`, which uses regular expressions. And in fact, if you type `M-x c\+`, then this works fine. 

I think you can use non-regular-expression matching instead, using something like this:
```
(setq ivy-re-builders-alist '((t . regexp-quote)))
```

/cc @abo-abo.
