### ISSUE TITLE
what the function name of system-clipboard copying and pasting?

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#394]
## Reproduce
> init-evil.el

> (require 'general)
> (general-evil-setup t)
> (nvmap :prefix "SPC"
>         "=" 'the-function-name-of-copy  
       "-" 'the-function-name-of-paste)

**Comment by purcell** [comment]
I'm not sure that there are any such functions which are specific to the system clipboard - that's termed the "secondary selection". Generally you'd just configure your Emacs to synchronise the system and Emacs clipboards, and use the regular functions like `copy-region-as-kill` etc.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
but when I use M-w to copy the word that also I can use cmd+v to paste from system-clipboard.
It's a personal config or emacs's default set?

**Comment by purcell** [comment]
I think the only relevant setting in this config is `(setq save-interprogram-paste-before-kill t)`, in `init-editing-utils.el`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the pointing is very precision.
further doubt, if there is a function name act as the behavior of M-w and C-y.
