### ISSUE TITLE
Can the emacs config work offline after full download once ?

### ISSUE THREAD

**Issue by chechunli** [purcell/emacs.d#396]
hi, purcell, 
    Can Emacs config(.emacs.d) work offline after I download it first time. 
    because I want to use it in the environment without internet.

**Comment by purcell** [comment]
Yes, absolutely!

**Comment by chechunli** [comment]
but how to config, I use your configuration

**Comment by purcell** [comment]
There's nothing you need to do: just run it once while connected to the internet, then it will work without internet access later.

**Comment by chechunli** [comment]
but, I met a error and don't continue init process anyway, and log is:
Debugger entered--Lisp error: (error "Could not create connection to melpa.org:443")
  signal(error ("Could not create connection to melpa.org:443"))
  error("Could not create connection to %s:%d" "melpa.org" 443)
  url-http([cl-struct-url "https" nil nil "melpa.org" nil "/packages/ag-20161027.1758.el" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-https([cl-struct-url "https" nil nil "melpa.org" nil "/packages/ag-20161027.1758.el" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("https://melpa.org/packages/ag-20161027.1758.el" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("https://melpa.org/packages/ag-20161027.1758.el" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously("https://melpa.org/packages/ag-20161027.1758.el")
  url-insert-file-contents("https://melpa.org/packages/ag-20161027.1758.el")
  package-install-from-archive([cl-struct-package-desc ag (20161027 1758) "A front-end for ag ('the silver searcher'), the C ack replacement." ((dash (2 8 0)) (s (1 9 0)) (cl-lib (0 5))) single "melpa" nil nil nil])
  mapc(package-install-from-archive ([cl-struct-package-desc ag (20161027 1758) "A front-end for ag ('the silver searcher'), the C ack replacement." ((dash (2 8 0)) (s (1 9 0)) (cl-lib (0 5))) single "melpa" nil nil nil]))
  package-download-transaction(([cl-struct-package-desc ag (20161027 1758) "A front-end for ag ('the silver searcher'), the C ack replacement." ((dash (2 8 0)) (s (1 9 0)) (cl-lib (0 5))) single "melpa" nil nil nil]))
  package-install(ag)
  (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package))
  (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(ag)
  (progn (require-package (quote ag)) (require-package (quote wgrep-ag)) (setq-default ag-highlight-search t) (global-set-key (kbd "M-?") (quote ag-project)))
  (if (executable-find "ag") (progn (require-package (quote ag)) (require-package (quote wgrep-ag)) (setq-default ag-highlight-search t) (global-set-key (kbd "M-?") (quote ag-project))))
  eval-buffer(#<buffer  *load*-545345> nil "c:/Users/DEV/.emacs.d/lisp/init-grep.el" nil t)  ; Reading at buffer position 302
  load-with-code-conversion("c:/Users/DEV/.emacs.d/lisp/init-grep.el" "c:/Users/DEV/.emacs.d/lisp/init-grep.el" nil t)
  #<subr require>(init-grep nil nil)
  funcall(#<subr require> init-grep nil nil)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t)))))
  (let (ad-return-value) (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis ... require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))) ad-return-value)
  ad-Advice-require(#<subr require> init-grep)
  apply(ad-Advice-require #<subr require> init-grep)
  require(init-grep)
  eval-buffer(#<buffer  *load*> nil "c:/Users/DEV/.emacs.d/init.el" nil t)  ; Reading at buffer position 2479
  load-with-code-conversion("c:/Users/DEV/.emacs.d/init.el" "c:/Users/DEV/.emacs.d/init.el" t t)
  load("c:/Users/DEV/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
目测网络问题 开个代理应该能解决

**Comment by purcell** [comment]
As the error message says, your Emacs is unable to connect to MELPA with SSL (ie. https). That could be because of your firewall, or because your Emacs was not compiled with support for SSL. The best solution is to fix this, but you can also try changing [these lines](https://github.com/purcell/emacs.d/blob/0012d9cb67866c2d86d26943bdd3dfd929afdc4a/lisp/init-elpa.el#L29-L31) so that `http` is used for MELPA instead of `https`.

**Comment by chechunli** [comment]
sorry to bother you again, I update my emacs config in A PC in my home and it runs well. I also change the https to http. after that I copy the whole .emacs.d folder to B PC in my corp. but I also met a new error about connect to melpa.org, Can I work around this error by changing some config in .emacs.d ?
the error is:
Debugger entered--Lisp error: (error "Could not create connection to melpa.org:443")
  signal(error ("Could not create connection to melpa.org:443"))
  error("Could not create connection to %s:%d" "melpa.org" 443)
  url-http([cl-struct-url "https" nil nil "melpa.org" nil "/packages/ag-20161027.1758.el" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-https([cl-struct-url "https" nil nil "melpa.org" nil "/packages/ag-20161027.1758.el" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("https://melpa.org/packages/ag-20161027.1758.el" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("https://melpa.org/packages/ag-20161027.1758.el" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
开代理 或 http://elpa.emacs-china.org

**Comment by chechunli** [comment]
I can't connect to internet, it's not the proxy issue

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> error "Could not create connection to melpa.org:443"
may be require connect to the elpa and compile package first

**Comment by chechunli** [comment]
I just remove the init-grep.el, it work..
thanks your help purcell.
