### ISSUE TITLE
Windows: JavaScript editing slow

### ISSUE THREAD

**Issue by rrooij** [purcell/emacs.d#397]
JavaScript editing is very slow on Windows when using the latest purcell default config from git and the latest available Emacs for Windows.

I've only tested it on EcmaScript 6 files yet, but I doubt that the behavior is different on ES5.

**Comment by purcell** [comment]
Thanks for the report. I'm not going to be able to test this on Windows, sorry. Is the file extremely large? (Could you send it to me for testing, if it's not proprietary?) Have you enabled `linum-mode`?

**Comment by rrooij** [comment]
I'll report more later when I have access to a Windows computer. Stay tuned!
