### ISSUE TITLE
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (file-missing "Searching for program" "No such file or directory" "git")

### ISSUE THREAD

**Issue by xishi00** [purcell/emacs.d#398]
When I update the installed packages by using package-list mode, emacs frequently pops up this error and stop updating. Why?
The following is my logs.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Loading /home/yg/.emacs.d/recentf...done
Cleaning up the recentf list...
File /home/yg/.emacs.d/elpa/jump-20161016.2313/jump-autoloads.el removed from the recentf list
File /home/yg/.emacs.d/elpa/inflections-20161017.157/inflections-autoloads.el removed from the recentf list
File /home/yg/.emacs.d/elpa/inf-ruby-20161019.1425/inf-ruby-autoloads.el removed from the recentf list
File /home/yg/.emacs.d/elpa/erlang-20161108.47/erlang-autoloads.el removed from the recentf list
File /home/yg/.emacs.d/elpa/company-20161113.1747/company-autoloads.el removed from the recentf list
File /home/yg/.emacs.d/elpa/ivy-20161123.1333/ivy-autoloads.el removed from the recentf list
Cleaning up the recentf list...done (6 removed)
Loading /home/yg/.emacs.d/custom.el (source)...done
Add Chinese-pyim dict "Greatdict-elpa" to ‘pyim-extra-dicts’。
Loading /home/yg/.emacs.d/.session...done
No desktop file.
Desktop restored in 1.21ms
init completed in 12813.10ms
For information about GNU Emacs and the GNU system, type C-h C-a.
Package refresh done
18 packages can be upgraded; type ‘U’ to mark them for upgrading.
18 packages marked for upgrading.
Upgrade these 18 packages (aggressive-indent-20161201.1001, cider-20161201.757, counsel-20161205.124, erlang-20161129.304, htmlize-20161205.1201, inf-ruby-20161204.1637, intero-20161204.626, ivy-20161204.48, js2-mode-20161205.1446, ledger-mode-20161204.758, magit-20161205.1302, magit-popup-20161201.1352, page-break-lines-20161205.2251, php-mode-20161205.1642, projectile-rails-20161130.1025, rspec-mode-20161129.1525, skewer-mode-20161205.419, with-editor-20161201.925)? (y or n) y
Package menu: Operation started [Upgrading 18]
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
cl--assertion-failed: Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))
18 packages marked for upgrading.
Upgrade these 18 packages (aggressive-indent-20161201.1001, cider-20161201.757, counsel-20161205.124, erlang-20161129.304, htmlize-20161205.1201, inf-ruby-20161204.1637, intero-20161204.626, ivy-20161204.48, js2-mode-20161205.1446, ledger-mode-20161204.758, magit-20161205.1302, magit-popup-20161201.1352, page-break-lines-20161205.2251, php-mode-20161205.1642, projectile-rails-20161130.1025, rspec-mode-20161129.1525, skewer-mode-20161205.419, with-editor-20161201.925)? (y or n) y
Package menu: Operation started [Upgrading 18]
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
Extracting with-editor-20161201.925/
Extracting with-editor-20161201.925/with-editor-pkg.el
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor-pkg.el
Extracting with-editor-20161201.925/with-editor.el
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor.el
Extracting with-editor-20161201.925/dir
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/dir
Extracting with-editor-20161201.925/with-editor.info
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor.info
Making version-control local to with-editor-autoloads.el while let-bound!
Generating autoloads for with-editor-pkg.el...done
Generating autoloads for with-editor.el...done
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor-autoloads.el
Checking /home/yg/.emacs.d/elpa/with-editor-20161201.925... [3 times]
Compiling /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor.el...done
Wrote /home/yg/.emacs.d/elpa/with-editor-20161201.925/with-editor.elc
Checking /home/yg/.emacs.d/elpa/with-editor-20161201.925...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
Extracting skewer-mode-20161205.419/
Extracting skewer-mode-20161205.419/skewer-html.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-html.el
Extracting skewer-mode-20161205.419/cache-table.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/cache-table.el
Extracting skewer-mode-20161205.419/skewer-mode.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-mode.el
Extracting skewer-mode-20161205.419/skewer-setup.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-setup.el
Extracting skewer-mode-20161205.419/skewer-css.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-css.el
Extracting skewer-mode-20161205.419/skewer-bower.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-bower.el
Extracting skewer-mode-20161205.419/skewer-everything.user.js
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-everything.user.js
Extracting skewer-mode-20161205.419/skewer-mode-pkg.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-mode-pkg.el
Extracting skewer-mode-20161205.419/example.html
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/example.html
Extracting skewer-mode-20161205.419/skewer-repl.el
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-repl.el
Extracting skewer-mode-20161205.419/skewer.js
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer.js
Generating autoloads for cache-table.el...done
Generating autoloads for skewer-bower.el...done
Generating autoloads for skewer-css.el...done
Generating autoloads for skewer-html.el...done
Generating autoloads for skewer-mode-pkg.el...done
Generating autoloads for skewer-mode.el...done
Generating autoloads for skewer-repl.el...done
Generating autoloads for skewer-setup.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-mode-autoloads.el
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/cache-table.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/cache-table.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-bower.el...
Turning on magit-auto-revert-mode...done
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-bower.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-bower.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-css.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-css.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-html.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-html.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419... [3 times]
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-mode.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-mode.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-repl.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-repl.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Compiling /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-setup.el...done
Wrote /home/yg/.emacs.d/elpa/skewer-mode-20161205.419/skewer-setup.elc
Checking /home/yg/.emacs.d/elpa/skewer-mode-20161205.419...
Done (Total of 7 files compiled, 2 skipped)
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
Extracting rspec-mode-20161129.1525/
Extracting rspec-mode-20161129.1525/rspec-mode-pkg.el
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/rspec-mode-pkg.el
Extracting rspec-mode-20161129.1525/rspec-mode.el
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/rspec-mode.el
Extracting rspec-mode-20161129.1525/snippets/
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/sfgb
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/sfgb
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/back
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/back
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/dc
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/dc
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/let
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/let
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/expb
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/expb
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/exp
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/exp
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/cont
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/cont
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/descm
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/descm
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/itiexp
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/itiexp
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/desc
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/desc
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/aft
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/aft
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/scn
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/scn
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/it
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/it
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/lfgb
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/lfgb
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/sbj
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/sbj
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/sp
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/sp
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/feat
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/feat
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/lfgc
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/lfgc
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/iexp
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/iexp
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/sfgs
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/sfgs
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/helper
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/helper
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/sfgc
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/sfgc
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/lfgs
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/lfgs
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/featm
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/featm
Extracting rspec-mode-20161129.1525/snippets/rspec-mode/bef
Wrote /home/yg/.emacs.d/elpa/rspec-mode-20161129.1525/snippets/rspec-mode/bef
apply: Searching for program: No such file or directory, git
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (file-missing "Searching for program" "No such file or directory" "git")
16 packages marked for upgrading.
Upgrade these 16 packages (aggressive-indent-20161201.1001, cider-20161201.757, counsel-20161205.124, erlang-20161129.304, htmlize-20161205.1201, inf-ruby-20161204.1637, intero-20161204.626, ivy-20161204.48, js2-mode-20161205.1446, ledger-mode-20161204.758, magit-20161205.1302, magit-popup-20161201.1352, page-break-lines-20161205.2251, php-mode-20161205.1642, projectile-rails-20161130.1025, rspec-mode-20161129.1525)? (y or n) y
Package menu: Operation started [Upgrading 16]
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
apply: Searching for program: No such file or directory, git
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (file-missing "Searching for program" "No such file or directory" "git")
16 packages marked for upgrading.
Upgrade these 16 packages (aggressive-indent-20161201.1001, cider-20161201.757, counsel-20161205.124, erlang-20161129.304, htmlize-20161205.1201, inf-ruby-20161204.1637, intero-20161204.626, ivy-20161204.48, js2-mode-20161205.1446, ledger-mode-20161204.758, magit-20161205.1302, magit-popup-20161201.1352, page-break-lines-20161205.2251, php-mode-20161205.1642, projectile-rails-20161130.1025, rspec-mode-20161129.1525)? (y or n) y
Package menu: Operation started [Upgrading 16]
Contacting host: mirrors.tuna.tsinghua.edu.cn:80
Parsing tar file...done
apply: Searching for program: No such file or directory, git
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (file-missing "Searching for program" "No such file or directory" "git")
user-error: Minibuffer window is not active
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by purcell** [comment]
Well, there's an error there saying that "git" isn't found on your system. Is that the case? What happens when you use `M-:` to evaluate `(executable-find "git")`?

**Comment by xishi00** [comment]
Yes, I did not install git. I never used it. My emacs seems performs well after git bing installed. Thank you!
