### ISSUE TITLE
question about M-x Slime

### ISSUE THREAD

**Issue by clfx2015** [purcell/emacs.d#399]
Excuse me,dear purcell.
I'm a beginner of common lisp and Emacs.I download your repository yesterday from Github.
I learned that typing M-x Slime to start the Slime.But it display "apply: Searching for program: no such file or directory, lisp".How to solve the problem?And I have search the past issues,find the same problem comment by other(https://github.com/purcell/emacs.d/issues/70).But I cann't understand.
Looking forward for your reply,thanks a lot!

**Comment by emuio** [comment]
you can see the issues[#398](https://github.com/purcell/emacs.d/issues/398), maybe the same problem.
It means that "lisp" isn't found on your system.
Maybe you can try to install [sbcl](http://www.sbcl.org/platform-table.html) and set the inferior-lisp-program variable to "sbcl",add blow code to your init-slime.el.
(setq inferior-lisp-program "sbcl")

**Comment by clfx2015** [comment]
@emuio thanks a lot.
According to your suggestion,I install the sbcl using "sudo apt install sbcl" on my OS.
And then add the code(setq inferior-lisp-program "/usr/bin/sbcl") in my init-slime.el.
Finally,type M-x Slime,it works.
Thanks again.
