### ISSUE TITLE
Invalid version syntax: ‘0.22.-3.1

### ISSUE THREAD

**Issue by cnglen** [purcell/emacs.d#402]
(setq package-archives
      '(
        ("popkit" . "http://elpa.popkit.org/packages/")
        ))

The error message: 

Debugger entered--Lisp error: (error **"Invalid version syntax: ‘0.22.-3.1’**")
  signal(error ("Invalid version syntax: ‘0.22.-3.1’"))
  error("Invalid version syntax: `%s'" "0.22.-3.1")
  version-to-list("0.22.-3.1")
  #[257 "\211@\300A@!D\207" [version-to-list] 4 "\n\n(fn ELT)"]((flycheck "0.22.-3.1"))
  mapcar(#[257 "\211@\300A@!D\207" [version-to-list] 4 "\n\n(fn ELT)"] ((cider "0.8.1") (flycheck "0.22.-3.1") (let-alist "1.0.1") (emacs "24")))
  package-desc-from-define("flycheck-clojure" "20160705.321" "Flycheck: Clojure support" (quote ((cider "0.8.1") (flycheck "0.22.-3.1") (let-alist "1.0.1") (emacs "24"))) :url "https://github.com/clojure-emacs/squiggly-clojure")
  apply(package-desc-from-define ("flycheck-clojure" "20160705.321" "Flycheck: Clojure support" (quote ((cider "0.8.1") (flycheck "0.22.-3.1") (let-alist "1.0.1") (emacs "24"))) :url "https://github.com/clojure-emacs/squiggly-clojure"))
  package-process-define-package((define-package "flycheck-clojure" "20160705.321" "Flycheck: Clojure support" (quote ((cider "0.8.1") (flycheck "0.22.-3.1") (let-alist "1.0.1") (emacs "24"))) :url "https://github.com/clojure-emacs/squiggly-clojure"))
  package-load-descriptor("/home/gang/.emacs.d/elpa/flycheck-clojure-20160705.321")
  package-load-all-descriptors()
  package-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/gang/.emacs.d/init.el" nil t)  ; Reading at buffer position 549
  load-with-code-conversion("/home/gang/.emacs.d/init.el" "/home/gang/.emacs.d/init.el" t t)
  load("/home/gang/.emacs.d/init" t t)
  #[0 "\205\266

**Comment by emuio** [comment]
use 'add-to-list' replace 'setq'
for example: 
(add-to-list 'package-archives
             '("popkit" . "https://elpa.popkit.org/packages/"))

**Comment by cnglen** [comment]
@emuio 
update to, error still exists: 
```
(add-to-list 'package-archives
'("popkit" . "https://elpa.popkit.org/packages/"))
```


The cause of the error is by **0.29.-3**, which was **0.29alpha**
- old  flycheck-elm-pkg.el （NO error）
`(define-package` "flycheck-elm" "20160717.257" "Flycheck support for the elm language" '((flycheck "0.29alpha") (emacs "24.4")) :url "https://github.com/bsermons/flycheck-elm")
- new  flycheck-elm-pkg.el (REPROT error)
`(define-package` "flycheck-elm" "20160717.1757" "Flycheck support for them language"  '((flycheck "0.29.-3") (emacs "24.4") ) :url "https://github.com/bsermons/flycheck-elm" )

See https://melpa.org/#/flycheck-elm for 0.29.-3

**Comment by cnglen** [comment]
after changing the ELPS mirror, the problem is solved. 

this mirror is not suggested: http://elpa.popkit.org/packages/
