### ISSUE TITLE
Can not return to regular find-file to create new files

### ISSUE THREAD

**Issue by KevinWangTHU** [purcell/emacs.d#403]
Hi!

I can not create a new file when I type `c-x c-f` followed by `c-f`. The mini-buffer remains unchanged. The result is shown below.
![screen shot 2016-12-15 at 11 54 42 pm](https://cloud.githubusercontent.com/assets/8873538/21255663/2c716408-c322-11e6-8bd5-7816cbe065a3.png)

Also, if I enable `ido-mode`, the mini-buffer becomes
![screen shot 2016-12-15 at 11 55 14 pm](https://cloud.githubusercontent.com/assets/8873538/21255764/c06bec1e-c322-11e6-8f74-4c11e4a0bc62.png)
However if I type `c-x c-f` followed by `c-f`, then it becomes the picture before.

I have been using your config files for some time, but recently it does not work anymore for me. I am not sure if it is my problem since I am really new to Emacs, but it seems that I have the same problem on my company's computer either (I'll check that with other computers tomorrow).

Thank you very much for your help!

**Comment by purcell** [comment]
This should still work out of the box. Recently I changed from `ido` to `ivy` for this config, and it looks like you still have `ido-mode` enabled. It's `ivy` in your first screenshot, and `ido` in the second. Try disabling `ido-mode` and restart Emacs. (With `ivy`, you don't need `C-f` when creating a new file.)

**Comment by purcell** [comment]
Also, the commit I just pushed (965d47a) might help this to work automatically for you.

**Comment by KevinWangTHU** [comment]
Now I understand that the `ivy-mode` is now working. However, say if I want to create a new file named `10.py` but it will give the following if I have some other similar files:
<img width="272" alt="screen shot 2016-12-16 at 12 25 07 am" src="https://cloud.githubusercontent.com/assets/8873538/21256291/4a9f2dda-c326-11e6-9536-c4d456fcb49c.png">

In such situation, how to create a new file named `10.py`?

However I guess it should be something about `ivy-mode` and I should check the documentation.

**Comment by purcell** [comment]
Just hit `C-M-j`. See the `ivy-help` doc for more: https://github.com/abo-abo/swiper/blob/master/doc/ivy-help.org :-)

**Comment by emuio** [comment]
I also use `C-j` to instead `C-M-j`. Because it's easy to hit, and has almost same result.

**Comment by KevinWangTHU** [comment]
Thank you very much!
