### ISSUE TITLE
Can't use the C-s M-w to copy 

### ISSUE THREAD

**Issue by tru2dagame** [purcell/emacs.d#404]
I am using the GNU Emacs 25.1.1 installed by Homebrew. 
I can't use 'M-w' to copy the mark set.
When I use this shortcuts, it copies the whole line for me.
Is there a way to check or fix for this issue?

**Comment by tru2dagame** [comment]
For more detail:

When I use 'C-s M-w', it shows 'Mark saved where search started'. Then I try 'C-y' to paste the words. It pastes the whole line for me.

But when I use 'C-@' to activate the mark, then 'M-w'. It works to copy the words I selected.

![2016-12-21 at 9 18 pm](https://cloud.githubusercontent.com/assets/1673006/21390675/1c09261e-c7c3-11e6-9c9c-766375760221.png)

**Comment by emuio** [comment]
Press 'C-h  k M-w' to find the key-binding on 'M-w'.

**Comment by tru2dagame** [comment]
Hi @emuio 

```
M-w runs the command whole-line-or-region-kill-ring-save (found in
global-map), which is an interactive autoloaded compiled Lisp function
in ‘whole-line-or-region.el’.

It is bound to <C-insertchar>, <C-insert>, M-w.

(whole-line-or-region-kill-ring-save PREFIX)

Copy region or PREFIX whole lines.
```

**Comment by tru2dagame** [comment]
I see the main idea is to "Cut/copy the current line if no region is active".

But when I use the "C-s C-w" key to select words, it identifies as no region is active.

Is there a workaround to fix this?

**Comment by emuio** [comment]
hi @tru2dagame 
Now I see your question. 
You can try replace 'whole-line-or-region-kill-ring-save' to 'kill-ring-save', like below code:
`(global-set-key (kbd "M-w") 'kill-ring-save)`

**Comment by purcell** [comment]
If I'm understanding this issue well, I think your expectations are incorrect.

`C-s` never actually selects the highlighted word, so the region is unset, and therefore `M-w` copies the entire line. To copy the word, you'd need to exit `isearch`, e.g. with `RET` (or `C-RET`) and then select it, e.g. with `C-M-SPC`, then copy with `M-w`.

**Comment by tru2dagame** [comment]
@purcell Thank you for your suggestion.

**Comment by tru2dagame** [comment]
Hi @purcell, I worked this out by using this suggestion: https://stackoverflow.com/questions/2183726/emacs-copy-with-regex

So that we can use `C-s C-w` to select words, and `M-w` to copy if needed.
If nothings selected by `C-s C-w`, `M-w` is still `whole-line-or-region-global-mode`.
