### ISSUE TITLE
can't use debug in ivy

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#406]
sometimes when use `M-x toggle-debug-on-error`
the message buffer doesn't show the error's position
I have to try to carry one function to another
there is a `debug` function but I invoke it in a trouble
> Debugger entered: nil
  funcall-interactively(debug)
  call-interactively(debug record nil)
  command-execute(debug record)
  #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("debug")
  ivy-call()
  ivy-read("M-x " ("debug" "toggle-debug-on-error" "eval-buffer" "edebug-defun" "describe-variable" "apropos" "magit-status" "package-delete" "package-install" "w3m" "emms" "dired" "kill-buffer" "grep" "emms-browser" "pdf-tools-install" "gnus" "emms-start" "hydra-emms/body" "org-indent-mode" "emms-show" "emms-stop" "emms-pause" "desktop-save" "w3m-view-image" "apropos-command" "bookmark-bmenu-list" "paredit-doublequote" "paredit-convolute-sexp" "align" "doctor" "emms-seek" "bookmark-set" "recover-file" "avy-goto-char" "bookmark-jump" "bookmark-delete" "customize-variable" "paredit-wrap-curly" "list-matching-lines" "paredit-wrap-angled" "paredit-wrap-square" "apropos-documentation" "evil-forward-word-end" "evil-next-visual-line" "evil-find-file-at-point-with-line" "ag" "cd" "ri" "5x5" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
  recursive-edit()
  debug()
  funcall-interactively(debug)
  call-interactively(debug record nil)
  command-execute(debug record)
  #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("debug")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "eval-buffer" "edebug-defun" "describe-variable" "apropos" "magit-status" "package-delete" "package-install" "w3m" "emms" "dired" "kill-buffer" "grep" "emms-browser" "pdf-tools-install" "gnus" "emms-start" "hydra-emms/body" "org-indent-mode" "emms-show" "emms-stop" "emms-pause" "desktop-save" "w3m-view-image" "apropos-command" "bookmark-bmenu-list" "paredit-doublequote" "paredit-convolute-sexp" "align" "doctor" "emms-seek" "bookmark-set" "recover-file" "avy-goto-char" "bookmark-jump" "bookmark-delete" "customize-variable" "paredit-wrap-curly" "list-matching-lines" "paredit-wrap-angled" "paredit-wrap-square" "apropos-documentation" "evil-forward-word-end" "evil-next-visual-line" "evil-find-file-at-point-with-line" "ag" "cd" "ri" "5x5" "arp" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
  recursive-edit()
  debug()
  funcall-interactively(debug)
  call-interactively(debug record nil)
  command-execute(debug record)
  #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("debug")
  ivy-call()
  ivy-read("M-x " ("eval-buffer" "toggle-debug-on-error" "edebug-defun" "describe-variable" "apropos" "magit-status" "package-delete" "package-install" "w3m" "emms" "dired" "kill-buffer" "grep" "emms-browser" "pdf-tools-install" "gnus" "emms-start" "hydra-emms/body" "org-indent-mode" "emms-show" "emms-stop" "emms-pause" "desktop-save" "w3m-view-image" "apropos-command" "bookmark-bmenu-list" "paredit-doublequote" "paredit-convolute-sexp" "align" "doctor" "emms-seek" "bookmark-set" "recover-file" "avy-goto-char" "bookmark-jump" "bookmark-delete" "customize-variable" "paredit-wrap-curly" "list-matching-lines" "paredit-wrap-angled" "paredit-wrap-square" "apropos-documentation" "evil-forward-word-end" "evil-next-visual-line" "evil-find-file-at-point-with-line" "ag" "cd" "ri" "5x5" "arp" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f�\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by purcell** [comment]
Sorry, I can't provide support for this sort of general emacs question.
