### ISSUE TITLE
can't save register when exit emacs

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#407]
something I check in `init-session,el`
the desktop-save-mode is on
### before leave emacs and save session config in register:
<img width="178" alt="2016-12-28 9 31 44" src="https://cloud.githubusercontent.com/assets/16307328/21522998/3760050e-cd45-11e6-83b6-732c5d0b5480.png">

### reopen emacs then list register:
<img width="317" alt="2016-12-28 9 33 56" src="https://cloud.githubusercontent.com/assets/16307328/21523015/6191f012-cd45-11e6-93f9-6bbd8704b3e4.png">

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
someone here?

**Comment by purcell** [comment]
Guess nobody else has seen this issue, sorry. I certainly haven't encountered it, and I just tried now to reproduce this and can't do so.
