### ISSUE TITLE
write javascript don't have completion

### ISSUE THREAD

**Issue by haormj** [purcell/emacs.d#409]
emacs version:25.1.1
system:deepin 
I want to use emacs write web application,but it could't complete well

**Comment by purcell** [comment]
It's a dynamic language, so you're never going to get great completion, sorry. `company` should already give you completion for symbols in the current and other buffers you have open.

To get more than that, we would need something which really understands your code and loads it for you in the background: Ruby has "robe", Common Lisp has "slime", Clojure has "cider", Python has "rope". There's no equivalent for Javascript with Emacs, as far as I know.
