### ISSUE TITLE
requests for ask emacs version 25.1

### ISSUE THREAD

**Issue by hackrole** [purcell/emacs.d#410]
I am new to emacs. I heard everywhere this config was good. And it seems more simple for me to get-started without go too far from emacs-way(which spacemacs does). 

I use emacs on mac os and homebrew, the brew install emacs 25.1 now. And this version cannot work with this config. I tried to install emacs 24.4, but face more questions. It is hard for me to resolve this.

So I would ask if would you please update this config to support emacs version 25.1??

**Comment by purcell** [comment]
I am using this config with Emacs 25.x, and there's a passing Travis build for that version too. What is the problem you have found?

**Comment by hackrole** [comment]
Warning (initialization): An error occurred while loading ‘/Users/daipeng/.emacs.d/init.el’:

Assertion failed: (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by purcell** [comment]
That's a data download issue. Are you behind a proxy that is truncating your downloads? Try deleting `~/.emacs.d/elpa` and restart Emacs.

**Comment by hackrole** [comment]
yes, I behind a proxy. And there is a question.
I have this code in lisp/init-pre-local.el
```
;; use proxy for melpa
(setq url-proxy-services '(("http" . "http://127.0.0.1:8090")
                           ("https" . "http://127.0.0.1:8090")
                           ("no_proxy" .  "localhost")))
```
but it seems not work.

so I have to start emacs in terminal by
```
http_proxy=127.0.0.1:8090 https_proxy=127.0.0.1:8090 emacs
```
this would works, this confuse me. cause when I try the prelude emacs config. the lisp code above works.

**Comment by purcell** [comment]
`init-preload-local` is not loaded until after `init-elpa`, which is perhaps something I will change. In the meantime, you can edit the order in `init.el`.

**Comment by hackrole** [comment]
thanks, I have a really bad network. I am reinstall the elpa pakcage now. I will write the results after it finish. Really thanks.

**Comment by purcell** [comment]
:+1:

**Comment by hackrole** [comment]
It works now. Thanks
