### ISSUE TITLE
Emacs hangs when typing cpp codes

### ISSUE THREAD

**Issue by yrxwin** [purcell/emacs.d#411]
I installed default package and couple of lines of custom style configuration in `init.el`. Emacs frequently hangs (for several seconds, sometimes even couple of minutes) while typing cpp codes. Is this related to `autocomplete`? What should I do to avoid this? Thanks!

**Comment by yrxwin** [comment]
This disk I/O is high when hanging.

**Comment by purcell** [comment]
Not sure, sorry, I don't work with `c++`. The easy way to find out whether it's related to autocompletion is to turn it off in the buffer, and see if it still happens: `M-x company-mode`.

**Comment by yrxwin** [comment]
Thanks @purcell   After turning off `company-mode`, I could code smoothly without hanging. There might be bottleneck on the disk I/O when using autocomplete. I should switch to a SSD.
