### ISSUE TITLE
some Mojibake in todo list

### ISSUE THREAD

**Issue by Steven-AA** [purcell/emacs.d#413]
Hi,
I'm not sure about how to describe this issue.
```
DONE test 
CLOSED: [2017-02-10 \326\334\316\345 01:42]
 :LOGBOOK:
State "DONE"       from "TODO"       [2017-02-10 \326\334\316\345 01:42]
 :END:
```
 \326\334\316\345
How to fix this?

**Comment by purcell** [comment]
Please can you provide steps to reproduce this? Have you customised your config?

**Comment by Steven-AA** [comment]
I am learning to use Emacs, and I was told it would be easy if I just copy your setup. I did it just after installing Emacs. Then I met this issue. I am not sure whether there is any config to be customized. 
By the way, I used windows 10 and the language that my computer uses is Simplified Chinese, maybe it is relevant.
Now I am using Emacs on Linux, the issue just gone.

**Comment by weipan789** [comment]
you are clever ,using emacs without windows.

在 2017年02月13日 17:57, Steven-AA 写道:

**Comment by purcell** [comment]
Okay, thanks. I'm not going to be able to reproduce or fix this, so I'm going to close the issue.
