### ISSUE TITLE
company-quickhelp-frontend error

### ISSUE THREAD

**Issue by weipan789** [purcell/emacs.d#414]
Hi,
i have something wrong like blow
```
Company: frontend company-quickhelp-frontend error "Symbol's function definition is void: pos-tip-hide" on command hide
```

how i to do with it.

**Comment by wangruifei** [comment]
Me too

**Comment by purcell** [comment]
Please provide steps to reproduce this, including platform and emacs version.

**Comment by weipan789** [comment]
Xubuntu 16.04    and  emacs-version "24.5.1"

**Comment by weipan789** [comment]
`C-x b ` and want to select a buffer-name . can't switch buffer and occur the error.

**Comment by purcell** [comment]
Okay, and you're running Emacs in a terminal window, or a GTK/X window?

(In any case, see https://github.com/expez/company-quickhelp/issues/64, which I think will solve this problem once merged.)

**Comment by weipan789** [comment]
Thank you for your reply and help. I really use Emacs in a terminal window. And i will have a try soon.

**Comment by weipan789** [comment]
Okay, i remove the old .emacs.d and git clone again, now it is ok in GUI window and terminal window.

**Comment by wangruifei** [comment]
my emacs is 25.1.1 and in terminal of mac 10.12.3. I have deleted the old .emacs.d and clone the latest version of .emacs.d but the problem is still occurs

**Comment by purcell** [comment]
This problem should go away when https://github.com/expez/company-quickhelp/issues/64 is merged upstream.

**Comment by purcell** [comment]
I believe this is now fixed upstream in `company-quickhelp`.
