### ISSUE TITLE
Seems package-autoremove dropping useful packages.

### ISSUE THREAD

**Issue by xinyifly** [purcell/emacs.d#415]
When I use `package-autoremove` command, it always tips 65 packages to be removed. Then they will be installed after next emacs start.

**Comment by YuanPre** [comment]
@xinyifly This seems to be a bug or a feature of emacs. A long time unwanted package will be credited to the scope of `package-autoremove`.
I have this problem when I use other configuration files. Even when I use emacs default configuration is the same.

**Comment by YuanPres** [comment]
@xinyifly 
Have you manually modified or deleted the `~/.emacs.d/custom.el` ?
The variable in this file:
```
(custom-set-variables
package-selected-packages 
)
```
determine whether a package is useful.
  
Any package that is not in this variable will be treated as a useless package.
and deleted by `autoremove`.

**Comment by purcell** [comment]
Nope, there's a complicated interaction between the order in which packages are initialised/installed in this config and when the custom file is loaded. There's no easy way to solve it, and the addition of `package-selected-package` to `package.el` was a design mistake, in my opinion.

**Comment by YuanPres** [comment]
@purcell 
Yeap. I also think it is a design mistake.
But it seems emacs official does not intend to change anything...
I have reported bugs to GNU people on this issue. 
They insist that `package-selected-package` is normal. And gave me the above reply.

**Comment by junjiemars** [comment]
```pacakge-selected-packages``` just keep track you'd installed packages, and ```package-remove``` just do a reverse operation, it's all natural. If you want to override it there are a way to do that.
