### ISSUE TITLE
Fedora 25 Can't load Theme

### ISSUE THREAD

**Issue by BalalaXMX** [purcell/emacs.d#416]
Excuse me,My English is Very Poor.
I using Fedora 25 x86_64 ,GNOME Session,Emacs Version:25.1
It can't load some theme.my emacs start page is empty.
Thank you.

**Comment by purcell** [comment]
When you start Emacs up for the first time with this configuration, you should get asked whether to treat the theme as safe: you must choose "yes". Look in the `*Messages*` buffer for errors.

**Comment by BalalaXMX** [comment]
Thank you , I forgot to install some python packages
