### ISSUE TITLE
I'm in the execution of the test - startup. Sh warnings

### ISSUE THREAD

**Issue by travelgeezer** [purcell/emacs.d#417]
geezerdeMacBook-Pro:.emacs.d geezer.$ ./test-startup.sh 
Attempting startup...
Loading /Users/geezer./.emacs.d/init.el (source)...
Loading /Users/geezer./.emacs.d/recentf...
Cleaning up the recentf list...
Cleaning up the recentf list...done (0 removed)
Checking whether Dash is installed
Loading /Users/geezer./.emacs.d/custom.el (source)...
Loading /Users/geezer./.emacs.d/.session...
Desktop restored in 0.00ms
init completed in 4.07ms
Warning (emacs): recentf mode: Cannot open load file: No such file or directory, vc-darcs
Startup successful

**Comment by purcell** [comment]
Maybe not all of your packages installed cleanly? Does `M-x find-library` allow you to find the `vc-darcs` library?

**Comment by travelgeezer** [comment]
I use the` M-x find-library`  found no `vc-darcs` library.
Do I need to install the `vc - darcs` library?

**Comment by purcell** [comment]
It should get installed automatically at startup by the code in `init-darcs.el`, so it's not clear why you wouldn't have it. Have you customised the config at all?

**Comment by travelgeezer** [comment]
I used your latest configuration,Perform the `test - startup`. Sh appeared a lot of warning at compile time.The compiler will be my information below, I am 25.1.1 version of emacs

**Comment by travelgeezer** [comment]
In toplevel form:
marshal.el:148:15:Warning: Unknown slot ‘:output’
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
marshal.el:191:44:Warning: ‘object-p’ is an obsolete function (as of 25.1);
    use ‘eieio-object-p’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
marshal.el:200:36:Warning: ‘object-p’ is an obsolete function (as of 25.1);
    use ‘eieio-object-p’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
../../lisp/init-github.el: ‘defgeneric’ is an obsolete macro (as of 25.1); use ‘cl-defgeneric’ instead.
marshal.el:206:30:Warning: ‘object-p’ is an obsolete function (as of 25.1);
    use ‘eieio-object-p’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
../../lisp/init-github.el: ‘defgeneric’ is an obsolete macro (as of 25.1); use ‘cl-defgeneric’ instead.
marshal.el:220:25:Warning: ‘object-p’ is an obsolete function (as of 25.1);
    use ‘eieio-object-p’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
../../lisp/init-github.el: ‘defgeneric’ is an obsolete macro (as of 25.1); use ‘cl-defgeneric’ instead.
marshal.el:229:46:Warning: ‘call-next-method’ is an obsolete function (as of
    25.1); use ‘cl-call-next-method’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
marshal.el:233:15:Warning: ‘call-next-method’ is an obsolete function (as of
    25.1); use ‘cl-call-next-method’ instead.
marshal.el:233:9:Warning: Unknown slot ‘:input’
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
marshal.el:243:6:Warning: ‘call-next-method’ is an obsolete function (as of
    25.1); use ‘cl-call-next-method’ instead.
../../lisp/init-github.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.

**Comment by travelgeezer** [comment]
This is just a small part, can you tell me whether related to I use emacs versionOr I also need to other local software environment support?

**Comment by purcell** [comment]
Nope, those warnings can be ignored: they are due to an upstream library (I've just sent [a PR to fix some of them](https://github.com/sigma/marshal.el/pull/3)).

**Comment by purcell** [comment]
(i.e. your Emacs version is fine.)

**Comment by travelgeezer** [comment]
Ok, I understand.Thank you for solve my doubts.   ^_^
