### ISSUE TITLE
How to Change the elpa Repositories at First Start?

### ISSUE THREAD

**Issue by BalalaXMX** [purcell/emacs.d#419]
Excuse me . I am here to ask you again. My English is very poor.Please forgive me
 I living in China. You Know,Chinese Government has the GFW firewall.Some websites have been blocked among include "http://melpa.org",So I have to Change the elpa repositories in China.But I don't Know Which file should to modify.I have created the "init-preload-local.el" and "init-local.el" with your instructions,But they don't work at first start. It is only after all plug-ins are loaded.
Would you direct me? Thank you very much.

**Comment by lukertty** [comment]
init-elpa.el 
```elisp
(setq package-archives '(("melpa-cn" . "http://elpa.emacs-china.org/melpa/")
                      ("org-cn"   . "http://elpa.emacs-china.org/org/")
                      ("gnu-cn"   . "http://elpa.emacs-china.org/gnu/")))
```

**Comment by purcell** [comment]
Yep, thanks @lukertty.
