### ISSUE TITLE
About using dried-mode

### ISSUE THREAD

**Issue by jamieabc** [purcell/emacs.d#421]
When using dired-mode to rename file, if I want to rename file `bar` to `ba`, the auto complete will show `bar` and I cannot enter the filename that has same prefix. How can I rename a file that has same prefix under dired mode?

**Comment by purcell** [comment]
That's specific to `ivy`, the completion system: the trick there is to use `C-M-j`, I believe.

**Comment by jamieabc** [comment]
Thanks, it works~
