### ISSUE TITLE
How to do the yml file auto indentation?

### ISSUE THREAD

**Issue by tru2dagame** [purcell/emacs.d#422]
<img width="754" alt="2017-04-09 21 32 58" src="https://cloud.githubusercontent.com/assets/1673006/24837689/57946f78-1d6c-11e7-8ad0-1c0ca8927550.png">

Is it possible to do the auto indentation yml file? If I select all of these lines and press `tab`, I got these as the screenshot.

**Comment by purcell** [comment]
Auto-indentation of yaml is impossible, sorry, as for Python, Haskell and other file formats in which indentation defines meaning. The computer cannot know which indentation you want, because it cannot know what meaning you intend.
