### ISSUE TITLE
What license do you use ?

### ISSUE THREAD

**Issue by YuanPre** [purcell/emacs.d#423]
Hello Purcell . Excuse me, occupy tag of issues.
I want to use your configuration in my club. My club is a LGBT public welfare organization.I don't know what license you use.So I dare not use.In order to avoid legal disputes.
Thank you very much.

**Comment by purcell** [comment]
Hi! There's a LICENSE file in the repository: https://github.com/purcell/emacs.d/blob/master/LICENSE

It's a BSD-style licence, so very permissive. :-)

**Comment by YuanPre** [comment]
Thank you very much!
