### ISSUE TITLE
Why do you like the "Light" color themes?

### ISSUE THREAD

**Issue by YuanPre** [purcell/emacs.d#424]
Most other emacs configruations use the "Dark" color theme by default (like spacemacs). Why do you like to use "Light" color theme ?
Excuse me .Thank you.

**Comment by purcell** [comment]
I actually don't use it myself: I mostly use the "bright" Tomorrow theme. I expect users to use `M-x customize-themes`. I might switch to using that as the default, because I maintain the Tomorrow themes more actively than the Solarized themes.

**Comment by purcell** [comment]
(I changed the defaults.)

**Comment by YuanPre** [comment]
Thank you for your answer. I like the "Dark" theme because the "Dark" theme in the current high brightness screen will not be so dazzling.but "Light" theme is also nice.

**Comment by YuanPre** [comment]
Wow ! The "Bright Tomorrow" color theme coincides with my expectations. Thank you very much!

**Comment by purcell** [comment]
Great! It was always there: try `M-x customize-themes`, and you'll find there are a few variations, with different levels of contrast.

**Comment by YuanPre** [comment]
Thanks for guidance, I know that can do that But I'm a "keep the default" person. HAHAHA.
