### ISSUE TITLE
Compile log: Magit and Magit-core not found?

### ISSUE THREAD

**Issue by JiaHong-Lee** [purcell/emacs.d#425]
Dear Sir,

I am a newbie to emacs. The compile log popped up when I used your emacs configurations. By clicking into the errors, I found out that the lines:
`(require 'magit)` 
and 
`(require 'magit-core)`
are displayed with "Searching for program: No such file or directory, git" at the mini-buffer. 

But I do have magit.el and magit-core.el files at the ~/.emacs.d/elpa-25.1/magit-20170410.414 directory. So I'm not sure what the problem is. Hopefully you can resolve this for me.

I am using GNU Emacs 25.1.1 (i686-w64-mingw32) of 2016-11-16 on Windows 10 Home Version 1607 (OS Build 14393.953).

This is the excerpt taken from the compile log:
```
﻿Compiling no file at Thu Apr 13 09:06:36 2017
Leaving directory ‘c:/Users/Lee Jia Hong/AppData/Roaming/.emacs.d/elpa-25.1/org-fstree-20090723.819’

Compiling file c:/Users/Lee Jia Hong/AppData/Roaming/.emacs.d/elpa-25.1/org-fstree-20090723.819/org-fstree.el at Thu Apr 13 09:06:36 2017
Entering directory ‘c:/Users/Lee Jia Hong/AppData/Roaming/.emacs.d/elpa-25.1/org-fstree-20090723.819/’

In toplevel form:
git-rebase.el:73:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-apply.el:33:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-autorevert.el:29:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-bisect.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-blame.el:31:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-branch.el:34:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-commit.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-core.el:36:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-diff.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-ediff.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-extras.el:27:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-files.el:33:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-log.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-margin.el:36:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-mode.el:36:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-notes.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-obsolete.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-process.el:40:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-refs.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-remote.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-repos.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-sequence.el:32:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-stash.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-status.el:30:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-submodule.el:26:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-subtree.el:26:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-wip.el:33:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit-worktree.el:33:1:Error: Searching for program: No such file or directory, git

In toplevel form:
magit.el:56:1:Error: Searching for program: No such file or directory, git

Compiling no file at Thu Apr 13 09:06:39 2017
Leaving directory ‘c:/Users/Lee Jia Hong/AppData/Roaming/.emacs.d/elpa-25.1/org-cliplink-20160819.900’
```

**Comment by nothingthere** [comment]
是不是系统上没安装git？

**Comment by YuanPre** [comment]
Is your `git` installed?

**Comment by JiaHong-Lee** [comment]
Hi @YuanPre @nothingthere, 

I have GitHub desktop application installed, and is located here at C:\Users\Lee Jia Hong\AppData\Local\GitHub. I can see that there is git installed inside the sub-directory PortableGit_f02737a78695063deace08e96d5042710d3e32db as git-bash.exe and git-cmd.exe.

Is there any way that I can refer Emacs to that directory and use the git found inside there?

**Comment by nothingthere** [comment]
Try execute  (executable-find "git") in your emacs。If it return a string, indicates that git installed on your system. If return nil, indicates that it may have some wrong with the install of git. I have not used emacs on Windows. It may be a problem of emacs on Windows.

:smile: sorry for my English.

**Comment by YuanPre** [comment]
@nothingthere @JiaHong-Lee 

The git file PATH and Emacs HOME path may be problematic.
and what you might need is `git`,  Not `GitHub Desktop`.

Sorry for my English, too.
I speak English in Google translation...

**Comment by YuanPre** [comment]
I have a suggestion:
Use `Emacs in Cygwin`, Can avoid a lot of unnecessary path problems. Because the `Emacs` is a GNU Program for Unix.

**Comment by JiaHong-Lee** [comment]
Hi @nothingthere ,
I am not sure what you meant by executing (executable-find "git"). I tried `M-x executable-find` but no such command found. Also, I tried putting the line `(executable-find "git")` into `init.el`, but nothing happened too. So I supposed it doesn't work that way.

Hi @YuanPre ,
Following your previous suggestion, I uninstalled `GitHub Desktop` and install the `Git` from [https://git-for-windows.github.io/](https://git-for-windows.github.io/).

After running `M-x magit-status`, this is an excerpt from my `*Messages*`:
```
Turning on magit-auto-revert-mode...done
Create repository in c:/Users/Lee Jia Hong/Desktop/? (y or n) y
```
Then there is a `.git` folder on my desktop. Now running `M-x magit-version` returns `Magit 20170410.414, Git 2.12.2.windows.2, Emacs 25.1.1, windows-nt`. So I suppose it works now! =)
           
 <br  />
Thanks @nothingthere  @YuanPre  for helping me out. Thank you very much, I really appreciate it! =D 
 <br  />  
    
P.S. Actually I understand Chinese...

**Comment by YuanPre** [comment]
@JiaHong-Lee 
It does not matter, in fact, I also guess. I use emacs only four weeks time, and I have no windows environment. I rely on the general debug method for linux to guess your problem.
And we speak English in order to make the creator here: Steve Purcell understand.

**Comment by purcell** [comment]
Either use `M-x customize-variable` to modify (and save) the `magit-git-executable` variable so that it points to your `git` executable, or add a file `~/.emacs.d/lisp/init-local.el`, with contents something like the following:

```el
(setq magit-git-executable "/path/to/your/git.exe")
(provide 'init-local)
```

Then restart, and everything should work.

HOWEVER, I'm not sure which of `git-bash.exe` and `git-cmd.exe` you should use, or whether either of those will work with `magit`, and I don't use Windows, so I can't help further with that, sorry: you might need to install a different `git` version, e.g. with `mingw`.
