### ISSUE TITLE
use ivy with projectile

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#426]
I think the `init-ivy.el` has already configured it
If can make every find file or directory step a `projectile-find-file` or `projectile-find-dir` like

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
use ivy can automatically create non-existent file
is there a way to create the directory yet?

**Comment by purcell** [comment]
Not sure, sorry.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
my bad
the question is too abstract
just list a example for instance:
in org mode when I use `C-c C-a (org-attach)` to choose a file
minibuffer pop up the file path and I have to jump directory per layer
the projectile is so good if can use in that situation
