### ISSUE TITLE
python-mode function args name do not show completely in mini-buffer

### ISSUE THREAD

**Issue by Vicriss** [purcell/emacs.d#430]
Hi,purcell. I got a problem. Maybe it is not exactly.
If I call a function, the function args name will display in mini-buffer when I put the cursor in the part of arg of the function. However, it show uncompletely. If the name of args contain underline, mini-buffer only show the part of name which after the underline.

**Comment by purcell** [comment]
I don't think this is exactly related to this config: you should probably report it upstream, against [anaconda-mode](https://github.com/proofit404/anaconda-mode). (P.S. `eldoc` is the mechanism which shows that info in the minibuffer, so mention that if you file an issue.)

**Comment by Vicriss** [comment]
okey, thank your response and advice :)
