### ISSUE TITLE
Can I delete the old plugin folder?

### ISSUE THREAD

**Issue by YuanPre** [purcell/emacs.d#431]
Hey Purcell:
Today, The `emacs 25.2` released.
As you said, you use the version number to name the plugin folder. So the plugins is installed again in `~/.emacs.d/elpa-25.2`.
Then,Can I delete the old plugin folder? (`~/.emacs.d/elpa-25.1`).
In addition, I suggest。the release version (like 25.1,25.2) don't need to separate storage.
I feel only to separate the large version (like 24,25) will be more convenient.
If there is an offense, please forgive me.
Thank you very much.

**Comment by purcell** [comment]
> Then,Can I delete the old plugin folder? (~/.emacs.d/elpa-25.1).

Yes.

> In addition, I suggest。the release version (like 25.1,25.2) don't need to separate storage.
> I feel only to separate the large version (like 24,25) will be more convenient.

The Elisp bytecode can change between minor versions, and so can the definitions of system-wide macros. It's therefore safer to include the minor versions, and new Emacs releases are infrequent. If you like, you can sym-link multiple directories together.

**Comment by YuanPre** [comment]
I understand what you mean, thank you.
Thank you for forgiving my English……
