### ISSUE TITLE
Emacs 26.0 Package Installation

### ISSUE THREAD

**Issue by goangit** [purcell/emacs.d#432]
Using emacs 26.0.50 manual installation of packages (sometimes?) results in creation of the directory ~/.emacs.d/elpa (related to gnupg key signatures). Following this creation emacs reports an issue loading ~/.emacs.d/init.el

File error: File is a directory, /home/greg/.emacs.d/elpa-26.0/elpa

The problem does not appear when starting with emacs -q

> emacs --init-debug &

Debugger entered--Lisp error: (file-error "File is a directory" "/home/greg/.emacs.d/elpa-26.0/elpa")
  rename-file("~/.emacs.d/elpa" "/home/greg/.emacs.d/elpa-26.0")
  (progn (message "Default package locations have changed in this config: renaming old package dir %s to %s." package-user-dir versioned-package-dir) (rename-file package-user-dir versioned-package-dir))
  (if (file-directory-p package-user-dir) (progn (message "Default package locations have changed in this config: renaming old package dir %s to %s." package-user-dir versioned-package-dir) (rename-file package-user-dir versioned-package-dir)))
  (let ((versioned-package-dir (expand-file-name (format "elpa-%s.%s" emacs-major-version emacs-minor-version) user-emacs-directory))) (if (file-directory-p package-user-dir) (progn (message "Default package locations have changed in this config: renaming old package dir %s to %s." package-user-dir versioned-package-dir) (rename-file package-user-dir versioned-package-dir))) (setq package-user-dir versioned-package-dir))
  eval-buffer(#<buffer  *load*-749138> nil "/home/greg/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 891
  load-with-code-conversion("/home/greg/.emacs.d/lisp/init-elpa.el" "/home/greg/.emacs.d/lisp/init-elpa.el" nil t)
  #<subr require>(init-elpa nil nil)
  funcall(#<subr require> init-elpa nil nil)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t)))))
  (let (ad-return-value) (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis ... require-start-time))) (add-to-list (quote sanityinc/require-times) (cons feature time) t))))) ad-return-value)
  ad-Advice-require(#<subr require> init-elpa)
  apply(ad-Advice-require #<subr require> init-elpa)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/home/greg/.emacs.d/init.el" nil t)  ; Reading at buffer position 1571
  load-with-code-conversion("/home/greg/.emacs.d/init.el" "/home/greg/.emacs.d/init.el" t t)
  load("/home/greg/.emacs.d/init" t t)

**Comment by purcell** [comment]
I'm also using a snapshot version of Emacs, but I don't see this same issue. Since you're seeing it only in a development Emacs build, in which there are frequently bugs, maybe try updating your Emacs. Ultimately, if it's not easily reproducible I'm not going to investigate it myself.

**Comment by YuanPres** [comment]
@purcell I'am also using emacs 26.0 development version, too. And sometimes, I will install packages without elpa,too.
 but I haven't met this same issue.

@goangit I **DO NOT** understand your meaning `"manual installation of packages"`. Is it "Installation packages without package manager(elpa)" ?

**Comment by goangit** [comment]
Hi folks, thanks for your replies.

With a fresh git clone of purcell/emacs.d: 

$ emacs-snapshot &  

installs some packages, asks permission to run sanityinc themes and then produces warning

Failed to verify signature: nlinum-1.6.el.sig

The directory .emacs.d/elpa/ exists at this point.

I am on Ubuntu 16.04, in case that matters.

**Comment by YuanPres** [comment]
@goangit Looks like your plugin requires digital signature authentication...
But it will only find the authentication file from the directory it considers.
  
I have never used that plugin...
So sorry, I can not give you any help...

**Comment by goangit** [comment]
Thank you @YuanPres. 

The package is installed as a result of the (require-package 'nlinum) call on line 75 of init-editing-utils.el. 

I believe that if this signature was verified the process would hang in a similar way on a small number of other package verifications.

**Comment by YuanPres** [comment]
@goangit Do you have the GitHub Address of that package ? 
I'd like to try it. And in China, Government blocks the internet. So I can only visit a few foreign websites. And the Github included.

**Comment by YuanPres** [comment]
@goangit The `nlinum` can not be stable compatible. This plugin is only available in versions 23.x, 24.x, 25.x .
I DO NOT have any reference, but I got this answer when I asked in the `emacs-china` QQ group.

**Comment by goangit** [comment]
@YuanPres nlinum comes from the ELPA: http://elpa.gnu.org/packages/

**Comment by goangit** [comment]
@purcell can you confirm whether you are able to reproduce the issue shown in box 4 of this thread? Thank you.

**Comment by goangit** [comment]
FYI, I added 

(setq package-check-signature nil) 

to init-elpa.el and this problem seems to be resolved. 

I still don't quite understand how it arose or whether that is a particularly good solution and would be grateful for any insight. Thanks.

**Comment by RyanMcCarl** [comment]
I was able to fix this by deleting the "elpa" folder in my .emacs.d.

**Comment by lijunsong** [comment]
well, the problem is that elpa still exists after `rename-file`. You can just remove elpa folder in your `.emacs.d`.

I am using emacs-snapshot, so I got the same signature failed problem.  Good to hear that the stable version doesn't have this problem.
