### ISSUE TITLE
Where is your menu bar configuration?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#434]
Hello, Purcell. Your configuration is very useful for my learning emacs. but I have a little problem:

I want to disable the titlebar(The effect looks like spacemacs or [redguardtoo/emacs.d](https://github.com/redguardtoo/emacs.d.git) ).
Because I think the titlebar is very very useless and ugly.
  
but in your configuration , I don't know where your titlebar configuration is.....
So It's very kind of you again, sorry.
  
Thank you.

**Comment by purcell** [comment]
Normally you would just make your frame full-screen using something like `M-x toggle-frame-fullscreen`. Is that what you meant?

**Comment by YuanPres** [comment]
No ,It isn't what I mean.
I want to disable "File Edit ...." bar. The `titlebar`, It isn't `fullscreen`.

**Comment by YuanPres** [comment]
![virtualbox_arch linux_30_04_2017_17_38_32](https://cloud.githubusercontent.com/assets/26828933/25563339/2b8a36bc-2dcd-11e7-8a9b-3d70dd0a368f.png)
@purcell  look this picture.
I want to disable the bar that displays "File Edit ..."...

**Comment by YuanPres** [comment]
Sorry ,I'm wrong. I should call it "menubar"
I want to disable that displays "File Edit ..." bar
  
I really think that bar is  very useless and ugly.
I would like to ask, what will you enable it in the configuration ?
If you are offended please forgive me

**Comment by purcell** [comment]
I actually don't know why you're seeing the menu bar. It's disabled in my config, because I agree that it's not terribly helpful. Perhaps there's an error in your config before [the code in `init-gui-frames.el`](https://github.com/purcell/emacs.d/blob/0171dbd58b3ee6840b7654582647b9f77557859a/lisp/init-gui-frames.el#L61-L65) is executed?

If not, you can also choose `M-x customize-variable`, then enter `menu-bar-mode`, change to `nil` and save.

**Comment by YuanPres** [comment]
@purcell  I don't understand what you mean.....In your default configuration, the menu bar is closed?
I keep the default settings all the time. But the `menubar` always displayed.
  
The second way you say is valid. however,When I reinstall, the menu bar will appear again.
  
Is this picture's top menu bar ? I want to disable this picture with the words "File ..." on top .
![Uploading VirtualBox_Arch Linux_30_04_2017_19_36_38.png…]()

**Comment by YuanPres** [comment]
I remind you that disabled the menu bar on OS X,  the panel should have nothing.
The menu bar is enabled:
<img width="1280" alt="2017-04-30 8 04 38" src="https://cloud.githubusercontent.com/assets/26828933/25564269/3908a2d2-2de2-11e7-96d8-73d27a6a0494.png">
The menu bar is disabled(by `customize-variables`):

**Comment by JiaHong-Lee** [comment]
Notice that too when I first used Mr. Steve's configuration few weeks ago.

Now tried again downloading and loading Mr. Steve's configuration, and can confirm that the configuration does not hide the menu-bar by default, so I hide it by adding this line to my init.el:
```
;; DISABLE MENU-BAR
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
```

Hope that it helps. Thanks!

My environment:
Windows 10 Version 1607 (OS Build 14393.1066)
Emacs build of GNU Emacs 25.1.1 (i686-w64-mingw32) of 2016-11-16

**Comment by YuanPres** [comment]
@JiaHong-Lee I know this way. 
But I think Mr. Steve does not seem to notice the menu bar in other WM will be displayed.
Because Mr. Steve seems to want to hide the menu bar
I don't know what OS he uses. 
This problem seems to be hidden on the OS he uses.

**Comment by YuanPres** [comment]
Thank you.

**Comment by purcell** [comment]
@YuanPres Thanks for the report and related discussion. I'm on OS X and never had an issue with this, but I'm happy to commit this change because I do indeed want the menu bar to be hidden by default in all frame types.

**Comment by YuanPres** [comment]
@purcell Sure, because the OS X menu bar location is very strange. HAHAHA!
And.... I have just tested the new version on all the WM and DE  I use and macOS 10.12.4
This time they all work fine.
Thank you very much! 👍

**Comment by YuanPres** [comment]
@purcell I have a question for this issue to ask you for advice:
Would you like to tell me what the code is doing?
```
~/.emacs.d/lisp/init-gui-frames.el
  
...
(add-hook 'after-make-frame-functions
          (lambda (frame)
            (with-selected-frame frame
              (unless window-system
                (set-frame-parameter nil 'menu-bar-lines 0)))))
...
   
```
  
I have tried to change this code to fix this issue, but it is invalid.
 Please forgive my foolishness...

**Comment by purcell** [comment]
I think the intention was to disable the menu bar _only_ in terminal frames: I only use OS X currently, where `menu-bar-mode` has no effect. So the code says "when you've made a frame, then if it's a terminal frame, set the menu bar height to 0."

**Comment by YuanPres** [comment]
@purcell  Thanks

**Comment by YuanPres** [comment]
Thanks for your patience.
And……Now that you have completely closed the menu bar in the previous code.
So can I remove this code?
（I have some obsessive-compulsive disorder……haha)
@purcell

**Comment by YuanPres** [comment]
Thanks. It meets my expectations.
