### ISSUE TITLE
How to customize your configuration to support the C language auto-completed?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#435]
Hello, Purcell: 
Excuse me, I am learning C programing language. I need the C language auto-completed, but I don't want to change configuration. 
So I want to add the features I need without destroying your configuration frame. But I don't have enough knowledge to determine what I should do. 
Would you like to give me some advice ? I do not want to be "Reach Party", but it is difficult for me.
  
Thank you.

**Comment by purcell** [comment]
As for where to put your code, you'd want to add your own `init-c.el`, probably, and load it from `init.el`.

I don't know what you should put in it, though, sorry. `company` has a `company-clang` backend. You might consider looking to see what support Spacemacs or Redguartoo's fork of this repo have for C and C++.

**Comment by emuio** [comment]
Hi, Purcell:
Maybe you have put someone's name wrong.

https://github.com/redguardtoo/emacs.d

**Comment by purcell** [comment]
> https://github.com/redguardtoo/emacs.d

Yep, thanks.
