### ISSUE TITLE
Which key is the Super key on macOS in your configuration ?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#438]
Hello Purcell. 
  
I have to use  <kbd>⌘</kbd> (`Super (Command)`) to use a function, but in your configuration. the <kbd>⌘</kbd> is bind to <kbd>Alt</kbd>. So How can I use the <kbd>⌘</kbd> ?
  
I am sorry to have brought you so much trouble.
Thank you.

**Comment by purcell** [comment]
My default config says the following in `init-osx-keys.el`:
```
  (setq mac-command-modifier 'meta)
  (setq mac-option-modifier 'none)
```

If you would like either `Option` or `Command` to work as `Super`, then you can change one of the above variables to `'super`.

**Comment by YuanPres** [comment]
Thanks
