### ISSUE TITLE
Is this a helm/ivy bug ?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#439]
Hello:
Sometimes, I will see this interface:
![virtualbox_arch linux_10_05_2017_19_59_53](https://cloud.githubusercontent.com/assets/26828933/25926437/c678c25e-3621-11e7-8b30-8971132abd21.png)
  
As you can see, the background of the complete list disappears. Which front-end are you using? I have to report a bug...

**Comment by purcell** [comment]
I'm not sure exactly what steps you've followed in the above screenshot, so it's not clear to me which completion you've triggered. Could you provide steps please?

**Comment by YuanPres** [comment]
1. Start Emacs
2. `C-x C-f` to open `for.sh`
3. Type `#!/usr/bin/en`, then type `TAB`.

But the problem is not just in one place, It appears in the following cases:
- Shell Scripts variables.
- Python with anaconda.
- Ruby
**...**

**Comment by YuanPres** [comment]
And……The emergence of this problem is completely no law.
It may suddenly appear at any time.

**Comment by purcell** [comment]
Okay, so that completion comes from `company`. Which colour theme, Emacs version and `company` version do you have, and have you customised this config? I have never seen this issue with my default config, so I'm not sure I can help you much here.

**Comment by YuanPres** [comment]
It doesn’t matter, if it is not your problem, I will report bugs to the upstream,
because sometimes, I often see this problem.
  
I didn't customize your configuration.
My Version:
```
Version: GNU Emacs 25.2.1 (x64_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22
Color theme: sanityinc-tomorrow-bright
```

**Comment by YuanPres** [comment]
So what plugin do you use as an auto-complete front end? I really want to know.
Thank you.

**Comment by purcell** [comment]
> So which plugin do you use as an auto-complete front end? I really want to know.
> Thank you.

`company` for completion in buffers, and `ivy` elsewhere (ie. in the minibuffer).

**Comment by YuanPres** [comment]
Thanks...
And...It has been from time to time ... ...

**Comment by purcell** [comment]
I just encountered this case myself, and figured out what was going on: you probably triggered a `completion-at-point` call. It looks like by default, `ivy` sets itself as the `completion-in-region-function`. So what we both saw is an `ivy` popup, which uses the normal ivy minibuffer colours, and there's no obvious way to change its background colour.

This is a new behaviour in `ivy`, and I have now disabled it: I will replace it with a `company` handler instead, if I can figure out how to do that.

**Comment by purcell** [comment]
Having investigated this, I think I'll revert the change, and just keep the previous behaviour. I guess it would be nice if `ivy` displayed a background colour here, but it still actually works well.

**Comment by YuanPres** [comment]
@purcell 
When the auto-complete window pops up automatically, there will not be any problems.
But in the <kbd>tab</kbd> key to call out the window, there will be problems in the picture

**Comment by purcell** [comment]
Yes. When it pops up automatically, that's `company`. When it pops up on `TAB`, that's `ivy`.

**Comment by YuanPres** [comment]
@purcell 
I have a question :
Why don't you use the `helm` ?

**Comment by purcell** [comment]
It's a very big and intrusive package, which introduces quite a different style of  working with Emacs. I'm happy if it works for other people, but I don't like it myself.

**Comment by YuanPres** [comment]
Well.
It's really VERY VERY BIG BIG BIG............
