### ISSUE TITLE
How Can I create a file ?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#440]
Hello, Purcell:
I want to Create a file. But ivy will automatically fill the existing file name based on the name I entered.
Like:
Existing file Name:
```
bala.sh
```
Enter: `a.sh` ，There will be `bala.sh`
.
So....how can I create `a.sh` in emacs?
Thank  @you! 😀

**Comment by YuanPres** [comment]
![virtualbox_arch linux_14_05_2017_08_48_00](https://cloud.githubusercontent.com/assets/26828933/26030323/e90f195e-3882-11e7-9e2d-f3bf0c72829f.png)

This is a picture of my question.

**Comment by purcell** [comment]
This is an `ivy` question, really, but the answer is `C-M-j` -- this key effectively says to `ivy` "just accept exactly what I've entered."

**Comment by YuanPres** [comment]
Thanks. The <kbd>C-M-j</kbd>  works.
