### ISSUE TITLE
Unknown upattern `(quote asciiart)`

### ISSUE THREAD

**Issue by bowenchen6** [purcell/emacs.d#442]
where i enter C-x o in my emacs, some thing happen:
Unknown upattern `(quote asciiart)`

**Comment by purcell** [comment]
That's probably a bug in the `switch-window` package. I see some related work was done [there recently](https://github.com/dimitri/switch-window/commits/master). Try updating that package, and/or restarting emacs. If there's still an issue, file it on the upstream repo so someone with more specific knowledge can help you. Good luck!

**Comment by bowenchen6** [comment]
OK
