### ISSUE TITLE
A suggestion about elpa repositories.

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#443]
Hello Purcell. I would like to make a suggestion but the government blocked internet. So the Twitter is not available. So I had to say here...I'm sorry for my reckless and very poor English...
  
Saving your presence, I think you should completely disable using  `http` and should use `https`. Because `http` is very fragile. So `http` is vulnerable to network attacks.
  
Just yesterday, our company was attacked by `MITM`, all GNU elpa (using `http` by default) packages were replaced with the wrong data. We reinstalled emacs and your configuration, the results have not changed anything. All GNU elpa packages are not available. but all melpa packages (using `https`) are not affected in anyway...
  
Until we solved the attack, these packages are all available.
  
So I think the `http` is also very insecure even as a download link now. I hope you can completely disable `http` in your configuration.
As far as I know, the computer / OS without `ssl` almost does not exist now. 
For Windows users, I think you should let them solve their own problems. It is not difficult anyway.
  
The above is my advice. I just hope that everything is safer. If I created some useless advice for my ignorance, please forgive me. And...
Pardon me my offence! 

Thank you very much.

**Comment by purcell** [comment]
Makes sense, done. Ideally, Emacs would make "https" the default for this.

**Comment by YuanPres** [comment]
The `org` repository is not use ? 
But you still only force use ssl for `gnu`  ... ...
Well, thank you very much.

**Comment by purcell** [comment]
> The org repository is not use ?

Ah yes, that seems to work too. Updated.

**Comment by YuanPres** [comment]
Well……Thanks.
Do you write the code in this way for compatibility?
Finally ask you a question:
Before I get your suggestions , I am dealing with this:
Delete:
``` emacs-lisp

...
;; We include the org repository for completeness, but don't normally
;; use it.
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))


(defconst sanityinc/no-ssl (and (memq system-type '(windows-nt ms-dos))
                                (not (gnutls-available-p))))

;;; Also use Melpa for most packages
(add-to-list 'package-archives
             `("melpa" . ,(if sanityinc/no-ssl
                              "http://melpa.org/packages/"
                            "https://melpa.org/packages/")))

...
```
Add:
``` emacs-lisp

...
;; We include the org repository for completeness, but don't normally
;; use it.
(add-to-list 'package-archives `("org" . "https://orgmode/elpa/"))


;;; Also use Melpa for most packages
(add-to-list 'package-archives `("melpa" . "https://melpa.org/packages"))

...

```

Will be there anything wrong with that?
Thank you very much !

**Comment by YuanPres** [comment]
@purcell 
Yes. The org-mode's official https repository is not unreliable at all ! I’m using the `emacs-china` repositories now, so I forgot it...
I'm sorry to have trouble you...
And...
Would you like to answer the above comment question?
Will there be any problem "Completely abolish" http support like me ?

**Comment by purcell** [comment]
> Will there be any problem "Completely abolish" http support like me ?

Yes, in general, but it's unlikely to be a problem for you. On certain Windows systems, Emacs does not support https. Those "if" conditions were added for that reason.

**Comment by YuanPres** [comment]
Thanks

**Comment by YuanPres** [comment]
Well...I want to do it (As in the above forced to abolish http) in my fork, and will write some warnings like “For Windows users, I think you should can solve ssl problems by yourself, It is not difficult anyway.”,
and add your link: 
`http://חנוך.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html` 
in my README.org.
  
I am very disgusted with Windows. So I **DO NOT** want to support Windows and its users.
  
Did this infringe your copyright ?

**Comment by purcell** [comment]
You can do what you want in your own fork: licence is BSD. https://github.com/purcell/emacs.d/blob/master/LICENSE

**Comment by YuanPres** [comment]
And....
I found that I was really stupid.
The `emacs-china` https repositories I using are very reliable.
but the `gnu` and `org-mode`’s official https repositories are unreliable...
Don't know why, the GNU Project doesn’t seem very welcome https.
Probably because of “Freedom is not Free”...
I’m so sorry to have trouble you...
