### ISSUE TITLE
Add magit-gitflow suport

### ISSUE THREAD

**Issue by kimichen13** [purcell/emacs.d#446]
Can you add `magit-gitflow` support, just add `(maybe-require-package 'magit-gitflow)` to `init-git.el`, and then `(add-hook 'magit-mode-hook 'turn-on-magit-gitflow)`.

Thanks.

**Comment by purcell** [comment]
Hi - thanks for getting in touch, but I don't need that package myself, so I'm not going to add it to the config. But you can easily add it in your own fork as described in the README.

**Comment by kimichen13** [comment]
OK, thanks.
