### ISSUE TITLE
Why do you want to keep the “org” elpa repository ?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#447]
Hello:

I did not encounter any problems, I was just curious, why do you want to keep the `org` elpa repository?

Thanks.

**Comment by purcell** [comment]
I don't really have a good reason to keep it right now, personally. Some people (not me) rely a lot on having the latest `org` version, and *some* packages on MELPA may depend on `org-plus-contrib` or on very new versions of `org`.

**Comment by YuanPres** [comment]
That is, the `org` on "org" repository is usually relatively new?

**Comment by purcell** [comment]
Yes, it's a snapshot build, like MELPA, but published directly by the maintainers. And MELPA doesn't have an `org` package. I prefer to use a recent Emacs version in order to ensure I have a reasonably new (but stable) `org` version.
