### ISSUE TITLE
How can I add a company backend ?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#449]
Hello, Mr.Purcell: 
I'm sorry to have trouble you twice  today........

I want to add a `company` backend, but I added the configuration (follow the instructions for these plugins) without any effect.
Please see my file:
```emacs-lisp
~/.emacs.d/init-cc.el

(when (maybe-require-package 'irony)
  (add-hook 'c-mode-hook 'irony-mode)
  (add-hook 'c++-mode-hook 'irony-mode)
  (add-hook 'objc-mode-hook 'irony-mode))
(after-load 'irony-mode
  (diminish 'irony-mode))

(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))

(when (maybe-require-package 'company-irony-c-headers)
(eval-after-load 'company
  '(add-to-list
    'company-backends '(company-irony-c-headers company-irony))))


(provide 'init-cc)
```

I have done all the other work. (For example, add `(reqiure 'init-cc)` to `init.el`)

**What mistakes did I make ?**

Also, I've seen some guidance on elpa packages in many emacs tutorials and other people's configurations

Their `init-elpa` file is generally like this:

```emacs-lisp
setq package-archives '(("gnu"   . "xxx")
                         ("melpa" . "xxx")))

.....................................

(require-package 'xxx)
(require-package 'xxx)

........................................
```
But I did not see the above code in your configuration. What is your implementation ?

Then I see that you use a lot of your own created functions to create this emacs configuration.（like `sanityinc/xxx`).

**Is my error related to not using these functions ?**

Thank you very much.

**Comment by purcell** [comment]
No, you're generally doing the right thing.

I can't really spend much time helping here, but my guess is that your `eval-after-load` block is getting executed before a similar block in `init-company.el`, so your settings are getting lost. Try making sure that `init-cc.el` is loaded after `init-company.el`.
