### ISSUE TITLE
python complete

### ISSUE THREAD

**Issue by JoveYu** [purcell/emacs.d#45]
I tried many ways to achieve complete python syntax but has never been able to,my python path is python2 ,how to use the completion?

**Comment by kxxoling** [comment]
Is this still in discussion? Jedi autocompletion and virtualenv support is really valuable for us Python developers. Autopep8 or yapf is also appreciated for Python code formatting. 

But I'm still a newcomer to Emacs world, though I like to know if there's anything that I can help.

**Comment by purcell** [comment]
`anaconda-mode` is now enabled by default in this config.
