### ISSUE TITLE
Wrong type argument: listp, t

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#450]
Hello:
  
  
Emacs Version:
```
GNU Emacs 25.2.1 GTK+ version 3.22.10
```
After  updating your commit (use `git pull`) today, I have seen the following in the minibuffer :
```
Wrong type argument: listp, t
```
And the `scratch` interface does not appear Welcome Message:" Happy hacking ... "

I re-downloaded a fresh configuration and did not make any changes, the results are the same.

Thanks.

**Comment by purcell** [comment]
Yep, config is temporarily broken, pending https://github.com/wolray/symbol-overlay/pull/9.

**Comment by YuanPres** [comment]
@purcell 
Yeah, I revert to the previous version to solve the problem. it works.
Also I saw that PR, but still **DO NOT** know what the plugin is better than the original......

**Comment by purcell** [comment]
Problem is now fixed if you update your packages.

**Comment by YuanPres** [comment]
Thanks.
But I will not to use this packages....
The rendering of this plug-in makes me feel very chaotic......
Highlight may not be very efficient and accurate, but it looks very neat.....
