### ISSUE TITLE
Failed to verify signature

### ISSUE THREAD

**Issue by bowenchen6** [purcell/emacs.d#451]
I use emacs-snapshot version.
now, something happen, which like #383 
 `Failed to verify signature: nlinum-1.7.el.sig`

**Comment by purcell** [comment]
Sorry, but that's not specific to this configuration. You probably have `gpg` installed, and `package-check-signature` enabled, and the GNU ELPA public key is not in your keyring. Not sure how that stuff works, sorry, so I can't help with it.

**Comment by YuanPres** [comment]
If it not work.

**RESTART AND RESTART AGAIN!!!!**


These signature verification mechanisms sometimes do some metaphysical bugs......
I have reported this bug to GNU, and they did not give me any solution.

**Comment by bowenchen6** [comment]
@YuanPres  OK
