### ISSUE TITLE
Why do you only use the "maybe-require-package" on diminish in ivy settings?

### ISSUE THREAD

**Issue by YuanPres** [purcell/emacs.d#457]
Hello Purcell, Sorry for taking your time again.

I've been reading your code to avoid me raised these annoying little problems again.
But when I read these two places, I didn't understand again.,,

In your `lisp/init-ivy.el`
```emacs-lisp
    (when (maybe-require-package 'diminish)
      (diminish 'ivy-mode)))
```
```emacs-lisp
  (when (maybe-require-package 'diminish)
    (after-load 'counsel
      (diminish 'counsel-mode)))
```

Why do you only use "maybe-require-package" for diminish in these both places? I see you did not use this judgment function in other places. You just used `(diminish 'xxx)`.
Will there it be in danger to don't use `maybe-require-package` here ?

Thank you.

**Comment by purcell** [comment]
I use `maybe-require-package` when I know that the package may not be compatible with a version of Emacs supported by this config. Ideally all of the config would use that rather than `require-package`, but I'm not ready to fix it all. `use-package` would be a good package to use if I did that.

**Comment by YuanPres** [comment]
Thanks.

**Comment by YuanPres** [comment]
In other words, the latest version can remove it?
And, in fact, I have always had a problem ...


**Why DO NOT you use `use-package`?**

`Use-package` seems to be used by many people to simplify their configuration ...

Because migration requires a great cost you?
