### ISSUE TITLE
By default, where is your fontconfig ?

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#459]
I only see the font size setting in your `init-fonts.el`, but I did not see the "what font to use" setting.

So...Where does your font configuration inherit?

I know how to manually specify the font, but I want to know this.

Thanks.

**Comment by purcell** [comment]
Nowhere: that's not a decision I make for users. Just `M-x customize-face` for `default`, and then choose the preferred family and size, but leave the other attributes unset so that they can be themed.

**Comment by ReimuXMX** [comment]
You may not understand what I mean...
In fact I also found that you did not set the font. 
So this setting inherits from "Emacs default settings"...  :-)
Thank you very much.
