### ISSUE TITLE
What is the ^L ?

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#462]
Hello, Sorry for taking your time.

When I use other editors to view your configuration file, often see these characters:
```
^L
```
AND
```
;;---------------------------
;; ... (It looks like your comments）
;;----------------------------
```

I guess that the above code is for segment, but I do not know what the `^L` is.  I searched on Google, but did not get a definite answer.

**I want to know what the configuration would be affected if the `^L` is deleted.**

And if I guess yes, you do use these code to segment the file,
**Why do you need to use two methods to segment it?**

Thank you.

**Comment by terlar** [comment]
The `^L` is a control character representing page break, which means when "printing" the document it should print a new page. Removing these won't affect the config.

A nicer way to display them is to use this for example:
https://github.com/purcell/page-break-lines

Using the comments you can split into shorter sections while the page break could be used for larger sections to make a bigger distinction.

**Comment by purcell** [comment]
And this config already uses `page-break-lines`, so you shouldn't be seeing the raw characters.

Regarding `^L` vs `;;--------`, I just haven't gone through all the code and tidied it into one style.

**Comment by ReimuXMX** [comment]
@purcell 
Thanks....
I also found that these files seem to be created at different times.

**And so, what kind of segmentation symbol do you expect to use ?**

Sorry for taking your time again.

**Comment by purcell** [comment]
Generally I prefer ^L these days.

**Comment by ReimuXMX** [comment]
Thanks

Well, `^L` is really a good symbol, because it will not be deformed because of the window width ....
