### ISSUE TITLE
Would you like to add yasnippet?

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#463]
Hello:

The [YASnippet](https://github.com/joaotavora/yasnippet) and its snippets can help a lot of people (including me) write javascript, HTML and CSS .
Are you interested in this plugin? 

Sorry for taking your time.

**Comment by purcell** [comment]
No thanks, tried it years ago.

**Comment by ReimuXMX** [comment]
Okay………

**Comment by ReimuXMX** [comment]
Well, I try to add this feature ...
My level is not enough, so it has lot of bugs. 
And these snippets are not as I wish.
So forget ...
