### ISSUE TITLE
Some tabs.

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#465]
I found some tabs in your files:

+ init-editing-utils.el: line `263~266`, line `275~276` ;
+ init-python-mode.el: line `3` ;
+ init-sessions.el: line `23` ;

Are these your typo? 
or must use the `TAB` ?

**Comment by purcell** [comment]
Thanks, fixed. And no, not intentional: tabs are the work of the devil. ;-)

**Comment by ReimuXMX** [comment]
Thanks
