### ISSUE TITLE
Light / dark switch seems to have some problems

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#466]
Hello:
When using your default `color-theme-sanityinc-tomorrow` theme, everything is ok. 
But when I changed some of the "more custom" theme (like `leuven` or `monokai`), there will be two themes working together.

The result will lead to a lot of very strange user interface. Such as white background with white font.

I know this is my problem, but I want to ask you why you don't use `disable-theme` / `load-theme`, but use the `customize-theme`?

Thank you :-)

**Comment by purcell** [comment]
`customize-themes` uses `disable-theme` and `load-theme` internally. To prevent multiple themes being enabled, use `M-x customize-themes` yourself, and choose the theme you prefer.

**Comment by ReimuXMX** [comment]
Thanks. it works.

**Comment by omouse** [comment]
I just ran into this issue and the fix you suggested works, thanks! :+1:

**Comment by maddovr** [comment]
I know this issue is closed but it still happens to me on emacs 26.3. So I have commented your init-themes.el (deleted the file and commented the line in init.el), and I've been using `customize-themes` to set a theme, the problem is the background doesn't change for me. So for example I'm using the two modus themes (not together, but I wish I could), I go to `customize-themes`, select the light one and save. Everything works. Again `customize-themes` I select the dark one and everything changes (font colors, modeline, buttons) but the background doesn't (it still remains white, thus being nearly unreadable). What am I doing wrong?

**Comment by purcell** [comment]
@maddovr Not really sure, sorry. Is there any indication that this behaviour is related to my config specifically?

**Comment by maddovr** [comment]
> @maddovr Not really sure, sorry. Is there any indication that this behaviour is related to my config specifically?

Yes it is. I tried specifically with modus themes (operandi and vivendi) on your config and the background doesn't change (buttons and fonts do, modeline also does change), tried on a fresh emacs (deleting your .emacs.d) and customize-themes works as intended. Tried several things (changing your init-themes.el to use modus-themes, customize-themes, creating a function to toggle between each theme), the colorscheme does change but the background doesn't.
I'm on emacs 26.3 on ubuntu 20.04
-

**Comment by purcell** [comment]
If I install both those themes then I can flip back and forth between them using the `M-x customize-themes` interface without seeing any weird modelines like that. And, looking closer, it looks like you're using some sort of custom modeline which *isn't* part of my config, so I think there's an extremely good chance that is the problem...

**Comment by maddovr** [comment]
It's the DOOM modeline, I removed it and it still won't work (it's not just the modeline that changes, if you look closely the buttons changed as well)

**Comment by maddovr** [comment]
I fixed this issue by deleting custom.el, something apparently went wrong there and I've switched to set things fully in elisp now.

**Comment by snowman** [comment]
when you `M-x customize-themes RET`,
select theme `sanityinc-tomorrow-bright`,
then exit Emacs.

When restart Emacs, it'll restore color settings from
variable `desktop-saved-frameset` of file `.emacs.desktop` even with `(custom-set-variables '(custom-enabled-themes nil))`:

```
( foreground-color . "#eaeaea" )
( background-color . "#000000" )
( mouse-color      . "black"   )
( border-color     . "#424242" )
```

**Comment by purcell** [comment]
@snowman Looks like you can add settings to `frameset-filter-alist`, e.g.
```el
(with-eval-after-load 'frameset
  (push '(foreground-color . :never) frameset-filter-alist))
```
etc
