### ISSUE TITLE
Some functions of ruby-mode seem out of date

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#467]
Hello: 

You replaced the `highlight-symbol` with the `symbol-overlay`, but you did not seem to have made the update in the ruby configuration.

Anyway, I now see the effect is this ... "do / end / class ..." still can wake up `symbol-overlay`.These keywords remain highlighted.

Your function: 
```emacs-lisp
(defun sanityinc/suppress-ruby-mode-keyword-highlights ()
  "Suppress highlight-symbol for do/end etc."
  (set (make-local-variable 'highlight-symbol-ignore-list)
       (list (concat "\\_<" (regexp-opt '("do" "end")) "\\_>"))))
(add-hook 'ruby-mode-hook 'sanityinc/suppress-ruby-mode-keyword-highlights)
```

Thank you.

**Comment by purcell** [comment]
The highlighting you're seeing is from `show-paren-mode`. The above patch is probably no longer required, and I'll delete it if so.

**Comment by ReimuXMX** [comment]
Well……

I have deleted it, and did not find abnormal.
