### ISSUE TITLE
Guide-key does not display properly on small resolution windows

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#469]
Hello:
I often need to open some windows of 80-character width, but this time `guide-key` can only show a part.

<img width="688" alt="2017-07-20 4 40 39" src="https://user-images.githubusercontent.com/26828933/28408592-92be2c4e-6d6a-11e7-938d-3683d4ef34db.png">

And  if I then shorten the height, then the guide-key does not work directly.
This is error message:
```
Error running timer ‘guide-key/popup-function’: (error "Window #<window 3 on *scratch*> too small for splitting")
```
Thank you.

**Comment by purcell** [comment]
That's a guide-key issue, I'd say, not an issue with this config.
