### ISSUE TITLE
How can I get source in org-mode ?

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#470]
Hello:

You seem to have used some plugins to make links and code blocks appear directly as previews in `org-mode`:
![virtualbox_arch linux_23_07_2017_11_15_47](https://user-images.githubusercontent.com/26828933/28496241-1a27d9ca-6f99-11e7-86a2-ab18a2d4f797.png)

But I want to get source code like this:
```
[[[https://www.gnu.org/software/emacs/][file:https://img.shields.io/badge/Build%20With-Emacs-f596aa.svg]]
```
So...What can I do ?

Thank you. 
And sorry for my poor English...

**Comment by purcell** [comment]
That's just how org works. Use M-x fundamental-mode or similar. This is an org question, though, so please don't file issues here constantly.

**Comment by ReimuXMX** [comment]
Thanks.
And sorry.
I will pay attention.

**Comment by emuio** [comment]
@ReimuXMX 

> To show the internal structure of all links, use the menu entry Org->Hyperlinks->Literal links.

You can find this in [http://orgmode.org/manual/Link-format.html](http://orgmode.org/manual/Link-format.html)
