### ISSUE TITLE
How to change the font of chinese?

### ISSUE THREAD

**Issue by zhuruliang** [purcell/emacs.d#471]
I've google much to found the solution, but I still can't find how to change the font of chinese.

**Comment by ReimuXMX** [comment]
https://github.com/tumashu/cnfonts

You may be looking for this.

**Comment by purcell** [comment]
Yep, sorry, I can't help with this.

**Comment by creamidea** [comment]
You can try the code below. This is my font setting:
```el
(defun set-cjk-font (family size)
  "Set Chinese/Japan/Korea Font.
FAMILY:  Microsoft Yahei
SIZE"
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     ;; :height font-size
     (font-spec :family family :size size))))
```

Or, you can use the library that @ReimuXMX mentioned

Good luck :)

**Comment by zhuruliang** [comment]
@creamidea thanks
