### ISSUE TITLE
python-mode anaconda-mode: auto-convert 'or' into character like 'v', and pc runs slow then

### ISSUE THREAD

**Issue by limTeTE** [purcell/emacs.d#479]
Hi, Steve. 
     This might not be an issue on other computer.  I work with python script in Emacs25,2 with your emacs configuration, and my pc is a little bit out of date(cpu is INTEL I3, and memory size is 4G).
When I run to this line of python code:
 
  `if pnstr == 'all' or int(pnstr) > tot:`. 

   The machine goes down and runs very slow, even a 'C-n' move could take several seconds. I want to know if this auto convert from operator 'or' to symbol like 'v' could be inhibited, anyway?
Thank you~

**Comment by purcell** [comment]
If you prefer, you can edit `init-python.el` so that it does not automatically disable anaconda.

Re. the symbols, look for (and disable) `global-prettify-symbols-mode`, I think.

**Comment by limTeTE** [comment]
​apreciate that, thank you!​

2017-08-13 9:59 GMT+08:00 Steve Purcell <notifications@github.com>:
