### ISSUE TITLE
Failed to verify signature: nlinum-1.7.el.sig emacs

### ISSUE THREAD

**Issue by xishi00** [purcell/emacs.d#482]
Emacs reports the signature error during the initialization with the purcell's latest configure. But when I change : (setq package-check-signature nil), then it reports package 'lively-' is unavailable.

is it a bug? how to fix it?

thanks!

**Comment by purcell** [comment]
Re. the signature issue, I sometimes see that on the Travis build. Just restart or refresh the package list and try again.

Re. `lively`, see #481.

**Comment by xishi00** [comment]
the signature issue occurs whenever you initialize the emacs,that is, start emacs with fresh downloading configure. Refreshing the package list just does no effect to me. It warns this problem for two packages, nlinum and csv-mode, which are all from GNU. If I install nlinum manually, it will skip the signature checking. But if i do the same with csv-mode, the emacs will report error: File already exists.
