### ISSUE TITLE
Why do you want to make sure ido-mode is disabled?

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#484]
Hello:

I noticed some code in the `init-ivy.el`:

``` emacs-lisp
......

  (add-hook 'after-init-hook
            (lambda ()
              (when (bound-and-true-p ido-ubiquitous-mode)
                (ido-ubiquitous-mode -1))
              (when (bound-and-true-p ido-mode)
                (ido-mode -1))
              (ivy-mode 1)))

......
```

You seem to be sure that `ido-mode` is disabled.

Why do you want to do that?

I removed these code, and then used for some time, I never saw ido-mode started ...

**Comment by purcell** [comment]
Yes, that was temporary, when I was switching from `ido`. I can now remove it from my config.

**Comment by ReimuXMX** [comment]
Thanks
