### ISSUE TITLE
Emacs gets stuck by invalid function org-babel-header-args-safe-fn

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#486]
I use your latest emacs.d and Emacs 25.2. I worked fine in the past. 
Today I installed the Org by M-x list-packages.
When I restarted my Emacs, it got stuck with the following message in the minibuffer:

Invalid function: org-babel-header-args-safe-fn

Could you help me with this issue?

Thanks

**Comment by purcell** [comment]
I'm also using Emacs 25.2, and don't see this issue. Do you also have an `org` or `org-plus-contrib` package in `~/.emacs.d/elpa-25.2`? And generally speaking, if you start with `--debug-init`, you'll get a helpful stacktrace when the error happens, so that you can paste it here.

**Comment by purcell** [comment]
Great, glad you figured that out! This isn't generally a configuration I can support.

It's possible some of the other `org-*` packages aren't compatible with the latest `org` version, so it might be hard to get things working.

However, it's also possible that the other `org-*` packages just need to be byte-compiled against the newer org package. So you could try installing the new `org` package, and then delete all the other packages. When Emacs restarts it will reinstall and recompile the other packages.

**Comment by haifenghan** [comment]
Great. It works.
Following your instructions, I delete org-*:
`~/.emacs.d/elpa-25.2$ rm -rf org-cliplink-20170724.413/ org-fstree-20090723.819/ org-pomodoro-20161119.226/`

After restarting Emacs, everything seems OK.

Thanks you, expert!
