### ISSUE TITLE
Automatically added "(package-initialize)"

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#487]
Hello:

When I manually install some packages, `~/.emacs.d/init.el` will be automatically written  `(package-initialize)`.
This will cause difficulties when synchronizing your configuration with `git pull`.

I noticed that this line of code has been written into `init-elpa.el`, so I suspect that some load order issues.
Because I see a lot of other configurations put this line on the top of `init.el`.

My Emacs version is 25.2 on archlinux.

Thanks.

**Comment by purcell** [comment]
That's the reason for [this line](https://github.com/purcell/emacs.d/blob/528ca470c6258101ebc6e69fd0092d8384122112/init.el#L32). Emacs adds it automatically if it doesn't find it in your config, but a comment is sufficient.

**Comment by ReimuXMX** [comment]
Well...This reason I served

**Comment by ReimuXMX** [comment]
> a comment is sufficient.

I understand this now.
It seems that package.el will automatically detect whether this code exists ...
