### ISSUE TITLE
How to End Prompts Upon Starting Emacs

### ISSUE THREAD

**Issue by davidpgil** [purcell/emacs.d#488]
I am a beginner at Emacs and installed your emacs.d per some recommendations. After installing I am prompted with a buffer that says:

```
"require 'color-theme-sanityinc-tomorrow'
(color-theme-sanityinc-tomorrow--define-theme bright)

```
The bottom bar says:

> Please answer y or n. Loading a theme can run Lisp code. Really load? (y or n)

I always can bypass this by hitting "y". Howver, I need to do this every time I restart Emacs. How do I stop getting this prompt?

I believe this may be due to the fact that I don't have Admin priveleges on my work computer. Please advise.

My system description:
Windows 7
Emacs 25.2

I have another issue after that where I am told '~/emacs.d./server' is unsafe. I believe this is a permissions issue as well. How do I stop these prompts?

Thanks very much.

David

**Comment by purcell** [comment]
No idea about Windows and how privileges might affect Emacs start-up, sorry, though perhaps some users would like to chime in here.

Normally the "safe theme" preference would be saved into `~/.emacs.d/custom.el`, so you shouldn't have to type it every time you start Emacs. I googled the "server unsafe" error and [found this](https://stackoverflow.com/questions/885793/emacs-error-when-calling-server-start), which might help you. Good luck!

**Comment by purcell** [comment]
I'd add that the "server" error is probably causing the "safe theme" customisation to not get saved properly, so I'd imagine fixing the former will solve the latter.

**Comment by davidpgil** [comment]
I also know how to use Google :)

I was hoping for a workaround that won't require needing admin rights. I guess I need to remove the server then? What do I need to do to your emacs.d to remove the server component dependency?

**Comment by purcell** [comment]
Take a look at https://github.com/purcell/emacs.d/blob/528ca470c6258101ebc6e69fd0092d8384122112/init.el#L139-L141

**Comment by davidpgil** [comment]
That did it. Thanks.
