### ISSUE TITLE
The key combination C-M-b doesn't work

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#490]
When pressing the key combination `C-M-b`, Emacs always pops up a soft keyboard as follows:

![screenshot from 2017-08-31 19-39-49](https://user-images.githubusercontent.com/4157827/29921761-6eb158d0-8e85-11e7-95fb-4a5cf581f9a8.png)

In fact, these keys are bound to the function `backward-sexp`. 

I know it's not the issue of emacs.d. However I can't find a solution.
 @purcell Could you please help me with it? Thanks

**Comment by purcell** [comment]
Keys that are intercepted by your window system never reach Emacs. You'll need to find out what thing in your system is popping up the keyboard and disable that, then Emacs should work as expected.
