### ISSUE TITLE
Win10：Cannot start Slime

### ISSUE THREAD

**Issue by ZhuJiayou** [purcell/emacs.d#495]
1. I wanna use Emacs to edit Common Lisp.
2. SBCL cannot be installed in my computer(Windows 10).
3.  I installed CLisp.
4. When I input “M x slime” to start Slime, it shows "No such file or directory, lisp".
5. Then I turn to read your config "init-common-lisp.el", I find "SBCL" and "CCL", but no "CLisp", I'm wondering that maybe your configurations donot suport CLisp.
6. As for Emacs, I'm a greenhand. I donot know how to do with it.
7. It will be so kind for you to help me.
Best Wishes!

**Comment by purcell** [comment]
I've just never used `clisp`, sorry. You can probably just add a block similar to one of the others in `init-common-lisp.el`. If you find something that works for you, I'll be happy to merge a patch!

**Comment by sagaidealsee** [comment]
Thanks Steve,Could you please share some configuration about latex?Thankssaga                                                                                                                                                                        Sent from my 格力空调...                                                                                                                                                                            From: notifications@github.comSent: September 23, 2017 7:09 PMTo: emacs.d@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [purcell/emacs.d] Win10：Cannot start Slime (#495)  I've just never used clisp, sorry. You can probably just add a block similar to one of the others in init-common-lisp.el. If you find something that works for you, I'll be happy to merge a patch!

**Comment by purcell** [comment]
> Thanks Steve,Could you please share some configuration about latex

No, I don't use LaTeX myself, sorry.
