### ISSUE TITLE
Always throw an error when coding in python

### ISSUE THREAD

**Issue by luojiebin** [purcell/emacs.d#497]
Emacs for Mac on Macbook Pro, when code in Python. It throw these:

File "/Users/xxxxx/.emacs.d/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py2.7.egg/anaconda_mode.py", line 17, in <module>
    from jedi import Script, NotFoundError
    ImportError: cannot import name NotFoundError

How can I fix it? Thanks.

**Comment by purcell** [comment]
Hi! I don't have that problem, sorry, but I note that I have a slightly newer `anaconda-mode` egg version, 0.1.9. You might try deleting the `~/.emacs.d/anaconda-mode` directory and restarting Emacs, which would hopefully force the newer version to be installed. If that doesn't help, I'd suggest contacting the anaconda mode author, sorry.
