### ISSUE TITLE
company and page-break-lines are not compatible

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#501]
Hello

Your code [here](https://github.com/purcell/emacs.d/blob/2bbffff0a00c2d7c2d0ed7c67aba7daecc2bbaa0/lisp/init-company.el#L28) seems to be invalid.

Whether I add or remove these code, I will see these:

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/26828933/31371957-37ddecfa-adc6-11e7-8c5d-9f56fbe977aa.png">

Thank you.

**Comment by purcell** [comment]
Odd. Works perfectly for me.

> GNU Emacs 26.0.50 (build 2, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-09-16

**Comment by ReimuXMX** [comment]
In fact, I feel very strange .......

My Emacs Version:
```
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-17
```
OS Version:
```
Arch Linux with linux-4.13.5-1-ARCH
```
And........
In the input `setq` and other things at the beginning, work properly.

But when you enter some function parameters, etc., the work is abnormal.

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/26828933/31579895-0be1b8d8-b173-11e7-84df-6630531ea227.png">

**Comment by purcell** [comment]
Probably 1ae3332 will resolve this for you.

**Comment by re-mx** [comment]
Thank you.
It works.
