### ISSUE TITLE
Ruby mode autocompletion keyword

### ISSUE THREAD

**Issue by jsirex** [purcell/emacs.d#504]
I'm not sure where to start, is it a bug of this .emacs.d repo or ruby-mode repo.
Here is the case:
```ruby
"XXXX".downcase
an_array.each do|
```
Emacs tries to autocomplete each word I'm typing. So when I'm trying to type "do" it automatically adds "wncase". Tab or enter inserts me "an_array.each downcase".

If you have a variable "ending" now you can't write "end" because autocomplete knows only "ending" word. Is it lack of dictionary words or something else?

**Comment by purcell** [comment]
> I'm not sure where to start, is it a bug of this .emacs.d repo or ruby-mode repo.

There is no `ruby-mode` repo: `ruby-mode` is now built into Emacs.

With the latest version of Emacs I can't reproduce this issue, so it's quite likely that upgrading your Emacs would help.
