### ISSUE TITLE
Expression for constant `sanityinc/no-ssl` may not be correct.

### ISSUE THREAD

**Issue by blueabysm** [purcell/emacs.d#506]
In the file [lisp/init-elpa.el:L32-L33](https://github.com/purcell/emacs.d/blob/12755e44a1965ef7bb78efc386a7b86e72cd521d/lisp/init-elpa.el#L32-L33).

``` emacs-lisp
(defconst sanityinc/no-ssl (and (memq system-type '(windows-nt ms-dos))
                                (not (gnutls-available-p))))
```
This snippet tells us that **only if** the current operating system is Windows **and** the gnutls is not available, the constant `sanityinc/no-ssl` would be filled with `t`. In other cases it is always `nil`. May it be incorrect?

According to [this document](https://www.gnu.org/software/emacs/manual/html_node/emacs-gnutls/Help-For-Users.html),  `gnutls-available-p` may return `nil` sometimes even if one has installed openssl properly. (Actually this is what happens to me using emacs on **macOS 10.13** with gnutls installed. For some reasons I cannot always establish a connection to melpa.org:443 or elpa.gnu.org:443 by command `gnutls-cli --x509cafile nil -p 443 <domain>`. When it fails to connect through SSL, I evaluate `gnutls-available-p` and get a `nil`, but I'm still forced to use https and get stuck.)

Do we need to ensure that `sanityinc/no-ssl` only affects on Windows? (I personally remove `system-type` checking, it seems fine.🙂)

Thanks!

**Comment by blueabysm** [comment]
I personally remove `system-type` checking, seems works fine to me. 🙂
```emacs-lisp
(defconst sanityinc/no-ssl (not (gnutls-available-p)))
```

**Comment by ReimuXMX** [comment]
Yep... I also encountered this situation in the **macOS 10.13**.

However, I personally prefer to use SSL / TLS at any time for any connection to ensure security.


> "If you don't want to support SSL / TLS, please get out!"

I said so to my subordinates.

Please forgive my offense and poor English.

**Comment by purcell** [comment]
Thanks! I want to disable SSL in the fewest possible circumstances, so the expression is correct, and only works around certain issues with Emacs on Windows. In this case, the expression alerted you to the fact that your installation is broken, and the best response IMO  would be to fix it rather than work around it. :-)

**Comment by blueabysm** [comment]
@purcell Thanks for your reply!

It's weird that I do have command `gnutls-cli` (version 3.4.14, 3.5.15 and 3.5.16(currently the linked one)) properly installed by homebrew, but `brew info emacs` tells me that gnutls is missing as an optional dependency of emacs.

Running command
```shell
gnutls-cli --x509cafile nil -p 443 melpa.org
```
 gives me a fatal error in certificate (if not timeout in fortunate), while
```shell
HTTPS_PROXY=http://localhost:1087 curl --verbose https://melpa.org
```
works fine. 

That's why I consider it as a network problem. (seems that gnutls-cli do not support proxy)

Paste the output of my `*Messages*` after a long stuck when I pressed `r` to refresh `*Packages*`.

```
Opening TLS connection to ‘melpa.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘melpa.org’...done
Opening TLS connection to ‘elpa.gnu.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 elpa.gnu.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect elpa.gnu.org:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘elpa.gnu.org’...done
Package refresh done
4 packages can be upgraded; type ‘U’ to mark them for upgrading.
```
Hope these helpful.

@ReimuXMX Stop being offensive before you know everything about someone.

**Comment by blueabysm** [comment]
`--with-gnutls` does matter...

I've reinstalled my emacs by
```shell
brew reinstall emacs --with-cocoa --with-gnutls
```
and evaluated
```emacs lisp
(gnutls-available-p)
```
and got no longer `nil` but
```emacs lisp
(macs AEAD-ciphers ciphers digests gnutls3)
```

But I am still not able to establish a stable SSL connection to melpa.org:443 or elpa.gnu.org:443, even if `(gnutls-available-p)` is non-nil.

**Comment by purcell** [comment]
Yeah, I really haven't found a reliable way to determine if SSL connections will work, other than by actually trying to make them. The check with `gnutls-available-p` was what seemed to work for some people on Windows who definitely could not make SSL connections, and I incorporated it only to reduce the number of questions. So I'm not sure if there's a general solution.

I get the same response from `(gnutls-available-p)` as you, on a Mac, and my SSL connections work fine. Emacs actually falls back (or even prefers?) the `openssl` command in some cases: `(executable-find "openssl")` returns `"/usr/bin/openssl"` for me. If you've got a different version on your path then that could be a problem.

**Comment by blueabysm** [comment]
Agree with you that there may not be a general solution, so I made a switch to manually enable/disable SSL among different network environments. Anyway, thanks for your replies!
