### ISSUE TITLE
Python Inconsistent hierarchy - Try installing a more recent version of python-pylint

### ISSUE THREAD

**Issue by sshaginyan** [purcell/emacs.d#511]
I get this error message when in Python mode.

![screen shot 2017-11-01 at 10 46 19 pm](https://user-images.githubusercontent.com/325014/32311710-4ca2b420-bf57-11e7-91f1-6e271c19c988.png)

Environment 
macOS High Sierra version 10.13
emacs 25.3

I have the latest version of the repo 83525d66fa195901e8881a62ffb485d212a39bed
I've also updated all my third party packages.

![screen shot 2017-11-01 at 10 56 56 pm](https://user-images.githubusercontent.com/325014/32311854-0be9a190-bf58-11e7-8fdf-8247974b92f4.png)

Same thing happens in Ubuntu.

**Comment by purcell** [comment]
This is an anaconda issue, not specific to this config, so you might like to ask the anaconda maintainer. My guess, though, is that the `anaconda` on your Python path is the wrong version to work with your code, python version, or anaconda.el.
