### ISSUE TITLE
Ask to select coding system when exit from Emacs

### ISSUE THREAD

**Issue by ZhuJiayou** [purcell/emacs.d#516]
I use your configs in Windows10, GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-27.

Every time I try to exit from Emacs, it will ask me to select coding system.
No metter which I select or how I set, it's always there. Like this:

![prb](https://user-images.githubusercontent.com/32535222/32951612-78acd060-cbe5-11e7-84cb-bed0f63f8735.PNG)

Do you know Why and How to do with it??
(Emacs can be closed, but it's annoying.)

**Comment by purcell** [comment]
Do you know which file it's trying to save at that point?

**Comment by ZhuJiayou** [comment]
Yeah, it's trying to save "/.emacs.d/recentf" which is always generated automately.

And here is it's contents:

_;;; Automatically generated by ‘recentf’ on Sat Nov 18 13:33:15 2017._

_(setq recentf-list_
      _'(_
        _"d:/Programs/Emacs/.emacs.d/recentf"_
        _))_

_(setq recentf-filter-changer-current 'nil)_

-------------------------------------------------------------------------------------------------------------------------

_;; Local Variables:_
_;; coding: utf-8-emacs_
_;; End:_

**Comment by purcell** [comment]
That's strange. I've never seen that error before, and don't know how to fix it, sorry. I'd be surprised if it's a direct result of this configuration. I don't have access to a Windows system on which to test it, but if you figure out how to avoid the problem, let me know. :-)

**Comment by emuio** [comment]
Hi @ZhuJiayou ,Try to run this code and exit the Emacs.

    (setq session-save-file-coding-system 'utf-8)

Maybe you have the same problem like me.

**Comment by ZhuJiayou** [comment]
@emuio Thank you very much kind sir :) Works fantastically.

**Comment by purcell** [comment]
I committed a change to make this the default: ba7d2a1
