### ISSUE TITLE
org-babel-clojure

### ISSUE THREAD

**Issue by perchard** [purcell/emacs.d#518]
Thank you for making your configuration publicly available – it's made learning emacs a pleasure.

I'm attempting to use [org-babel-clojure](http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-clojure.html) to evaluate clojure code in org-mode documents. Per the org-babel-clojure docs I've added, to `init-local.el`:

    (require 'ob-clojure)
    (setq org-babel-clojure-backend 'cider)
    (provide 'init-local)

I also tried setting `org-babel-clojure-backend` in `init-preload-local.el`, in case it had to be set before requiring cider (it made no difference).

I can start a REPL from an org file and can evaluate code in that REPL. However when I attempt to evaluate a code block in the org file I launched the REPL from, the minibuffer reads 'Not connected'.

I note [support for other languages via babel](https://github.com/purcell/emacs.d/blob/52009a1b96ab5dc41d65d863b761159afea539d7/lisp/init-org.el#L367) in `init-org.el`, however clojure is absent. So, I was wondering – is this a known issue?

**Comment by perchard** [comment]
To follow up on this, for anyone else who might encounter this issue –

I solved by [upgrading org-mode to the latest development version](http://orgmode.org/worg/org-faq.html#keeping-current-with-Org-mode-development) which is currently 9.1.3. Version 8.2.10 was installed by default.

**Comment by purcell** [comment]
Great, thanks for following up.
