### ISSUE TITLE
Dired-goto-file command not working as intended

### ISSUE THREAD

**Issue by JiaHong-Lee** [purcell/emacs.d#519]
Dear Sir,

The dired-goto-file function (bound to 'j' in dired mode) does not open the file specified inside a subdirectory. 

Intuitively, I would want it to open the file, or at least direct me to its location. As shown in the following gif, at the end of the command, my cursor position remains unchanged with a message "Mark set" returned in the buffer.

![emacs_dired-goto-file](https://user-images.githubusercontent.com/24759194/33184707-e2051d92-d0b8-11e7-940a-ccb6f6d27010.gif)
(Trying to goto a file called "bar" in a subdirectory called "test1")
&nbsp;
Is this an intended behaviour, or is it a bug? 

Thank you for your time!

My environment: GNU Emacs 25.1.1 running on Ubuntu 16.04.3 LTS.

**Comment by purcell** [comment]
Not sure, sorry - I don't use that command myself, and that is a core Emacs function which I have not modified in this config.

**Comment by JiaHong-Lee** [comment]
@purcell 
I see, thank you for your reply!
