### ISSUE TITLE
Python-mode doesn't work

### ISSUE THREAD

**Issue by ZhuJiayou** [purcell/emacs.d#521]
I use your configs in Windows10, GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-27.

When I type "C-c C-p" to run Python file.
It doesn't work.

And there're some wannings:
*Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally.*

Do you know why?

**Comment by purcell** [comment]
Not sure, sorry, but given the warning you pasted, you should check that `python-shell-interpreter` contains the name of a Python interpreter that you can run, and that the `readline` library is available in it.
