### ISSUE TITLE
nxml not closing tags

### ISSUE THREAD

**Issue by gasparfm** [purcell/emacs.d#525]
When creating a new XML file and trying to automatically close a tag on </ it isn't working as spected.

I've modified init-nxml.el and put (setq nxml-slash-auto-complete-flag t) inside add-hook:

(add-hook 'nxml-mode-hook (lambda ()
                            (set (make-local-variable 'ido-use-filename-at-point) nil))
                            (setq nxml-slash-auto-complete-flag t))

**Comment by purcell** [comment]
Works for me without this change. Can you provide steps to reproduce?
