### ISSUE TITLE
Debian Emacs25.3.1: could not create connection to elpa and melpa

### ISSUE THREAD

**Issue by limTeTE** [purcell/emacs.d#527]
Hi, Steve. I find my emacs cannot connect to melpa and elpa.
```lisp
Could not create connection to elpa.gnu.org: 443
Could not create connection to melpa.org: 443
```
But it's not a problem when i `sudo` it. Maybe there is something that i messed up. 
So, how can I check the connection and fix it. 
Thank you ~

**Comment by limTeTE** [comment]
Ah, also i find on Win10, Emacs just use `melpa.org:80`, what's the difference?
addition to the issue above, **linux server can connect to internet**, it's not a problem of internet connection.

**Comment by limTeTE** [comment]
After checking by `./test-startup.sh` in `~/.emacs.d` offered by Steve, i find out that my **GnuTLS** is broken. `sudo apt-get install gnutls-bin` solves this problem on Debian and Ubuntu.

**Comment by purcell** [comment]
Great, glad you figured it out, and thanks for noting the solution here.
