### ISSUE TITLE
Inexplicable ~/.insert-shebang.log

### ISSUE THREAD

**Issue by ReimuXMX** [purcell/emacs.d#532]
Hello, and sorry for my poor English.

I don't know when to start, in my home directory will automatically generate an empty file: `.insert-shebang.log`.
This file appears after loading your configuration for the first time. After I manually delete it, it no longer appears. But after re-installation will appear again.

I didn't manually install `insert-shebang`.

I currently only know so much, if there is any need to add information, please point out.

Thank you.

**Comment by purcell** [comment]
Yeah, I googled this for you, and perhaps you've installed [this package](https://github.com/syl20bnr/insert-shebang) - it's not included by any part of my config.

**Comment by ReimuXMX** [comment]
Sorry for my stupidity......

The Emacs distribution I'm currently installing "cleverly" includes `insert-shebang`

It's in my `/usr/share/emacs/25.3/site-lisp/insert-shebang/`......

Thank you for your reply.
