### ISSUE TITLE
sml-mode can't work

### ISSUE THREAD

**Issue by lastchiliarch** [purcell/emacs.d#533]
Hi, I had installed sml-mode but it didn't work after I swith to your emcas configure.

sml-mode seems not installed or wasn't actived.
I opend an sml file, the major mode was funamental instead of sml.

sml-mode was worked well when I used  ~/.emacs .
~/.emacs content:

(add-to-list 'load-path "~/.emacs.d/color-theme/")
(put 'upcase-region 'disabled nil)
                                        ;(require 'color-theme)
                                        ;(color-theme-initialize)
                                        ;(color-theme-matrix)
(setenv "PATH" (concat "/usr/local/smlnj/bin:" (getenv "PATH")))
(setq exec-path (cons "/usr/local/smlnj/bin"  exec-path))

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

(package-initialize)

  (setq package-archives
        '(("melpa" . "https://melpa.org/packages/")) )

What Can I do to fix this?

**Comment by purcell** [comment]
I don't provide any `sml` support. You can install the necessary packages, though. You might like to add something like `(require-package 'sml-mode)` to your `init-local.el` file -- follow the instructions in the README to create that file.

**Comment by lastchiliarch** [comment]
Thanks a lot.
 I followed your advice but it seems conflicted with init-sessions. After I commentd init-sessions, sml-mode works.
