### ISSUE TITLE
can't not complete in slime

### ISSUE THREAD

**Issue by duanqd** [purcell/emacs.d#538]
when I'm  in an empty `emacs-lisp-mode`, `slime` and `eshell`, it seems that company does not work . The error message is shown below:

```el
Company: An error occurred in auto-begin
Company: backend company-nixos-options error "Wrong type argument: stringp, nil" with args (prefix)

**Comment by E-Neo** [comment]
I have similiar problems :
GNU Emacs 25.3.1 (Archlinux)
![screenshot](https://user-images.githubusercontent.com/11346327/35280682-dde1516a-008b-11e8-91c0-7668f3388e7e.png)

**Comment by duanqd** [comment]
I will close this cause I just disable `nix-mode`(ie. init-nix)  in `init.el`.

**Comment by purcell** [comment]
This is an upstream bug for which I've submitted a fix, but I'll work around it locally in my config too.

https://github.com/travisbhartwell/nix-emacs/pull/46
