### ISSUE TITLE
Package 'project-local-variables-' is unavailable

### ISSUE THREAD

**Issue by andybao** [purcell/emacs.d#540]
Hi Purcell and all,

System: macOS Sierra (10.12.6)
Emacs version: 25.3, 24.4

Following error popup when emacs run this config file first time.
error: Package 'project-local-variables-' is unavailable

I guess it may because melpa removed all emacswiki packages.

Thanks for any suggestion and help.
BR
Andy Bao

**Comment by re-mx** [comment]
See melpa/melpa#5260
And melpa/melpa#5008
