### ISSUE TITLE
Why don't you use web-mode instead of sgml-mode?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#541]
Hello: 
I am sorry for asking you some silly questions again.

But I really didn't understand why you don't use [web-mode](https://github.com/fxbois/web-mode). The current HTML scheme is very hard to use for mixed files of HTML, CSS and JavaScript.

Sorry for taking your time.

Thank you.

**Comment by purcell** [comment]
I don't like many of the design choices in `web-mode`, sorry, including that it would require substantial additions to my themes because it hard-codes so many new faces of its own. I'd rather use something that's simpler, but I understand that `sgml-mode` might not suit everyone.

**Comment by re-mx** [comment]
Thank you for your reply.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
how does it implement the code folding in this mode?

**Comment by re-mx** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut 

See this: https://github.com/purcell/emacs.d/blob/master/lisp/init-folding.el

**Comment by purcell** [comment]
> See this: https://github.com/purcell/emacs.d/blob/master/lisp/init-folding.el

Yep, which is funny, because I pretty much consider code folding evil, and I never actually use it myself outside org-mode. :-)

**Comment by re-mx** [comment]
Collapsing code is useful in some editors that underline can not scroll……:-)
