### ISSUE TITLE
Warning: Cannot find nixos option file.

### ISSUE THREAD

**Issue by getong** [purcell/emacs.d#542]
emacs start for a long time and hold a white board, until I type something on it and then it starts to open files.
My OS is Debian. Don't know why.

**Comment by purcell** [comment]
That's annoying, sorry. Probably related to https://github.com/travisbhartwell/nix-emacs/pull/39, and I've submitted further fixes in https://github.com/travisbhartwell/nix-emacs/pull/46. Maybe I'll disable the nix stuff for now.

**Comment by getong** [comment]
Thanks.
