### ISSUE TITLE
Python execute buffer error

### ISSUE THREAD

**Issue by MSaadiSalem** [purcell/emacs.d#543]
When I am trying to execute the python buffer, I am facing this error. 

> Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
>   count-lines(1 nil)
>   py-execute-base(nil nil nil "/path/to/python/file/test.py")
>   py-execute-file("/path/to/python/file/test.py")
>   py-execute-buffer-base()
>   py-execute-buffer()
>   funcall-interactively(py-execute-buffer)
>   call-interactively(py-execute-buffer nil nil)
>   command-execute(py-execute-buffer)

py-submit-bug-report:

> Debugger entered--Lisp error: (wrong-type-argument commandp py-submit-bug-report)
>   call-interactively(py-submit-bug-report nil nil)
>   command-execute(py-submit-bug-report)

**Comment by purcell** [comment]
The "py-execute-buffer" command you're apparently running is not part of my config, so it's not something I can provide support for, sorry.
