### ISSUE TITLE
The question about sharp quote

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#545]
Hello:

Why do you just use the sharp quote (#') for `sanityinc/no-trailing-whitespace` here?
https://github.com/purcell/emacs.d/blob/76e2147b4e0c4e7e33e72ba189f48894f4b24283/lisp/init-whitespace.el#L11-L19

I saw that you didn't use sharp quote elsewhere for this function.
So I am a little puzzled.

I'm sorry for taking your time.
Thank you very much!

**Comment by purcell** [comment]
I went through a spell of using `#'` instead of `'`, but there's not really much difference, so mostly I've reverted to simply using `'`. So you may find some inconsistencies like this. :-)

**Comment by re-mx** [comment]
Thank you for your reply!

Well ... I've also experienced ... and it's my obsessive-compulsive disorder......

I only follow the original author of package now, 
I only handle the issue according to their method.
Otherwise my obsessive-compulsive disorder will not cure ...

**Comment by re-mx** [comment]
Well......

This is my problem, I believe I can not cure it

I always want to format all my code in **one** way. For me, practicality is not the first thing to consider....

I will continue to do these meaningless formatting work. 
I file this issue just to confirm this sharp quote is not a special role.

Sorry for taking up your time.

**Comment by purcell** [comment]
> I always want to format all my code in one way.

Emacs Lisp really needs something like `gofmt`/`elm-format`/`hindent`... :-)
