### ISSUE TITLE
M-/ completion does not do anything, how to re-enable

### ISSUE THREAD

**Issue by yrdeboer** [purcell/emacs.d#546]
Hi, first of all many thanks for providing this emacs settings.
I have tried it and you did a much better job than I ever did, I never got the python IDE to work fully right.

There is a word-completion feature in the "bare" emacs that suggests completions of words from words it has already seen during the session, using M-/

I was wondering if you knew how to re-enable that because in your setup the M-/ completion does not do anything.

Kind regards.

**Comment by yrdeboer** [comment]
Looks like I'm talking about "dabbrev-expand".
https://www.gnu.org/software/emacs/manual/html_node/emacs/Dynamic-Abbrevs.html

**Comment by purcell** [comment]
Yep, this is a slight frustration for me too - I used to use `M-/` for `hippie-expand`, which is a built-in completion facility very similar to `dabbrev`.

Eventually I re-bound that key to `company`, but `company`'s behaviour in this regard often isn't helpful. `company` has a list of enabled completion backends, including the `company-dabbrev` backend, but it stops with the first backend that returns a prefix.

In practice, then, when you're completing a word that *might* be a code symbol, the `company-capf` backend might say "Yes, I found a symbol I can complete", then it returns no completions when asked. And `company` stops there, without falling back to the `company-dabbrev` backend. I can see why this might be the way it is, and perhaps @dgutov has comments regarding this, but in the meantime, the only alternative is to bind a separate key to either `hippie-expand` or to a wrapper command for `company-complete` that `let`-binds `company-backends` to `'(company-dabbrev)`.

**Comment by yrdeboer** [comment]
I see, thanks.
I now bount M-- to dabbrev and already am used to it :)

**Comment by dgutov** [comment]
> I can see why this might be the way it is, and perhaps @dgutov has comments regarding this

I've answered this many times in the issue tracker. The idea is to avoid false positives. Of course, sometimes users want *some* completions anyway. `M-x company-other-backend` can help with that.

Try binding it to `M-/`, maybe. The trick is to only press it until you see the list of completions you like.

**Comment by purcell** [comment]
> I've answered this many times in the issue tracker. The idea is to avoid false positives. Of course, sometimes users want some completions anyway. M-x company-other-backend can help with that.
> 
> Try binding it to M-/, maybe. The trick is to only press it until you see the list of completions you like.

Thanks @dgutov - I didn't make the connection that `company-other-backend` can be used interactively. Makes sense! I'm trying out [binding M-/ to that command in `company-active-map`](https://github.com/purcell/emacs.d/commit/39ac083d1586207d49c06fa622e4e776de6c6a5d).

**Comment by dgutov** [comment]
Actually, I figured you might use it for the global binding, and bind `M-/` to something else in the "active" map. Otherwise, the result is too different from `hippie-expand`.

Up to you, of course. This config can also be helpful.
