### ISSUE TITLE
how to change the setq variable between two major mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#548]
for instance:
```
(setq 'abc t)   ;; in a mode
(setq 'abc nil) ;; in b mode
```

**Comment by beacoder** [comment]
(after-load 'a
  (setq 'abc t))   ;; in a mode

(after-load 'b
  (setq 'abc nil))   ;; in b mode

FYI:

(if (fboundp 'with-eval-after-load)
    (defalias 'after-load 'with-eval-after-load)
  (defmacro after-load (feature &rest body)
    "After FEATURE is loaded, evaluate BODY."
    (declare (indent defun))
    `(eval-after-load ,feature
       '(progn ,@body))))

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Having tied this scheme, the `'abc` seemed not automatically change except you manually enable the major mode

**Comment by beacoder** [comment]
Then how about this one.

(add-hook 'a-mode-hook
  (lambda () (setq 'abc t)))  ;; in a mode

(add-hook 'b-mode-hook
  (lambda () (setq 'abc nil)))  ;; in b mode

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
I think this is the same as above, let me have a try

**Comment by beacoder** [comment]
not sure what your use case is.
maybe you could try to make 'abs as buffer-local variable.
(make-local-variable 'abc)

then for different buffer with different major mode.
you could use either after-load or mode-hook to customize it.

**Comment by dcorking** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut  How are you changing modes? Is `abc` a buffer local variable (or file local / dir local / global ) ?  

I don't think that this question is specific to `emacs.d`. My apologies if you know this already but for the benefit of others with similar questions:
1. You might want to test your code with a clean Emacs (start with `emacs -q` )
2. You might get better support at other Emacs support channels (see 'Where to get help from people' at https://www.emacswiki.org/emacs/GetHelp )

**Comment by dcorking** [comment]
This might help: https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html#Buffer_002dLocal-Variables

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Sorry for lately response, the case for me is
```
'abc in c mode
c is a minor mode hooked with a mode and b mode
```

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the buffer-local should not be the answer
can be setq use in 'auto-mode-alist method
