### ISSUE TITLE
the strange return-and-indent behavior

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#549]
the position of cursor is changed when toggle `evil-mode` state
```
<div>|
</div>

<div>        ;; use evil-mode `o` operation (return and auto indent)
  |
</div>

<div>        ;; back to normal mode
|
</div>
```

**Comment by dcorking** [comment]
purcell/emacs.d does not include [`evil`](https://melpa.org/#/evil) ([He doesn't use it.](https://github.com/purcell/emacs.d/issues/251#issuecomment-73774527))

According to [their README](https://github.com/emacs-evil/evil/blob/master/README.md) evil has a mailing list and an IRC channel.

**Comment by purcell** [comment]
Yep, I don't really have any suggestions here, sorry.
