### ISSUE TITLE
Emacs25.3.1 "cannot connect to orgmode.org:443"

### ISSUE THREAD

**Issue by limTeTE** [purcell/emacs.d#551]
Hi, Steve.
I'm using Emacs25.3.1 on Debian9.3, and met question like this:
```
Debugger entered--Lisp error: (error "Could not create connection to orgmode.org:443")
signal(error ("Could not create connection to orgmode.org:443"))
```
No idea for what this is and any advice is appreciated~

**Comment by limTeTE** [comment]
and this is the result got by './test-startup.sh':

```
Opening TLS connection to ‘orgmode.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 orgmode.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 orgmode.org’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 orgmode.org --protocols ssl3’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 orgmode.org --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect orgmode.org:443 -no_ssl2 -ign_eof’...
Opening TLS connection with ‘openssl s_client -connect orgmode.org:443 -no_ssl2 -ign_eof’...failed
Opening TLS connection to ‘orgmode.org’...failed
Debugger entered--Lisp error: (error "Could not create connection to orgmode.org:443")

```

**Comment by purcell** [comment]
Your Emacs does not appear to be compiled with support for SSL, or have access to a command line program it could use to perform SSL network requests. Otherwise, it's possible you're affected by a firewall or proxy which is preventing you from connecting to orgmode.org.

**Comment by limTeTE** [comment]
i check it and it's the firewall preventing the connection. Can i install the .emacs.d configuration offline, like copying from other computer which has installed the .emacs.d to my target pc?

**Comment by purcell** [comment]
Yes, that should work - once all the packages are installed, you can just copy over the `.emacs.d` directory and it should start up fine on another computer.

**Comment by limTeTE** [comment]
I'll try that, thank you very much~

2018-03-11 9:48 GMT+08:00 Steve Purcell <notifications@github.com>:
