### ISSUE TITLE
Restore default Ivy completion style

### ISSUE THREAD

**Issue by masolino** [purcell/emacs.d#553]
https://github.com/purcell/emacs.d/blob/86adc49d280633d2e83e52e1e9c302ecbeac3666/lisp/init-ivy.el#L25

Hi, I'm trying to restore default [Ivy completion style](http://oremacs.com/swiper/#completion-styles)
`(setq ivy-re-builders-alist
      '((t . ivy--regex-plus)))`

Or disable `sanityinc/enable-ivy-flx-matching`

How can I do?
Thanks

**Comment by purcell** [comment]
I didn't really build that to be a toggle, so your options are:
- Don't call `sanityinc/enable-ivy-flx-matching`
- Restart Emacs. :-)
- Use `(setq-default ivy-re-builders-alist '((t . ivy--regex-plus)))` <- note the `setq-default`
