### ISSUE TITLE
Company-quickhelp is not available in this emacs version or frame

### ISSUE THREAD

**Issue by louiszgm** [purcell/emacs.d#554]
**Emacs Version: 25.3.1**

When i type something, and toggle the quickhelp window. 

I got the error below.
I have tried rm **.emacs.d**,and clone againe. And it still happen
```
Debugger entered--Lisp error: (error "company-quickhelp is not available in this emacs version or frame")
  signal(error ("company-quickhelp is not available in this emacs version or frame"))
  error("company-quickhelp is not available in this emacs version or frame")
  company-quickhelp--show()
  apply(company-quickhelp--show nil)
  timer-event-handler([t 0 0 500000 nil company-quickhelp--show nil idle 0])

```

**Comment by purcell** [comment]
What platform are you on, and is the Emacs you're using built with support for a graphical frontend?

**Comment by louiszgm** [comment]
It is GNU Emacs, I started it by `-nw`
I'm on **macOs High Sierra 10.13.3**

**Comment by purcell** [comment]
I took a look, and this is an upstream issue for which I've submitted a PR here: https://github.com/expez/company-quickhelp/pull/82
