### ISSUE TITLE
slime-repl?

### ISSUE THREAD

**Issue by jhsygg** [purcell/emacs.d#556]
File error: Cannot open load file, No such file or directory, slime-repl

**Comment by jhsygg** [comment]
This file: "~/.emacs.d/elpa-25.3/slime-20180308/contrib/slime-repl.el"  exist!

**Comment by dcorking** [comment]
Can you post a debugger stacktrace? I can't reproduce this on my machine.

Your filename differs from mine, which is:

    ~/.emacs.d/elpa-25.3/slime-20180308.733/contrib/slime-repl.el

(note the `.733` on my machine)

As a stab in the dark, it would probably do no harm to uninstall and reinstall slime.

**Comment by jhsygg** [comment]
yes my filename is 
~/.emacs.d/elpa-25.3/slime-20180308.733/contrib/slime-repl.el

**Comment by dcorking** [comment]
Does it work yet? If not uninstall and reinstall and post a stack trace.

**Comment by jhsygg** [comment]
Thank you, it does not works. 
Does not have "~/.emacs.d/elpa-25.3/slime-20180308.733/contrib/"  in my "load-path" variable.

**Comment by dcorking** [comment]
for backtrace `M-x toggle-debug-on-error`

**Comment by jhsygg** [comment]
Cannot open load file: No such file or directory, slime-repl

**Comment by purcell** [comment]
Please provide steps to reproduce. This is not yet an actionable bug report, sorry.

**Comment by jhsygg** [comment]
Thank you,  The steps:
fedora27, 1. sudo dnf install -y emacs
                2. git clone https://github.com/purcell/emacs.d.git ~/.emacs.d
                3. from Terminal run emacs ... Done
                4. restart emacs, than M-x package-refresh-contents, restart emacs ...

**Comment by purcell** [comment]
Why would that trigger anything to do with `slime`? Is there another step which involves running something specific to common lisp?
