### ISSUE TITLE
Adding "pyvenv" breaks autocompletion for python

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#561]
With an unmodified git clone, python autocompletion works fine. However because I'm using `pipenv`, I wanted to be able to switch virtual environments. So I created an init-local.el file into which I put `(request-package 'pyvenv)`, to give me access to the `pyvenv-workon` command.

After restarting, when I visit any python module, I don't get autocompletion at all

**Comment by purcell** [comment]
Sorry to hear that, but I don't work with Python much these days, and because I'm incredibly busy in recent months I haven't time to reproduce your config and figure out what's going on.
