### ISSUE TITLE
minimap or sublimity ?

### ISSUE THREAD

**Issue by azzamsa** [purcell/emacs.d#562]
I personally have strong visual memory. So when I lost in long source code files, looking to minimap help me a lot where to scroll.

I see you did not use this techniques. I don't find any minimap / sublimity config here.

So. How did you figure it out : 
- find where you are in large source code file / latex essay ?
- visualize where your position is ?

Do you only rely on modeline information or anything else ? 

Thank you very much :)

**Comment by dcorking** [comment]
For me: 
a. my team usually keeps files short 😄 
b. `M-x global-linum-mode`
c. find-definition tools (typically bound to `M-.`)

Minimap is very nice and configuration is optional, though I am not sure I like sacrificing that much screen area. purcell's mileage may vary

**Comment by purcell** [comment]
I agree completely with @dcorking's three points here, which I also follow.

Believe it or not, `nyan-mode` helps me with this, together with the new Emacs 26 line numbering. So I have the following in my `init-local.el`:

```el
(when (fboundp 'display-line-numbers-mode)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode))

(when (maybe-require-package 'nyan-mode)
  (setq-default nyan-animate-nyancat t
                nyan-wavy-trail t)
  (add-hook 'after-init-hook 'nyan-mode))
```

**Comment by purcell** [comment]
(They're a bit opinionated, so even though this is my personal config, I haven't made the above part of the published version.)

**Comment by azzamsa** [comment]
> new Emacs 26 line numbering.

I think from now I have to enable 'watching' in emacs github miror :). I don't know any new improvement. I still use Emacs 25 in Debian and linum-mode.

> Emacs now supports optional display of line numbers in the buffer.
This is similar to what 'linum-mode' provides, but much faster and
doesn't usurp the display margin for the line numbers [Emacs 26 News](https://github.com/emacs-mirror/emacs/blob/ff49d86b6419f88205ff9a5d8b1cc46fcda8371c/etc/NEWS#L493)

> Believe it or not, nyan-mode helps me with this

This is the first package I installed. Following jekor tutorial. Alright then I will try your workflow.

> I haven't made the above part of the published version.

Sorry, OOT. Do you put this repo on different dir than ~/.emacs.d or do you tell git to ignore certnain lines ?
(For now I put my config under ~/.emacs.d but since I change it often. I dont want mess my git, and make change to published version only when my experience is completed. )

**Comment by purcell** [comment]
> I think from now I have to enable 'watching' in emacs github miror :). I don't know any new improvement. I still use Emacs 25 in Debian and linum-mode.

I'd suggest just reading the release announcements, or related "What's new" blog posts. That's how I typically learn about these things. BTW, `nlinum` is a bit faster than `linum`.


> Sorry, OOT. Do you put this repo on different dir than ~/.emacs.d or do you tell git to ignore certnain lines ?
> (For now I put my config under ~/.emacs.d but since I change it often. I dont want mess my git, and make change to published version only when my experience is completed. )

No, I check this out as `~/.emacs.d`, but I have an `init-local.el` on each machine (work/home) which I do not check in. The README describes how to use that file.

**Comment by azzamsa** [comment]
> I'd suggest just reading the release announcements, or related "What's new" blog posts. That's how I typically learn about these things.

Thank you :). I will follow this path.

> The README describes how to use that file.

Oh thanks. I will adapt this. Thanks :)

Thank you for your contribution to community. (from this issue I also learn that you allocate your time very good. only reply issue in morning and so on, I have to allocate my time too) . Thanks.

**Comment by azzamsa** [comment]
I need to know my current position using analog feedback. Yes, analog feed back is more trusted and convenient at least for me. As described in 'scroll-bar' section by [Steve Yegge](https://sites.google.com/site/steveyegge2/effective-emacs).

I'm *suffering* from this problem for long. Since I disabled line-mode and scroll-bar-mode. [full story here](https://twitter.com/_wilfredh/status/1050155492264296450). Until I find [yascroll-el](https://github.com/m2ym/yascroll-el). Oh my.
