### ISSUE TITLE
org-fstree seems to be removed by Melpa or other elpa repo

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#563]
Hello:

After I re-cloned your repo and started Emacs, I received an exception  by `maybe-require-package`.
Because of my current work, it is forbidden to copy any development information. So can not provide specific information, sorry.

In short, after I refreshed all elpa repos, execute `package-install RET org-fstree`, it shows `package is unavailable`.

Thank you.

**Comment by dcorking** [comment]
I can reproduce something similar (on macOS GNU Emacs 25.3.1) by
1. delete org-fstree with the package manager UI
2. restart Emacs
3. evaluate `(maybe-require-package 'org-fstree)`

messages buffer:
```
Evaluating...
Importing package-keyring.gpg...done
Contacting host: orgmode.org:80
Contacting host: melpa.org:443 [2 times]
Package refresh done
41 packages can be upgraded; type ‘U’ to mark them for upgrading.
Couldn’t install optional package ‘org-fstree’: (error "Package ‘org-fstree-’ is unavailable")
nil
```

The above message is not an error, just a message, so Emacs works normally for me. Do you get an error? If so is there any way you can reproduce it, for example when not at work?

I can't find the package on [MELPA](https://melpa.org/#/org-fstree) or [orgmode.org](https://orgmode.org/elpa.html) so I expect it has been pulled.

I don't use `org-fstree`. If you do then you'll probably have to install it manually: http://www.burtzlaff.de/org-fstree/

**Comment by purcell** [comment]
Yep, we dropped it from MELPA, and I didn't get around to updating my config. Done now, thanks!

**Comment by re-mx** [comment]
Thank you.

And...Would you like to tell me why MELPA dropped `org-fstree` ?

**Comment by re-mx** [comment]
Thank you.

And...Would you like to tell me why MELPA dropped `org-fstree`?

**Comment by dcorking** [comment]
It didn't come from a secure source: https://github.com/melpa/melpa/commit/6824fa8fb5b34bef91fc5c0e1345a976ea53690f

**Comment by re-mx** [comment]
@dcorking Thanks.

And...This seems to be the aftermath of the accident a few months ago...

**Comment by dcorking** [comment]
What accident? (BTW melpa/melpa#3004 was opened in 2015)

**Comment by re-mx** [comment]
Okay, I seem to be wrong...sorry.

**Comment by dcorking** [comment]
Probably OT but please tell me about an accident (email address in my profile).

FWIW apparently org-fstree is considered too crufty to be worth moving to SSL/TLS: https://github.com/melpa/melpa/issues/3004#issuecomment-375910969

**Comment by re-mx** [comment]
@dcorking 
I confused it with melpa/melpa#5008.
