### ISSUE TITLE
Unknown emacs close error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/emacs.d#564]
When I want to close emacs, it prevent with a error message
```
Warning (emacs): recentf mode: Wrong type argument: listp, \.\.\.
```

**Comment by purcell** [comment]
Not sure, sorry. I don't see this.

Sometimes cache files like `~/.recentf` can get corrupted, so one solution is to kill Emacs and delete the cache file.
