### ISSUE TITLE
Theme not applied to every SCSS file

### ISSUE THREAD

**Issue by masolino** [purcell/emacs.d#565]
Hi,
I have this problem with SCSS files: the first loaded file has the theme correctly applied, but not other SCSS files opened later.
Thanks
![emacs](https://user-images.githubusercontent.com/18376/38128738-140dfb50-33fc-11e8-8ae5-50c752887492.jpg)

**Comment by masolino** [comment]
I've updated to Emacs 26 and the problem is gone

**Comment by purcell** [comment]
Indeed, this seems to have been reported upstream as https://github.com/antonj/scss-mode/issues/36, so I'll close this here.

**Comment by purcell** [comment]
See https://github.com/purcell/emacs.d/commit/f1eb10a63c7ff782572d6cb6aa7b43483085531b: if you also remove the installed `scss-mode` package, then everything should work fine.

**Comment by masolino** [comment]
Perfect! Thank you @purcell
