### ISSUE TITLE
"init-windows.el" may be confusing

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#568]
Hello:

I recommended your configuration to many friends and they all said it was very good.

But some people are confused. He thinks that the "init-windows.el" should be about configuration of "Microsoft Windows". I agree with this. Because I also found that not everyone is aware of the concepts in Emacs.

I know that naming is difficult... But I'd like you to tell me why you named this file so.

Thank you very much.

**Comment by purcell** [comment]
Windows is the name Emacs uses for the panes within frames. Yes, it's confusing. I'll add a comment, but I probably won't rename the file.

**Comment by re-mx** [comment]
Thank you.

In fact, I feel that the file called `init-window.el` will be slightly better.
Because the "window" I see in Emacs info is not plural.
