### ISSUE TITLE
Symbol Overlay operations

### ISSUE THREAD

**Issue by masolino** [purcell/emacs.d#569]
https://github.com/purcell/emacs.d/blob/e2e21caab281574700e55013283744ec2bf1b6c7/lisp/init-editing-utils.el#L103-L109

Hi, 

maybe you can consider adding `yaml-mode-hook` to line 104 to use `symbol-overlay` on `yaml` files and `(define-key symbol-overlay-mode-map (kbd "M-i") 'symbol-overlay-put)` to line 110 to [toggle all overlays of symbol at point](https://github.com/wolray/symbol-overlay#usage) and activate the key-bindings defined in `symbol-overlay-map`.

Thanks

**Comment by purcell** [comment]
Done & done - thanks!
