### ISSUE TITLE
supporting lldb

### ISSUE THREAD

**Issue by senhui-guo** [purcell/emacs.d#570]
Hi, I found this [lldb-enhanced el file](https://opensource.apple.com/source/lldb/lldb-76/utils/emacs/) written by Apple, would you care to check it out? Seems okay tho. Thanks.

**Comment by dcorking** [comment]
1. Do you use it in your own form of emacs.d? If so, any tips for integrating it?
2. This is not based on the modern debugging framework in Emacs, so it may be tricky to integrate.

**Comment by purcell** [comment]
Isn't `gud` available elsewhere anyway? It's many years since I used a debugger in Emacs, so this isn't something I'd be keen to integrate in the config, sorry.

**Comment by senhui-guo** [comment]
@dcorking Nope, I loaded this file directly and press M-x lldb to use it, it seemed to work fine.
