### ISSUE TITLE
IRC and Email

### ISSUE THREAD

**Issue by azzamsa** [purcell/emacs.d#571]
Hi.

Sorry for asking. I don't find my question in other issue nor it's mentioned in README that your config only focus for programming.

I don't find email and irc config here.  Do you use IRC client and email client other than emacs ? or you use emacs for both but the config are not published ?

Thank you :)

**Comment by purcell** [comment]
Thanks for asking!

I haven't really used IRC since about 1995, but I have connected occasionally using `erc`, and that didn't really require any configuration.

For mail I mostly use Apple Mail, but I have used GNUS for mailing lists in the past, and every couple of years I try `mu4e` for my email, only to get frustrated. So I have local configurations for both of those packages, but mostly just to configure my particular server and account preferences.

**Comment by azzamsa** [comment]
Thank you so much for the answer. I am really satisfied. You provide the reason and history too. :) 
Thanks.

Sorry. By the way. I am surprised with this 

> I haven't really used IRC since about 1995

Sorry, But how do you keep in touch with other *hackers* (emacs hackers or haskell hackers , etc )? I think they hang up mostly in IRC.

**Comment by purcell** [comment]
> Sorry, But how do you keep in touch with other hackers (emacs hackers or haskell hackers , etc )? I think they hang up mostly in IRC.

They might do, but I don't, and I think there are many more experienced developers who are *not* on IRC than who are.

Many years ago I spent a lot of time on language-specific or technology-specific mailing lists, but I generally find I don't need to ask many direct questions: I find out the solutions to my issues via tool documentation, articles or stackoverflow questions etc. I think always-on chatrooms are not good for focus or productivity.

**Comment by azzamsa** [comment]
> They might do, but I don't, and I think there are many more experienced developers who are not on IRC than who are.

TIL

>  I think always-on chatrooms are not good for focus or productivity.

Great advice. I find this warning too somewhere in article when the first time I set up IRC client.
Sure, I see the time-pattern you answer the issue in github. I belive you have good time management. 

It will be great if you would share it in blog post. Since most time management article don't cover managing time on open source project (managing isssue, mailing list, etc). :)

**Comment by azzamsa** [comment]
>  is that I intensively batch-process a bunch of stuff when I have chunks of time available

Thank you for this advice.

> so it's a familiar habit like reading the news.

Sure. Then I have to build good habits :)

Thanks lot Mr. Purcell. Thanks
