### ISSUE TITLE
group tags issue

### ISSUE THREAD

**Issue by feng823** [purcell/emacs.d#573]
I find that the following group tags is not parsed properly .
```
#+TAGS: [ Control : Context Task ]
#+TAGS: [ Persp : Vision Goal AOF Project ]
```
[ and ] are taken as tags.
Do you know what the problem is?

**Comment by purcell** [comment]
No idea, sorry, but it's also not very clear what you mean. Whatever the case, I expect this is probably an org-mode issue, so I'll go ahead and close this: if you investigate it and discover that it's specific to this configuration, then please re-open the issue.

**Comment by feng823** [comment]
Finally, I find out it is a problem of org-mode. Group tag is  added in version 8.3. But the org-mode I am using is 8.2.10. I think maybe that is the problem.

**Comment by purcell** [comment]
Great, glad you figured it out
