### ISSUE TITLE
sanityinc/pp-xml-region from init-nxml.el not working well

### ISSUE THREAD

**Issue by beacoder** [purcell/emacs.d#574]
"begin" is evaluated before defined, should be "beg" instead.

Fix =>

(defun sanityinc/pp-xml-region (beg end)
  "Pretty format XML markup in region. The function inserts
linebreaks to separate tags that have nothing but whitespace
between them.  It then indents the markup by using nxml's
indentation rules."
  (interactive "r")
  (unless (use-region-p)
    (setq beg (point-min)
          end (point-max)))
  ;; Use markers because our changes will move END
  (setq beg (set-marker (make-marker) beg)
        end (set-marker (make-marker) end))
  (save-excursion
    (goto-char beg)
    (while (search-forward-regexp "\>[ \\t]*\<" end t)
      (backward-char) (insert "\n"))
    (nxml-mode)
    (indent-region beg end)))

**Comment by purcell** [comment]
Fixed, thanks.
