### ISSUE TITLE
can't enable menu-bar-mode

### ISSUE THREAD

**Issue by cppddz** [purcell/emacs.d#577]
when i enable` menu-bar-mode`, I get an error
``Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  undo-tree-current(nil)
  (undo-tree-node-previous (undo-tree-current buffer-undo-tree))
  (and undo-tree-mode (not buffer-read-only) (not (eq t buffer-undo-list)) (undo-tree-node-previous (undo-tree-current buffer-undo-tree)))
  redisplay_internal\ \(C\ function\)()
``
my emacs version : 25.3.1
os: deepin linux 15

**Comment by dcorking** [comment]
I occasionally see a similar error on other functions.

Does this happen on any other functions? If so, as far as I can tell, this sometimes occurs if the desktop file does not save correctly. Quickest repair is:
1. Shut down Emacs
2. Delete the saved desktop (usually $HOME/.emacs.d/.emacs.desktop)
3. Start Emacs

**Comment by purcell** [comment]
I'm not able to reproduce this, sorry, so I'm not really sure how to help.

**Comment by cppddz** [comment]
I found that when commented (require 'init-gui-frames) in the init.el file, I can enable menu-bar-mode.
I checked out to the commit  4e487d4ef2ab39875d96fd413fca3b075faf9612 . On this commit，there is no conflict between menu-bar-mode and undo-tree.
I got this problem on windows7 and linux .
Here is what I do:
I  clone the master branch from github, start emacs ,then type "M-x menu-bar-mode" , then I got this error .

**Comment by haifenghan** [comment]
I have a similar issue. After replacing undo-tree with the latest version 0.6.6, it is fixed.

**Comment by unickuity** [comment]
> I have a similar issue. After replacing undo-tree with the latest version 0.6.6, it is fixed.

This solve the problem for me, thanks
