### ISSUE TITLE
Error "Not inside a list."

### ISSUE THREAD

**Issue by ZhiminPeng** [purcell/emacs.d#578]
When I open a `.py` file, and try to use `meta + }` for paragraph forwarding, I get the following error:

![image](https://user-images.githubusercontent.com/5410393/39562856-a7ceb2be-4e62-11e8-974d-7b62acfd748f.png)

However, for other type of files, `meta + }` works.

**Comment by dcorking** [comment]
Another way to move forward in Python is `end-of-defun` which has several bindings:
` <C-M-end>, C-M-e, ESC <C-end>`. 

The behaviour of `M-}` seems to be a side-effect of [paredit-mode](http://melpa.milkbox.net/#/paredit) or its companion package [paredit-everywhere](http://melpa.milkbox.net/#/paredit-everywhere). See [`init-paredit.el`](https://github.com/purcell/emacs.d/blob/master/lisp/init-paredit.el)

`M-}` is bound to `(paredit-close-curly-and-newline)` in several modes (such as C Ruby Python and Javascript). In other modes (such as Elisp) `M-{` is bound to `forward-paragraph`, the Emacs default.

`(paredit-close-curly-and-newline)` works for me in Ruby and Javascript (though it isn't a function I normally need.) It works for me also in C and Python, but if I invoke it _outside_ a pair of curly braces `{}` then  _in C and Python_ it gives the same backtrace you got:
```
Debugger entered--Lisp error: (error "Not inside a list.")
  signal(error ("Not inside a list."))
  error("Not inside a list.")
  paredit-missing-close()
  paredit-move-past-close-and-reindent(125)
  paredit-move-past-close-and(125 #[nil "\301 \302 \210\203\212\303y\210\304\210Aj\210@c\210))\305 \210\3061(\307 0\202,\210\202-\210\310\311!\207" [comment\.point paredit-find-comment-on-line newline -1 nil lisp-indent-line (scan-error) indent-sexp paredit-blink-paren-match t] 2])
  paredit-move-past-close-and-newline(125)
  paredit-close-curly-and-newline()
  funcall-interactively(paredit-close-curly-and-newline)
  call-interactively(paredit-close-curly-and-newline nil nil)
  command-execute(paredit-close-curly-and-newline)
```

I am not sure if it is best worked around in the config, or by contributing a fix to one of the upstream projects. You might like to rebind `M-{` to `end-of-defun` in python-mode and see how it works for you.

**Comment by purcell** [comment]
Yep, that's because of `paredit-everywhere`, but you're right that this is more likely annoying than helpful in most cases, so I've just removed that binding in `paredit-everywhere`.
