### ISSUE TITLE
elisp: C-J does not work

### ISSUE THREAD

**Issue by sundexian** [purcell/emacs.d#579]
I am learning elisp. I pressed c+j after i entered (+ 1 1). And it just change to the next line without the result 2.  While, if i press c+x c+e, the result  will be showed at echo area.

**Comment by dcorking** [comment]
The paredit package caused this. More detail at https://stackoverflow.com/questions/28566206/emacs-c-j-for-elisp-interaction#28567147

**Comment by dcorking** [comment]
Evaluate this in your elisp buffer:
```elisp
(local-set-key (kbd "C-j") 'eval-print-last-sexp)
```

@purcell how could we hack [`init-paredit.el`](https://github.com/purcell/emacs.d/blob/master/lisp/init-paredit.el) to leave the original `C-j` binding in place in lisp-interaction-mode ?

**Comment by dcorking** [comment]
Easiest solution for learning elisp might be to try `ielm` mode, which is shell-like (return to evaluate).
For example, `M-x ielm`
```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (+ 1 1) ;; press return
2 (#o2, #x2, ?\C-b)
ELISP> 
```

See https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Interaction.html

**Comment by purcell** [comment]
@sundexian It's not clear whether you're talking about IELM or just a regular elisp buffer. Only in IELM would you expect `C-j` at the end of an expression to execute it - is that what you meant?

**Comment by sundexian** [comment]
@purcell  Thank you for your reply. I tried this in the buffer named *scratch*. I'll try to use the IELM mode as you and dcorking said.

**Comment by dcorking** [comment]
@purcell In the scratch buffer of vanilla Emacs, `C-j` evaluates an expression. However paredit replaces this key binding.

**Comment by purcell** [comment]
> In the scratch buffer of vanilla Emacs, C-j evaluates an expression. However paredit replaces this key binding.

Ah - interesting! I didn't know that, probably because I've been a paredit user for such a long time.

**Comment by purcell** [comment]
Since this is a paredit choice, and everyone should use paredit, I'm going to close this issue without changing my config: to change the behaviour yourself, you'd just unbind that key from `paredit-mode-map`.
