### ISSUE TITLE
windows server2012: file-error "Searching for program" "No such file or directory" "python"

### ISSUE THREAD

**Issue by limTeTE** [purcell/emacs.d#582]
Hi, I met this problem on my win 2012server. Information is listed below and sorry for the paste format here:

> Debugger entered--Lisp error: (file-error "Searching for program" "No such file or directory" "python")
  make-process(:name "anaconda-mode" :buffer #<buffer *anaconda-mode*> :command ("python" "-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11"))
  apply(make-process (:name "anaconda-mode" :buffer #<buffer *anaconda-mode*> :command ("python" "-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11")))
  start-process("anaconda-mode" #<buffer *anaconda-mode*> "python" "-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11")
  apply(start-process "anaconda-mode" #<buffer *anaconda-mode*> "python" ("-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11"))
  start-file-process("anaconda-mode" #<buffer *anaconda-mode*> "python" "-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11")
  apply(start-file-process "anaconda-mode" #<buffer *anaconda-mode*> "python" ("-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11"))
  start-pythonic(:process "anaconda-mode" :buffer "*anaconda-mode*" :sentinel #[514 "\301\300#\207" [#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3] anaconda-mode-ensure-directory-sentinel] 6 "\n\n(fn PROCESS EVENT)"] :args ("-c" "\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n" "~/.emacs.d/anaconda-mode/0.1.11"))
  anaconda-mode-ensure-directory(#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3])
  anaconda-mode-start(#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3])
  anaconda-mode-call("eldoc" anaconda-mode-eldoc-callback)
  anaconda-mode-eldoc-function()
  eldoc-print-current-symbol-info()

I use anaconda3 and do not add its path to environemnt var like PATH.
How can i solve this or, at least, shutdown this yelling .

**Comment by limTeTE** [comment]
add to the commet before, I use `M-: exec-path` to check what `$PATH` is used in this windows server, after that i manually add the path of anaconda's python.exe to the `$PATH`, check the Emacs's path again and nothing changed, Backtrace still give this

> Debugger entered--Lisp error: (file-error "Searching for program" "No such file or directory" "python")

**Comment by purcell** [comment]
Thanks for reporting this. It appears due to the code in `pythonic.el`, and I've [filed an issue there](https://github.com/proofit404/pythonic/issues/4) on your behalf. I'll close this one because I can't fix it here. :-)

**Comment by limTeTE** [comment]
Thanks for your help.

**Comment by purcell** [comment]
This has apparently been fixed upstream, so maybe try updating your packages. :-)

**Comment by limTeTE** [comment]
I'll try, thx~
