### ISSUE TITLE
Windows7:: Error on server 

### ISSUE THREAD

**Issue by loveminimal** [purcell/emacs.d#584]
```
Warning (initialization): An error occurred while loading ‘c:/Users/LiuZengXi/AppData/Roaming/.emacs.d/init.el’:

error: The directory ‘~/.emacs.d/server’ is unsafe
```
how???

and after comment it, it's okay.

**Comment by xuchengpeng** [comment]
@loveminimal 
To fix it change the owner of the directory ~/.emacs.d/server:
* from Properties select the Tab “Security”,
* select the button “Advanced”,
* select the Tab “Owner”
* change the owner to your account name

**Comment by purcell** [comment]
Thanks @xuchengpeng - presumably Emacs creates that directory with incorrect ownership. Not sure how I could automatically fix it, or even whether that would be appropriate. So, @loveminimal, I'm going to close this, sorry, but you might consider filing an Emacs bug if you think the default behaviour is incorrect on your platform.
