### ISSUE TITLE
kill-back-to-indentation doesn't work right

### ISSUE THREAD

**Issue by scu2013** [purcell/emacs.d#585]
kill-back-to-indentation in init-editing-utils file doesn't work right for me. It will delete the whole line when I using C-M-<backspace> or M-x kill-back-to-indentation.

**Comment by purcell** [comment]
Weird - it works perfectly for me. Can you provide steps to reproduce, please?

**Comment by scu2013** [comment]
I picked some dot el file in lisp directory for myself in emacs configuration. Function named kill-back-to-indentation is provided by init-editing-utils.
I write hahah[some whitespace], and then invoke this function. It kills the whole line.

Emacs version: GNU Emacs 26.1

**Comment by dcorking** [comment]
Please show us how your line is indented during your test.

**Comment by dcorking** [comment]
Could the docstring be slightly ambiguous. [It says](https://github.com/purcell/emacs.d/blob/1c6eb88d0a03eb6569d127b65dcfa0a23c85c4a6/lisp/init-editing-utils.el#L194) "Kill from point back to the first non-whitespace character on the line".  This could mean (in a left-to-right language like Lisp) _kill back to the leftmost non-whitespace char_ or _kill back to the rightmost non-whitespace char_. It actually kills back to the leftmost. In context with the name of the function it is not ambiguous, but a little tricky to read.

I can't suggest an improvement at the moment: sometimes English is more difficult than code.

**Comment by dcorking** [comment]
In line 4 of the following code, the indentation is column 3 (the letter 'd' is the first non-whitespace character in the line.) So the command kills everything between column 3 and point.
```rb
# a class
class Foo
  # a method
  def bar
  end
end
```
Animation below:
![screencast 2018-06-14 14-59-19](https://user-images.githubusercontent.com/2813357/41416973-0602b1f8-6fe4-11e8-9b86-44294cc18235.gif)

**Comment by scu2013** [comment]
Oh I see. thanks for you help. I misunderstand this function. It works right!

**Comment by purcell** [comment]
Yep, it's perhaps not super clear. This function uses the built-in "back-to-indentation" command, which uses the same "first non-whitespace character on the line" phrase, so I probably copied the wording from there.
