### ISSUE TITLE
First-start is very slow

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#587]
Hello:

The output of compile-log is very slow. Only appears in Emacs 26.1@Arch Linux.

Emacs almost stuck here:

<img width="1280" alt="2018-06-18 8 50 37" src="https://user-images.githubusercontent.com/26828933/41523449-9e2567ca-730c-11e8-91e4-c8a4d5ccc70e.png">
Not present on Mac (Emacs For Mac OS X version).

If you need more information, please let me know.

Thanks.

**Comment by purcell** [comment]
Thanks. It's probably not something I can test or influence, sorry: seems like an Emacs version issue.

**Comment by re-mx** [comment]
Thanks.
