### ISSUE TITLE
How to install package which is not in melpa or other websites

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#588]
I want to install asy-mode which is described in [here](http://asymptote.sourceforge.net/doc/Editing-modes.html).
I find it's not in melpa or other web site emacs can access, therefore, I can't install it automatically by 'list-packages' or similar.

Do you have similar function to install package for this case?

Many thanks

**Comment by dcorking** [comment]
I didn't try `asy-mode` but I think the simplest way to do this is paste the 5 lines of code from [the manual page](http://asymptote.sourceforge.net/doc/Editing-modes.html) into `~/.emacs/lisp/init-local.el` followed by `(provide 'init-local)`. (I like to check my own changes to that file into my personal branch of the git repo.)

Detailed instructions in the README at [Changing themes and adding your own customization](https://github.com/purcell/emacs.d/blob/master/README.md#changing-themes-and-adding-your-own-customization)

**Comment by haifenghan** [comment]
Thanks for your help. @dcorking

**Comment by purcell** [comment]
There's also `M-x package-install-file`.
