### ISSUE TITLE
How to find local file after entering TRAMP mode.

### ISSUE THREAD

**Issue by mbhinder** [purcell/emacs.d#589]
I apologize if this has been asked before. Once I edit a remote file using `ssh:` C-x C-f starts off in the remote `cwd`. This is useful but but the `Find file` dialog does not let me backspace all the way past the `user@remote-host` part so that I can find local files.

As a workaround, I've been switching to the `scratch` buffer and then using C-x C-f but it is kind of slow.

**Comment by purcell** [comment]
Ah, interesting - I hadn't noticed this. That key is bound to `counsel-find-file`, and I don't override its settings, so this is probably an Ivy issue: maybe @abo-abo is aware of this?

**Comment by abo-abo** [comment]
> As a workaround, I've been switching to the scratch buffer and then using C-x C-f but it is kind of slow.

I use either <kbd>~</kbd> or <kbd>//</kbd> in this case. I would say this is the official way of doing it, suggestions for improvement welcome. There's also <kbd>M-o b</kbd>.

**Comment by mbhinder** [comment]
Both `~`  and `//` did the trick, many thanks! @abo-abo
