### ISSUE TITLE
Any interest in replacing require-package with use-package?

### ISSUE THREAD

**Issue by jguenther** [purcell/emacs.d#590]
I've found that `use-package` greatly simplifies a lot of things, and can help to separate package configuration from other customizations. It also has the benefit of handling a lot of the busywork with deferred loading, etc., reducing a lot of repetition and generally making the config more clear.

It'd be quite a big change, but it wouldn't have to all happen at once. I'd be willing to help, as I've already moved a lot of my config to `use-package` and merge conflicts are getting pretty crazy.

**Comment by purcell** [comment]
I've considered this, but it's not currently worth the effort for me (or disruption for the many users).

I also quite like that the code written with `require-package` is quite easy to understand: `use-package` is convenient, but it also wraps up some fundamentals, like `with-eval-after-load`, that Emacs users should understand IMO.

So I'm going to close this, sorry, but might well change things in time.
