### ISSUE TITLE
error: The directory ‘~/.emacs.d/server’ is unsafe

### ISSUE THREAD

**Issue by loveminimal** [purcell/emacs.d#593]
server and coding system have made me so saddly.....

**Comment by dcorking** [comment]
I can't reproduce this error. Also, the `server` directory is not part of this project.

What versions of Emacs and OS are you using?

What are the steps to reproduce this?

**Comment by loveminimal** [comment]
@dcorking 

Firstly, thank you very much. 

And then, The res message like this:
```
Warning (initialization): An error occurred while loading ‘c:/Users/LiuZengXi/AppData/Roaming/.emacs.d/init.el’:

error: ‘c:/Users/LiuZengXi/AppData/Roaming/.emacs.d/server’ is not a safe directory because it is not owned by you (owner = nil (544))

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

and I have commented the code like this:

```
; (require 'server)
; (unless (server-running-p)
;   (server-start))
```
Now，it can work well.

I think it may be caused by Windows system. My system is **Windows 7 Home**.  The error exited in Emacs version 25.3 and 26.x.

To system coding, add the code:

```
;;; Set Unicode.

(set-language-environment 'utf-8)
(set-locale-environment "utf-8")

(setq buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;;(set-default-font "Noto Sans Mono" 11)
;;(set-default-font "Monaco 11")

(set-default-font "Monaco" 11)
(set-fontset-font "fontset-default" 'chinese-gbk "Noto Sans Mono")
```
and now it  can also work well. 

In a word, windows has no efforts on coding.

**Comment by dcorking** [comment]
With those lines commented `emacsclient` won't work.

I think the root cause of the problem is that you (or a tool you use) has created 
`c:/Users/LiuZengXi/AppData/Roaming/.emacs.d/server`
which your Emacs tried to load instead of its built-in server package (which is normally in `emacs/25.3/share/emacs/25.3/lisp/server.elc` wherever you installed Emacs 25.3)
 
Find out why you have the `server` directory and then rename or delete it.

(I don't use Windows very often, but I don't think the cause is either Windows or purcell/emacs.d)

**Comment by loveminimal** [comment]
@dcorking
Without those line commented, `emacsclient` woks well here...
I think the path rules of windows is the problem, and purcell's configuration is running in mac.
There has no other server. Whatever, thank you.

**Comment by dcorking** [comment]
If you still have a problem with coding systems that disappears when you don't use purcell's emacs.d, I suggest you [open a new issue](https://github.com/purcell/emacs.d/issues/new). 

If you still get the same problem when you start emacs with `emacs -q`, or in your own config (such as https://github.com/loveminimal/emacs.d-me) then I suggest you ask on a general Emacs support forum.

I am afraid I know very little about Chinese characters so I probably won't be able to help, but others might.

**Comment by loveminimal** [comment]
> If you still have a problem with coding systems that disappears when you don't use purcell's emacs.d, I suggest you [open a new issue](https://github.com/purcell/emacs.d/issues/new).
> 
> If you still get the same problem when you start emacs with `emacs -q`, or in your own config (such as https://github.com/loveminimal/emacs.d-me) then I suggest you ask on a general Emacs support forum.
> 
> I am afraid I know very little about Chinese characters so I probably won't be able to help, but others might.

Thank you, it has been resolved now.
