### ISSUE TITLE
Symbol's value as variable is void: normal-gc-cons-threshold 

### ISSUE THREAD

**Issue by flyonrails** [purcell/emacs.d#594]
My emacs version is 26.1 . When startup emacs, there is a warning  "Symbol's value as variable is void: normal-gc-cons-threshold ". I think maybe the lambda function can't hold the variable.Below is a test, maybe not correct.
```lisp
(let ((x 10))
    (defun f ()
     	(print "%s" x)))
(f)
```
Thank you.

**Comment by flyonrails** [comment]
```lisp
(let ((normal-gc-cons-threshold (* 20 1024 1024))
      (init-gc-cons-threshold (* 128 1024 1024)))
  (setq gc-cons-threshold init-gc-cons-threshold)
  (add-hook 'after-init-hook
            (lambda () (setq gc-cons-threshold normal-gc-cons-threshold))))
```

**Comment by purcell** [comment]
Weird. This indicates that `lexical-binding` is not set, but it is enabled at the top of the file. So this feels like a bug in that specific Emacs version, and I don't see it locally.
