### ISSUE TITLE
Lisp error: (void-function magit-define-popup)

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [purcell/emacs.d#595]
I'm getting this one since today.

Debugger entered--Lisp error: (void-function magit-define-popup)
  (magit-define-popup docker "Popup for docker." 'docker :man-page "docker" :options '((72 "Host" "--host ")) :actions (cons "Docker" (cons (list 99 "Containers" (docker-utils-set-then-call 'docker-arguments 'docker-containers)) (cons (list 105 "Images" (docker-utils-set-then-call 'docker-arguments 'docker-images)) (cons (list 110 "Networks" (docker-utils-set-then-call 'docker-arguments 'docker-networks)) (cons (list 118 "Volumes" (docker-utils-set-then-call 'docker-arguments 'docker-volumes)) '("Other" (77 "Machines" docker-machines))))))))
  eval-buffer(#<buffer  *load*-494462> nil "/home/s/.emacs.d/elpa-26.1/docker-20180728.1948/docker-autoloads.el" nil t)  ; Reading at buffer position 878
  load-with-code-conversion("/home/s/.emacs.d/elpa-26.1/docker-20180728.1948/docker-autoloads.el" "/home/s/.emacs.d/elpa-26.1/docker-20180728.1948/docker-autoloads.el" nil t)
  load("/home/s/.emacs.d/elpa-26.1/docker-20180728.1948/docker-autoloads" nil t)
  package--activate-autoloads-and-load-path(#s(package-desc :name docker :version (20180728 1948) :summary "Emacs interface to Docker" :reqs ((emacs (24 5)) (dash (2 14 1)) (docker-tramp (0 1)) (magit-popup (2 12 3)) (s (1 12 0)) (tablist (0 70)) (json-mode (1 7 0))) :kind nil :archive nil :dir "/home/s/.emacs.d/elpa-26.1/docker-20180728.1948" :extras ((:url . "https://github.com/Silex/docker.el") (:maintainer "Philippe Vaucher" . "philippe.vaucher@gmail.com") (:authors ("Philippe Vaucher" . "philippe.vaucher@gmail.com")) (:keywords "filename" "convenience")) :signed nil))
  package--load-files-for-activation(#s(package-desc :name docker :version (20180728 1948) :summary "Emacs interface to Docker" :reqs ((emacs (24 5)) (dash (2 14 1)) (docker-tramp (0 1)) (magit-popup (2 12 3)) (s (1 12 0)) (tablist (0 70)) (json-mode (1 7 0))) :kind nil :archive nil :dir "/home/s/.emacs.d/elpa-26.1/docker-20180728.1948" :extras ((:url . "https://github.com/Silex/docker.el") (:maintainer "Philippe Vaucher" . "philippe.vaucher@gmail.com") (:authors ("Philippe Vaucher" . "philippe.vaucher@gmail.com")) (:keywords "filename" "convenience")) :signed nil) nil)
  package-activate-1(#s(package-desc :name docker :version (20180728 1948) :summary "Emacs interface to Docker" :reqs ((emacs (24 5)) (dash (2 14 1)) (docker-tramp (0 1)) (magit-popup (2 12 3)) (s (1 12 0)) (tablist (0 70)) (json-mode (1 7 0))) :kind nil :archive nil :dir "/home/s/.emacs.d/elpa-26.1/docker-20180728.1948" :extras ((:url . "https://github.com/Silex/docker.el") (:maintainer "Philippe Vaucher" . "philippe.vaucher@gmail.com") (:authors ("Philippe Vaucher" . "philippe.vaucher@gmail.com")) (:keywords "filename" "convenience")) :signed nil) nil deps)
  package-activate(docker)
  package-initialize()
  eval-buffer(#<buffer  *load*-248069> nil "/home/s/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 2557
  load-with-code-conversion("/home/s/.emacs.d/lisp/init-elpa.el" "/home/s/.emacs.d/lisp/init-elpa.el" nil t)
  #<subr require>(init-elpa nil nil)
  funcall(#<subr require> init-elpa nil nil)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list 'sanityinc/require-times (list feature require-start-time time) t))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list 'sanityinc/require-times (list feature require-start-time time) t)))))
  (let (ad-return-value) (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (when (and (not already-loaded) (memq feature features)) (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list 'sanityinc/require-times (list feature require-start-time time) t))))) ad-return-value)
  ad-Advice-require(#<subr require> init-elpa)
  apply(ad-Advice-require #<subr require> init-elpa)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/home/s/.emacs.d/init.el" nil t)  ; Reading at buffer position 1592
  load-with-code-conversion("/home/s/.emacs.d/init.el" "/home/s/.emacs.d/init.el" t t)
  load("/home/s/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25be19>)()
  command-line()
  normal-top-level()

**Comment by purcell** [comment]
That's a problem upstream with the autoloads in https://github.com/Silex/docker.el/blob/master/docker.el#L44-L56 - cc @Silex.

**Comment by Silex** [comment]
This should be fixed already by https://github.com/Silex/docker.el/commit/82a35820c69323690a42883086a45ce7a1dbe1fd

I think you can close this, reopen if needed.

**Comment by Silex** [comment]
:wink:
