### ISSUE TITLE
html and css auto completion

### ISSUE THREAD

**Issue by fuzunspm** [purcell/emacs.d#597]
could you please guide me how do i auto complete css names inside html tags and in addition is it possible to do something like this

`div*3 -> 3 x <div></div>`
or
`div.class > <div class=""></div>`

and javascript auto completion is not as perfect as python's. Python's auto-complete is very good where js's so bad it won't complete console.log

**Comment by dcorking** [comment]
Sometimes company-complete ( `M-/`) works for classes in html-mode, but if the class is multi-word snake case, you have to complete each word, which isn't ideal.

Javascript's autocompletion completes snake_case names but I experience the same as you regarding console.log (or any of the browser or Node's built-in identifiers, such as document or browser).

It might be worth (a) digging into [company mode docs](http://company-mode.github.io/) and (b) experimenting with different [third party company backends](https://github.com/company-mode/company-mode/wiki/Third-Party-Packages) and posting your experiences here. For example, if you have an [an HTML language service](https://github.com/Microsoft/vscode-html-languageservice) or  [one JavaScript language service](https://github.com/sourcegraph/javascript-typescript-langserver), or [another](https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio) installed, `company-lsp` might give you useful completions.

The configuration is in [emacs.d/lisp/init-company.el](https://github.com/purcell/emacs.d/blob/master/lisp/init-company.el)

**Comment by purcell** [comment]
Yeah, I'm not sure there's a good general-purpose option for javascript completion, since it generally involves hooking into a javascript interpreter, and that might be in a browser or a node.js environment.
