### ISSUE TITLE
Projectile 20180808.833 loses short-cut keys

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#598]
After upgrading to Projectile 20180808.833, all short-cut keys are lost.
I can get quick response here, so the issue is created here.

**Comment by purcell** [comment]
Did you restart Emacs?

**Comment by terlar** [comment]
Could this potentially be related to the recent removal of projectile default keybinding prefix?

https://github.com/bbatsov/projectile/commit/9c6e981

**Comment by haifenghan** [comment]
Thansk @terlar @purcell

Do you know how to select and set prefix key for projectile?

**Comment by terlar** [comment]
```elisp
(setq projectile-keymap-prefix (kbd "C-c C-p"))
```
