### ISSUE TITLE
visual-fill-column does not seem to be installed

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#601]
Hello:

https://github.com/purcell/emacs.d/blob/126202d26c3a3605dba2c3850db61ad1e5886cf1/lisp/init-fonts.el#L11

You mentioned `visual-fill-column` here, but this package seems to have never been installed. 

If this is something you set deliberately, please close this issue.

Thanks.

**Comment by purcell** [comment]
`visual-fill-column` is a package depended on by `writeroom-mode`, which is installed via `init-org.el`.
