### ISSUE TITLE
require-package will not be added to package-selected-packages after first startup

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#603]
Hello:

This problem has existed for two years, at least since I started using your configuration (2017).
I took it out again today because I had trouble with this issue recently.

When the first load is completed, if you call `require-package` in init-local.el, the installed packages will not be logged to `package-selected-packages`. I accidentally pressed the package-autoremove and uninstalled the packages that were installed later.

Thanks, and sorry for my poor English.

**Comment by purcell** [comment]
Yep, I've looked at this before and it's really hard to fix. Ultimately `package-selected-packages` is a misfeature in `package.el`.

**Comment by purcell** [comment]
See https://github.com/purcell/emacs.d/search?q=package-selected-packages&type=Commits for some context.

**Comment by re-mx** [comment]
It might have been designed to resemble autoremove in apt.

Some people will always be obsessive disorder.
Also, if you only consider your current configuration structure. Do you think the `min-version` parameter is still useful now?

**Comment by re-mx** [comment]
This is indeed a wrong design...

**Comment by purcell** [comment]
I think I even filed an emacs bug about it at some point, but I can't remember now.

**Comment by purcell** [comment]
I've committed a workaround in 34dfdd3, but I'm not particularly happy about it.

**Comment by re-mx** [comment]
Indeed... the cost of this workaround is a bit big...

Maybe we can only continue to feed back this bug upstream and look forward to solving it...

I will close this issue first...

**Comment by re-mx** [comment]
Update:

I looked at some other configuration (like `doom-emacs`, `prelude` or `spacemacs` to handle this problem...

They all gave up.
