### ISSUE TITLE
Symbol’s function definition is void: tablist-minor-mode

### ISSUE THREAD

**Issue by NobbZ** [purcell/emacs.d#604]
I use some parts of this config in my own.

Lets say, I have taken the foundation and the structure, but by far not your actual configuration. But I do have a problem with the provided `init-benchmarking`, especially the function `sanityinc/require-times`. When I run it, I do see the error message from the subject, and I am really not sure how to fix that, as I am not sure which package should provide that mode.

Can you help me with that?

On my main system I do use emacs 26.1. I was not yet able to check on my secondary systems if it works.

**Comment by purcell** [comment]
Unsure of the reason for this, sorry, but 3636cd1 should provide a workaround for you.

**Comment by NobbZ** [comment]
I fully downloaded your config now, and I learned that `tablist-minor-mode` comes from `tablist.el`, and a `grep \'tablist **/*.el` does find references in `tablist` (not very surprising), your `init-benchmarking.el` (we knew that as well) and in some of the files that belong to `docker`.

So thats why you have it, I do not. I have not (yet) put anything docker related into my configuration.

Perhaps you should be more explicit in your configuration about `tablist` beeing a dependency, instead of relying on it beeing pulled in as a transitive dependency?

**Comment by purcell** [comment]
Ah, I see you're using 26.1 -- is that the system on which you encountered this issue? I'm using 27, which reports that this function is autoloaded.
