### ISSUE TITLE
What does the initial-scratch-message mean?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#608]
Hello.

Further, I don't understand why the word "Hacking" is used.

Because I am a non-English speaking person. I am sorry if I asked a silly question.

Thank you very much.

**Comment by purcell** [comment]
"Hacking", to programmers, means "programming clever solutions". Non-programmers use it to mean "breaking into computer systems", but I think the users of this config are programmers, so I use this phrase to help them feel welcome.

**Comment by re-mx** [comment]
Thank you very much！
