### ISSUE TITLE
ivy-use-virtual-buffers is breaking inf-ruby

### ISSUE THREAD

**Issue by xinyifly** [purcell/emacs.d#610]
### Issue
When I switch to a recent file using `C-x b` (`ivy-switch-buffer`) (with `ivy-use-virtual-buffers` set to `t`), I get a buffer which `buffer-file-name` not a pure string, like this:

Describe `buffer-file-name`
```
buffer-file-name is a variable defined in ‘C source code’.
Its value is
#("/root/a-rails-project/repl/repl.rb" 0 34
  (face ivy-virtual))
Local in buffer repl.rb; global value is nil
```

Then I execute `inf-ruby-console-rails`

After I use `ruby-send-*` (eg. `ruby-send-region`), it shows:

```
irb(main):001:0> 
irb(main):002:0' irb(main):003:0' irb(main):004:0* 
```

### More details
Then I pressed `C-d`, then `Enter`, got this:

```
irb(main):004:0> 
Traceback (most recent call last):
SyntaxError ((irb):4: syntax error, unexpected end-of-input)
irb(main):005:0> 
```

If I re-open this file using `C-x C-v`(`find-alternate-file`), will get pure string `buffer-file-name` 

```
buffer-file-name is a variable defined in ‘C source code’.
Its value is
"/root/a-rails-project/repl/repl.rb"
Local in buffer repl.rb; global value is nil
```

And `inf-ruby` will work normally:
```
irb(main):006:0' irb(main):007:0' <3
=> nil
irb(main):008:0> 
```

I think it's related to this line
https://github.com/nonsequitur/inf-ruby/blob/master/inf-ruby.el#L435

**Comment by purcell** [comment]
Okay... I'm not sure this is something specific to this config.

**Comment by xinyifly** [comment]
@purcell I'm not sure if I should open this issue in ivy or inf-ruby. I opened the issue here considering some people may occur same problem using ivy from this config.

IMO, `buffer-file-name` is a built-in variable, it may be reasonable that `inf-ruby` assumes it's pure string. But I don't know if it's necessary for ivy to modify `buffer-file-name` .

I initially created this issue here for other people at least can locate their problem using searching engine after spent my hours in the strange behavior. Feel free to close this issue or let me know where should I put this issue?
