### ISSUE TITLE
Why use "let" for gls config?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#618]
Hello

In `init-dried.el`:
https://github.com/purcell/emacs.d/blob/5d0d99a6074593b8eb0b8a3198625cef5d729be3/lisp/init-dired.el#L3-L5

Why not just judge `(executable-find "gls")` directly, but use a local variable?
e.g.:
```elisp
(when (executable-find "gls")
  (setq insert-directory-program "gls"))
```
Thanks.

**Comment by purcell** [comment]
I guess my code sets the variable to the full path of "gls", and your version repeats the string "gls". I'm not sure if one version is better than the other, but I wouldn't bother changing it, personally.

**Comment by re-mx** [comment]
Indeed... your method needs to define a local variable, and my method may have errors about the PATH environment variable...
