### ISSUE TITLE
“~/.emacs.d/site-lisp" is not in load-path

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#619]
Hello:

I found that this folder itself does not seem to be in the load-path. Why is it so designed?

Thanks.

**Comment by purcell** [comment]
It's made so that you can put libraries in sub-directories of `site-lisp`: those sub-directories *are* added to `load-path`.

**Comment by unmem** [comment]
I found this confusing but yeah, but now aha

**Comment by purcell** [comment]
I actually don't use the `site-lisp` directory at all myself.
