### ISSUE TITLE
Please update projectile mode line lighter configuration

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#620]
Hello:

See bbatsov/projectile#1287
and https://github.com/bbatsov/projectile/commit/bbca83fce64007e710dd0bc2a1932b9410de1b66

Sorry, I didn't do PR because I don't know what you want to change.

Thanks.

**Comment by bbatsov** [comment]
See https://projectile.readthedocs.io/en/latest/configuration/#mode-line-indicator
