### ISSUE TITLE
Do you still have to explicitly require ibuffer-vc?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#622]
https://github.com/purcell/emacs.d/blob/a33e98df888c2c1c4ff5e65eed76f4d1d99571f8/lisp/init-ibuffer.el#L30-L33

Is there any way to fix it in ibuffer-vc? 
Sorry, I am a little obsessive.

Thanks.

**Comment by purcell** [comment]
Yep, not going to change things to add complication just to make this easier, sorry.
