### ISSUE TITLE
Are there any plans to use smartparens?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#625]
Hello

I found that the behavior of `paredit` is sometimes annoying...

Thank you.

**Comment by purcell** [comment]
Nope. I've tried `smartparens` a couple of times in the past, and found it no better than `paredit` for Lisp, and equally sometimes-annoying for other languages.

**Comment by dcorking** [comment]
@haifenghan which feature(s) of smartparens do you particularly recommend that we don't see from the combination of electric-pair and show-paren minor modes?

**Comment by haifenghan** [comment]
Such as:
 `sp-rewrap-sexp` is an interactive compiled Lisp function in ‘smartparens.el’.

Examples:

  (foo |bar baz) -> [foo |bar baz]   ;; [

  (foo |bar baz) -> [(foo |bar baz)] ;; C-u [

**Comment by haifenghan** [comment]
And paredit maybe be used in Lisp mode only.

**Comment by dcorking** [comment]
purcell doesn't want it, but that is why he provides [init-local.el](https://github.com/purcell/emacs.d#changing-themes-and-adding-your-own-customization)

something like this should get you started,
```elisp
(when (maybe-require-package 'smartparens)
  (remove-hook 'after-init-hook 'electric-pair-mode))
```

but I tried to use `sp-rewrap-sexp` and I always get errors like, "Impossible pair prefix selected: (" so I am probably using it wrongly.

**Comment by haifenghan** [comment]
Hi @dcorking 
Do you know where to add `(require 'smartparens-config)`?

**Comment by haifenghan** [comment]
Hi @dcorking 
After adding your code and creating a file named `init-local.el` under `.emacs.d/lisp`, there is an error as follows:

```
Warning (initialization): An error occurred while loading ‘/home/haifeng/.emacs.d/init.el’:

error: Loading file /home/haifeng/.emacs.d/lisp/init-local.el failed to provide feature ‘init-local’

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by re-mx** [comment]
@haifenghan 

Add `(provide 'init-local)` to the footer of your init-local.el file.

In addition `(require 'smartparens-config)` should be added to `(when (maybe-require-package 'smartparens) ...)`.

Please make good use of Google.

**Comment by haifenghan** [comment]
@re-mx 
Thanks.
Following your suggestion, `(require 'smartparens-config)` still doesn't work for me.

**Comment by re-mx** [comment]
@haifenghan

```elisp
(when (maybe-require-package 'smartparens)
  (require 'smartparens-config)
  (remove-hook 'after-init-hook 'electric-pair-mode)
  (add-hook 'after-init-hook 'smartparens-mode))
```

Is your code like this?

Sorry, my English is very poor and may have caused you misunderstanding.

**Comment by haifenghan** [comment]
The code is as follows:
![image](https://user-images.githubusercontent.com/4157827/47845247-78ed0b80-ddff-11e8-8e1f-9faedbb12bc9.png)

However, there are no shortcut keys for smartparens after enabling smartparens-mode.

**Comment by re-mx** [comment]
Replace `(add-hook 'after-init-hook 'smartparens-mode) with `(add-hook 'after-init-hook 'smartparens-global-mode)`.

**Comment by haifenghan** [comment]
Hello @re-mx 

Can you use the default short-cut keys?
I still can't use it.
