### ISSUE TITLE
"lsregister" don't exist in the new version of macOS

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#627]
Hello:

https://github.com/purcell/emacs.d/blob/7ce37fbcf598daaeda11645e1ae6bac2fe22b5c7/lisp/init-dash.el#L3-L10

The `lsregister` here does not exist at least in macOS Mojave.

Thanks.

**Comment by purcell** [comment]
Hmm, odd. I'm on Mojave and I have this file.

**Comment by re-mx** [comment]
Yes... This file seems to appear again after reinstalling the OS. It seems to be a bug in macOS.

By the way, the macOS installer will give me a different macOS every time...

Thank you.
