### ISSUE TITLE
elm-format-on-save is set repeatedly

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#630]
Hello:

Your commit https://github.com/purcell/emacs.d/commit/e8d706e388939bb0ad120c3d56fb137ac7b84ba0 seems to have caused this variable to be set repeatedly.

https://github.com/purcell/emacs.d/blob/d96802f1c5a20be20d0a86178a61bae9065c2bbc/lisp/init-elm.el#L2-L8

I don't make PR because I don't know what you want.

Thanks.

**Comment by purcell** [comment]
Yup, thx.
