### ISSUE TITLE
C/C++ Language support

### ISSUE THREAD

**Issue by c4dr01d** [purcell/emacs.d#631]
Hello, I'm a C/C++ Developer and fan of Emacs, Can you add some C/C++ coding features to this?IDE is so heavy to me, I want keep my C/C++ develop environment simple.

**Comment by purcell** [comment]
I don't work with C/C++ very often, so I don't know what the best choices would be for this, sorry. I usually just rely on the built-in modes for C, together with `M-x compile`. I try to avoid making configuration decisions about languages that I don't use often.
