### ISSUE TITLE
strange behaviors of paredit-mode in python major mode

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#637]
When editing a python code, the keys `M-;` will produce a elisp comment.
And other keys also have strange behaviors, such as `Enter`, etc.

**Comment by purcell** [comment]
> When editing a python code, the keys `M-;` will produce a elisp comment.

I don't see the same behaviour: `M-;` gives me `#`. And `Enter` maps to `newline-and-indent`, which is pretty standard across Emacs. So I don't think paredit is affecting things here.

**Comment by haifenghan** [comment]
I can reproduce it by:
1. enable paredit-mode
2. exit Emacs
3. open Emacs again

Then you'll see the strange behaviors.

**Comment by purcell** [comment]
Ah, but you shouldn't enable `paredit-mode` in Python buffers -- it only supports lisp, so what you're seeing is to be expected.
