### ISSUE TITLE
Any more support of python

### ISSUE THREAD

**Issue by blithefeng** [purcell/emacs.d#642]
Personally, the configuration of python is quite simple. Is there a plan for more support of it? like virtualenv, flake, etc.

**Comment by purcell** [comment]
No, I don't currently work enough with Python to have a strong opinion on what should be added.

Flake is already supported by `flycheck`, though, as far as I know.

**Comment by JackLovel** [comment]
@blithefeng
 I get the article named [Emacs – The Best Python Editor?](https://realpython.com/emacs-the-best-python-editor/])  through my browser , maybe can help you.
