### ISSUE TITLE
projectile-ag not work 

### ISSUE THREAD

**Issue by crazyrunsnail** [purcell/emacs.d#646]
I install `ag` package by ```package-install```
When i press ```C-c C-p s s``` and enter a string, but get:
```
Ag started at Sat Oct 27 09:43:56

ag --literal --group --line-number --column --color --color-match 30\;43 --color-path 1\;32 --smart-case --stats -- default .
zsh:1: command not found: ag
```
I'm sure I can use `ag` with iterm2 in my mac which installed by brew.
I restart Emacs and get the same message.
Any help？
Emacs version: 26.1

**Comment by purcell** [comment]
I wouldn't normally provide support for packages I don't use myself, but I think what's happening here is that you're being affected by my recent change in c01ca45: my guess is that your shell config files are not set up correctly. Specifically, I imagine you might have installed `ag` in a directory that is added to your `PATH` in `~/.zshrc`, which is for interactive shells only. Such paths should be set up in `~/.zshenv` instead. Is that the cause?

**Comment by purcell** [comment]
(Specifically, for Homebrew, you'd want to add `/usr/local/bin` to your `PATH` in `~/.zshenv`.)

**Comment by crazyrunsnail** [comment]
@purcell You are Right! 
Add ```export PATH=/usr/local/bin:$PATH``` to ```~/.zshenv```, restart emacs, some package install, and the ```projectile-age``` run well.
Thank you very much!
