### ISSUE TITLE
How to add user-defined config to org-mode?

### ISSUE THREAD

**Issue by crazyrunsnail** [purcell/emacs.d#649]
As personal reason, I want to turn on `truncate-line` option. 
I add following code into `init-local.el`:
```
(defun davino/org-mode()
  "Customize org mode."
  (progn)
  (setq truncate-lines t)
  (setq org-ellipsis "⤵")
  )
(add-hook 'org-mode 'davino/org-mode)
```
But there is nothing changed.
How to add my user-defined to `org-mode`?

**Comment by dcorking** [comment]
The[ `progn` special form requires a body,](https://www.gnu.org/software/emacs/manual/html_node/eintr/progn.html) so your parens are in the wrong place.

This works for me:
```elisp
(defun davino/org-mode()
  "Customize org mode."
  (progn
    (setq truncate-lines t)
    (setq org-ellipsis "⤵")))
(add-hook 'org-mode 'davino/org-mode)
```

**Comment by crazyrunsnail** [comment]
@dcorking 
I replace your code to my init file, but it still don't work for me.
By the way,  I add `org-bullets` followed the code, like this:
```
(defun davino/org-mode()
  "Customize org mode."
  (progn
    (setq truncate-lines t)
    (setq org-ellipsis "⤵"))
  )
(add-hook 'org-mode 'davino/org-mode)
;; org-bullets
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
```
Is it  a matter ?

**Comment by dcorking** [comment]
Please provide the exact steps you used, and the symptoms you observed. (Please be detailed as I don't use org mode myself.)

Does your code work when you load Emacs without the rest of the init file (with `emacs -q`)?

When I fixed the parentheses in your code, I reloaded org mode and then checked the values of the 2 variables you wanted to change, with `C-h v` and they were set correctly. When I am troubleshooting, I like to remove code to narrow down the problem, so probably best to comment out your org-bullets code for now.

**Comment by dcorking** [comment]
Do what works for you.

**Comment by crazyrunsnail** [comment]
@dcorking Just write code ```(setq org-ellipsis "⤵")``` in ```init-local.el``` not in the ```davino/org-mode``` function work for me

**Comment by crazyrunsnail** [comment]
@dcorking This may illustrates the customized function did'n't add to the ```org-mode-hook```

**Comment by dcorking** [comment]
the hook is called 'org-mode-hook (not 'org-mode as you wrote) so try something like:
```elisp
(defun davino/org-mode()
  "Customize org mode."
  (progn
    (setq truncate-lines t)
    (setq org-ellipsis "⤵"))
  )
(add-hook 'org-mode-hook 'davino/org-mode)
```

No-one can help you when you say 'work for me' and 'not work'. Tell us how you test, what you expect to see, and what you actually see.

**Comment by crazyrunsnail** [comment]
@dcorking Thanks a lot.
First, I add following in the ```init-local.el```, *NOTE* 
```emacs-lisp
;;;
```
I restart Emacs, but there is no change when I open an org file.
But If I comment the code above, and only add
```emacs-lisp
(setq org-ellipsis "⤵")
```
It works when I restart Emacs and open an org file.
It may illustrate that the code(the function ```davino/org-mode```) I first written may not hook to ```org-mode-hook ```
This is what trouble me.

**Comment by dcorking** [comment]
I can reproduce this.  This behaviour seems similar, but not identical, to the odd one described in the doc for org-ellipsis:

> The change affects only Org mode (which will then use its own display table).
> **Changing this requires executing ‘M-x org-mode’ in a buffer to become
> effective.**
> 
> You can customize this variable.

I can reproduce this behaviour with `emacs -q`. So I conclude that it is not related to emacs.d. I suggest you work around it in the manner you have found, or discuss it with the wider Emacs community: https://www.emacswiki.org/emacs/GetHelp
