### ISSUE TITLE
wgrep is not work with sanityinc/counsel-search-project

### ISSUE THREAD

**Issue by oizhaolei** [purcell/emacs.d#654]
About last week, Nov 15, I update all packages, then I found the wgrep begun not work.
All my packages and emacs.d are update to date.

This is my steps:
```
M-?        sanityinc/counsel-search-project     // search in current project
C-c C-o    ivy-occur                                          // open result  in new wint
w          ivy-wgrep-change-to-wgrep-mode    // chagne to wgrep mode
......// do some edit
C-x C-s    wgrep-finish-edit                              // message: "(no change to be performed)"
```
But, ag, swiper and rgrep is doing well with wgrep.

I don't know how should i fix it?
Thanks！

**Comment by purcell** [comment]
Yes, I just discovered this too. This must be an upstream issue with either wgrep or ivy. I haven't had time to investigate it yet.

**Comment by purcell** [comment]
Reported in https://github.com/abo-abo/swiper/issues/1813

**Comment by oizhaolei** [comment]
solved
