### ISSUE TITLE
What are they use of args "rbeg" and "rend" of sanityinc/isearch-exit-other-end?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#656]
https://github.com/purcell/emacs.d/blob/add16e79c067a9de36ff74909691f44f8b18efde/lisp/init-isearch.el#L36

Thanks.

**Comment by purcell** [comment]
Looks like they're unnecessary. :-)

**Comment by re-mx** [comment]
Thanks.

I can't think of why the original author would do this.

Maybe because this is actually part of the original author configuration.
