### ISSUE TITLE
[question] what's the point of after-init-hook?

### ISSUE THREAD

**Issue by JJPandari** [purcell/emacs.d#657]
I see you enable some modes in `after-init-hook`, and the document says this hook runs after user init file and all packages. I assume you do this to speed things up a bit, but I'm wondering, how can `putting something in this hook`/`make something run after all other init process` make things faster? Those codes in this hook runs at startup anyway, not like `autoload`, which loads code at some later time.

**Comment by purcell** [comment]
Yep, true, but they run after some other significant things have taken place, e.g. loading of the custom file (particularly). I took a look recently at running some of the snippets on idle instead: I believe use-package supported this at one point, but removed that option, so I imagine there must be some downsides.
