### ISSUE TITLE
Is the "site-lisp" folder and its configuration still useful?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#663]
Hello:

There is at least no package that needs to be managed manually.

So I think it would be better to reconsider the role and configuration of this folder.

For example: remove some grabbing functions, or consider changing the name of this folder.

Please forgive my obsessive-compulsive disorder......

Thanks.

**Comment by dcorking** [comment]
at the moment I use `site-lisp/` for a couple of packages that aren't available in MELPA (in my case for ruby-style and rails-reloaded )

name changes are no problem to me

**Comment by re-mx** [comment]
@dcorking 
I really have some obsessive-compulsive disorder...so I submitted this issue.

If this issue is stupid... I will close it.

**Comment by re-mx** [comment]
@dcorking And I have some doubts about a question: `site-lisp` should be set before `elpa`, or after? 

The reason Mr. Purcell sets this up is that there may be another `package.el`, but now this assumption does not exist.

**Comment by dcorking** [comment]
Not everything is in ELPA. Thanks for pointing out [`init-site-lisp.el`](https://github.com/purcell/emacs.d/blob/master/lisp/init-site-lisp.el) - there are some utilities in there I didn't know about.

IMO this is a good place to download arbitrary files from emacswiki or github. But since purcell's config doesn't contain any arbitrary files,  would it help to rename `site-lisp` to `local-lisp` for consistency with `init-local.el`?

I don't know about your question: 
> `site-lisp` should be set before `elpa`, or after?
do you mean in `load-path`? if so I think customizations should be first in case they redefine functions, but I never redefine functions so it doesn't matter to me.

**Comment by purcell** [comment]
`site-lisp` should take priority on `load-path` here. I think everything is set up how I want it, so I'll go ahead and close this.

**Comment by re-mx** [comment]
Indeed... if you put the site-lisp folder in the head of the load-path, it may cause some function coverage problems...

**Comment by dcorking** [comment]
Perhaps you have found a bug.

I created a test directory `site-lisp/foo`. This is how `load-path` looks on my personal branch, which is how I want it, with `foo` highest priority:
```lisp
("/Users/dcorking/.emacs.d/site-lisp/foo" 
"/Users/dcorking/.opam/system/share/emacs/site-lisp" 
"~/.emacs.d/site-lisp/rails-reloaded" 
"/Users/dcorking/.emacs.d/elpa-26.1/add-node-modules-path-20180710.2342" 
"/Users/dcorking/.emacs.d/elpa-26.1/ag-20180225.1040" 
 ....
```

but in purcell's master branch, this happens:
```lisp
("/Users/dcorking/.emacs.d/elpa-26.1/add-node-modules-path-20180710.2342" 
"/Users/dcorking/.emacs.d/elpa-26.1/ag-20180225.1040" 
... 
"/Users/dcorking/.emacs.d/elpa-26.1/yascroll-20170315.1906" 
"/Users/dcorking/.emacs.d/elpa-26.1/yasnippet-20181015.1212" 
"/Users/dcorking/.emacs.d/site-lisp/foo" 
"/Users/dcorking/.emacs.d/lisp" "/Library/Application Support/Emacs/26.1/site-lisp"
 "/Library/Application Support/Emacs/site-lisp"
```

here elpa is top priority, then `foo`, then purcell's code.

I am not sure yet if this difference is a bug in my code, a bug in purcell's code, or just something I don't understand yet or tested incorrectly.

`"GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31"`

**Comment by re-mx** [comment]
@dcorking Thanks for your test.
I think this is the intention of Mr. Purcell, not a bug.

The solution I am using now is to force `~/.emacs.d/lisp` and `~/emacs.d/site-lisp` in the header of `load-path`. This saves startup time.

In my `init.el`
```elisp
...
(defun remx/setup-load-path (&rest _)
  "Set up `load-path'."
  (push (expand-file-name "site-lisp" user-emacs-directory) load-path)
  (push (expand-file-name "lisp" user-emacs-directory) load-path))

(advice-add 'package-initialize :after #'remx/setup-load-path)

(remx/setup-load-path)
...
```
