### ISSUE TITLE
Benchmark “require time” may increase startup time

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#665]
Hello:

After my tests, I did find a perceptible change.

So I don't think it should be enabled by default, but rather let the user open it by some way.

Thank you.

**Comment by purcell** [comment]
What sort of difference in time are you seeing?

**Comment by re-mx** [comment]
About 100-200ms...

My computer is old (MacBook Pro with Retina display, 2013), so it may not be so obvious on your computer.

**Comment by re-mx** [comment]
It's really related to computer performance... There is less than 50ms difference on my MacBook Pro 2018.

**Comment by purcell** [comment]
Hmm, interesting. Overall the config really isn't optimised for super-fast startup, and I don't think I want to make this aspect configurable. The simple workaround is to comment out `(require 'init-benchmarking)` in `init.el` locally.

**Comment by re-mx** [comment]
Thank you.
