### ISSUE TITLE
Reduce the entries in desktop-global-to-save?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#666]
Hello:

I really think that something you restore are a little bit many....

Like a bunch of variables starting with `ido-` (I remember that your configuration is now completely unused `ido`?), and other variables that other historical storage modes (such as `savehist-mode`) will record. I don't think they need to be here.

Or simply drop `desktop-save-mode` and use only `session.el`? I see a lot of people doing this.

Please forgive my obsessive-compulsive disorder.

Thank you.

**Comment by purcell** [comment]
Yep, I'm happy to accept fixes that reduce duplication while keeping the overall functionality the same. I want to keep `desktop-save-mode` because I want my frames and window layouts etc. to be restored.

**Comment by re-mx** [comment]
Thanks for your reply...

I will try to submit a PR...
BTW, Is it necessary to repeat records in `desktop-save-mode` for items already recorded in `savehist-mode`?

If not necessary, the settings for `desktop-global-to-save` can be removed completely - the default value is sufficient.

**Comment by re-mx** [comment]
Ok... I will keep some items that seem more important.

I use the default value of `desktop-global-to-save` myself, and there is no problem at the moment. Because the variables you add are almost all histories of minibuffer...

I will close this issue first. And I will submit a PR...

Let's talk about it later.
