### ISSUE TITLE
In cygwin, alt-x or ESC x does not work

### ISSUE THREAD

**Issue by quaziashfaq** [purcell/emacs.d#668]
I am using cygwin latest version and GNU Emacs 26.1.
After I load the purcell/emacs package, `alt-x` or `ESC x` does not work. When I press `alt-x`, minibuffer shows this text: `Symbol’s value as variable is void: feature`
When I use `emacs -Q`, then `alt-x` works.
What could be the issue? How can I dig it in?

**Comment by purcell** [comment]
`M-x` is bound to `counsel-M-x` in my config, but `execute-extended-command` with `emacs -Q`, hence the difference. So it seems like something is going wrong with `counsel-M-x`.

You can add `(setq debug-on-error t)` to the start of `init.el` before starting Emacs, then you should get a more complete stacktrace for the error, which you can paste here.

**Comment by quaziashfaq** [comment]
`(setq debug-on-error t)` is already set in `init.el`. After I press `Alt-x`, there is no text other than `Symbol’s value as variable is void: feature`
I ran 
`$ ./test-startup.sh
Attempting startup...
Loading /home/***/.emacs.d/init.el (source)...
Loading /home/***/.emacs.d/custom.el (source)...
Symbol’s value as variable is void: feature`

I got the above output. It is supposed to print `Startup successful` as per the script.

**Comment by quaziashfaq** [comment]
In the `Messages` buffer, I saw the warning as `if: Symbol’s value as variable is void: feature`. Then I tried to find which line can cause the issue from init.el file. I found this line `(require 'init-lisp)` giving the error.

**Comment by purcell** [comment]
Hmm, odd! Good detective work. It's still hard to guess what might be wrong, but the two sets of output from `test-startup` indicate that something in your `custom.el` was causing the breakage. Had you added any additional customisation? Maybe worth having a look to see what's in there.

**Comment by quaziashfaq** [comment]
Hi Mr. Purcell,
No I have not added any additional customization. 
In the `init-lisp.el` script, I have commented out these lines and then it's okay and I can use `alt-x` keys.

`;(when (maybe-require-package 'auto-compile)`
`;  (add-hook 'after-init-hook 'auto-compile-on-save-mode)`
`;  (add-hook 'after-init-hook 'auto-compile-on-load-mode))`

**This is my thought only:** However this seems not to be the problem as they just compile the `.el` scripts. That might mean in some other places, code is breaking for my environment. Now how can I find that?

**Comment by purcell** [comment]
Interesting. So I'm guessing the error is related to [this line in auto-compile.el](https://github.com/emacscollective/auto-compile/blob/6ce4255ab9a0b010ef8414c5bd9a6d6d9eea012f/auto-compile.el#L760). That `defadvice` is referring implicitly to the `feature` arg name, and maybe that doesn't work when there the function is already advised, as it is in my config. It's possible a fix would be for the `defadvice` forms in `auto-compile.el` to explicitly declare their args. Any guesses at that, @tarsius?

**Comment by purcell** [comment]
(The advice in my config is [here](https://github.com/purcell/emacs.d/blob/0902440435ed52e9c4217662c339f0c95c62c5b0/lisp/init-benchmarking.el#L9-L21))

**Comment by tarsius** [comment]
I've pushed a new version, which uses `nadvice`.

**Comment by quaziashfaq** [comment]
It works! Thank you Mr. Bernoulli.

**Comment by purcell** [comment]
Awesome, thanks @tarsius!
