### ISSUE TITLE
Symbol's function definition is void: fullframe

### ISSUE THREAD

**Issue by yangli0534** [purcell/emacs.d#670]
Debugger entered--Lisp error: (void-function fullframe)
  (fullframe list-packages quit-window)
  eval-buffer(#<buffer  *load*-76746> nil "c:/Users/xxxxx/AppData/Roaming/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 3580
  load-with-code-conversion("c:/Users/xxxxx/AppData/Roaming/.emacs.d/lisp/init-elpa.el" "c:/Users/xxxxxx/AppData/Roaming/.emacs.d/lisp/init-elpa.el" nil t)
  #<subr require>(init-elpa)
  apply(#<subr require> init-elpa nil)
  (prog1 (apply orig feature args) (if (and (not already-loaded) (memq feature features)) (progn (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list 'sanityinc/require-times (list feature require-start-time time) t)))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (apply orig feature args) (if (and (not already-loaded) (memq feature features)) (progn (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list 'sanityinc/require-times (list feature require-start-time time) t))))))
  sanityinc/require-times-wrapper(#<subr require> init-elpa)
  apply(sanityinc/require-times-wrapper #<subr require> init-elpa)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "c:/Users/xxxxxx/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 1595
  load-with-code-conversion("c:/Users/xxxxxx/AppData/Roaming/.emacs.d/init.el" "c:/Users/xxxxxx/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/xxxxxx/AppData/Roaming/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000be22d>)()
  command-line()
  normal-top-level()

**Comment by purcell** [comment]
Not sure how to reproduce this, sorry. The relevant code says
```el
(require-package 'fullframe)
(fullframe list-packages quit-window)
```
so `require-package` must have failed in an unusual way and not generated the autoloads for the `fullframe` macro properly. Can you successfully `M-x find-library fullframe`? Perhaps the file is truncated or corrupted?

**Comment by yangli0534** [comment]
Thank you for reply. The error occurred on a latest Emacs version. When I replaced it with a older one, no such error.
