### ISSUE TITLE
How to disable key bindings prompt?

### ISSUE THREAD

**Issue by sherrywong1220** [purcell/emacs.d#672]
Hi Steve. I am new to emacs and found your awesome. When I enter command, emacs right side will display key bindings. What package implement this feature? How can disable it? 
<img width="1674" alt="2018-12-23 00 17 30" src="https://user-images.githubusercontent.com/19210342/50376491-3fd75780-0648-11e9-9529-11c5b73e62e9.png">

**Comment by purcell** [comment]
That's `guide-key`: it's enabled on [this line](https://github.com/purcell/emacs.d/blob/0902440435ed52e9c4217662c339f0c95c62c5b0/lisp/init-editing-utils.el#L324) .

**Comment by purcell** [comment]
For what it's worth, I find these hints very helpful, even though I've been using Emacs for a very long time: if I type key sequences fast enough because I am familiar with them, the hints don't pop up.
