### ISSUE TITLE
Dired open directories which begin with a dot (.) cause problem

### ISSUE THREAD

**Issue by josephyoung** [purcell/emacs.d#676]
My emacs ver: 
> GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

os is win 10 home chinese simplified. 
Backtrace:

> Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "git")
  make-process(:name "git" :buffer #<buffer  *diff-hl-dired* tmp status> :command ("git" "--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var"))
  apply(make-process (:name "git" :buffer #<buffer  *diff-hl-dired* tmp status> :command ("git" "--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var")))
  start-process("git" #<buffer  *diff-hl-dired* tmp status> "git" "--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var")
  apply(start-process "git" #<buffer  *diff-hl-dired* tmp status> "git" ("--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var"))
  start-file-process("git" #<buffer  *diff-hl-dired* tmp status> "git" "--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var")
  apply(start-file-process "git" #<buffer  *diff-hl-dired* tmp status> "git" ("--no-pager" "add" "--refresh" "--" ".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var"))
  vc-do-command(#<buffer  *diff-hl-dired* tmp status> async "git" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") "--no-pager" "add" "--refresh" "--")
  apply(vc-do-command #<buffer  *diff-hl-dired* tmp status> async "git" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") ("--no-pager" "add" "--refresh" "--"))
  vc-git-command(#<buffer  *diff-hl-dired* tmp status> async (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") "add" "--refresh" "--")
  vc-git-dir-status-goto-stage(#s(vc-git-dir-status-state :stage update-index :files (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") :update-function #f(compiled-function (entries &optional more-to-come) #<bytecode 0x27bc7c1>) :hash #<hash-table equal 0/65 0x27bc7cd>))
  vc-git-dir-status-files("c:/cygwin64/home/Joseph/.emacs.d/" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") #f(compiled-function (entries &optional more-to-come) #<bytecode 0x27bc7c1>))
  apply(vc-git-dir-status-files ("c:/cygwin64/home/Joseph/.emacs.d/" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") #f(compiled-function (entries &optional more-to-come) #<bytecode 0x27bc7c1>)))
  vc-call-backend(Git dir-status-files "c:/cygwin64/home/Joseph/.emacs.d/" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") #f(compiled-function (entries &optional more-to-come) #<bytecode 0x27bc7c1>))
  diff-hl-dired-status-files(Git "c:/cygwin64/home/Joseph/.emacs.d/" (".agignore" ".dir-locals.el" ".emacs.desktop" ".emacs.desktop.lock" ".git" ".gitignore" ".historian" ".session" ".smex-items" ".travis.yml" ".uptimes.el" "LICENSE" "README.md" "auto-save-list" "custom.el" "elpa" "elpa-26.1" "eshell" "history" "init.el" "lisp" "magithub" "org-clock-save.el" "projectile-bookmarks.eld" "pyim" "recentf" "server" "site-lisp" "snippets" "test-startup.sh" "var") #f(compiled-function (entries &optional more-to-come) #<bytecode 0x27bc7c1>))
  diff-hl-dired-update()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("c:/cygwin64/home/Joseph/.emacs.d/" nil)
  dired-noselect("~/.emacs.d/")
  run-hook-with-args-until-success(dired-noselect "~/.emacs.d/")
  find-file-noselect("c:/cygwin64/home/Joseph/.emacs.d/" nil nil nil)
  find-file("c:/cygwin64/home/Joseph/.emacs.d/")
  counsel-find-file-action("c:/cygwin64/home/Joseph/.emacs.d/")
  ivy-call()
  #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nIf PRESELECT is not nil, then select the corresponding candidate\nout of the ones that match the INITIAL-INPUT.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is redisplayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x31996d9>)("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nIf PRESELECT is not nil, then select the corresponding candidate\nout of the ones that match the INITIAL-INPUT.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is redisplayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x31996d9>) ("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file))
  ivy-historian--nadvice/ivy-read(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nIf PRESELECT is not nil, then select the corresponding candidate\nout of the ones that match the INITIAL-INPUT.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is redisplayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x31996d9>) "Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  apply(ivy-historian--nadvice/ivy-read #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nIf PRESELECT is not nil, then select the corresponding candidate\nout of the ones that match the INITIAL-INPUT.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is redisplayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes the candidate, which is a string, as its only argument.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x31996d9>) ("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file))
  ivy-read("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  counsel-find-file()
  funcall-interactively(counsel-find-file)
  call-interactively(counsel-find-file nil nil)
  command-execute(counsel-find-file)

**Comment by quaziashfaq** [comment]
Hi,
Which directory are you trying to open with `alt-x dired`?
And from your backtrace, it looks like it can't find `git` which should not be since you cloned this `purcell/emacs.d` package with `git` command. Right? Hmm. Let's see what Mr. Purcell says..

**Comment by josephyoung** [comment]
> 
> 
> Hi,
> Which directory are you trying to open with `alt-x dired`?
> And from your backtrace, it looks like it can't find `git` which should not be since you cloned this `purcell/emacs.d` package with `git` command. Right? Hmm. Let's see what Mr. Purcell says..

It's .emacs.d I was trying to open with dired.
After I changed the encoding settings, the issue solved.
