### ISSUE TITLE
Symbol’s value as variable is void: feature

### ISSUE THREAD

**Issue by lvii** [purcell/emacs.d#679]
Hi

Start `emacs-nox` 26.1 under Fedora 29 64bit with an error:

`Symbol’s value as variable is void: feature`

I have cloned a clean git repo.

**Comment by quaziashfaq** [comment]
Hi,
Your issue seems to be same as mine. Check this [issue page](https://github.com/purcell/emacs.d/issues/668).

**Comment by lvii** [comment]
@quaziashfaq Thank you.

After I update `auto-compile` package, this problem was solved.

**Comment by purcell** [comment]
Thanks for helping out here, @quaziashfaq.
