### ISSUE TITLE
How to disable `whole-line-or-region-global-mode` globally in init-local?

### ISSUE THREAD

**Issue by tru2dagame** [purcell/emacs.d#683]
Sorry for this silly question. 
I'd like to disable `whole-line-or-region-global-mode` for some reason.

I can only set it disable in `custom.el`. Is there a way to disable it in init-local?

I want to sync my local conf through my laptops and I want keep custom.el as clean as possible.

Thanks,
Tru

**Comment by tru2dagame** [comment]
I couldn't disable it, so I tried to bind the key globally.

`(global-set-key (kbd "M-w") 'kill-ring-save)`

It won't work if I set these in the `init-local.el`.

**Comment by tru2dagame** [comment]
```
(require 'whole-line-or-region)
(global-set-key [remap whole-line-or-region-kill-ring-save] 'kill-ring-save)
```

This is a workaround finally works for me.

#404 

<img width="2272" alt="2019-01-01 02 04 18" src="https://user-images.githubusercontent.com/1673006/50565414-8d9b4080-0d69-11e9-97a7-371c865b24f1.png">

**Comment by purcell** [comment]
Setting the mode variable won't work, if that's what you were trying. Something like `(whole-line-or-region-global-mode -1)` in your `init-local.el` should work fine, though.
