### ISSUE TITLE
Why do you want to make the compile behavior load after `compile` is loaded?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#687]
Hello and sorry for my English.

In your commit https://github.com/purcell/emacs.d/commit/7f47e64a83a87134b12755464407a30711ff5eb3, You load the "compile behavior" after `compile`, why?

Thank you very much!

**Comment by purcell** [comment]
This is just a startup optimisation. This makes the code execute later, and not at all if `compile.el` is never loaded.

**Comment by re-mx** [comment]
Thank you.
