### ISSUE TITLE
What's the name of theme used here?

### ISSUE THREAD

**Issue by M-DFK** [purcell/emacs.d#690]
I found the theme is just appealing,   
What's the name of this theme?

**Comment by purcell** [comment]
https://github.com/purcell/emacs.d/search?q=theme&unscoped_q=theme :-)

**Comment by purcell** [comment]
In other words, the config includes my sanityinc-tomorrow and sanityinc-solarized themes, but the defaults are from https://github.com/purcell/color-theme-sanityinc-tomorrow/
