### ISSUE TITLE
"sanityinc/dash-installed-p" may slow down startup time

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#691]
Hello

I recently started using macOS, so I found this problem.

The startup time has increased by about 0.1s - 0.5s... It may be trivial, but I did feel it.

I personally don't think there is any good solution to this problem... I just observed this phenomenon.

I have seen other popular configurations prefer to install `dash-at-point` anyway...but they are modular, and dash support is not enabled by default...

**Comment by purcell** [comment]
I'm not generally concerned about aggressively minimising startup time, but in this case I've gone ahead and removed the slow shell command call.

**Comment by re-mx** [comment]
Thank you.
