### ISSUE TITLE
What is the use of "ivy-historian"?

### ISSUE THREAD

**Issue by re-mx** [purcell/emacs.d#692]
Hello... sorry to bother you again

I don't know what this package is for. Or I think whatever `ivy-historian` is enabled or not, and the behavior of `ivy` has not changed...

What I did wrong?

Thank you.

**Comment by purcell** [comment]
Yeah, I'm also not sure that it's doing much, so I've removed it, because I'm not interested in investigating in more detail. :-)

**Comment by re-mx** [comment]
Thank you for your reply.

I am still at the stage of interest in the survey (it's better to say that my career requires a lot of investigation work). But for this problem, I did not find any valuable clues.

Perhaps the behavior of `ivy` itself has changed so that `ivy-historian` is not needed? But this is also a guess.

**Comment by re-mx** [comment]
I also saw the example in the README of `ivy-historian`.

But my point is "what is the use of this?"

Maybe because I am heavily dependent on `company` and rarely use `ivy` (but I use `counsel` very often). So the impact of `ivy-historian` is even smaller.

**Comment by purcell** [comment]
Yeah, I really like the big effect that `smex` has on `M-x` (and `counsel-M-x`) so I hoped that `ivy-historian` would magically make some other `ivy`-based commands better...

**Comment by re-mx** [comment]
Yeah……

But I actually stopped using `ivy-historian` very early...because I basically prefer that the completion list is the same every time. Instead of making changes based on my habits.

But for interactive input like `counsel`, I prefer the behavior of smex.
