### ISSUE TITLE
elm lang company and flycheck setup

### ISSUE THREAD

**Issue by thepreacher** [purcell/emacs.d#695]
Hi Steve, with your current elm setup, do you have company completion and flycheck working? I have duplicated your elm config albeit using use-package. Below is all there is to that:

```
(use-package elm-mode
  :ensure t
  :mode ("\\.elm\\'" . elm-mode)
  :after (company flycheck)
  :config
  (when (executable-find "elm-format")
    (setq-default elm-format-on-save t))
  (push 'company-elm company-backends)

  (use-package elm-test-runner
    :ensure t)

  (use-package flycheck-elm
    :ensure t
    :config
    (flycheck-elm-setup)))

```
At the moment, I don't get autocompletion pop ups at all and flycheck doesn't work either. I'm not asking you to debug my config for me, I just need to know you don't have any such issues in order to direct my debugging.

**Comment by purcell** [comment]
Oh, and `flycheck-elm` _is_ working for me fine, but you might like to try running the check command manually. You haven't really provided info beyond "flycheck doesn't work" so it's hard to guess what might be wrong.

**Comment by thepreacher** [comment]
Ah! I'm using Elm 0.19 so I'm out of luck then what a shame. Anyway I've subscribed to the linked issue on elm-mode in order to follow how your effort to find a solution is coming along. About the `flycheck` not working, it's working now. I changed the code to:
```
  (use-package flycheck-elm
    :ensure t
    :hook (flycheck-mode . flycheck-elm-setup)))
```

and it's now works as expected.

Thanks
