### ISSUE TITLE
How can I add one more extension for js mode

### ISSUE THREAD

**Issue by yuanlai** [purcell/emacs.d#696]
On javascript-mode
```
(setq auto-mode-alist (cons `("\\.\\(js\\|es6\\)\\(\\.erb\\)?\\'" . ,preferred-javascript-mode)
                            (loop for entry in auto-mode-alist
                                  unless (eq preferred-javascript-mode (cdr entry))
                                  collect entry)))
```
If I want to replace the default extension setup with .js .ts .tsx, how should I change this configure?

**Comment by purcell** [comment]
If you want to add a new entry, just add another entry to `auto-mode-alist` in the standard way (e.g. with `add-to-list`). If you want to remove an association from the above code, you'd have to edit that code directly, sorry.

**Comment by purcell** [comment]
(Related: I just changed the above code in 54b2175)
