### ISSUE TITLE
Some issues with "show-trailing-whitespace enabled by default"

### ISSUE THREAD

**Issue by yurimx** [purcell/emacs.d#697]
Hello Mr.Purcell.

`show-trailing-whitespace` is enabled by default in your configuration. I found that this seems to cause whitespace to be highlighted where whitespace should not be displayed (Like Magit and ibuffer).

Screenshot:
![2019-02-17 6 46 13](https://user-images.githubusercontent.com/26828933/52911857-b14c2300-32e4-11e9-9cf6-a6d45b873b59.png)
![2019-02-17 6 46 47](https://user-images.githubusercontent.com/26828933/52911861-b9a45e00-32e4-11e9-928f-4ee1b4d76378.png)

Why don't you just only set this variable in the buffers/modes that needs to highlight the trailing whitespace?

Thank you.

**Comment by purcell** [comment]
Whether it works with a blacklist or a whitelist of modes, there can always be corner cases. I really like to make sure I can see trailing whitespace, so I prefer a blacklist.

The problem in this case is that Transient doesn't use a mode, so it has no hooks.

I'll experiment locally with a whitelist instead, and might consider switching.

**Comment by purcell** [comment]
(Re. `ibuffer-mode`, its parent is `special-mode`, so `show-trailing-whitespace` should already be set to `nil` there. I'm therefore surprised to hear you're seeing whitespace marked there.)

**Comment by yurimx** [comment]
Thank you for your reply.

Indeed, if you want to make sure you see whitespace, the blacklist is better.

> (Re. `ibuffer-mode`, its parent is `special-mode`, so `show-trailing-whitespace` should already be set to `nil` there. I'm therefore surprised to hear you're seeing whitespace marked there.)

The place I see whitespace is the `*iBuffer confirmation*` buffer. The main buffer of the ibuffer does not have this problem.
