### ISSUE TITLE
How do I include org-checklist?

### ISSUE THREAD

**Issue by n0ego** [purcell/emacs.d#701]
Hi

I'd like to include/install org-checklist but it doesn't work so far.

I've tried C-h-v org-modules => customize => tick org-checklist => restart. Reviewing the list and org-checklist remains to be ticked but when change an item from NEXT status to DONE, no checkbox is reset.

The item looks like this:
```
* NEXT Weekly Review [5/5]
SCHEDULED: <2019-02-23 Sat ++1w>
:PROPERTIES:
:RESET_CHECK_BOXES: t
:END
1. [X] Loose Papers [1/1]
   - [X] Remove loose stuff from desk

2. [X] Pro
   
```

**Comment by purcell** [comment]
Unsure, sorry, I don't use that package and I don't currently have time to look into this.

**Comment by minostro** [comment]
@n0ego did you read this? https://stackoverflow.com/questions/20164918/how-to-untick-checkboxes-in-org-mode-for-the-next-cyclic-repetitive-task
