### ISSUE TITLE
What the recommand file structure for the org-agenda under gtd?

### ISSUE THREAD

**Issue by sjkyspa** [purcell/emacs.d#702]

**Comment by purcell** [comment]
I'm not sure that it makes much difference: you just add files to org's agenda file list, ideally with each file or subtrees tagged with categories, and then the provided GTD views should work okay. But then again, this is one of the more personal parts of my config, so I'm not entirely sure if/how this will easily work for others.

**Comment by sjkyspa** [comment]
I am studying the org-mode with your config. By reading the init-org.el, I can not infer what the work flow you use？capture to what file? how to refile the todos? Would you please give me a little demo for how(the workflow) you use org-mode to manage todos? thanks.

**Comment by purcell** [comment]
While I can't easily prepare a demo, I added a few notes in `init-org.el` to explain this a little: bed5f8ef
