### ISSUE TITLE
pdflatex: command not found from M-x shell.

### ISSUE THREAD

**Issue by zhoulaifu** [purcell/emacs.d#703]
On a Mac OS, I can run `pdflatex` from the iTerm, but not from Emacs Shell.  I understand this should be a PATH issue and saw some solutions, such as:

- https://www.johndcook.com/blog/2016/11/30/setting-up-emacs-shell-on-a-mac/

- https://stackoverflow.com/questions/4393628/emacs-shell-command-not-found

What would be your preferred solution to this?

**Comment by purcell** [comment]
I already use `exec-path-from-shell` by default, so this should work, but you are probably setting the `PATH` in a start-up file used only for interactive shells. See the [exec-path-from-shell README](https://github.com/purcell/exec-path-from-shell/#setting-up-your-shell-startup-files-correctly) for more on this.

**Comment by purcell** [comment]
Does this work for you with my update, as above?

**Comment by zhoulaifu** [comment]
Yeah, it works with your updated repo. Thank you for taking time to fix this minor issue! Would you briefly explain, for someone who knows little about Emacs, how you solve the issue?

Besides, you suggested, in https://github.com/purcell/exec-path-from-shell/#setting-up-your-shell-startup-files-correctly, that "config files should therefore set the environment variables to their exact desired final values". But, that can be out of some users' control.   In my bash_profile, for example,   there is 
"export PATH="/Users/zhfu/anaconda2/bin:$PATH", which is automated added by Anaconda2 installer, apparently.

**Comment by purcell** [comment]
Great, glad it's working. There's a lot of background to the explanation, but it's more about understanding `exec-path-from-shell` and how processes inherit their environment variables from their parents. I tried to explain it in the `exec-path-from-shell` README but I probably need to add more detail there.
