### ISSUE TITLE
Failed to verify signature archive-contents

### ISSUE THREAD

**Issue by abhiroopdatta7** [purcell/emacs.d#706]
Failed to verify signature archive-contents.sig:
Bad signature from 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org>
Command output:
gpg: Signature made Sunday 17 March 2019 02:40:03 PM IST using DSA key ID 7FBDEF9B
gpg: BAD signature from "GNU ELPA Signing Agent <elpasign@elpa.gnu.org>" [unknown]

**Comment by purcell** [comment]
So this happened the first time you installed this config? Or just started happening now, after using the config for a while?

**Comment by abhiroopdatta7** [comment]
Hi.
Sorry you can close the issue. I saw that the issue is not with the config. Even when i removed the config the same issue i am getting.

**Comment by purcell** [comment]
Okay, thanks.
