### ISSUE TITLE
flycheck-clojure continues to complain after cider-jack-in

### ISSUE THREAD

**Issue by gustavjf** [purcell/emacs.d#711]
I am getting the following error every time flycheck-clojure encounters a problem in a Clojure buffer after running `cider-jack-in`.

```
Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 4) 0)
  #f(compiled-function (buffer ex rootex sess) #<bytecode 0x18b58a1>)()
  #f(compiled-function (response) #<bytecode 0x18b591d>)((dict "ex" "class clojure.lang.Compiler$CompilerException" "id" "33" "root-ex" "class clojure.lang.Compiler$CompilerException" "session" "33fc242a-f680-490e-ab84-7bfc8ecdd151" "status" ("eval-error")))
  nrepl--dispatch-response((dict "ex" "class clojure.lang.Compiler$CompilerException" "id" "33" "root-ex" "class clojure.lang.Compiler$CompilerException" "session" "33fc242a-f680-490e-ab84-7bfc8ecdd151" "status" ("eval-error")))
  nrepl-client-filter(#<process nrepl-connection> "d2:ex45:class clojure.lang.Compiler$CompilerException2:id2:337:root-ex45:class clojure.lang.Compiler$CompilerException7:session36:33fc242a-f680-490e-ab84-7bfc8ecdd1516:statusl10:eval-erroreed2:id2:337:session36:33fc242a-f680-490e-ab84-7bfc8ecdd1516:statusl4:doneeed18:changed-namespacesde2:id2:339:repl-type3:clj7:session36:33fc242a-f680-490e-ab84-7bfc8ecdd1516:statusl5:stateee")
```

Steps to reproduce:

1. Clone the config to ~/.emacs.d
2. Run `lein new app scratch` in the terminal.
3. Open Emacs
4. Navigate to `scratch/src/scratch/core.clj`.
5. Run `C-c M-j` or `M-x cider-jack-in` in the `core.clj` buffer.
6. Write incorrect Clojure code.
7. A new buffer with the error appears and no squiggly lines show up under the offending code.

![flycheck-clojure_error](https://user-images.githubusercontent.com/3981598/56455877-be2cd780-6364-11e9-9e91-a4c569b7a993.png)

What I've tried:

1. [Make sure](https://github.com/purcell/emacs.d/issues/382#issuecomment-281060475) `acyclic/squiggly-clojure` is included as a dependency when running `cider-jack-in` via `M-: cider-jack-in-dependencies [RETURN]`. It is:

![cider-jack-in-dependencies](https://user-images.githubusercontent.com/3981598/56455905-2bd90380-6365-11e9-84e6-c51bdd6bd252.png)

2. [Check if](https://github.com/clojure-emacs/squiggly-clojure/issues/47#issuecomment-288486651) `flycheck-clojure-setup` is evaluated after CIDER is loaded. It seems like this was already [done](https://github.com/purcell/emacs.d/commit/3ba677fd1da5c8e58fd07bb302aec601810135b2) in your config.

3. Check to see if `squiggly-clojure.core` is loaded in the CIDER repl. It seems to be loaded but when trying to evaluate `squiggly-clojure.core` in the repl, I get a `java.lang.ClassNotFoundException`. Since I'm new to Clojure and CIDER, I'm not sure if it's somehow related to the flycheck issue.

![squiggly-clojure_cider-repl-error](https://user-images.githubusercontent.com/3981598/56456014-67c09880-6366-11e9-872b-326850e97009.png)

Any ideas as to what might be causing this error? Should I move this issue to the CIDER or squiggly-clojure repos?

**Comment by purcell** [comment]
> Any ideas as to what might be causing this error? Should I move this issue to the CIDER or squiggly-clojure repos?

Unsure, sorry. I actually don't work with clojure these days, and the related code in my config is pretty basic.

**Comment by gustavjf** [comment]
No problem, thanks for having a look!
