### ISSUE TITLE
How to close function description in specific mode

### ISSUE THREAD

**Issue by yuanlai** [purcell/emacs.d#715]
If I use typescript mode, how to close the point-function-description in minibuffer.

<img width="576" alt="屏幕快照 2019-06-08 上午10 16 22" src="https://user-images.githubusercontent.com/10742934/59140894-96f29e00-89d6-11e9-951f-7f012aeed69d.png">

**Comment by purcell** [comment]
You can't "close" it, because the minibuffer might at any point display messages, and sometimes they are multi-line like this. But if you don't want these messages to appear at all, you can probably disable eldoc-mode, e.g. `(add-hook 'typescript-mode-hook (lambda () (eldoc-mode -1)))`.
