### ISSUE TITLE
guide-key breaks query-replace, making replace-string fail with args-out-of-bounds error

### ISSUE THREAD

**Issue by ysmolsky** [purcell/emacs.d#723]
On Emacs 26.2 guide-key breaks `replace-string` as vanilla and anzu commands. Disabling `guide-key-mode` helps. Guide-key package was abandoned, but I have created issue explaining what is wrong with it anyway: https://github.com/kai2nenobu/guide-key/issues/49

Not sure if you experience this kind of problem. I wanted to chime in to save others from the pain I had to go through: identifying the bad package was not trivial. 

If you can reproduce this with `replace-string`, and disabling it resolves the problem for you too, then I would advise to remove this from the config files as it is being used by, I suppose, many others.

According to the https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31586, it can affect users with Emacs > 24.5.

**Comment by purcell** [comment]
Closing because no longer using guide-key. :-)

Sorry for not responding earlier. I never saw this error myself.
