### ISSUE TITLE
Organizing configuration with org-mode.

### ISSUE THREAD

**Issue by jcguu95** [purcell/emacs.d#725]
This is more like a question rather than an issue.

I noticed that [Prof Zamansky](https://cestlaz.github.io/stories/emacs/) uses org-mode to organize his emacs configs. As a huge fan of org-mode, I am very happy with that solution, because org-mode makes the file easier to browse, read, distribute, export... etc. For example, [it](https://github.com/zamansky/using-emacs/blob/master/myinit.org) serves as a documentation for itself, and integrates with github well.

This can be done by adding `(org-babel-load-file (expand-file-name "~/.emacs.d/myinit.org"))` in `init.el`, and create another `.emacs.d/myinit.org` which contains the configs, self-commented! 

### Question
Are there any drawbacks that prevent you from using that method? What prevents you from using that? I'd like to combine advantages from both sides if there's none... 

Thank you very much in advance!

**Comment by jangid** [comment]
One of the biggest disadvantage of using ord-mode configuration files is that the syntax checkers don't work properly in org-mode. Checking will be done only at the run-time.

**Comment by purcell** [comment]
> because org-mode makes the file easier to browse, read, distribute, export... etc.

I don't really agree with this for cases when the org content is primarily code. For primarily textual content I like org-mode very much, and also for technical documentation with code snippets.

In particular with lisp, so many features in Emacs make emacs lisp seamless and convenient to work with, and most of them are made less seamless and convenient by the act of putting emacs lisp in org code blocks. (This is the superset of @jangid's specific point above.)

**Comment by jcguu95** [comment]
Thank you for the answer that came only after rich experience with working with emacs/lisp!
