### ISSUE TITLE
Code jumping support by dumbjump

### ISSUE THREAD

**Issue by lanzhiheng** [purcell/emacs.d#726]
Thank you for your configuration, it is very helpful for me, Sometimes I write C programming language in Emacs, I find that it is hard for me to find the definition of the function. I think the 
[dumbjum](https://github.com/jacktasia/dumb-jump) can be a suitable choice for it. Can I create the PR for supporting this feature ?

**Comment by purcell** [comment]
Hi! Thanks for getting in touch.

> Can I create the PR for supporting this feature ?

No thanks. I might try `dumb-jump` myself at some point (I've been thinking about it recently, actually), but in general I won't add anything to the config that I'm not using myself. So, you might see support arrive at some point, but in the meantime it should be easy to add it to your local config.

**Comment by jangid** [comment]
Lan <notifications@github.com> writes:

> Thank you for your configuration, it is very helpful for me, Sometimes I write C programming language in Emacs, I find that it is hard for me to find the definition of the function. I think the 
> [dumbjum](https://github.com/jacktasia/dumb-jump) can be a suitable choice for it. Can I create the PR for supporting this feature ?

This feature is built-in. Jumping to definition and back. It works for
elisp, c, c++, java and almost all programming languages.

I use these two key combinations: M-, M-.

**Comment by lanzhiheng** [comment]
@jangid Cool, It is a very useful feature. Another question, If we want to use the build in tags system we must generate the `TAGS` file manually first. Is there any plugins to make this process automatic ?

**Comment by jangid** [comment]
Lan <notifications@github.com> writes:

> want to use the build in tags system we must generate the `TAGS` file
> manually first. Is there any plugins to make this process automatic ?

[[info:emacs#Xref][info:emacs#Xref]]

As per the above info page, etags is shipped with Emacs. And this is
automatically activated by major-modes of various programming
languages. I didn't have to manually generate TAGS.

**Comment by lanzhiheng** [comment]
@jangid Oh, let me try it, thank you very much.
