### ISSUE TITLE
RET is mapped to paredit-newline in Python mode

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#729]
When editing the python code, the <enter> key is remapped to the command `paredit-newline`.
It will introduce an issue of format loss below the newline.
Could we remap the <enter> key to `newline-and-indent`?

Below is the key binding of python mode:

```
python-mode is an interactive autoloaded compiled Lisp function in
‘python.el’.

(python-mode)

Parent mode: ‘prog-mode’.

Major mode for editing Python files.

key             binding
---             -------

C-c             Prefix Command
RET             paredit-newline
ESC             Prefix Command
DEL             python-indent-dedent-line-backspace
<backtab>       python-indent-dedent-line
<remap>         Prefix Command

C-M-i           completion-at-point
C-M-x           python-shell-send-defun

C-c C-c         python-shell-send-buffer
C-c C-d         python-describe-at-point
C-c C-f         python-eldoc-at-point
C-c C-j         imenu
C-c C-l         python-shell-send-file
C-c C-p         run-python
C-c C-r         python-shell-send-region
C-c C-s         python-shell-send-string
C-c C-t         Prefix Command
C-c C-v         python-check
C-c C-z         python-shell-switch-to-shell
C-c <           python-indent-shift-left
C-c >           python-indent-shift-right

```

**Comment by purcell** [comment]
This was due to `paredit-everywhere`, which I've recently stopped using locally. I've pushed that change in eeee6adf.

**Comment by haifenghan** [comment]
After `git pull` and restart my emacs, I have the same issue.
How can I make it take effect?

**Comment by purcell** [comment]
Was this in buffers re-opened by `desktop.el`? In those cases, `desktop` restores the minor modes. You might consider explicitly uninstalling the `paredit-everywhere` package (or `M-x package-autoremove` should help), otherwise run `M-x normal-mode` in those buffers.

**Comment by purcell** [comment]
Sure, that would also work. :-)

**Comment by haifenghan** [comment]
Dear purcell,
After git pull again, I reactive the paredit-everywhere. It works fine and there is no such issue any more.
It must be others cause the issue. I'm sorry that my fault makes we lose the good package
I likes paredit-everywhere. Could you enable it again?

**Comment by purcell** [comment]
> Could you enable it again?

I probably won't, because I've stopped using it. If I notice that I miss it, I will restore it. In the meantime you can easily enable it in your local config if you like.

**Comment by haifenghan** [comment]
OK
