### ISSUE TITLE
Command as meta, or Option as meta

### ISSUE THREAD

**Issue by zhoulaifu** [purcell/emacs.d#730]
Hi, it seems that my meta-key is mapped to cmd with this setting, which is also reflected in your lisp/init-osx-keys.el:

  (setq mac-command-modifier 'meta)
  (setq mac-option-modifier 'none)

I wonder whether such is a personal choice or maybe it works better under some situations, e.g., remote access to servers. Is it safe to use Option as meta?

**Comment by jangid** [comment]
It is actually a matter of personal choice. You are right.

Also, just to inform you that Emacs 27 will have option-key mapped to
META and command-key mapped to SUPER. This will be default behaviour
which you obviously can modify. I kind of like this new mapping. Keeping
right-option and right-command free for MacOS default behaviour.

**Comment by purcell** [comment]
Yeah, the rationale for my defaults is that I quite like using `Option`-based composition of accented chars, e.g. Option-e e => é, and also Command is more ergonomic than Option on a Mac. It's a trade-off because Command-w in a terminal will definitely close the window, so in iTerm I set left Option to send Esc+, ie. Meta, and then I use Option as Meta in a terminal.

I don't know if this is the best setup for most users, but I keep using it because of the ergonomics of Command as Meta.

**Comment by jangid** [comment]
Yeah, I agree. Ergonimically Command key is best suited as Meta. But I
just trained my fingers to use left side keys for Emacs and right side
keys for MacOS related stuff.

I tried to use Caps-lock for Control and left-Command for Meta. That was
best ergonomics. But for some reason I switched back to my default setup
as specified above.

**Comment by purcell** [comment]
Haha, I never ever use the right-hand-side modifiers. Though I bought a wacky mechanical keyboard recently so I've been trying to train myself to use both sides. :-)

**Comment by jangid** [comment]
> Though I bought a wacky mechanical keyboard recently so I've been
> trying to train myself to use both sides. :-)

When I wasn't using Mac a decade ago, I was using TVS Keyboard. Love
it. It still is in good shape. Mechanical keyboards are a damn good
investment.

**Comment by purcell** [comment]
> It still is in good shape. Mechanical keyboards are a damn good investment.

Yep. Meanwhile:  https://twitter.com/sanityinc/status/1201596235678932995

**Comment by jangid** [comment]
> https://twitter.com/sanityinc/status/1201596235678932995
What a coincident! one other guy also has the f-key broken. Could this
be a manufacturing defect?

**Comment by purcell** [comment]
Everything about the keyboard is a manufacturing defect, haha!

**Comment by jangid** [comment]
hahaha! that's true.
