### ISSUE TITLE
How To disable a editing feature?

### ISSUE THREAD

**Issue by taotanty** [purcell/emacs.d#731]
When I coding,the config make some default action that I don't want.

1. for example with python:

`
def for_test():
    
def gen_test1(min, max):
l = []
if min > 0 and max > 0  and max > min:
`
I finished gen_test1 function first. 
Then I need add for_test before 'gen_test1' function.
When I wrote 'for_test():', and press enter key, 
the next function code become like before.

2. another example with lua ,the default action that I want to disable it.

`function Scene:test ()
end`
How Can I disable the default blank ?

**Comment by purcell** [comment]
Your comment has lost the indentation, so it's not clear what you mean, sorry. You can use <code>```</code> to  properly escape  multi-line  code examples. The lua example is also not clear: I can type that code snippet without problems.

**Comment by taotanty** [comment]
1. Line breaks affect the following code layout
2.`function Scene:test ()` to become `function Scene:test()`

**Comment by purcell** [comment]
I just can't duplicate that. I type `function Scene:test ()`, then return, and the line is left unchanged.

**Comment by taotanty** [comment]
Will, Maybe config something different between us
