### ISSUE TITLE
Cannot change to other disks in MS Windows

### ISSUE THREAD

**Issue by shrubbroom** [purcell/emacs.d#732]
When I tried to switch to other files via C-x C-f, I can't move my cursor to the head of the path, which means that I can only open the files under the head of "c:" in MS Windows. This troubles me much and I can only open the files in other disks with $ runemacs D: or $ runemacs E: when running the emacs.

**Comment by shrubbroom** [comment]
Sorry for that disturbing, I find that I can change to other files by simply input the absolute path of each file. This issue will be closed.

**Comment by purcell** [comment]
Glad you figured it out! 👍
