### ISSUE TITLE
Disable paredit, so can use parinfer

### ISSUE THREAD

**Issue by deoqc** [purcell/emacs.d#733]
Thx for the amazing package.

How is the best way to accomplish? Paredit seems scattered around, could not find a good way...

**Comment by purcell** [comment]
You'll have to edit the code a little. To keep the changes minimal, probably you can comment out `(require 'init-paredit)` in `init.el`, and add `(remove-hook 'sanityinc/lispy-modes-hook)` to `init-local.el`.
