### ISSUE TITLE
The time stamp produced by org-mode get garbled and Rg cannot search Chinese

### ISSUE THREAD

**Issue by eriFelaP** [purcell/emacs.d#736]
Hi Purcell，

I am an Emacs user from the Chinese world. I encountered two problems when using your configuration (without any modification) under Windows 10:

1. The time stamp produced by org-mode get garbled;

![1](https://user-images.githubusercontent.com/38934286/75642756-9510ef00-5c77-11ea-8259-e606e4c96496.PNG)

2. `rg` cannot search Chinese.

It is also impossible to write time stamp to the org-clock-save.el file due to the garbled.

![2](https://user-images.githubusercontent.com/38934286/75642791-be317f80-5c77-11ea-9e43-f0c4b97c1cc2.PNG)

I've found  commenting out the following two lines of code in `init-locales.el` can solve these problems.

``` elisp
(prefer-coding-system 'utf-8) ;; problem 2
(setq locale-coding-system 'utf-8) ;; problem 1
```

But I'm not sure that's the right way to change it, because I don't know exactly what these code mean. Maybe you have a more better solution:-)

PS: My Emacs version is `Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29`. My ripgrep version is `ripgrep-11.0.2-x86_64-pc-windows-msvc`

**Comment by purcell** [comment]
Aww, sorry to hear that. I would have trouble debugging this, due to the locale and not having access to a Windows machine. I know that there are a lot of Chinese users of this config, so perhaps someone could comment on this?

**Comment by eriFelaP** [comment]
Thank you for your reply!

For the first problem, We might be able to set the variable `system-time-locale` to `"C"` to avoid Chinese (or other non-english languages) in the timestamp. This will get around the problem for a while.

``` elisp
(setq system-time-locale "C")
```

As for the second problem, commenting out `(prefer-coding-system 'utf-8)` is obviously not a good idea, because in my case it makes garble in magit's commit log.

**Comment by Eason0210** [comment]
@eriFelaP  I suggest that you use the date in English format, which can completely solve this `coding system` problem.   
And also check the region setting as below: 
![image](https://user-images.githubusercontent.com/47546452/103608427-4ba7c500-4f56-11eb-8e48-254e68f1da35.png)
