### ISSUE TITLE
Failed to verify signature: mmm-mode-0.5.7.tar.sig

### ISSUE THREAD

**Issue by jangid** [purcell/emacs.d#739]
On a freshly checked out repository, I got this:

```
Warning (initialization): An error occurred while loading ‘/Users/pankaj/.emacs.d/init.el’:

Failed to verify signature: mmm-mode-0.5.7.tar.sig
```
and with ‘--debug-init’ option I get this

```
Failed to verify signature mmm-mode-0.5.7.tar.sig:
No public key for 066DAFCB81E42C40 created at 2019-09-21T23:25:58+0530 using RSA
Command output:
gpg: keyblock resource '/Users/pankaj/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory
gpg: Signature made Sat Sep 21 23:25:58 2019 IST
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
```

**Comment by purcell** [comment]
This isn't enough information, sorry - what Emacs version are you using, what platform are you on (looks like MacOS?) and do you have any local modifications? I'm on MacOS with Emacs 26.3 and don't see this issue.

**Comment by jangid** [comment]
Really sorry about that. Here is my environment.

I am on emacs-27 HEAD. Default build. No customizations. Just "make install" in it. And copied the "nextstep/Emacs.app" to "/Applications/". Yes I am on MacOS Catalina (10.15.3).

No customizations in "~/.emacs.d/" as well. I have deleted by previous "~/.emacs.d" and fresh cloned from this repo.

**Comment by purcell** [comment]
It's still a bit hard to comment on what might be causing this because when you build from source, you could be linking to various different versions of gnutls, openssl etc. You also may have various versions of gpg on your path. What I'd suggest would be to try downloading a build from emacsformacosx.com, and see whether you get the same issues. Both the 26.3 and 27pre builds from there work okay for me, which gpg 2.2.19 from homebrew on the path.

**Comment by jangid** [comment]
As you see in the above debug message,

`gpg: keyblock resource '/Users/pankaj/.emacs.d/elpa/gnupg/pubring.kbx'`

But when I inspect my `~/.emacs.d/` there is no `elpa` directory. Instead `elpa-27.0` is created by my build. But even in that directory there is no `.../gnupg/pubring.kbx`. I'll also try with emacs-26.3 and report.

**Comment by jangid** [comment]
With the version downloaded from emacsformacosx.com, this one warning for the first time. Next time it is okay.

`Error (frameset): Wrong number of arguments: #<subr set-window-fringes>, 5`

I also tried to launch from my own build of emacs-26 branch. With that also there are some problems. There is this message in minibuffer,
```
Recursive load: "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz", "/Users/pankaj/work/code/savannah/emacs/mybuild/emacs26/Emacs.app/Contents/Resources/lisp/server.el.gz"
```
And then M-x key also show the above message in minibuffer. So it interferes user actions.

For now, I am using the downloaded build. But let us keep it open for the upcoming 27.0 release.

**Comment by purcell** [comment]
> With the version downloaded from emacsformacosx.com, this one warning for the first time. Next time it is okay.

That's because of downgrading the version, so that the desktop saved by Emacs 27 can't be understood by Emacs 26.
