### ISSUE TITLE
anaconda-mode: logical and replaced with turned V

### ISSUE THREAD

**Issue by zbinkz** [purcell/emacs.d#743]
Hi, been using your config for a few weeks and just stumbled on this feature(?) in anaconda-mode. when typing logical and (or) it is automatically replaced with turned v (normal v). It happens everywhere in the python source except the comments. Tested it in the scratch buffer and it doesn't happen there so I guess it is specific to anaconda-mode. Google search gave nothing. Any idea why it's happening? Snapshot attached. I'm on Debian stable (10.4)

![Screenshot_20200528_202056](https://user-images.githubusercontent.com/46252795/83207277-cd15ba00-a120-11ea-8ebf-b80ead8e762c.png)

**Comment by purcell** [comment]
That's because I enable `global-prettify-symbols-mode`, and `python-mode` supports it: https://github.com/purcell/emacs.d/blob/master/lisp/init-editing-utils.el#L111

You can remove that line in your config if you prefer.

**Comment by purcell** [comment]
I have a kind of love/hate relationship with it, and might end up just not enabling it by default, ultimately.

**Comment by zbinkz** [comment]
Okay thanks. I'm definitely removing this option cause the code throws an error in python3 from the konsole. You got my vote for disabling it by default :)

**Comment by purcell** [comment]
> cause the code throws an error in python3 from the konsole

Well the code is just the same, and in a GUI Emacs frame, copying it gives the "and or" instead of the math chars, but I guess if you're using a terminal frame and copying/pasting via the terminal's built-in support, then this could happen, yes!

**Comment by purcell** [comment]
I've just turned it off by default, anyhow! :-)
