### ISSUE TITLE
menu-bar-lines

### ISSUE THREAD

**Issue by donneyT** [purcell/emacs.d#744]
<img width="648" alt="截屏2020-07-23 下午4 18 22" src="https://user-images.githubusercontent.com/60682638/88273491-d8dec080-cd0c-11ea-8737-fc6a91851176.png">

on my macOS 10.15 
emacs 26.3 
your emacs.d 

(menu-bar-mode -1) can work both on  GUI/Terminal

don`t need set menu-bar-lines

but if hack emacs like pic   when emacs start   the menu-bar still there

I don't understand the purpose of this

<img width="648" alt="截屏2020-07-23 下午4 18 22" src="https://user-images.githubusercontent.com/60682638/88276363-7fc55b80-cd11-11ea-8d13-9e1e9dc57f78.png">

**Comment by purcell** [comment]
Agreed, fixed.
