### ISSUE TITLE
agenda can`t work

### ISSUE THREAD

**Issue by donneyT** [purcell/emacs.d#745]
[屏幕录制2020-07-28 下午5.35.11.zip](https://github.com/purcell/emacs.d/files/4987733/2020-07-28.5.35.11.zip)

emacs26.3  macOS 10.15.6  your emacs.d

(setq org-default-notes-file " ~/.emacs.d/refile.org")
(setq org-agenda-files " ~/.emacs.d/refile.org")
I set the value of the variable then use the c-c c org-capture
create a TODO or NOTE
next  c-c a open agenda list
press a
can`t show agenda view 
I don`t what happened

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/60682638/88655799-d364ea00-d101-11ea-876c-89f772aaa3fd.png">

**Comment by donneyT** [comment]
some info:         Non-existent agenda file ~/org/* NEXT 12313123. [R]emove form list or [A]bort?
bu

**Comment by purcell** [comment]
I don't think this problem is specific to this configuration, sorry. Try actually killing the agenda buffer, in case the action you were performing is just trying to reload it with an old set of agenda files.
