### ISSUE TITLE
Error on Emacs 27: load-history-filename-element: Wrong type argument: stringp, (require . server)

### ISSUE THREAD

**Issue by luozikuan** [purcell/emacs.d#748]
every time I open a org file or enter org-mode manually, it shows `Wrong type argument: stringp, (require . server)` on minibuffer. I tried reset whole .emacs.d to the latest status of origin master, it persist.

**Comment by vietor** [comment]
Upgrade the emacs version.

https://emacsformacosx.com/ the newest version is 27.1-1

**Comment by purcell** [comment]
I'm running 27.1 now, having upgraded from 26.3, and I haven't seen this issue at all. Additionally, all the startup tests pass in CI for all the stable versions of Emacs. If you can provide a method for reproducing this, let me know.

**Comment by luozikuan** [comment]
> Upgrade the emacs version.
> 
> https://emacsformacosx.com/ the newest version is 27.1-1

It works!!! thank you!!!

**Comment by luozikuan** [comment]
> I'm running 27.1 now, having upgraded from 26.3, and I haven't seen this issue at all. Additionally, all the startup tests pass in CI for all the stable versions of Emacs. If you can provide a method for reproducing this, let me know.

Thanks for the reply, the problem is gone after I upgraded to 27.1-1   :-)
