### ISSUE TITLE
It seems that my (server-running-p) always return "t".  

### ISSUE THREAD

**Issue by zhoulaifu** [purcell/emacs.d#750]
It seems that under this setting my (server-running-p) always returns "t".  Is it expected?

**Comment by purcell** [comment]
Yes, see https://github.com/purcell/emacs.d/blob/master/init.el#L160-L164

Is this causing problems for you?

**Comment by zhoulaifu** [comment]
I see. And thank you for pointing out the exact lines where "server-start" is invoked. 

It is a minor issue for me because when I double-click a file, say an ORG file, from a Finder window (Mac OS), a new Emacs frame opens with apparently a new server. But   actually I would hope that double-click an ORG file should be associated with. "emacsclient", the one without  "server-start".  I see some SO answers on how to. associate double-click with "emacsclient", like [this one ](https://stackoverflow.com/questions/45548847/how-to-open-an-emacs-file-in-os-x-by-double-clicking-on-it-using-the-emacsclie). But I would like to know what would you do if you want to launch emacsclient from a non-terminal place like Finder. 

Many thanks!

**Comment by zhoulaifu** [comment]
Finally, I use Automator to create emacsclient script. Double-link is then associated with emacsclient. It seems unnecessarily complex though.
