### ISSUE TITLE
whole-line-or-region-comment-dwim-2 doesn't work fine on a blank line

### ISSUE THREAD

**Issue by haifenghan** [purcell/emacs.d#751]
Dear @purcell 

When pressing the M-j, it will call the function `whole-line-or-region-comment-dwim-2`.
It works fine on a non-blank line.

However, on a blank line, it will mark the line from the beginning of the line to the indentation position.
There is no comment added.

Could you look at it?

Environment: Emacs 27.1, whole-line-or-region: 20200911.2339

Thanks

**Comment by purcell** [comment]
Hmm, good catch -- I'll take a look at this
