### ISSUE TITLE
Get 'end of file during parsing' error for uptimes.el

### ISSUE THREAD

**Issue by ziyunch** [purcell/emacs.d#753]
Just upgraded to Emacs 27.1 (OSX Catalina), and I got "uptimes-read-uptimes end of file during parsing" and "Error running timer 'uptimes-saves': (End of file)" errors, and this prevents me from exiting Emacs.

I am able to exit Emacs only by comment out line149-151 in init.el and delete the package. Is this an incompatible issue for uptimes and Emacs 27?
```
;;(when (maybe-require-package 'uptimes)
;;  (setq-default uptimes-keep-count 200)
;;  (add-hook 'after-init-hook (lambda () (require 'uptimes))))
```

**Comment by purcell** [comment]
Sounds like your uptimes save file is corrupt. Try deleting `~/.emacs.d/.uptimes.el`

**Comment by ziyunch** [comment]
Deleting ` ~/.emacs.d/.uptimes.el` seems working, thanks! Strangely this file was empty.

**Comment by purcell** [comment]
Weird. I've never seen that happen locally.

**Comment by rxa254** [comment]
same issue in Ubuntu 22; same fix works 4 years later!

**Comment by purcell** [comment]
Yeah, it's mysterious. I don't see that the `uptimes` author @davep has received any bug reports about it. Getting `End of file` while saving the uptimes seems very unusual!

**Comment by davep** [comment]
Yup, can confirm that in the 25 years that `uptimes` has been around, nobody has ever approached me with this at all, let alone with a reproducible example of it.

I guess I could add some sort of guard against the "database" being empty, but I sense it would be more interesting if those seeing the problem could isolate a method of reproduction.
