### ISSUE TITLE
win 10 System encoding ?

### ISSUE THREAD

**Issue by aaa1999** [purcell/emacs.d#754]
Hello,I am a greenhand on emacs.I learned emacs some days ago.Today,I try to git clone your emacs config files.But I encountered a problem.After I gitted clone your config files.Some errors happened on My emacs on win10.The errors are alike the charset can't encode some chars.I tried to select my charsets (gbk).But after a while,the same errors happend .I don't know why.Could you please tell me what I can do to fix this problem?I think it's a bug in your config files.

thanks.Best wishes!

**Comment by purcell** [comment]
Hmm, not sure, sorry. Any Windows users able to comment here please?

**Comment by aaa1999** [comment]
ok,I solved this problem in other forms.Thank you for spending time on my questions.Thanks a lot.

**Comment by aaa1999** [comment]
In win10.you can write this 


```
(when (eq system-type 'windows-nt)
 (setq gc-cons-threshold (* 512 1024 1024))
 (setq gc-cons-percentage 0.5)
 (run-with-idle-timer 5 t #'garbage-collect) 
  (setq garbage-collection-messages t) )
```


in your init.el files.
It can fix your problesm a lot.
