### ISSUE TITLE
Couldn’t install optional package

### ISSUE THREAD

**Issue by yangli0534** [purcell/emacs.d#755]
Contacting host: melpa.org:443
Couldn’t install optional package ‘yaml-mode’: (file-error "https://melpa.org/packages/yaml-mode-20200725.1836.el" "Not found")
Contacting host: melpa.org:443
Couldn’t install optional package ‘docker-compose-mode’: (file-error "https://melpa.org/packages/yaml-mode-20200725.1836.el" "Not found")
Contacting host: melpa.org:443
Couldn’t install optional package ‘terraform-mode’: (file-error "https://melpa.org/packages/terraform-mode-20170112.517.el" "Not found")
Couldn’t install optional package ‘nix-mode’: (file-error "https://melpa.org/packages/nix-mode-20200915.1537.tar" "Not found")
Couldn’t install optional package ‘auto-compile’: (file-error "https://melpa.org/packages/packed-20180318.1729.el" "Not found")
Contacting host: melpa.org:443
Couldn’t install optional package ‘cider’: (file-error "https://melpa.org/packages/parseclj-20190531.711.tar" "Not found"

**Comment by purcell** [comment]
`M-x package-refresh-packages`.

**Comment by purcell** [comment]
See the "Updates" section in the README...
