### ISSUE TITLE
errata: site-lisp/README

### ISSUE THREAD

**Issue by snowman** [purcell/emacs.d#756]
https://github.com/purcell/emacs.d/blob/b8948ae6ea8ac63a090682cc89049d3eb900157d/site-lisp/README#L1-L3

> `This directory (errata: does not added to load-path)` and its immediate subdirectories will be added to load-path at start-up time.

https://github.com/purcell/emacs.d/blob/b8948ae6ea8ac63a090682cc89049d3eb900157d/lisp/init-site-lisp.el#L7-L20

**Comment by purcell** [comment]
Sorry, it's not clear what the issue here is.

**Comment by snowman** [comment]
The content of https://github.com/purcell/emacs.d/blob/master/site-lisp/README says:

> This is a place for 3rd party code which isn't available in MELPA or
> other package repositories.
> 
> This directory and its immediate subdirectories will be added to
> load-path at start-up time.

but https://github.com/purcell/emacs.d/blob/b8948ae6ea8ac63a090682cc89049d3eb900157d/lisp/init-site-lisp.el#L7-L20 only adds every non-hidden immediate subdirectories, and not including the `site-lisp/` folder itself into `load-path`.

**Comment by purcell** [comment]
> only adds every non-hidden immediate subdirectories, but not including the site-lisp/ parent folder itself into load-path.

Are you sure? Locally, I can see that `~/.emacs.d/site-lisp` is in `load-path`.

**Comment by snowman** [comment]
![1605517700](https://user-images.githubusercontent.com/16096559/99233569-5edbc580-282e-11eb-83b8-4fe80fd76e87.png)

![output](https://user-images.githubusercontent.com/16096559/99236531-479ed700-2832-11eb-9ddf-91ea53a1f758.png)
