### ISSUE TITLE
init-python.el

### ISSUE THREAD

**Issue by ncouture** [purcell/emacs.d#757]
Don't get me wrong, after discovering pyenv and pyenv-virtualenv[1] I feel in love with the ability to have just any Python at my fingertips, and completion-mode with documentation at point is very nice to have.

What I'd like to question is how safe are these project to run on your local computer? They perform an insane amount of operations and the overall source code for the project and its dependencies would take me a full-time year to wrap my head around.

And so it falls in the same bucket as nvm, npm; nice but potentially highly insecure.

How do you deal with this? If it possible to run them in a virtual machine transparently from Emacs?

Thanks for the advice,
Nicolas

1) https://gist.github.com/purcell/81f76c50a42eee710dcfc9a14bfc7240

**Comment by ncouture** [comment]
Do you work in a virtual machine?

**Comment by purcell** [comment]
Firstly, I don't work with Python very much these days at all. But I've actually switched to using nix + direnv instead of virtualenv/pyenv, and it is an approach which extends to other languages too. I recorded a screencast about this: https://www.youtube.com/watch?v=TbIHRHy7_JM&feature=youtu.be
