### ISSUE TITLE
Disabling fringe indicators / ruler guides

### ISSUE THREAD

**Issue by RyanMcCarl** [purcell/emacs.d#770]
Hello, I am using this repo as my base emacs config. Does anyone know where these fringe ruler guides are coming from and how to disable them?

![image](https://user-images.githubusercontent.com/13208682/108106387-bc0c3080-7042-11eb-9d1e-9be2b42e32f5.png)

**Comment by purcell** [comment]
I think this is due to `indicate-buffer-boundaries`, set in `init-editing-utils.el`. You should be able to change it locally, or override it using customisation or your `init-local.el`.
