### ISSUE TITLE
selectrum change the default minibuffer height

### ISSUE THREAD

**Issue by Eason0210** [purcell/emacs.d#773]
Hi @purcell ,

With the latest version of selectrum, when we use` C-x, b `or `M-x` , the height of minibuffer will only show one candidate.  
it can be change back to old behavior by below setting :
```
  (setq-default selectrum-fix-vertical-window-height t)
```
![image](https://user-images.githubusercontent.com/47546452/108681720-6fd15c80-752a-11eb-8368-e172b39f6099.png)

OS: Arch Linux, Emacs 28.0.50/ Emacs 28.0.50 native-comp
OS: Windows 10 20H2 , Emacs 28.0.50 native-comp

**Comment by ctrl2wei** [comment]
Try to set marginalia-align-offset. I rely on this to solve this problem.

**Comment by Eason0210** [comment]
> Try to set marginalia-align-offset. I rely on this to solve this problem. 
Thanks, It seems this problem is not from selectrum only. Because, it works well on my Macbook and other set of Windows computer.

**Comment by purcell** [comment]
This is actually an upstream bug

https://github.com/raxod502/selectrum/issues/435

**Comment by purcell** [comment]
I'll probably commit the workaround for now, but it's not ideal, and I've been chasing up the issue for a few days.

**Comment by Eason0210** [comment]
I close this issue, since we have switch to vertigo.

**Comment by purcell** [comment]
Ah, true, thanks.
