### ISSUE TITLE
What is the right way to remove a package included in purcell / emacs.d  

### ISSUE THREAD

**Issue by wickedjargon** [purcell/emacs.d#776]
I am attempting to remove/disable paredit, but can't find a way to do it successfully. Can you please advise what is the best way to remove or disable this package? I'd like it either removed or disabled by default.

**Comment by purcell** [comment]
In that specific case you can probably put the following in `init-local.el`:

```el
(remove-hook 'sanityinc/lispy-modes-hook 'enable-paredit-mode)
```

**Comment by purcell** [comment]
The general answer is that you could edit `init-lisp.el` directly in your fork.
