### ISSUE TITLE
The order of company candidates is incorrect in Emacs lisp mode

### ISSUE THREAD

**Issue by Eason0210** [purcell/emacs.d#778]
Hi @purcell , with latest commit, the order of company candidates is incorrect in Emacs lisp mode. 
But it works well in the other major modes .

![image](https://user-images.githubusercontent.com/47546452/120056135-f0917e80-c06c-11eb-83c3-d4ec80503a14.png)

[similar issue, orderless & company-capf](https://github.com/oantolin/orderless/issues/23)

**Comment by purcell** [comment]
So `completion-styles` was set to `(substring orderless)`, and that var apparently affects completion-at-point. The solution here was to remove `substring` from `completion-styles`: the new value is `(basic partial-completion orderless)`.

**Comment by yugaego** [comment]
Not as a fix, but as an additional option, you might also be interested to try [company-transformers](https://github.com/company-mode/company-mode/blob/ee3177cdad47cbe92242eeb52c7bdb9505282db6/company.el#L474) customization setting. Such as, f.i.
`(setq company-transformers '(company-sort-by-occurrence))`

**Comment by purcell** [comment]
Interesting, thanks. I checked it out briefly but it wasn't obvious to me if there'd be a benefit right now.

**Comment by Eason0210** [comment]
Hi, @purcell    
Now we have changed the completion style  to `  (setq completion-styles '(basic partial-completion orderless))` globally, this also affect the completion in minibuffer.  Now the behavior is like this:
<img width="812" alt="before" src="https://user-images.githubusercontent.com/47546452/122626063-e6e2c000-d0da-11eb-8077-6da874e6d72a.png">

I think it is better to set minibuffer completion-styles to use only orderless to get a better experience.   
something like this would work.

```
    (defun sanityinc/use-orderless-in-minibuffer ()
    (interactive)
    (setq-local completion-styles '(orderless)))
  (add-hook 'minibuffer-setup-hook 'sanityinc/use-orderless-in-minibuffer)
```
Now it the behavior is like this:
<img width="824" alt="after" src="https://user-images.githubusercontent.com/47546452/122626086-00840780-d0db-11eb-9283-0e5fe3e143b3.png">

**Comment by purcell** [comment]
Agree, done

**Comment by liuyinz** [comment]
@purcell After I set a local value in minibuffer, It seems confilct with consult async related command.

 See https://github.com/minad/consult/issues/396, the origin grep and filter style fails.
