### ISSUE TITLE
copy, paste doesn’t work properly

### ISSUE THREAD

**Issue by Oferiston** [purcell/emacs.d#782]
i don’t know whether it’s because of my operations or not.

C-Space select a region 
M-w while the region is still highlighted
C-g to cancel the highlight
Move the cursor to the right position and C-y
It returns nothing or just the old content in the clipboard.

However C-w can work.

Version: emacs 25.3  Os: opensuse

**Comment by purcell** [comment]
> C-Space select a region
> M-w while the region is still highlighted

For me, this already cancels the highlight. :-/

> C-g to cancel the highlight

**Comment by Oferiston** [comment]
Thanks. I don't know why when i pressed M-w the mark was still highlighted. Problem solved.
