### ISSUE TITLE
emacs 27.2 custom.el can’t be saved

### ISSUE THREAD

**Issue by Oferiston** [purcell/emacs.d#783]
Each time i open the emacs, the new content i wrote in custom.el and init.el are cleaned. Which means i can’t do any customizations. 

* Emacs 27.2, Os opensuse leap 15.2 
* I installed emacs via snap(another package manager) not zypper cause zypper only provides emacs 25.3.

**Comment by Oferiston** [comment]
i installed emacs 27.2 through zypper which still doesn’t solve the problem.

**Comment by Oferiston** [comment]
problem solved.
When i initialized emacs, there is an error missing right version of cl-lib-highlight. so i deleted the use in init-lisp.el. And then restart emacs. All things are ok now,

**Comment by purcell** [comment]
>  there is an error missing right version of cl-lib-highlight. so i deleted the use in init-lisp.el.

That's fixed now, the package disappeared recently.
