### ISSUE TITLE
How to disable fill-column-indicator

### ISSUE THREAD

**Issue by wereket** [purcell/emacs.d#788]
Hello
when in a buffer M-x global-display-fill-column-indicator-mode removes the indicator.
I want it removed for good.
I put in my config 
(global-display-fill-column-indicator-mode -1) does not work
(global-display-fill-column-indicator-mode nil) does not work

![image](https://user-images.githubusercontent.com/89839215/133905883-da1c040b-200c-4aa4-8892-5304335923cf.png)

I am talking about the doted lines in the middle

Thanks for your time

**Comment by Eason0210** [comment]
@wereket  you can try  set `(setq-default display-fill-column-indicator-character "")` to get the same result you need.

**Comment by purcell** [comment]
I don't enable it globally. Rather, it is enabled explicitly in `prog-mode` by [this code](https://github.com/purcell/emacs.d/blob/master/lisp/init-editing-utils.el#L104). You can remove that code in your fork if you like.
