### ISSUE TITLE
`ob-ledger` may be deprecated in the git branch emacs29

### ISSUE THREAD

**Issue by hammerfunctor** [purcell/emacs.d#791]
As the title says, `org-mode` is broken in emacs29.

**Comment by Eason0210** [comment]
Because, in Emacs29, org-mode has been updated to version 9.5 .
The `contrib/` now lives in a separate repository.  See details:  https://orgmode.org/Changes.html

**Comment by purcell** [comment]
I still don't understand what is being reported or proposed here, sorry.

**Comment by hammerfunctor** [comment]
> I still don't understand what is being reported or proposed here, sorry.

For some input-method problems, I used `emacs-git` on my ArchLinux desktop. Then someday I routinely rolling update packages, `emacs-git` is silently updated to Emacs-29. Next time when I start Emacs and open a org file, Emacs fails to initialize org-mode, with `ob-ledger not found` or something printed in Message buffer.

As @Eason0210 said, some breaking changes occur in Emacs-29.

**Comment by purcell** [comment]
Super, thanks - I've committed a workaround.
