### ISSUE TITLE
Newline behavior affect the indentation

### ISSUE THREAD

**Issue by Eason0210** [purcell/emacs.d#792]
@purcell ,

I found that the indentation of close brace ( `}`)  and backet (`]` ) is wrong in` nix-code`, `c/c++-mode`, `js-mode` and so on.

You can reproduce it by input the code ` programs = { };`, and then press Enter inside the  `{ }` in `nix-mode`.

for example, this is my darwin.nix:

``` nix
{ pkgs, lib, config, ... }:

let home           = builtins.getEnv "HOME";
    tmpdir         = "/tmp";
in {
  imports = [ <home-manager/nix-darwin> ];

  programs = { #cursor is here, and Press Enter.

}; # this line will indent to the beginning of line.
}
```

And I found that it is the new line behavior affect the indentation.
https://github.com/purcell/emacs.d/blob/85ce2603e1b891bfa98f40ed3b9018024c62dc14/lisp/init-editing-utils.el#L79

**Comment by zhou1615** [comment]
I am not sure, but it seems the logic of newline-and-indent is changed.
I changed it to (global-set-key (kbd "RET") 'newline), everything works fine for me.

**Comment by purcell** [comment]
Hmm, I can't reproduce the initially-reported issue locally, with Emacs 28.1.

**Comment by tsilvap** [comment]
I can confirm this issue is still happening. I noticed this problem in `cperl-mode`, `c-mode`, and `js-mode`. I assume it happens in all prog-modes that use braces for blocks.

I'm providing the steps that I used to reproduce as well, in case it helps (Emacs 28.2, clean clone of the repo):
1. Open a new C file, say "main.c".
1. Insert the following code (except for the `|`, which represents where the cursor should be):
   ``` c
   int main()
   {
     if (a >= b) {|}
   }
   ```
1. Press `<return>` (or `M-x newline-and-indent`).

**Expected behavior**
``` c
int main()
{
  if (a >= b) {
    |
  }
}
```

**Actual behavior**
``` c
int main()
{
  if (a >= b) {
    |
}
}
```

**Comment by betaprior** [comment]
I am running into the same behavior with doom emacs running on 28.2.  As usual, it's easier to patch around a problem than figure out what's going on:

```
(defun my/fix-indentation-after-newline ()
  (save-excursion
    (next-line)
    (beginning-of-line)
    (if (looking-at "^[})]") (indent-according-to-mode))))

(advice-add 'newline-and-indent :after 'my/fix-indentation-after-newline)
```

**Comment by 4wardx** [comment]
Just as @tsilvap described, this unexpected behavior was triggered by `newline-and-indent`. After commenting the below line, problems will be solved.
https://github.com/purcell/emacs.d/blob/a9e0eb8c79293954b1d9a9d74c869c14fbe2992c/lisp/init-editing-utils.el#L72

But I am still thinking whether there exists a better solution for this. Anyway, the above method is an expedient for this issue.

**Comment by 4wardx** [comment]
Besides what @tsilvap has described, I found this behavior maybe caused by the conflict between `electric-pair-mode` and `newline-and-indent`.

If I turn off`electric-pair-mode` and run `newline-and-indent`, things go right, or turn on `electric-pair-mode`  and run `newline`, which is also works.

**Comment by 4wardx** [comment]
Besides what @tsilvap has described, I found this behavior maybe caused by the conflict between `electric-pair-mode` and `newline-and-indent`.

If I turn off`electric-pair-mode` and run `newline-and-indent`, things go right, or turn on `electric-pair-mode`  and run `newline`, which also works.
