### ISSUE TITLE
Hard to see curly brackets in exported HTML from org-mode

### ISSUE THREAD

**Issue by yszhang95** [purcell/emacs.d#799]
Using the night theme, the curly brackets for `C++` blocks in the exported HTML are very close to white and hard to visualize. Switching to day theme, it is fine to see brackets. Would you take this as an issue or suggest to make use of day theme instead? Many thanks in advance! The platform is fedora 34. I am not sure if this is a platform issue.

**Comment by purcell** [comment]
I imagine this means there's a face that is not customized in my `tomorrow` themes. Could you let me know which face that is? `M-x describe-face` on the curly bracket in the corresponding C++ buffer should tell you.

**Comment by yszhang95** [comment]
Under the theme 'tomorrow-night', putting the cursor on the outermost curly bracket in the org file, it shows `rainbow-delimiters-depth-1-face`. I also checked the HTML source text. It shows the corresponding markup is `<span style="color: #eaeaea;">{</span>`. I have a white background in the `firefox`.

And the outermost parentheses also have the similar issue, with `rainbow-delimiters-depth-1-face`, and the same markup in HTML. I am not sure if this is related to configurations for HTML exportation. Only the outermost brackets are hard to visualize.

I am using `org-mode 9.5` from `MELPA`, which is the first version shipped with `citation` functionalities.

**Comment by yszhang95** [comment]
Let us close it. I do not have a better choice to customize the font face. I can work with light theme. Thanks for the discussions!
