### ISSUE TITLE
consult--source-file and consult--source-project-file not found in consult.el

### ISSUE THREAD

**Issue by DavidRodGom** [purcell/emacs.d#802]
Dear @purcell,

I've cloned the repo this morning and, upon executing C-x b (switch-to-buffer) I've been getting error messages about 
`consult--source-file` and `consult--source-project-file` not being available. After looking into consult.el, neither are defined as defvars. Not being a LISP expert, I have opted for editing (locally) the init-minibuffer.el file as such: 

```
(sanityinc/no-consult-preview
     consult-ripgrep
     consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-recent-file consult--source-project-recent-file consult--source-bookmark)
;;   consult--source-file consult--source-project-file consult--source-bookmark)
```
It seems to work nicely now. Not sure if the issue is on my side, but better to report it than not. Hope it helps.

Note: I work with GNU Emacs 28.0.91, installed via Homebrew as `brew install d12frosted/emacs-plus/emacs-plus@28`
The file consult.el sits in `./.emacs.d/elpa-28.0/consult-20220207.2239/consult.el`

**Comment by purcell** [comment]
Fixed by #801, thanks
