### ISSUE TITLE
Rust flycheck setup no longer working

### ISSUE THREAD

**Issue by sgarciac** [purcell/emacs.d#808]
As far as I understand, 

```lisp
(when (maybe-require-package 'flycheck-rust)
  (with-eval-after-load 'rust-mode
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup)))
```

in the rust initializer is no longer working after the change from flycheck to flymake, but it is still needed. I got it working by replacing 'flycheck-mode-hook by 'flymake-mode-hook in the add-hook call.

**Comment by sgarciac** [comment]
Im closing this issue until I'm sure it's a problem with the initialization file and not some conflict with my own setup.

**Comment by purcell** [comment]
True, because flycheck-mode is never enabled. Instead, it should probably be
```el
(when (maybe-require-package 'flycheck-rust)
  (with-eval-after-load 'rust-mode
    (with-eval-after-load 'flycheck
      (flycheck-rust-setup))))
```
Would you like to test that out locally?

**Comment by purcell** [comment]
Hmm, in fact, that's not quite it. I'd probably try adding `flycheck-rust-setup` to `rust-mode-hook` instead.

**Comment by sgarciac** [comment]
```elisp
(when (maybe-require-package 'flycheck-rust)
  (with-eval-after-load 'rust-mode
    (add-hook 'rust-mode-hook #'flycheck-rust-setup)))
```
does work locally for me.

**Comment by purcell** [comment]
This got added to the default config, so closing now...
