### ISSUE TITLE
eldoc error: (void-function eldoc-documentation-compose)

### ISSUE THREAD

**Issue by tsilvap** [purcell/emacs.d#810]
I'm getting this error if I open e.g. a Python file.

This function is defined in `elpa-27.1/eldoc-1.11.1/eldoc.el`, but if I try to search for it with `C-h f` it doesn't show up. Even if I evaluate `(require-package 'eldoc)`, it still doesn't work. However, if I go to the `eldoc.el` file and evaluate the entire file, it works and the problem goes away.

I'm not really sure what is the right way to fix this.

**Comment by Eason0210** [comment]
Maybe you can try to update to Emacs 28.1, which is the latest stable release version.

`eldoc-documentation-compose` is a new function introduced at Emacs 28: https://github.com/emacs-mirror/emacs/commit/c0fcbd2c119b8418855f0931aceefbef717c5e53

**Comment by tsilvap** [comment]
I see, that worked for me. Thank you @Eason0210

**Comment by purcell** [comment]
Ah, good call, I should make sure this still works in older emacsen.
