### ISSUE TITLE
Improperly set `completion-styles` make `consult-line` and `vertico-repeat` not functionally well.

### ISSUE THREAD

**Issue by lynnux** [purcell/emacs.d#811]
Setting this https://github.com/purcell/emacs.d/blob/b484cada4356803d0ecb063d33546835f996fefe/lisp/init-minibuffer.el#L13-L15 
will cause two problem relate to `consult-line` and `vertico-repeat`, details see:
https://github.com/minad/consult/issues/571
https://github.com/minad/vertico/issues/227
After setting recommand by minad, like:
```
(setq completion-styles '(orderless basic)
      completion-category-defaults nil
      completion-category-overrides nil)
```
all problems are solved.

**Comment by minad** [comment]
To elaborate a bit.

- I recommend to set consistent completion-styles globally, e.g., orderless and basic.
- The completion-category-defaults and completion-category-overrides can be set for fine tuning per completion category.
- For completion-at-point/Corfu/Company I recommend to adjust the completion styles very locally only where the candidates are computed. In the case of Company this is the function company-capf--candidates, as documented in the [Orderless README](https://github.com/oantolin/orderless/blob/75eeae21971d86b51a712ed8ecd6434463b2d866/README.org#company.). However it may not even be necessary to do this. For Corfu I use my global default completion styles settings, which work well and give a consistent behavior across completion.

See also the [basic Vertico configuration](https://github.com/minad/vertico#configuration) and my elaborate [Orderless configuration](https://github.com/minad/consult/wiki#minads-orderless-configuration), if you are interested in going down that rabbit hole.

**Comment by purcell** [comment]
Thanks folks, yeah, I'll review the settings and make adjustments — thanks for providing such useful feedback.

**Comment by purcell** [comment]
I believe this is fixed now btw, thanks all.

**Comment by minad** [comment]
Thx! Just fyi, I updated Consult such that setting the completion-styles locally in the minibuffer (and per buffer) would work now properly. The minibuffer-local setting would then be used for minibuffer completion (e.g. Vertico) and the buffer-local setting in normal buffers would only apply to in-buffer completion (e.g. Corfu). But I still recommend setting completion styles globally for consistency. Tweaks can be made per completion category (completion-category-defaults, completion-category-overrides).

**Comment by purcell** [comment]
Great, thanks for taking the time to follow up with this extra info.
