### ISSUE TITLE
Error when switching from buffer opened with tramp

### ISSUE THREAD

**Issue by leeb-dev** [purcell/emacs.d#813]
Hi,

(OpenBSD 7.1 x86_64/Emacs 27.2/emacs.d cloned June 8)

When switching (C-x b) from a buffer opened with tramp, Emacs pauses (the pointer turns to a watch) then eventually returns an error in the minibuffer:

`cl-no-applicable-method: No applicable method: project-root, (vc . "/ssh:myhost.mydomain.com:/home/myuser/my-repo/")`

C-x C-b works fine - I get the full window buffer list, and can select a buffer to switch to.

C-x b also works fine, provided my current buffer is not using tramp. Any ideas?

**Comment by leeb-dev** [comment]
Ignore me. I thought I'd updated my packages, but hadn't. Updating from melpa seems to have fixed it.

Sorry.

**Comment by purcell** [comment]
Cool, glad you figured it out, thanks!
