### ISSUE TITLE
In eshell-mode , If I try to type string within "",  Emacs will add space automaticly between each char of this string.

### ISSUE THREAD

**Issue by yuanli186** [purcell/emacs.d#818]
Hello, purcell!

The issue:
In eshell-mode , If I try to type string within "",  Emacs will add space automaticly between each char of this string. i.e "helloword" will in below format:

"	h	e	l	l	o	w	o	r	l	d	"

My emacs env:
GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2022-05-12

How to stop the space input action?
Thanks!

**Comment by purcell** [comment]
This was a strange side-effect of enabling `corfu-auto` globally. I've solved the issue by unsetting that in `eshell-mode`, but I wonder if @minad has any thoughts about this?

**Comment by minad** [comment]
@purcell You can enable corfu-auto globally. But for Eshell you have to install workarounds, see https://github.com/minad/corfu#completing-in-the-eshell-or-shell. Unfortunately the pcompletr mechanism is slightly broken at least until Emacs 28. My cape package provides advices which fix this.

**Comment by purcell** [comment]
Thanks, looks like my quick fix might not be sufficient then. I'll follow your pointers. 🙏

**Comment by yuanli186** [comment]
@purcell @minad Thank you very much for your help!
