### ISSUE TITLE
How to disable auto-completion?

### ISSUE THREAD

**Issue by JiatuYan** [purcell/emacs.d#821]
I imported cdlatex package to write mathematic symbols by latex. To jump from one curly braces to another, i need tap tab frequently. However the auto-completion always opens a list and disable such jump. This really slows down my coding since i have to use C-C C-G to close the annoying list.

**Comment by purcell** [comment]
You should be able to set `corfu-auto` to `nil` locally in that mode, something like
```el
(add-hook 'latex-mode-hook (lambda () (setq-local corfu-local nil)))
```

**Comment by purcell** [comment]
Or if you don't want auto-completion anywhere, edit the corresponding line in `init-corfu.el`

**Comment by JiatuYan** [comment]
Maybe my package's version is so outdated that it does not have corfu. I found `company-mode` can fix my problem. But thanks anyway.
