### ISSUE TITLE
about:init-org.el

### ISSUE THREAD

**Issue by xiliuya** [purcell/emacs.d#824]
GNU Emacs 28.2

in line 365
When I restart emacs and execute the following code `C-x C-e`, the output is: `((emacs lisp. t)) `and org-babel-load-languages  value is `((emacs-lisp . t))`
but after run: `C-h v org-babel-load-languages `
output:will be: `((R . t) (ditaa . t) (dot . t) (emacs-lisp . t) (gnuplot . t) (haskell) (latex . t) (ocaml) (octave . t) (plantuml . t) (python . t) (ruby . t) ... `

How can I open the emacs org file  org-babel-load-languages with a value of ` ((R. t) (ditaa. t) (dot. t) (emacs lisp. t) (gnuplot. t) (haskell) (latex. t) (ocaml) (octave. t) (plantuml. t) (python. t) (ruby. t)`?

> (seq-filter
    (lambda (pair)
      (featurep (intern (concat "ob-" (symbol-name (car pair))))))
    '((R . t)
      (ditaa . t)
      (dot . t)
      (emacs-lisp . t)
      (gnuplot . t)
      (haskell . nil)
      (latex . t)
      (ledger . t)
      (ocaml . nil)
      (octave . t)
      (plantuml . t)
      (python . t)
      (ruby . t)
      (screen . nil)
      (sh . t) ;; obsolete
      (shell . t)
      (sql . t)
      (sqlite . t)))

**Comment by purcell** [comment]
Does aeb16fe help?

**Comment by xiliuya** [comment]
> Does [aeb16fe](https://github.com/purcell/emacs.d/commit/aeb16fe067d33cddf0065e6d486b9f33bdabd3c2) help?

yes ,it works.  Thank you very much for your help.
