### ISSUE TITLE
Lost fringe indicators left window

### ISSUE THREAD

**Issue by MonsterLiujia** [purcell/emacs.d#829]
Hi, @purcell ,first thanks for the configuration.
Recently I upgrade the packages, and find the fringe indicators in the left window disappear when moving the cursor.
like:
![1672394375](https://user-images.githubusercontent.com/88773754/210079047-f6c002a8-6c0a-4176-b1f2-a8f5a2678697.png)
![1672394424](https://user-images.githubusercontent.com/88773754/210079069-60fe68d4-d399-4b67-8e0b-0ac2df256311.png)

So I git clone your repository, and reinstall and the problem remains.

Through back and forth, I find the problem is the upgrade of package **symbol-overlay**, looks like there are some problems after last release.
I am using emacs 28.2 on linux.

**Comment by purcell** [comment]
I think that package is fixed upstream now, so this problem should go away once the MELPA package rebuilds
