### ISSUE TITLE
presses one key to turn into many keys

### ISSUE THREAD

**Issue by cntommy** [purcell/emacs.d#830]
hello @purcell 
in my Emacs@28.2 (9.0), sometimes I presses one key to turn into many keys(e.g. press a print afff), but I don't know how to troubleshoot
I wonder if some configs conflict?
thanks for your help!

**Comment by suliveevil** [comment]
This may help.

https://github.com/lastquestion/explain-pause-mode

**Comment by cntommy** [comment]
> Hmm, not sure, sorry. Perhaps after it happens you can try something like `M-x view-lossage` and then see if there's a repeatable sequence of actions you can use to reproduce the issue.

I came across this problem just now again, when I press "abcdefg", it print "jajbjcjdjejfjg", and I try `M-x view-lossage` ,the  screenshot is as follows
<img width="587" alt="image" src="https://user-images.githubusercontent.com/26520294/211864777-543e520a-01a1-4541-b1c5-62e9d7347f5b.png">

**Comment by cntommy** [comment]
> This may help.
> 
> https://github.com/lastquestion/explain-pause-mode

thanks, I'll try later

**Comment by cntommy** [comment]
> Another thing to try would be, when a key is repeating, hit `C-h k` ("describe-key") and then press the key again. It might show exactly what command is being run, and also whether there is some strange `advice` enabled.

this time I press "a", it prints "ma", and I use `C-h k`, it shows:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/26520294/212258445-ab5e7c41-5bb6-4d89-b780-bfcc518f98e9.png">

seems an extra "m" will be printed before the key I press
