### ISSUE TITLE
Using wdired to change file name, got error message.

### ISSUE THREAD

**Issue by kevinfis** [purcell/emacs.d#835]
Hello,
I tried using C-x C-q to call wdired to change file name in dired buffer, 
and emacs showed error message:
 "apply: Symbol’s function definition is void: dired-isearch-search-filenames"

I found if i comment out this line will let wdired working:
 (require 'init-site-lisp) ;; Must come before elpa, as it may provide package.elafter test

But i can't see what cause this in init-site-lisp.
Could anyone can reproduce this situation?

My test procedure:
 emacs -q 
 load-file init.el
 in emacs.d or any filder, using C-x C-q 
  or M-x wdired-change-to-wdired-mode, dired-toggle-read-only
 it can't into wdired mode and showed error message.

in emacs -q , wdired working fine.

system: emacs 29.06   Linux 6.1.9-arch1-1

**Comment by purcell** [comment]
Do you have anything in your site-lisp folder then?

**Comment by kevinfis** [comment]
Yes, i have put some folder and file from github in site-lisp folder, 
but i tested also fresh copy from github that only one file README in it.
i got error message when i used C-x C-q in dired buffer after startup,

**Comment by kevinfis** [comment]
Maybe  (require 'init-site-lisp) not cause the situation,
because if loaded it manually after startup,  not comment out it,
i only saw this text below in message buffer, 
but C-x C-q  can function well

Evaluating...
Company backend ’company-eclim’ could not be initialized:
Symbol’s function definition is void: company-eclim

**Comment by kevinfis** [comment]
@purcell 
If you don't reproduce this situation, i suggest let me hold this issue,
because wdired is working normally suddenly in my computer,
but i don't know what cause my emacs became normal unknowingly,
i just test and restart emacs a lot times.
so let me tried more time in the future.

**Comment by kevinfis** [comment]
Hi,
Purcell,
i closed this issue,
because i found the reason is not because of your config file after tested my files in site-lisp folder.

i found If i changed this file `dired-aux.el`  even to `dired-auw.el`, 
wdired will work well,
but i don't know why this file `dired-aux.el`(from emacswiki) will make wdired fail,
it is a normal char 0x78.

Thanks for your hint, 
let me can found the strange file!

Best regards

Kevin

**Comment by purcell** [comment]
Great, glad you tracked it down!
