### ISSUE TITLE
keybinding issues with paredit

### ISSUE THREAD

**Issue by psyconorlogy** [purcell/emacs.d#843]
Using `paredit-forward-slurp-sexp` keybinding `C-)` goes to end of next sexp instead of slurping.

Using describe-key, the issue seems to be that `C-)` is bound to `)` , which in paredit mode would explain this behavior. 
There is also the same problem with `C-(` being reduced to `(`.

**Comment by purcell** [comment]
Hmm, works just the same as always for me. Can you provide more info about your setup?

**Comment by psyconorlogy** [comment]
> Hmm, works just the same as always for me. Can you provide more info about your setup?

Seems the issue only occurs in emacs -nw mode. Also happens on spacemacs, so it is likely to be a problem with emacs itself. I have  sent a bug report to the mailing list.

**Comment by purcell** [comment]
Hmm. I also checked in a terminal, fwiw, but using `emacsclient -t` — in this case, it also worked fine.

**Comment by psyconorlogy** [comment]
Apparently it is to do with how the terminal takes inputs, so just don't use -nw when using paredit-mode.
Thanks for your work.
