### ISSUE TITLE
Multiple Python flymake checkers

### ISSUE THREAD

**Issue by devnich** [purcell/emacs.d#845]
Hi Steve,

I'm not sure if this is a bug, or expected behavior from the flymake-flycheck module.

I create a new Python file with a single line:
```python
import matplotlib.pyplot as plt
```

Flymake correctly highlights the line with a warning. Moving the cursor to the line causes 5 warnings to appear in the minibuffer:
```
Unused matplotlib.pyplot imported as plt [python-pylint]
'matplotlib.pyplot as plt' imported but unused [python-flake8]
Unused matplotlib.pyplot imported as plt [python-pylint]
'matplotlib.pyplot as plt' imported but unused [python-flake8]
'matplotlib.pyplot as plt' imported but unused
```

Do you have any suggestions on how to remove some of the redundancy? Thanks!

**Comment by ngn999** [comment]
I just uninstall pylint. :)

**Comment by purcell** [comment]
Hmm, it looks like the same checker is in there multiple times — I've pushed changes to the config (and to flymake-flycheck to address this). That might help a little. Note that you can add unwanted checkers to `flycheck-disabled-checkers` as needed.

**Comment by purcell** [comment]
@lvii added ✅
