### ISSUE TITLE
treesit config not load on startup

### ISSUE THREAD

**Issue by devceezi** [purcell/emacs.d#848]
Hi Steve, I've been using your configuration for a long time. I recently upgraded to emacs 29.1 and was trying to add some Treesit-related configuration to it, but after the update I see that you have added `init-treesit.el`

 But I found that when I started emacs on my computer, `init-treesit.el` was not evaluated. I did some trying and found that after emacs started, `(featurep 'treesit)` is `nil`, After I use `(require 'treesit)`, `(featurep 'treesit)` becomes `t`

Also, I noticed that `(treesit-available-p)` always returns t, regardless of whether there is `(require 'treesit)`.

I'm using Linux, `(emacs-version)` returns `"GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)"`

**Comment by purcell** [comment]
Thanks, I've committed what I think should be an appropriate fix.
