### ISSUE TITLE
Warning (treesit): Cannot activate tree-sitter, because language grammar for nix is unavailable (not-found)

### ISSUE THREAD

**Issue by causlayer** [purcell/emacs.d#853]
Warning (treesit): Cannot activate tree-sitter, because language grammar for nix is unavailable (not-found): (libtree-sitter-nix.so libtree-sitter-nix.so.0 libtree-sitter-nix.so.0.0 libtree-sitter-nix.dylib libtree-sitter-nix.dylib.0 libtree-sitter-nix.dylib.0.0) No such file or directory

macOS 12.7.1
Emacs Version 29.1 (9.0)

**Comment by purcell** [comment]
Thanks, I think that unnecessary warning should be resolved now.
