### ISSUE TITLE
Tidying up code

### ISSUE THREAD

**Issue by 4wardx** [purcell/emacs.d#857]
Hello @purcell,

As the title suggests, some code segments may need to be tidied up.

1. `init-terraform.el`, the footer is duplicated.

``` emacs-lisp
(provide 'init-terraform)
;;; init-terraform.el ends here
;;; init-terraform.el ends here
```

2. `init-uniquify.el`, the footer is collapsed.

``` emacs-lisp
(provide 'init-uniquify);;; init-uniquify.el ends here
```

**Comment by purcell** [comment]
thanks, fixed
