### ISSUE TITLE
emacs Got Assertion failed: (derived-mode-p 'ibuffer-mode)

### ISSUE THREAD

**Issue by bloodofdracula** [purcell/emacs.d#860]
Using stock starter kit without any adds or delete init or any modification (including custom.el).
Open some files from emacsd-29-1 distribution (downloaded from gnu site)
C-x C-b (ibuffer)
Use / to make some selection
Select by file extension option .
and enter
Select el type of file
Got Assertion failed: (derived-mode-p 'ibuffer-mode)
See attached screen pictures...

Same with other options..by size, filename..

After selecting . (/ - preceding) . (selecting by file extension) and BEFORE selecting extension el emacs display a buffer in the list and do not display the buffer list..strange

![ibuffer-01](https://github.com/purcell/emacs.d/assets/153940864/2b4733d4-4974-4866-b5bf-4fbdf56200c7)
![ibuffer-02](https://github.com/purcell/emacs.d/assets/153940864/28680798-b6e4-4631-8cd4-0c66c9ff779f)
![ibuffer-03](https://github.com/purcell/emacs.d/assets/153940864/cb57d57a-4d2a-4a56-9d51-f4b90a4c9fcd)
![ibuffer-04](https://github.com/purcell/emacs.d/assets/153940864/fa9ba42a-ed2b-49f5-a1ec-e1430bceaa1c)
![ibuffer-05](https://github.com/purcell/emacs.d/assets/153940864/331ff018-9d09-41cf-9e23-9543f64e59c1)

Using emacs 29.1
Development version 28fb02492c24 on master branch; build date 2023-12-10.

Linux Zorin. Emacs from snap store

**Comment by purcell** [comment]
Hmm, interesting: if you hit `/.` very quickly, so that the `which-key` window doesn't pop up, then this doesn't happen, so I think it's some sort of interaction between `which-key` and `ibuffer`. I'll see if I can figure out what the issue is. Interestingly, the equivalent in `dired` (`*.`) doesn't have the same issue.

**Comment by bloodofdracula** [comment]
I did a test on a stock emacs (same from snap without which-key) and it is working as it is supposed to do...Thanks for your answer and help.

**Comment by purcell** [comment]
I found and fixed it: some kind of weird interaction with the `fullframe` package, which I plan to replace anyway. So I've just disabled it for that command.

**Comment by bloodofdracula** [comment]
lisp/init-ibuffer.el

(require-package 'fullframe)
(with-eval-after-load 'ibuffer
 (fullframe ibuffer ibuffer-quit))

So I only need to suppress those lines..right ? Thanks for your nice work.

**Comment by purcell** [comment]
Yes, but I've pushed that change to this repo.
