### ISSUE TITLE
About the major-mode-remap-alist variable

### ISSUE THREAD

**Issue by xiangsheng** [purcell/emacs.d#861]
In the `init-treesitter.el`, the `major-mode-remap-alist` variable is set to `nil` at the beginning. However, this operation will overwrite the possible original value of this variable. 

I notice this problem because of the recent update of `AUCTeX`. This package now uses this variable at the init process of emacs to take over the control of several built-in mode, like latex mode. However, with the current setting of `init-treesitter.el`, the value set by `AUCTeX` is overwritten completely. Is there a better way to deal with this variable?

**Comment by purcell** [comment]
Yep, fixed now. There was no need to set those vars to `nil` — it was just there from when I was originally writing that code and re-running it often.
