### ISSUE TITLE
Relocate init-preload-local 

### ISSUE THREAD

**Issue by AlMaVizca** [purcell/emacs.d#863]
Thanks for your effort. Your Emacs dots facilitate my journey.

I was using straight to manage some packages, and recently decided to give it a try to elpaca.
On their [installer code](https://github.com/progfolio/elpaca?tab=readme-ov-file#installer) they mention it has to be loaded early into the init.el. 
I've found init-preload-local.el and the issue #199, but it's being loaded after 'init-elpa' which makes elpaca to throw a warning.
I found that moving:
https://github.com/purcell/emacs.d/blob/adf0e27c95cae4e19e2fee174170bac2ff7e83d3/init.el#L56-L57
In between of:
https://github.com/purcell/emacs.d/blob/adf0e27c95cae4e19e2fee174170bac2ff7e83d3/init.el#L19-L21

Will reduce the warnings and keep the dots working as usual, at least with the default configs.
Would this change create any trouble?

**Comment by purcell** [comment]
I think that would break configurations for people who expect the package system to have been initialised when `init-preload-local` is loaded. But you could always modify `init.el` directly in your fork — I don't intend these `init*-local.el` extension points to cover all potential use cases anyway.
