### ISSUE TITLE
`git-commit.el` has been part of magit, maybe can remove `git-commit.el` ?

### ISSUE THREAD

**Issue by Spike-Leung** [purcell/emacs.d#864]
Hi, purcell,

Recently, I encountered a warning that it seems `git-commit.el` is already part of `magit` and doesn't need to be installed separately. 

>■  Emergency (emacsql): Uninstall the `git-commit' package.
>
>The "git-commit.el" library is no longer distributed as a separate
>package.  It is now distributed as part of the `magit' package.
>
>The `git-commit' package now does nothing but display this warning.
>If it is located earlier on the `load-path' than `magit' is, then that
>prevents the proper "git-commit.el" libraries from `magit' from being
>loaded.
>
>Please uninstalling `git-commit' and then restart Emacs.

Should we update the configuration here to eliminate the warning?

https://github.com/purcell/emacs.d/blob/247d6e1cc534a30a2ceed9413f55a10bb3a53df0/lisp/init-git.el#L45

**Comment by purcell** [comment]
Yep, fixed, thanks!

**Comment by Spike-Leung** [comment]
Thank you !👍

**Comment by purcell** [comment]
I guess @tarsius will remove the `git-commit` package recipe from MELPA soon too — Jonas, let me know if you'd like me to do so.

**Comment by tarsius** [comment]
The purpose of the fake `git-commit` package is to be installed as an update for people who already have an older `git-commit` installed. That way that transitional version/package, can inform the user that they need to uninstall it (and potentially open issues such as this one). 

Without doing that older `git-commit` could end up remaining installed, which would become an issue, once the `git-commit.el` in `magit` has diverged enough.

I therefore intend to keep this fake package around for a while. That way, user who update their Emacs packages infrequently can also benefit from this transitional kludge.

**Comment by purcell** [comment]
Cool, I figured you'd have a transition plan so I didn't want to remove the package unilaterally without checking. Will leave it as-is, thanks.
