### ISSUE TITLE
sanityinc/consult-ripgrep-at-point can't work with C-u

### ISSUE THREAD

**Issue by wangdiqi** [purcell/emacs.d#866]
Dear @purcell ,

When i use `C-u M-?` to call `sanityinc/consult-ripgrep-at-point`, the variable `prefix-arg` in the function is nil. I'm not sure if this is just an error specific to my environment or if we should be using the `current-prefix-arg` variable here.

emacs version: GNU Emacs 28.1 (build 1, x86_64-apple-darwin20.4.0, Carbon Version 164 AppKit 2022.44)

Best regards.

**Comment by purcell** [comment]
Good catch, fixed now, thanks!
