### ISSUE TITLE
Should eat-semi-char-non-bound-keys keep growing?

### ISSUE THREAD

**Issue by dcorking** [purcell/emacs.d#867]
I think I have misconfigured something harmless but puzzling.

In my `custom.el` the list `eat-semi-char-non-bound-keys` is prepended with the same key (is it `M-w`?) each time I run my Emacs init script, which is forked from this one.

`custom.el` starts to look a little repetitive, like this:
```elisp
 '(eat-semi-char-non-bound-keys
   '([27 119]
     [27 119]
     [27 119]
     [24]
...
```

I think this form in [init-terminals.el](https://github.com/purcell/emacs.d/blob/master/lisp/init-terminals.el#L15) does it.
```elisp
  (with-eval-after-load 'eat
    (custom-set-variables
     `(eat-semi-char-non-bound-keys
       (quote ,(cons [?\e ?w] eat-semi-char-non-bound-keys)))))
```

It does no harm, and I can of course easily revert custom.el. I am just curious what I did wrongly or how to fix.

**Comment by dcorking** [comment]
I guess one thing I do differently compared to the parent repo, is that I commit `custom.el` to git.

**Comment by purcell** [comment]
Thanks, pushed a fix for this
