### ISSUE TITLE
Error during download request: Not Found

### ISSUE THREAD

**Issue by pidodo** [purcell/emacs.d#92]
Hi purcell
when i run emacs with your emacs.d, i get the erro:
"Error during download request: Not Found"
I google the error, i get this:
   https://github.com/purcell/emacs.d/issues/22
But i can't reslove it.
I run emacs with --debug-init, i get this:  (my system is freebsd 9.1)
 Debugger entered--Lisp error: (error "Error during download request: Not Found")
  signal(error ("Error during download request: Not Found"))
  error("Error during download request:%s" " Not Found")
  package-handle-response()
  package-download-tar(expand-region "20130409.658")
  package-download-transaction((expand-region))
  package-install(expand-region)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package$
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (p$
  require-package(expand-region)
  eval-buffer(#<buffer  *load*-961509> nil "/home/yayoo/.emacs.d/init-editing-utils.el" nil t)  ; Reading at buffer position 2470
  load-with-code-conversion("/home/yayoo/.emacs.d/init-editing-utils.el" "/home/yayoo/.emacs.d/init-editing-utils.el" nil t)
  ad-Orig-require(init-editing-utils nil nil)
  (with-no-warnings (ad-Orig-require feature filename noerror))
  (setq ad-return-value (with-no-warnings (ad-Orig-require feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (ad-Orig-require feature filename noerror))) (when (and (not already-loaded) (memq feature$
  (let\* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (setq ad-return-va$
  (let (ad-return-value) (let\* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (p$
  require(init-editing-utils)
  eval-buffer(#<buffer  *load*> nil "/home/yayoo/.emacs.d/init.el" nil t)  ; Reading at buffer position 1963
  load-with-code-conversion("/home/yayoo/.emacs.d/init.el" "/home/yayoo/.emacs.d/init.el" t t)
  load("/home/yayoo/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#$
  command-line()
  normal-top-level()

**Comment by laureenas** [comment]
Thank you @osener, fixed a similar issue for me!

**Comment by Deepakdubey90** [comment]
Thank you **@osener** , help me to fixed same issue.

**Comment by xxks-kkk** [comment]
Thank you @osener , it helps!
